### ISSUE TITLE
Некорректная обработка названия блога

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#151]
Последние версии и Alto и Start Kit из гитхаба.
1. Создаю блог с именем '>>> AnyTimeInterrogation <<<'
2. Сохраняется только '>>> AnyTimeInterrogation'
3. Скриншот.
   ![1111](https://cloud.githubusercontent.com/assets/6797881/3168011/8b324c52-eb78-11e3-9ee7-5f57e3f21fc3.png)

**Comment by shtrih** [comment]
Зачем вообще что-либо удалять? Это же заголовок, раз он не должен содержать html-теги, то просто выводить его всегда с фильтром `escape:'html'` в шаблоне. Если юзер таки написал туда теги, значит так было нужно (может, пишет статью про html5-теги, например).

**Comment by inliquid** [comment]
Тоже не понял логику...
