### ISSUE TITLE
Проблемы с управлением/логикой блогов - УЛУЧШЕНИЯ

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#232]
1. Нужны кнопки «заблокировать пользователя» в комментариях, у создателя, администраторов и модераторов блога.
2. Если пользователь не подписывается на блог, и пользователям разрешено оставлять комментарии, то его НЕВОЗМОЖНО ЗАБАНИТЬ. Более того, даже если запретить оставлять комментарии неподписанным пользователям, но дать возможность свободной подписки - пользователь просто может отписаться от блога после того, как оставил комментарий, и снова стать неуязвимым.

**Comment by andrey-v** [comment]
>Вопрос, нужен ли такой механизм?
Если необходимо, то вполне реализуется плагином (http://altocms.ru/addons/download/item/96/)[http://altocms.ru/addons/download/item/96/]

**Comment by inliquid** [comment]
Андрей не совсем так. Реализовать можно но логика остается с изъяном. Дело в том что фундаментальная проблема в том что заблокировать можно только подписчика. Как результат того решения, которое я сделал у себя - пользователь. если будет внимателен сможет принудительно подписывать других на свой блог. И если такая ситуация будет проявляться придется искать выход. Пока я просто полагаюсь на то что к тому времени когда моим пользователям это потребуется логика будет исправлена.

**Comment by inliquid** [comment]
Вопрос, нужен ли такой механизм?

Такой механизм нужен. Однозначно. Блокировка для комментариев - это полумера, как быть с голосованием например за топики и комментарии?
