### ISSUE TITLE
Не работает кнопка "пригласить" пользователя

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#233]
В администрировании блога есть такая форма. Сейчас настройка для всех блогов - свободная подписка, поэтому в принципе приглашение как ограничение доступа не нужно (не уверен что эти факты здесь связаны, но мало ли). А вот приглашение как именно приглашение в принципе пригодилось бы.

![1](https://cloud.githubusercontent.com/assets/6797881/4468737/86e5b68c-4903-11e4-969d-fcf10d9290af.png)

После нажатия на кнопку никакой реакции.

**Comment by inliquid** [comment]
Почему закрыто? =)

**Comment by andrey-v** [comment]
Только что проверил. Работает и в start-kit и в experience. Браузер ошибок ни каких в консоли не выводит?

**Comment by inliquid** [comment]
Вероятно проблема может быть в том, что этот блок/виджет (Пригласить) отображается там где не должен. Например у меня он показывается с моим типом блога - diary. 
При нажатии на кнопку ничего не происходит. Ее там или не должно быть совсем, или должно приходить приглашение, так?

![6](https://cloud.githubusercontent.com/assets/6797881/5648206/f517b55a-969d-11e4-91f7-5fab8a870ced.png)

**Comment by andrey-v** [comment]
Почему не должен? Если блог закрытый, то виджет будет и должен работать. 
А что возвращает ajax-запрос?
![q](https://cloud.githubusercontent.com/assets/1106990/5648435/921232d0-969f-11e4-9735-ee3c2f4f38ab.PNG)

**Comment by inliquid** [comment]
У этого блога подписка свободная. Не уходит аякс запрос, вообще ничего не происходит.
