### ISSUE TITLE
Не создается директория /_run/assets/skin/brand/assets/images

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#241]
В моей тестовой конфигурации на Windows все ок. 

В конфигурации на дебиане, под nginx - проблема - не создается папка, содержащая 404.jpg, это единственный файл - изображение для страницы 404):
/_run/assets/skin/brand/assets/images

На этот jpg ведет ссылка из static.css:
# not-found-bg {

```
background: url("../assets/images/404.jpg") no-repeat fixed 0 0 / cover rgba(0, 0, 0, 0);
height: 100%;
min-height: 100%;
overflow-x: hidden;
```

}

Другие папки с css/js содержимым создаются нормально, вот текущее содержимое /_run/assets/skin/brand

/var/www/example.com/_run/assets/skin/brand# ls -la *
2a1f5df5:
total 36
drwxr-xr-x 2 www-data www-data  4096 Окт  8 03:01 .
drwxr-xr-x 6 www-data www-data  4096 Окт  8 03:01 ..
-rw-r--r-- 1 www-data www-data   694 Окт  8 03:01 favicon.png
-rw-r--r-- 1 www-data www-data 22176 Окт  8 03:01 logo-footer.png

2a71cee3:
total 24
drwxr-xr-x 2 www-data www-data  4096 Окт  8 03:01 .
drwxr-xr-x 6 www-data www-data  4096 Окт  8 03:01 ..
-rw-r--r-- 1 www-data www-data 12560 Окт  8 03:01 skrollr.min.js

2df63688:
total 36
drwxr-xr-x 2 www-data www-data  4096 Окт  8 03:01 .
drwxr-xr-x 6 www-data www-data  4096 Окт  8 03:01 ..
-rw-r--r-- 1 www-data www-data 15377 Окт  8 03:01 animate.css
-rw-r--r-- 1 www-data www-data  6423 Окт  8 03:01 menus.css
-rw-r--r-- 1 www-data www-data  1875 Окт  8 02:55 static.css

5fa5b5cc:
total 12
drwxr-xr-x 2 www-data www-data 4096 Окт  8 03:01 .
drwxr-xr-x 6 www-data www-data 4096 Окт  8 03:01 ..
-rw-r--r-- 1 www-data www-data 4053 Окт  8 03:01 respond.min.js

(С правами, конечно все ок - другие файлы и папки создаются). Заново активировать шаблон, чистить кэш, и т.д. - пробовал.

Самое странное что на Windows все работает.

В логах все та же ошибка: https://github.com/altocms/altocms/issues/238

**Comment by inliquid** [comment]
Ошибка осталась...

**Comment by lexuspro** [comment]
Вы имеете ввиду картинка фоновая на странице 404 не показывается?

**Comment by inliquid** [comment]
Ну да, пока самостоятельно эту директорию не создать в _run и не скопировать туда 404.jpg, фона не видно. Это только под nginx. Права на родительскую директорию все корректные.

**Comment by lexuspro** [comment]
Лично с дебианом не знаком, но проблему понял, система неправильно распознает путь к картинке. Сейчас нет возможности проверить, попробуйте "поиграть" с путем картинки - url("./assets/images/404.jpg"), или так- url("..assets/images/404.jpg") или так url(".../images/404.jpg")

**Comment by inliquid** [comment]
Это в каком месте смотреть?

**Comment by lexuspro** [comment]
Это как раз в том коде css, который вы прислали с файла static.css

**Comment by inliquid** [comment]
Вопрос в том, почему на винде с апачем создается эта директория и туда копируется файл 404.jpg, а здесь нет. Если изменить этот путь, то он его просто не найдет. С таким заданием пути в static.css -> url("../assets/images/404.jpg"), получаем нормальный GET от браузера:

"GET /_run/assets/skin/brand/assets/images/404.jpg HTTP/1.1" 404 168 "http://example.com/_run/assets/skin/brand/7fd06294/static.css" "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"

(Ну и результат 404 как видно, т.к. файла не существует)

**Comment by inliquid** [comment]
Я понял в чем дело. Движок не имеет технической возможности отследить пути, которые зашиты в css, поэтому несмотря на то что говорил Вадим, он по-прежнему отрабатывает некоторые (видимо) запросы на статику, если конечно их получает. 
Настройки апача по умолчанию установлены таким образом 
1. Проверяется наличие файла на диске. Если он есть, то он отдается, если нет то
2. Запрашивается движок.

Видимо на шаге 2 этот файл и копируется в папку _run. 
У меня же был настроен nginx на безусловную отдачу статики с диска, как мы это и обсуждали в сообществе. но похоже что для таких запросов по-прежнему необходимо реализовать эту логику. поэтому немного модифицировал свой конфиг:

Внтури корневого location`а:

                        location ~ /brand/assets/images/.* {
                                try_files $uri @assets;
}

и собственно:

        location @assets {

                fastcgi_pass unix:/var/run/php5-fpm.sock;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/index.php;
                fastcgi_param QUERY_STRING    q=$uri&$args;
                fastcgi_param  SCRIPT_NAME /index.php;
        }

**Comment by inliquid** [comment]
На самом деле сейчас смотрю - все таки не до конца понимаю, почему проблема возникла только с этим одним файлом. В директории assets куча всего, включая всякие шрифты, ссылки на которые идут из *css файлов.

**Comment by inliquid** [comment]
Может он не обрабатывается таким вот образом просто потому что этого файла нет в конфиге скина?

`$config['head']['default']['css'] = array(
    /* Bootstrap */
    '___path.skin.dir___/themes/___view.theme___/bootstrap/css/bootstrap.min.css',

    /* Structure */
    '___path.skin.dir___/assets/css/base.css',
    '___path.frontend.dir___/libs/vendor/markitup/skins/default/style.css',
    '___path.frontend.dir___/libs/vendor/markitup/sets/default/style.css',
    '___path.frontend.dir___/libs/vendor/jcrop/jquery.Jcrop.css',
    '___path.frontend.dir___/libs/vendor/prettify/prettify.css',
    '___path.frontend.dir___/libs/vendor/nprogress/nprogress.css',
    '___path.frontend.dir___/libs/vendor/syslabel/syslabel.css',
    '___path.frontend.dir___/libs/vendor/prettyphoto/css/prettyphoto.css',
    '___path.skin.dir___/assets/css/smoothness/jquery-ui.css',
    '___path.skin.dir___/assets/css/responsive.css',

    /* Theme */
    '___path.skin.dir___/themes/___view.theme___/style.css',
    /* Themer Icons */
    '___path.skin.dir___/assets/icons/css/fontello.css',

    '___path.skin.dir___/assets/css/tinymce.css'       => array(
        'name'      => 'template-tinymce.css',
        'prepare'   => true,
        'merge'     => false,
    ),


);`

**Comment by aVadim483** [comment]
А каким образом static.css подключается?

**Comment by inliquid** [comment]
Видимо так
action.error.index.tpl

	<link href="{asset file='/assets/css/static.css'}" rel="stylesheet">

**Comment by lexuspro** [comment]
В конфиге попробуйте подключить файл методом 

'___path.skin.dir___/assets/css/static.css',

**Comment by aVadim483** [comment]
Да, проблема именно в том, что в шаблоне идет подключение, и CSS файл сам копируется в нужную папку, но без обработки, т.е. УРЛы внутри него не обрабатываются.

**Comment by inliquid** [comment]
Добавил кое-какие параметры в style.css, который есть в конфиге:
'___path.skin.dir___/themes/___view.theme___/style.css',

А именно:
.menu-feather > a {background: url("../assets/images/orange.png") no-repeat 50% 0%;}

В результате в результирующем файле ссылка так и осталась без изменений (я так и не понял модифицирует ее движок или нет), от браузера приходит такой запрос

178.173.4.126 - - [06/Jan/2015:22:41:31 +0300] "GET /_run/assets/images/orange.png HTTP/1.1" 404 168 "http://example.com/_run/assets/8670ca26d4d47c96380bb8c9d4a9abc8.css" "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"

(сам файл лежит в /common/templates/skin/brand/assets/images/)

пробовал по аналогии с друими ресурсами, с которыми все ок менять путь, например ../images/orange.png - не помогло.

Что-то я совсем перестал понимать логику...
