### ISSUE TITLE
Немного не стыкуется логика конфигов скинов

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#247]
Не знаю баг, или просто так нельзя настраивать изначально...

В настройках в шаблоне Brand есть такая особенность

`if ($config['www']['scroll']) {
    $config['head']['default']['js'][] = "___path.skin.url___/assets/js/jquery.nicescroll.min.js";
}`

Вкл/выкл соотвественно параметром скина 

`$config['www']['scroll'] = false;`

Так вот, если конфиг создан в папке app, то такой false не сработает, если в оригинальном конфиге стоит true. Файл все равно будет подключен.

**Comment by inliquid** [comment]
Андрей, я же прекрасно понимаю в какой подпапке в папке app должен лежать конфиг, ты невнимательно прочитал мой пост. Смысл в том, что при таком вот подключении:
if ($config['www']['scroll']) { $config['head']['default']['js'][] = "___path.skin.url___/assets/js/jquery.nicescroll.min.js"; }

если в оригинальном конфиге по-прежнему true, то файл подключится.

Соответственно вопрос, либо так вообще нельзя подключать (делать такое условие), либо менять логику обработки конфигов.

**Comment by andrey-v** [comment]
Действительно, не так понял. Загвоздка тут в чем, в файле конфига темы написано:
```php 
$config['www']['scroll'] = false;
// несколько строчек других параметров
if ($config['www']['scroll']) { 
     $config['head']['default']['js'][] = "___path.skin.url___/assets/js/jquery.nicescroll.min.js"; 
}
```
Это все находится в одном файле и, разумеется если в этом файле установлено **scroll=false** , то и а на следующей строке он будет **false** и по всему файлу таким же и останется. И только после того как этот файл загрузится, то поверх него будут записаны настройки из соответствующего файла папки app. Значение **scroll**, конечно поменяется, но ведь скрипт уже загружен ведь проверка была раньше чем прочитался файл настроек приложения.
