### ISSUE TITLE
Искажаются фотографии в фотосете

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#254]
Если загрузить в фотосет довольно много изображений, так что появляется кнопка "Показать еще фото", то после нажатия на последнюю, иконки изображений искажаются:

Да нажатия:
![1](https://cloud.githubusercontent.com/assets/6797881/4720113/c30159e2-592e-11e4-856c-e7279bb2f819.png)

После:
![2](https://cloud.githubusercontent.com/assets/6797881/4720114/c8b4f4ac-592e-11e4-8c82-2209f8e29e35.png)

Проверено в скинах brand и start-kit.

**Comment by inliquid** [comment]
Проблема осталась. Особенно актуально при взаимодействии с плагином br.

**Comment by andrey-v** [comment]
И без плагина br тоже самое. Дело в скрипте вывода галереи (. 
Буду искать в нем ошибку

**Comment by aVadim483** [comment]
По-моему, подобная ошибка была, если не указывать в атрибутах изображения размеры. В первую очередь это надо проверить
