### ISSUE TITLE
Не работает индикатор online/offline

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#261]
Сразу поле логина система показывает что пользователь онлайн. Но если я спустя скажем полчаса начинаю смотреть сайт, то везде - в профиле, в списке пользователей система показывает, что я оффлайн. Явные обновления страниц не помогают.

**Comment by inliquid** [comment]
Да, могу, проблема осталась:

![4](https://cloud.githubusercontent.com/assets/6797881/5647598/81a83ae0-9698-11e4-8397-efda3cc9b06e.png)

**Comment by inliquid** [comment]
Похоже что система отслеживает не активность пользователя а только лишь событие логина. То есть спустя какое-то время все пользователи показываются оффлайн, хотя все активно писали/комментировали

![5](https://cloud.githubusercontent.com/assets/6797881/5647888/f919d3de-969a-11e4-90f1-a77afbdca1f9.png)

**Comment by inliquid** [comment]
Что скажете? 
Проблема очень бросается в глаза в скине где индикатор online/offline всегда перед глазами, включая комментарии и подпись под топиком, в частности в скине Brand.

**Comment by inliquid** [comment]
Андрей, баг надо переоткрыть. Я готов со своей стороны отслеживать в каких ситуациях исчезает индикация online. (Она то есть то нет)

**Comment by andrey-v** [comment]
Переоткрываю,
у меня один раз такая ошибка появилась когда зарегистрировался новым пользователем и посмотрел список всех пользователей на сайте. Но больше не воспроизводится как я не старался. Тоже буду следить.

**Comment by inliquid** [comment]
По моим наблюдениям первое время после захода на сайт все нормально.
Спустя какое-то время, если активных действий не было, но сессия сохранена в куки и пользователь возвращается - система его узнает, но отображает что он оффлайн, даже если он добавляет комментарий (выше приводил скриншот), или обновляет страницу сайта - это не на что не влияет.

**Comment by inliquid** [comment]
Еще нюанс,  на всякий случай, не знаю может это влиять, у меня имя сессии изменено со стандартного PHPSESSID.

**Comment by inliquid** [comment]
Только что опять столкнулся с этой ситуацией - пользователь вернулся на сайт спустя какое-то время и система показывала его как offline. Не помогало:
- перезагрузка страницы (F5)
- принудительная перезагрузка (Ctrl-F5)
- Добавление комментария в топик

Зато сработала отправка нового письма другому юзеру - индикатор сразу обновился везде.

В следующий раз проверю добавление нового топика.

**Comment by aVadim483** [comment]
А вернулся он с автоматической авторизацией, т.е. логин и пароль не вводил?

**Comment by inliquid** [comment]
Прошу прощения, поторопился, не везде. Вообще мистика

Индиктор показывает как online теперь только в письмах,

![1](https://cloud.githubusercontent.com/assets/6797881/5818144/f3670e9c-a0c3-11e4-986a-342f2267d833.png)



 в профиле по-прежнему offline

![2](https://cloud.githubusercontent.com/assets/6797881/5818145/f8011380-a0c3-11e4-973e-646ab43c417a.png)


Вернулся без пароля, по сохраненной куки

**Comment by inliquid** [comment]
Если выйти-войти все снова ок становится.

**Comment by andrey-v** [comment]
Настройки кэшировния шаблонов не менялись?
```
$config['smarty']['compile_check']          = false; 
$config['smarty']['force_compile']          = false; 
$config['smarty']['merge_compiled_includes']= false; 
$config['smarty']['cache_lifetime']         = true;  
```

**Comment by inliquid** [comment]
Вот настройки, ничего не трогал здесь

/**
 * Настройки шаблонизатора Smarty
 */
$config['path']['smarty']['template'] = '___path.skins.dir___/___view.skin___/';
$config['path']['smarty']['compiled'] = '___path.tmp.dir___/templates/___view.skin___-___view.theme___/compiled/';
$config['path']['smarty']['cache']    = '___path.tmp.dir___/templates/___view.skin___-___view.theme___/cache/';
$config['path']['smarty']['plug']     = '___path.dir.engine___/classes/modules/viewer/plugs/';

$config['smarty']['compile_check']          = true;   // Проверять или нет файлы шаблона на изменения перед компиляцией, false может значительно увеличить быстродействие, но потребует ручного удаления кеша при изменения шаблона
$config['smarty']['force_compile']          = false;  // Принудительно компилировать шаблоны (отменяет действие 'compile_check')
$config['smarty']['merge_compiled_includes']= false;  // Слияние скомпилированных шаблонов (увеличивает скорость рендеринга при большом числе подшаблонов)
$config['smarty']['cache_lifetime']         = false;  // Кеширование отрендеренных шаблонов


(Почему-то последний параметр отличается)

**Comment by lexuspro** [comment]
На странице "Люди" такая же проблема?

**Comment by inliquid** [comment]
Да, это везде так.

**Comment by klaus-spb** [comment]
А если отключить кэширование ?

**Comment by inliquid** [comment]
Какое? Мемкеш?

**Comment by klaus-spb** [comment]
Мемкэш если его используете

**Comment by lexuspro** [comment]
сейчас код вывода статуса практически везде такой
``<span class="online-profile {if $oUserProfile->isOnline()}online{else}offline{/if}" title="{if $oUserProfile->isOnline()}{$aLang.user_status_online}{else}{$aLang.user_status_offline}{/if}"></span>``

Думаю, в нем проблема. Вадим, Андрей, Николай, что скажете?

**Comment by inliquid** [comment]
Проверю еще с добавлением топика, потом попробую без кеша.

Андрей, поставил так:
$config['smarty']['compile_check']          = true; 
$config['smarty']['force_compile']          = false; 
$config['smarty']['merge_compiled_includes']= false; 
$config['smarty']['cache_lifetime']         = false;  

Пойдет?))

**Comment by andrey-v** [comment]
Временные зоны в настройках у пользователей не менялись?

**Comment by inliquid** [comment]
Нет.

**Comment by inliquid** [comment]
Похоже проблема появляется все-таки не в момент возвращения по персистентной куке, а наоборот, спустя какое-то время после возвращения, но пока <b>сессионная</b> кука установлена. Похоже что достаточно зайти на сайт по персистентной куке, и где-то спустя час движок как будто перестает замечать сессию. Т.е. сессия не переустанавливается, движок перестает отображать статус пользователя, хотя сессия все еще валидна. Сейчас попробую перезапустить браузер, чтобы сессионная кука переустановилась - проверю.

**Comment by inliquid** [comment]
Да, все верно.

**Comment by inliquid** [comment]
Еще у меня отличный от дефолтного $config['security']['user_session_key']

**Comment by aVadim483** [comment]
От $config['security']['user_session_key'] никак не зависит, этот параметр специально вынесен в настройки, чтоб его менять можно было в целях усиления безопасности.

У меня вот что никак не устаканится в голове - существует какой-то алгоритм действий, при котором гарантированно этот баг можно получить? Или это как-то рандомно проявляется?

**Comment by inliquid** [comment]
Могу ошибаться, но похоже последовательность примерно такая
1. Предварительно нужно сохранить сессию, можно залогиниться, и, перезапустив браузер, открыть сайт
2. Система отображает статус "онлайн"
3. Не закрывая браузер подождать примерно час-полтора не создавая никакой активности
4. Теперь статус будет оффлайн до перезапуска браузера или пока пользователь не перелогинится

При этом как я написал выше есть мистическое поведение с отправкой писем, когда после отправки статус "онлайн" отображается только на странице личных сообщений, в других экшенах по-прежнему оффлайн.

**Comment by aVadim483** [comment]
Уточнение по п.3: что значит "не создавая никакой активности"?
И еще - это все при включенном кешировании в мемкеш, так?

**Comment by klaus-spb** [comment]
Я вижу проблему в кэше. Даже если допустить что модуль UpdateSession отрабатывает корректно, то в  $this->oSession всеравно остается старое время, записанное при создании сессии. То есть не сбрасывается кэш.

Функция которая получается сессию пользователя раздваивается из-за solid кэша на GetSessionsByArrayId и GetSessionsByArrayIdSolid . Думается в этом дело и надо смотреть какой кэш должен сбрасываться при апдейте времени в сессии

**Comment by aVadim483** [comment]
Кстати, да @inliquid а у параметра $config['sys']['cache']['solid'] какое значение?

**Comment by aVadim483** [comment]
Николай, похоже, ты прав: по умолчанию установлен солид-кеш, и при чтении сессии используется именно солид, а вот при записи - обычный, т.е. не-солид.

Если задать $config['sys']['cache']['solid'] = false, то проблема должна исчезнуть.

А вообще, есть внутренне ощущение, что проку от солид-кеша мало. Нужно будет внимательно проанализировать, и, возможно, отказаться от него в будущих версиях.

**Comment by inliquid** [comment]
Установлено
$config['sys']['cache']['solid']  = true;

**Comment by aVadim483** [comment]
Задайте $config['sys']['cache']['solid'] = false - проблема должна решиться

**Comment by aVadim483** [comment]
Кеш при этом все равно будет использоваться, только механизм немного другой будет

**Comment by klaus-spb** [comment]
Так может тогда в дистрибутиве поставить по умолчанию $config['sys']['cache']['solid'] = false; ?

**Comment by inliquid** [comment]
Если понятно в чем проблема, почему не исправить? Все до этого тестировалось (за последнее время) с этим типом кэша. Нет никакой гарантии что после смены не вылезут баги в других местах.

**Comment by klaus-spb** [comment]
Тогда всего то надо в GetSessionsByArrayIdSolid добавить в цикл установку кэша для каждой сессии в отдельности 
```php
           foreach ($data as $oSession) {
                $aSessions[$oSession->getUserId()] = $oSession;
				$this->Cache_Set(
                    array('time' => time(), 'session' => $oSession),
                    "user_session_{$oSession->getUserId()}", array(),
                    'P4D'
                );
            }
```

**Comment by klaus-spb** [comment]
А не , не все так просто. Solid кэш записывается надолго и сбрасывается только при создании сессии кого либо или при логауте.
В таком случае можно было в UpdateSession добавить обновление и по ключу от solid кэша. 
```php
$this->Cache_Set(array($this->oSession->getUserId()=>$this->oSession), "user_session_id_{$this->oSession->getUserId()}", array("user_session_update"), 'P1D');
```

В таком случае на странице пользователя будет актуальная информация об онлайне. Точнее если в запросе сессии будет фигурировать только один user_id то все будет работать. Если будет запрашиваться массив пользователей, то данные будут оседать в кэше на P4D или до чего-то логина или логаута

Тогда вижу один вариант ,убрать проверку на включенный solid кэш в функции GetSessionsByArrayId

**Comment by aVadim483** [comment]
В данном случае все оказалось проще - в User::UpdateSession() в конец добавлено
```
$this->Cache_CleanByTags(array('user_session_update'));
```
И теперь солид-кеш будет сбрасываться при обновлении любой сессии. Что значительно уменьшает эффективность кеша (в солид-режиме), но зато работать должно без ошибок

**Comment by aVadim483** [comment]
Но в любом случае подход к кешированию надо пересматривать, это очевидно

**Comment by inliquid** [comment]
Насколько не солид проигрывает солид кэшу в производительности?

**Comment by klaus-spb** [comment]
В таком случае толка от кэша сессиий нет вообще, если он будет чиститься после каждого открытия страницы.
Мне кажется чтоб было бы проще убрать solid кэш именно для сессий. Да было бы другое кеширование, но оно бы работало.

**Comment by inliquid** [comment]
После обновления с последним коммитом появился неприятный баг - иногда по непонятной причине, сохраненная сессия теряется, и приходится заново логиниться. Один раз это произошло сразу после того как я разлогинился тем же юзером но в другом браузере. И несколько раз  - на ровном месте.

**Comment by inliquid** [comment]
Последнее что я написал пока не проявлялось, возможно как-то повлиял апдейт смарти до последней версии, или еще какие-то параметры, например не солид кэш.

Однако сейчас я фиксирую стабильную новую "фичу" - при логауте система продолжает показывать пользователя онлайн, чего раньше не было. Напомню что `$config['sys']['cache']['solid'] = false;`

**Comment by aVadim483** [comment]
>при логауте система продолжает показывать пользователя онлайн

Имеется ввиду список юзеров онлайн? Или в профайле светится, что он онлайн?

**Comment by inliquid** [comment]
Это один и тот же индикатор онлайн/оффлайн, в списке, в профиле, и в комментариях. Везде где есть аватарка пользователя (шаблон Brand).

**Comment by andrey-v** [comment]
>Однако сейчас я фиксирую стабильную новую "фичу" - при логауте система продолжает показывать пользователя онлайн, чего раньше не было. 

Исправлено

**Comment by inliquid** [comment]
После этого исправления если перезапустить мемкэш вываливатся ошибка в лог и на главный экран

[LOG:1426433648.818-5505A670C7C30][2015-03-15 18:34:08][PID:2721][ERROR][[
E_NOTICE [8] unserialize(): Error at offset 0 of 32 bytes (/var/www/example.com/engine/libs/DklabCache/Cache/Backend/TagEmuWrapper.php on line 185)
--- call stack ---
unserialize() in /var/www/example.com/engine/libs/DklabCache/Cache/Backend/TagEmuWrapper.php on line 185
Dklab_Cache_Backend_TagEmuWrapper->_loadOrTestMulti() in /var/www/example.com/engine/libs/DklabCache/Cache/Backend/TagEmuWrapper.php on line 34
Dklab_Cache_Backend_TagEmuWrapper->load() in /var/www/example.com/engine/classes/modules/cache/Cache.class.php on line 322
ModuleCache->_backendLoad() in /var/www/example.com/engine/classes/modules/cache/Cache.class.php on line 543
ModuleCache->MultiGet() in /var/www/example.com/engine/classes/modules/cache/Cache.class.php on line 515
ModuleCache->Get()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/user/User.class.php on line 260
PluginInvites_ModuleUser->Cache_Get() in /var/www/example.com/common/classes/modules/user/User.class.php on line 260
ModuleUser->GetUsersByArrayId() in /var/www/example.com/common/classes/modules/user/User.class.php on line 173
ModuleUser->GetUsersAdditionalData() in /var/www/example.com/common/classes/modules/user/User.class.php on line 584
ModuleUser->GetUserById() in /var/www/example.com/common/classes/modules/user/User.class.php on line 81
ModuleUser->Init() in /var/www/example.com/engine/classes/core/Engine.class.php on line 377
Engine->InitModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 457
Engine->LoadModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 699
Engine->GetModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 612
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 773
Engine->__call()
Engine->User_GetUserCurrent()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1298
E::__callStatic() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1307
E::User_GetUserCurrent() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1307
E::User() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1325
E::IsAdmin() in /var/www/example.com/common/plugins/br/classes/hooks/HookAdmin.class.php on line 17
PluginBr_HookAdmin->RegisterHook() in /var/www/example.com/engine/classes/core/Engine.class.php on line 544
Engine->InitPluginHooks() in /var/www/example.com/engine/classes/core/Engine.class.php on line 523
Engine->InitHooks() in /var/www/example.com/engine/classes/core/Engine.class.php on line 285
Engine->Init() in /var/www/example.com/engine/classes/core/Router.class.php on line 172
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---
