### ISSUE TITLE
Неудобный редактор.

### ISSUE THREAD

**Issue by sem13** [altocms/altocms#286]
А еще, очень неудобно сделан редактор. Если топик очень большой, то кнопки редактирования находятся сверху. И выделить жирным, выставить по центру и т.д. становится проблематично, это нужно подняться в самый вверх страницы, а потом вниз что бы посмотреть результат.

Почему если изображение загружаешь через "Добавить изображение", то меню которое под редактором, там нет кнопки "добавить в топик", в том месте где я этого хочу. То приходится загружать через редактор, и мы опять возвращаемся к тому если нужно в конце добавить картинку, нужно подняться в самый верх.

**Comment by aVadim483** [comment]
Надо будет подумать насчет "плавающей" панели в обоих версиях редактора

**Comment by andrey-v** [comment]
Реализована плавающая панель для редакторов.
Добавление изображений из фотосета уже работает через сниппеты (https://github.com/altocms/altocms/issues/285)
