### ISSUE TITLE
Ошибка с начислением силы за комментарий

### ISSUE THREAD

**Issue by TheDreik** [altocms/altocms#288]
В /common/classes/modules/user/entity/User.entity.class.php идёт округление до двух знаков после нуля:
    public function getSkill() {
        return number_format(round($this->getProp('user_skill'), 2), 2, '.', '');
    }
Тогда как минимальное значение силы, прибавляемое за плюс к комментарию - это 0.004. Соответственно сила никак не повышается при голосовании за комментарий. Судя по тому, что в базе данных у поля для значения силы стоит три знака после ноля, я думаю это непреднамеренная недоработка.

**Comment by inliquid** [comment]
почему 1.1? Это же очевидный косяк, мне на 1.0.* тоже нужно чтобы сила начислялась за комментарии

**Comment by andrey-v** [comment]
Исправлено.
В конфиг добавлены [два параметра](https://github.com/altocms/altocms/blob/a6887edea02c174c5f190f15ce9c315919f3058b/common/config/config.php#L53-L54), которые регулируют количество знаков после запятой, которые будут выведены в шаблоне. Параметры не влияют на сохраненные данные, а только определяют количество выводимых знаков.
