### ISSUE TITLE
Обработка CSS-файлов, подключаемых через Smarty-функцию {asset ...}

### ISSUE THREAD

**Issue by aVadim483** [altocms/altocms#289]
Описание проблемы здесь: https://github.com/altocms/altocms/issues/241#issuecomment-68748555

**Comment by andrey-v** [comment]
В смарти функцию *asset* добавлен параметр **prepare** который устанавливает принудительную обработку ресурсов модулем ViewerAssets.
```
<link href="{asset file='/assets/css/static.css' prepare=true}" rel="stylesheet">
```
Так ка функция используется в основном не для обработки ресурса, а для получения ссылки на него параметр **prepare** по умолчанию выключен.

**Comment by aVadim483** [comment]
Андрей, там обязательно надо проверить такой кейс: в css-файле есть ссылка на локальный файл (либо шрифт, либо картинка), который лежит рядом или в где-то в соседней папке. И тогда этот файл должен копироваться в папку /_run/ и в итоговом css соответственно путь должен быть скорректирован. При обработке css-файлов из конфига это делалось, а вот при таком подключении были проблемы

**Comment by andrey-v** [comment]
Картинки копируются и ссылка в цсс на них меняются. Проверю с другими ресурсами.

**Comment by andrey-v** [comment]
Нужно было явно указать тип ресурса.
