### ISSUE TITLE
В админке не отображается статистика пользователя

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#290]
Не отображается ничего из представленного списка:
![3](https://cloud.githubusercontent.com/assets/6797881/5646893/014ef902-9692-11e4-9fbf-1dbc05ab3872.png)

**Comment by andrey-v** [comment]
Исправлено

**Comment by inliquid** [comment]
Андрей а как же эта часть?
![2](https://cloud.githubusercontent.com/assets/6797881/5694208/550d7b30-9959-11e4-9731-5544cd6d893c.png)

**Comment by andrey-v** [comment]
А её я не видел )
Будет исправлена

**Comment by andrey-v** [comment]
Исправлено,
![image](https://cloud.githubusercontent.com/assets/1106990/5694854/844f7724-998e-11e4-9c5c-cdea40e41a18.png)

**Comment by inliquid** [comment]
А что означает этот красный параметр - у меня он у всех пользователей имеет одинаковое значение

![1](https://cloud.githubusercontent.com/assets/6797881/5695400/864bb960-99b2-11e4-9090-714de5b03f28.png)

**Comment by aVadim483** [comment]
Зеленый - голосование в "плюс", красный - в "минус"

**Comment by inliquid** [comment]
Да я тоже так подумал, только вот что означает 1/0.0000 (т.е. сумма равна нулю) у всех пользователей, при том что эти пользователи минусы никому не ставили.

**Comment by aVadim483** [comment]
Т.е. юзер только зарегистрировался, и сразу имеет 1/0.000?

**Comment by inliquid** [comment]
Все куда сложнее. Обнаружил еще баг. Проверил еще раз на линуксе, где настроено объединение и сжатие css и js.
превое время в статистике не показывалось ниу одного пользователя значение для голосов за пользователей (средняя графа). После сброса кэша через "инструменты", стало показывать наоборот только эту графу.

![1](https://cloud.githubusercontent.com/assets/6797881/5697070/3631be62-99f7-11e4-855d-6608e51b181f.png)

**Comment by inliquid** [comment]
Еще один существенный момент - у всех юзеров теперь после сброса показывается только эта графа и одно и то же значение у всех - 2 / 0.840

**Comment by inliquid** [comment]
Забыл написать что включен мемкеш.

**Comment by aVadim483** [comment]
Все понятно, ошибка кеширования

**Comment by aVadim483** [comment]
Исправлено. Можно заменить только этот файл: https://github.com/altocms/altocms/blob/master/common/classes/modules/vote/Vote.class.php

**Comment by inliquid** [comment]
Так, теперь понятно откуда нули в минусе. Вернее понятно что есть еще баг.
При изменении рейтинга вручную в админке в минус сумма в минус остается равной нулю (сначала), при этом она ведет себя просто мистически, сначала красные цифры показывают один, голосую еще минус -> 2, еще раз -> снова 1... потом начинаю плюсовать, такая же мистика, то увеличивается то не увеличивается. Потом начинаю минусовать - красные цифры меняются, появляется ненулевое значение. Но когда я еще несколько минусов ставлю - все снова приходит к 1/0.0000 (т.е. число минусов должно увеличиваться, а происходит наоборот). При этом количество голосов у пользователя меняется.
![1](https://cloud.githubusercontent.com/assets/6797881/5709371/5dc30ab8-9aaa-11e4-9955-8463b8adc937.png)


Еще просьба - все-таки можно сделать так, чтобы вводить самому значение которое будет добавлять к рейтингу. Я так понимаю что тут коррекция происходит исходя из значения силы конкретного админа, что на мой взгляд не правильно. Не руками же в базу лезть....
