### ISSUE TITLE
Проблемы с добавлением комментариев на стену

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#293]
1. При добавлении комментария первого уровня все нормально. При попытке ответа на комментарий первого уровня - сообщения второго уровня появляются только после перезагрузки страницы.
2. Кнопка "Показать все X комментариев" - не работает.

Скины - start-kit и Brand.

![1](https://cloud.githubusercontent.com/assets/6797881/5663466/583d1e1c-9758-11e4-8b12-90f31329012b.png)

**Comment by andrey-v** [comment]
Исправлено
