### ISSUE TITLE
Проблемы с медиаресурсами

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#294]
'1'. Обнаружил, что в админке в "медиаресурсах", не учитывается использование изображений в качестве аватарок и фото профиля. Система предлагает их удалить, что очевидно вызовет недоумение пользователей.

![1](https://cloud.githubusercontent.com/assets/6797881/5689832/1bc989a2-987f-11e4-8c62-61488c065718.png)

'2'. В перечне медиаресурсов вообще нет аватарок блогов.

'3'. Кнопка "все типы" наверху лишняя и ведет на список блогов. Тоже касается кнопки "+"
![2](https://cloud.githubusercontent.com/assets/6797881/5689840/6525f7e8-987f-11e4-813c-bd3c531d84e9.png)

**Comment by andrey-v** [comment]
Механизм работы с изображениями, в том числе и с медиаресурсами полностью переработан в версии 1.1 https://github.com/altocms/altocms/issues/277

В том числе решены и эти проблемы.

**Comment by inliquid** [comment]
А как же быть тем кто остается на 1.0.*? 
А кнопки лишние?
