### ISSUE TITLE
Некорректная работа закрытых блогов

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#295]
Открываю новый баг, т.к. открылись новые подробности.

'1'. Создаю новый тип для блога со свободной подпиской, создаю экземпляр блога, и в администрировании вижу виджет "пригласить пользователей", который никак не реагирует на кнопку "пригласить". По логике должно быть что либо приглашение все-таки приходит (несмотря на свободную подписку), либо виджет не отображается вовсе.

'2'. На этом проблемы не заканчиваются. Создаю блог с подпиской по запросу. При этом:

'2.1'. Никакой технической возможности сформировать запрос администратору блога у пользователя нет. Т.е. фактически данный тип подписки не работает. 

'2.2'. Виджет "пригласить пользователей" точно также не работает, как и в п.1. Вообще ноль реакции.

'3'. Создаю блог с типом подписки по приглашению. Все ровно тоже самое. Ни отправить запрос, ни пригласить пользователя я не могу. Виджет "пригласить пользователя" не работает.

Шаблоны - brand и start-kit, последняя версия с гитхаба.

**Comment by inliquid** [comment]
Может быть объединить типы блогов "по запросу" и "по приглашению" - их разделение выглядит не естественным. Пусть на уровне шаблоне либо предоставляется та или иная возможность, либо нет. Просто странно почему если у меня блог по приглашению, я не могу рассмотреть заявку пользователя, и разрешить вступить в блог. Или наоборот если у меня блог по запросу, почему бы мне не пригласить кого-нибудь?

В любом случае я пока в глаза ни того не другого типа не увидел...

**Comment by andrey-v** [comment]
Пытаюсь воспроизвести ошибку (1) с такими настройками, но не получается:
- **Могут создавать пользователи** - Да
- **Минимальный рейтинг для создания** - 1
- **Подписка на блоги** - свободная
- **Кто может писать** - Только подписчики
- **Кто может читать** - Все
- **Кто может комментировать:** - Только подписчики
- **Показывать заголовки блогов** - Да
- **Индексировать контент** - Да
- **Тип контента** - Любой
- **Включен** - Да

**Comment by inliquid** [comment]
У меня тоже самое только минимальный рейтинг - 0, и комментировать могут все пользователи. Ты можешь проверить у меня на сайте.

**Comment by inliquid** [comment]
Отписал в личку.

**Comment by andrey-v** [comment]
А без сжатия и объединения скриптов?

**Comment by inliquid** [comment]
Отключил

**Comment by andrey-v** [comment]
1, 2.2, 3 - результат конфликта с плагином blogusers, остальное перенёс в отдельную задачу.
