### ISSUE TITLE
Слишком короткая длина названия типа блога 

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#296]
Ну очень короткая:

![1](https://cloud.githubusercontent.com/assets/6797881/5693529/f28d5236-9931-11e4-8468-cf454c3bf4d8.png)

Всего-то хотел написать по приглашениям.

**Comment by andrey-v** [comment]
Длина названия типа блога ограничена 32 символами. Если нужна большая длина то нужно в качестве названия указать фразу из языкового файла движка в двойных фигурных скобках. Сами языковые файлы нужно расположить в каталоге текстовок приложения **app/templates/language**.

Например, если создать там файлы *ru.php* и *en.php* и в них указать текстовки 
```php
<?php
return array(
    'my_type_hello_blog' => 'Закрытое сообщество (по приглашениям)',
);
```

то получится следующий результат:
![image](https://cloud.githubusercontent.com/assets/1106990/5694739/aa37c4ba-9988-11e4-8c5d-7c0d9e07074f.png)
