### ISSUE TITLE
Не работающий параметр " до какого размера ужимать картинки "

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#298]
Моуг только констатировать что указанный параметр в админке не на что не влияет, стало быть либо это баг, либо он должен быть убран
![1](https://cloud.githubusercontent.com/assets/6797881/5777791/c6ef5830-9da6-11e4-8254-ce62d0d5e0ab.png)

**Comment by andrey-v** [comment]
Параметр действительно нигде кроме админки не фигурирует.

**Comment by inliquid** [comment]
См. также -> https://github.com/altocms/altocms/issues/336

**Comment by andrey-v** [comment]
Исправлено, 70d6908f03f4aba07d2f3bfa5d0670060224767a
