### ISSUE TITLE
Некорректная обработка языковых файлов

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#299]
1. Языковой файл плагина ls перебивает системные установки.
2. Языковой файл плагина ls в папке app (/app/plugins/ls/templates/language) не перекрывает языковой файл в папке плагина.

**Comment by aVadim483** [comment]
Обработка языковых файлов плагина Ls выполняется действительно нестандартно, это сделано для обеспечения совместимости со старыми шаблонами.

Для того, чтобы переопределить текстовки плагина Ls, нужно создать языковой файл в директории /app/templates/language, и там задать все переопределяемые тексты.

**Comment by inliquid** [comment]
>Для того, чтобы переопределить текстовки плагина Ls, нужно создать языковой файл в >директории /app/templates/language, и там задать все переопределяемые тексты.

Каким образом, если там уже лежит ru.php и языковой файл плагина переопределяет все эти заданные в нем текстовки на свои?

**Comment by aVadim483** [comment]
Да, была ошибка в логике. Пофиксено. Сейчас последним подгружается языковой файл из /app/plugins/ls/templates/language
