### ISSUE TITLE
Загрузка изображений в фотосет не работает на планшетах и др. девайсах

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#300]
Альто использует для загрузки в фотосет загрузчик на основе swf. В результате на Android/iOS загрузка в фотосет перестает работать. Это серьезная проблема, и странно что никто еще не зарепортил баг. 
Прошу только не пишите, что мол это исправлено в следующей версии, которая еще в разработке, не тестировалась и под которую придется все переделывать. Если это очень сложная доработка, то нужен хотябы какой-то workaround.

**Comment by aVadim483** [comment]
Не хочу огорчать, но это действительно весьма непростая доработка, и именно поэтому решение этой проблемы (а она известна, и давно) вынесено в версию 1.1. Как уже анонсировалось, механизмы работы с изображениями в этой версии значительно переработаны, в т.ч. и реализован новый загрузчик. Тратить ресурсы на придумывание каких-то костылей в рамках ветки 1.0.х считаю нецелесообразным.

**Comment by inliquid** [comment]
Но проблема в том что версия 1.1 пока отсутствует (не говоря уж про тестирование). Разве сложно реализовать чтобы при недоступности flash плеера предоставлялся обычный интерфейс выбора файла, пусть даже добавление будет по 1 штуке?

**Comment by andrey-v** [comment]
Исправлено в версии 1.1
В версии 1.0 изменений по этой задаче вносится не будет (
