### ISSUE TITLE
tinymce.min.js подключается даже когда визуальный редактор не используется

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#303]
В целях оптимизации надо бы убрать это подключение. Насколько я понимаю в шаблон он попадает из переменной:

{$aHtmlHeadFiles.js}

**Comment by andrey-v** [comment]
Такого функционала в движке просто нет - отключать скрипты в зависимости от какого-то конфига Alto не умеет. И на самом деле ситуация тут более общая, ведь неиспользуемых скриптов может быть и больше (в шаблоне включаются отключаются скрипты, например), потому вынес проблему в отдельную большую задачу - https://github.com/altocms/altocms/issues/314.

Спасибо за идею )
