### ISSUE TITLE
Ошибки при включенном кешировании смарти шаблонов (cache_lifetime=true)

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#305]
Добавил к топику поле с типом "файл". Не что не предвещало проблем, т.к. раньше уже вроде тестировалось, однако при добавлении любого файла - вылетает фатальная ошибка

[LOG:1421867426.567-54BFF9A28A84A][2015-01-21 22:10:26][PID:8770][ERROR][[
E_ERROR [1] Call to undefined function content_54bff9a27eb5a7_94729153() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

**Comment by inliquid** [comment]
Строка 295 в указанном файле выделена

            try {
                ob_start();
                array_unshift($_template->_capture_stack, array());
                //
                // render cached template
                //
                <b>$_template->properties['unifunc']($_template);</b>
                // any unclosed {capture} tags ?
                if (isset($_template->_capture_stack[0][0])) {
                    $_template->capture_error();
                }
                array_shift($_template->_capture_stack);
                $_output = ob_get_clean();
            }
            catch (Exception $e) {
                ob_get_clean();
                throw $e;
            }

**Comment by inliquid** [comment]
При этом топик с файлом действительно добавляется. (Пользователь видит только ошибку)

**Comment by aVadim483** [comment]
Какой шаблон? Если один из родных, то менялся ли?
На start-kit только что проверил - добавляется топик с файлом.

**Comment by inliquid** [comment]
Да в том то и дело что у меня на локалхосте тоже все ок было. Сейчас уже не смогу проверить, возможно завтра. Шаблон brand. 

Топик-то добавляется, только вот юзеру выводится эта странная ошибка вместо топика.

**Comment by andrey-v** [comment]
А если очистить кэш шаблонов  ошибка повторится? Такое ощущение, что закэшировался шаблон без дополнительного поля файла, а потом, когда поле файла было подключено стал выводится не изменённый кэш.

**Comment by inliquid** [comment]
Да в первую очередь проверял - сбрасывал все через админку + руками сдержимое директорий, +Crtrl-F5 на странице. Единственное могу в рамках паранойи еще и php5-fpm ребутнуть, вдруг opcache как-то хитро что-то закешировал o_O

**Comment by inliquid** [comment]
Неа тоже самое... такое ощущение что вылетает ошибка при перенаправлении обратно. Можешь посмотреть у меня ежом.

**Comment by inliquid** [comment]
Редактирование - добавление и удаление проблем не вызывает.

**Comment by andrey-v** [comment]
Права на запись у папки с кэшированными шаблонами есть?
*- _tmp/templates/[шаблон]*
*- _tmp/templates/[шаблон]/cache*
*- _tmp/templates/[шаблон]/compiled*

**Comment by inliquid** [comment]
Есть, они бы после ручной чистки и не создались если бы не было

root@mail:/var/www/example.com/_tmp/templates/brand-light# ls -la
total 24
drwxr-xr-x 4 www-data www-data  4096 Янв 22 11:15 .
drwxr-xr-x 4 www-data www-data  4096 Янв 22 11:15 ..
drwxrwx--x 2 www-data www-data  4096 Янв 22 13:23 cache
drwxr-xr-x 2 www-data www-data 12288 Янв 22 12:31 compiled
root@mail:/var/www/example.com/_tmp/templates/brand-light#

**Comment by inliquid** [comment]
Содержимое папок

root@mail:/var/www/example.com/_tmp/templates/brand-light/compiled# ls -la
total 508
drwxr-xr-x 2 www-data www-data 12288 Янв 22 12:31 .
drwxr-xr-x 4 www-data www-data  4096 Янв 22 11:15 ..
-rw-r--r-- 1 www-data www-data  1249 Янв 22 11:15 light^0717f552bc2d40bb4d7700dbe40e42aed48d2b97.file.common.toolbar.tpl.php
-rw-r--r-- 1 www-data www-data  3178 Янв 22 11:15 light^0ad737e963244e64496bb6ea4dd7307dd9d0f4c0.file.widget.blogs.tpl.cache.php
-rw-r--r-- 1 www-data www-data  3337 Янв 22 11:15 light^14e9249cc1d5dfc4f6f23807093821fd5d0fa4f1.file.widget.stream.tpl.cache.php
-rw-r--r-- 1 www-data www-data  5116 Янв 22 11:15 light^15545d7cfe2c02417c0e36a00a1739c70dfeb33a.file.field.poll-edit.tpl.php
-rw-r--r-- 1 www-data www-data  2671 Янв 22 11:17 light^16d56e43733a4ca1a26b17247ced3f7d73ad533a.file.opacity-slider.tpl.cache.php
-rw-r--r-- 1 www-data www-data  9975 Янв 22 11:15 light^183da396b7831ff301551cc450591fc193d2b406.file.common.header_top.tpl.php
-rw-r--r-- 1 www-data www-data  4908 Янв 22 11:17 light^1b2450f3af1d36f43f515a265c86112256dd2011.file.widget.blog.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1639 Янв 22 11:17 light^1f605cfb2584c3947ca090b9819304484bb73ecb.file.topic.show.tpl.php
-rw-r--r-- 1 www-data www-data 11405 Янв 22 12:31 light^20b110ae2d7beb27978a4401ef162d96d715c798.file.action.login.index.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1465 Янв 22 11:17 light^2160016818d8cd27884f251d722bf8a0db920a58.file.link-color-picker.tpl.cache.php
-rw-r--r-- 1 www-data www-data  4554 Янв 22 11:17 light^28e08febe85b1c373516e6b8446fc7bff0570d6d.file.field.tags-show.tpl.php
-rw-r--r-- 1 www-data www-data  5941 Янв 22 11:15 light^381fdb50770cdceff4e3035b545041ca8ccf73ca.file.menu.content-create.tpl.php
-rw-r--r-- 1 www-data www-data  1483 Янв 22 11:17 light^4010a715bc0ba8f144b0b484e8f51d95764703b8.file.header-color-picker.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2826 Янв 22 11:15 light^434697cdea0ace292fb4835a03c81272753cc732.file.modal.upload_photoset.tpl.php
-rw-r--r-- 1 www-data www-data  1485 Янв 22 11:15 light^43c0dc93b49023a1fc429f9f3fa201ad51d5a4d8.file.footer-block2.tpl.php
-rw-r--r-- 1 www-data www-data 20845 Янв 22 11:17 light^44ce5b51e0c710f71a12a2ad3bdb87be0bae2123.file.topic.type_default-show.tpl.php
-rw-r--r-- 1 www-data www-data  8117 Янв 22 11:15 light^482ba6def3e899fb9c85ea50770b14c56e4055c8.file.field.photoset-edit.tpl.php
-rw-r--r-- 1 www-data www-data  1745 Янв 22 11:15 light^4ddc3eaffad7429cee451da97c1b40393c30c35d.file.widget.toolbar_admin.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1674 Янв 22 11:17 light^5654a6071dd88904f30c932fa98263b6056f5457.file.header-slider.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1031 Янв 22 11:17 light^5ae3deabf3a96637adbc93042a77c20c40545988.file.background-type.tpl.cache.php
-rw-r--r-- 1 www-data www-data  5876 Янв 22 11:15 light^604235aabbeb52f7bba78d3c56114f88ce0fbe83.file.widget.tags.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1723 Янв 22 11:15 light^64f2daceecd16633a7890101ef1b421771da4e25.file.fsicons.tpl.php
-rw-r--r-- 1 www-data www-data  2066 Янв 22 11:15 light^6874075a87bbde0d4127375508dbf2ee345182c6.file.menu.main_pages.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1473 Янв 22 11:17 light^6e269c8d0569637c0f4882f23c4c9884aecaf2e0.file.font-color-picker.tpl.cache.php
-rw-r--r-- 1 www-data www-data  6163 Янв 22 11:15 light^6edba5d50b3356b0d4b878f9ce6a117ea7b77cb5.file.widget.stream_comment.tpl.cache.php
-rw-r--r-- 1 www-data www-data  5172 Янв 22 11:15 light^72bd88528150eb4b41cc348cf42d5d4edaaaea8c.file.common.pagination.tpl.php
-rw-r--r-- 1 www-data www-data  1475 Янв 22 11:15 light^7921e4c7307c543e674c32da3c4b8131186ee2da.file.modal.empty.tpl.php
-rw-r--r-- 1 www-data www-data  1311 Янв 22 11:15 light^869c35921fedda0c615edc7febe613ffa0e4ac16.file.menu.content.tpl.php
-rw-r--r-- 1 www-data www-data  1589 Янв 22 11:15 light^8a2a3e5513b8e54306b3c528eb6c9de4c609b5e1.file.common.sidebar.tpl.php
-rw-r--r-- 1 www-data www-data  8277 Янв 22 11:15 light^8adcd38bccd228592af8a1e1398593e0328765eb.file.header-brand.tpl.php
-rw-r--r-- 1 www-data www-data  1864 Янв 22 11:15 light^8cacda1e853df5f45606868575ad044c827fe750.file.widget.blogInfo.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2558 Янв 22 11:15 light^8da6b0980ce53a34a54b270afecef7406e7d3f09.file.editor.markitup.tpl.cache.php
-rw-r--r-- 1 www-data www-data  9628 Янв 22 11:15 light^931452abda4cfe66210a2334fe7eb5a303db0a25.file.modal.upload_img.tpl.cache.php
-rw-r--r-- 1 www-data www-data 21097 Янв 22 11:15 light^94e1a27f804bbda780c143c05e62c5e2818c6bd7.file.action.index.index.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2004 Янв 22 11:15 light^994117310da1f390001fc777db597affde684a7e.file.topic.edit.tpl.php
-rw-r--r-- 1 www-data www-data 10250 Янв 22 11:15 light^a562e3d521a1d51bd9a7429bb41038896eea5bd2.file.widget.brandingTopic.tpl.cache.php
-rw-r--r-- 1 www-data www-data  7302 Янв 22 11:17 light^a9144f3653e3fe5eacf6a0f4bde48584b9c533c4.file.upload-blog-image.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2432 Янв 22 11:17 light^aad167b4fc7d0e63693dd01f10bbfe6a4b3b2a66.file.field.custom.file-show.tpl.php
-rw-r--r-- 1 www-data www-data  1342 Янв 22 11:15 light^ada9412c9537325992bb6f5429419cad6989eac8.file.widget.toolbar_scrollup.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2254 Янв 22 11:15 light^b171689507fb5ea1f4f632ca82a2b16f15bd1321.file.widget.blogs_top.tpl.cache.php
-rw-r--r-- 1 www-data www-data  3435 Янв 22 11:15 light^b5a1d4cd72ceb46568ce356b81472c6998beda98.file.common.messages.tpl.php
-rw-r--r-- 1 www-data www-data 22152 Янв 22 11:17 light^b80d534828fb3f91807ed13f3a5e298af6f1740a.file.action.blog.topic.tpl.cache.php
-rw-r--r-- 1 www-data www-data  4631 Янв 22 11:15 light^b81d032bcdb49b7ae7fd05d7cab9cb21538548f8.file.modal.write.tpl.php
-rw-r--r-- 1 www-data www-data  6218 Янв 22 11:15 light^be38e782e850c0456b118023c5b21d8960b8d8e6.file.menu.main.tpl.php
-rw-r--r-- 1 www-data www-data  7247 Янв 22 11:15 light^c014aa59c67530e52630e28b607e0ac48471064a.file.field.tags_help.tpl.php
-rw-r--r-- 1 www-data www-data  6931 Янв 22 11:15 light^c0f414586f58fc4e3028e793c43bd78ba363df7f.file.menu.topics.tpl.php
-rw-r--r-- 1 www-data www-data  1807 Янв 22 11:15 light^c6947af552666b1117084f1c0e76c451ad0e291a.file.common.editor.tpl.php
-rw-r--r-- 1 www-data www-data  2382 Янв 22 11:17 light^ccea8382fff8bd6f1eff8be993b3d9a99f0357c1.file.modal.crop_img.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2397 Янв 22 11:17 light^d1c74595b4e29d619d3e5464b8c554136a435ae4.file.widget.toolbar_comment.tpl.cache.php
-rw-r--r-- 1 www-data www-data 17905 Янв 22 11:17 light^d6a3d918c371d6738500c585fb52335f7377279d.file.css.inject.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1006 Янв 22 11:15 light^d8ced6734077aa650670616643dde4ab3faba883.file.copy.tpl.php
-rw-r--r-- 1 www-data www-data 11292 Янв 22 11:15 light^da0dcf8d0320f91747aa0af594c473b4ef7f69f6.file.topic.type_default-edit.tpl.php
-rw-r--r-- 1 www-data www-data  2719 Янв 22 11:15 light^dab03a13a52d558ae807f14ccba85d252a10d841.file.modal.favourite_tags.tpl.php
-rw-r--r-- 1 www-data www-data  5181 Янв 22 11:15 light^dabac2d2c8fac4c50284cd563e88c3d80df11c78.file.common.statistics_performance.tpl.cache.php
-rw-r--r-- 1 www-data www-data 21198 Янв 22 11:15 light^dc05444bd673ed9835400f163f6b2841a2db1a7c.file.action.content.add.tpl.cache.php
-rw-r--r-- 1 www-data www-data  2145 Янв 22 11:15 light^dd423d700b453184b92e6adc2e8c61645344ccd1.file.footer-block1.tpl.php
-rw-r--r-- 1 www-data www-data  3350 Янв 22 11:15 light^e8c888f7c2127d8b7348340ea4bbaa61fbc411ac.file.block.top.tpl.cache.php
-rw-r--r-- 1 www-data www-data 16807 Янв 22 11:17 light^eb07fc5ded6caa17004df4fac87964bb074aa420.file.comment.tree.tpl.php
-rw-r--r-- 1 www-data www-data  2609 Янв 22 11:15 light^eb41b99b9e252f5a895596e93d8725e10a072242.file.topic.list.tpl.php
-rw-r--r-- 1 www-data www-data  1563 Янв 22 11:15 light^ee000537e6e4e10cacbc8ce04ce8db579fdf7efe.file.field.tags-edit.tpl.php
-rw-r--r-- 1 www-data www-data  6783 Янв 22 11:17 light^eea5ead68c40fa948c1c44c90548ebd935a82a26.file.comment.paging.tpl.php
-rw-r--r-- 1 www-data www-data  3280 Янв 22 11:15 light^ef73860bc5d19be1534592d79d22ccdfc62371e2.file.field.custom.file-edit.tpl.php
-rw-r--r-- 1 www-data www-data  9768 Янв 22 11:15 light^f254bf4ea9aca9c4afe18e862f3196ce514df7ba.file.modern.tpl.php
-rw-r--r-- 1 www-data www-data   963 Янв 22 11:15 light^f52c4ea3a4c240ed5fd968a8f8d3ea92f9774792.file.imenu.tpl.php
-rw-r--r-- 1 www-data www-data  1813 Янв 22 11:16 light^f9dd3bb4091bb793e9805c290c63059dea449ff0.file.email.topic_new.tpl.cache.php
-rw-r--r-- 1 www-data www-data  1825 Янв 22 11:15 light^fee054121407575c4fde96557e99b3533727aec4.file.common.header_nav.tpl.php
root@mail:/var/www/example.com/_tmp/templates/brand-light/compiled#

**Comment by inliquid** [comment]
root@mail:/var/www/example.com/_tmp/templates/brand-light/cache# ls -la
total 328
drwxrwx--x 2 www-data www-data  4096 Янв 22 13:23 .
drwxr-xr-x 4 www-data www-data  4096 Янв 22 11:15 ..
-rw-r--r-- 1 www-data www-data  6780 Янв 22 13:23 light^0ad737e963244e64496bb6ea4dd7307dd9d0f4c0.widget.blogs.tpl.php
-rw-r--r-- 1 www-data www-data  1785 Янв 22 13:23 light^14e9249cc1d5dfc4f6f23807093821fd5d0fa4f1.widget.stream.tpl.php
-rw-r--r-- 1 www-data www-data  2312 Янв 22 13:23 light^1b2450f3af1d36f43f515a265c86112256dd2011.widget.blog.tpl.php
-rw-r--r-- 1 www-data www-data  9121 Янв 22 13:05 light^20b110ae2d7beb27978a4401ef162d96d715c798.action.login.index.tpl.php
-rw-r--r-- 1 www-data www-data  1151 Янв 22 13:23 light^4ddc3eaffad7429cee451da97c1b40393c30c35d.widget.toolbar_admin.tpl.php
-rw-r--r-- 1 www-data www-data  6860 Янв 22 13:23 light^604235aabbeb52f7bba78d3c56114f88ce0fbe83.widget.tags.tpl.php
-rw-r--r-- 1 www-data www-data  1085 Янв 22 13:23 light^6874075a87bbde0d4127375508dbf2ee345182c6.menu.main_pages.tpl.php
-rw-r--r-- 1 www-data www-data  7109 Янв 22 13:23 light^6edba5d50b3356b0d4b878f9ce6a117ea7b77cb5.widget.stream_comment.tpl.php
-rw-r--r-- 1 www-data www-data  1779 Янв 22 13:16 light^8cacda1e853df5f45606868575ad044c827fe750.widget.blogInfo.tpl.php
-rw-r--r-- 1 www-data www-data  3817 Янв 22 13:23 light^8da6b0980ce53a34a54b270afecef7406e7d3f09.editor.markitup.tpl.php
-rw-r--r-- 1 www-data www-data  7610 Янв 22 13:23 light^931452abda4cfe66210a2334fe7eb5a303db0a25.modal.upload_img.tpl.php
-rw-r--r-- 1 www-data www-data 77431 Янв 22 13:05 light^94e1a27f804bbda780c143c05e62c5e2818c6bd7.action.index.index.tpl.php
-rw-r--r-- 1 www-data www-data  5079 Янв 22 13:16 light^a562e3d521a1d51bd9a7429bb41038896eea5bd2.widget.brandingTopic.tpl.php
-rw-r--r-- 1 www-data www-data  1029 Янв 22 13:23 light^ada9412c9537325992bb6f5429419cad6989eac8.widget.toolbar_scrollup.tpl.php
-rw-r--r-- 1 www-data www-data  5535 Янв 22 13:23 light^b171689507fb5ea1f4f632ca82a2b16f15bd1321.widget.blogs_top.tpl.php
-rw-r--r-- 1 www-data www-data 68132 Янв 22 13:23 light^b80d534828fb3f91807ed13f3a5e298af6f1740a.action.blog.topic.tpl.php
-rw-r--r-- 1 www-data www-data  1963 Янв 22 12:01 light^ccea8382fff8bd6f1eff8be993b3d9a99f0357c1.modal.crop_img.tpl.php
-rw-r--r-- 1 www-data www-data  1439 Янв 22 13:23 light^d1c74595b4e29d619d3e5464b8c554136a435ae4.widget.toolbar_comment.tpl.php
-rw-r--r-- 1 www-data www-data   796 Янв 22 13:23 light^d6a3d918c371d6738500c585fb52335f7377279d.css.inject.tpl.php
-rw-r--r-- 1 www-data www-data  2747 Янв 22 13:23 light^dabac2d2c8fac4c50284cd563e88c3d80df11c78.common.statistics_performance.tpl.php
-rw-r--r-- 1 www-data www-data 63580 Янв 22 13:16 light^dc05444bd673ed9835400f163f6b2841a2db1a7c.action.content.add.tpl.php
-rw-r--r-- 1 www-data www-data  3238 Янв 22 13:05 light^e8c888f7c2127d8b7348340ea4bbaa61fbc411ac.block.top.tpl.php
-rw-r--r-- 1 www-data www-data  1240 Янв 22 13:18 light^f9dd3bb4091bb793e9805c290c63059dea449ff0.email.topic_new.tpl.php

**Comment by andrey-v** [comment]
Попробуй отключить кэширвоание шаблонов установив
$config['smarty']['cache_lifetime']         = false;

**Comment by inliquid** [comment]
Без кеширования работает...
Но этож баг, да? =)

**Comment by andrey-v** [comment]
Да

**Comment by inliquid** [comment]
Сегодня отключил это доп поле, тестировал без него и умудрился поймать такую же историю. Воспроизвести не удалось, но похоже что проблема может быть не только с этим дополнительным полем.

**Comment by andrey-v** [comment]
Дело, наверное, не в поле, а в самом кэшировании шаблонов.

**Comment by inliquid** [comment]
Но с этим полем 100% воспроизводимость. До этого не сталкивался.

**Comment by inliquid** [comment]
Сегодня эта ошибка выводилась в лог одновременно с другим старым странным сообщением, которое пишется постоянно если нет объединения/сжатия js.

[LOG:1422091192.273-54C363B842AFE][2015-01-24 12:19:52][PID:19517][ERROR][[
E_USER_WARNING [512] Can not prepare asset file "assets/js/script.js" (/var/www/example.com/engine/classes/modules/viewerasset/entity/Package.entity.class.php on line 166)
--- call stack ---
Func::SysWarning() in /var/www/example.com/engine/classes/modules/viewerasset/entity/Package.entity.class.php on line 166
ModuleViewerAsset_EntityPackage->MakeSingle() in /var/www/example.com/engine/classes/modules/viewerasset/entity/Package.entity.class.php on line 285
ModuleViewerAsset_EntityPackage->PreProcess() in /var/www/example.com/engine/classes/modules/viewerasset/entity/PackageJs.entity.class.php on line 64
ModuleViewerAsset_EntityPackageJs->PreProcess() in /var/www/example.com/engine/classes/modules/viewerasset/ViewerAsset.class.php on line 672
ModuleViewerAsset->Prepare()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/engine/classes/modules/viewer/Viewer.class.php on line 1529
PluginLs_ModuleViewer->ViewerAsset_Prepare() in /var/www/example.com/engine/classes/modules/viewer/Viewer.class.php on line 1529
ModuleViewer->BuildHeadFiles() in /var/www/example.com/engine/classes/modules/viewer/Viewer.class.php on line 2060
ModuleViewer->Shutdown() in /var/www/example.com/engine/classes/core/Engine.class.php on line 430
Engine->ShutdownModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 418
Engine->ShutdownModules() in /var/www/example.com/engine/classes/core/Engine.class.php on line 314
Engine->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 199
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1422091192.273-54C363B842AFE]

[LOG:1422091192.854-54C363B8D067C][2015-01-24 12:19:52][PID:19517][ERROR][[
E_ERROR [1] Call to undefined function content_54c363b8c73693_14239486() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

**Comment by andrey-v** [comment]
Эта ошибка (первая) может возникнуть когда какой-то плагин подключает не существующий файл   скрипта в основной файле плагина, движок его хочет отправить в assets, а найти не может.

**Comment by inliquid** [comment]
Почему эта ошибка отображается чуть ли не при каждом запросе (возможно при каждом) но при объединении и сжатии js - исчезает?

**Comment by andrey-v** [comment]
При включенном сжатии в assets копируются два скрипта, которые собираются из обстальных - один раз и эти два скрипта всегда есть. А при отключенном плагин хочет свой конкретный скрипт, а не один общий.

**Comment by inliquid** [comment]
приплыли... все сломалось и теперь при добавлении любого поста такая ошибка

[LOG:1422453638.209-54C8EB8633128][2015-01-28 17:00:38][PID:26668][ERROR][[
E_ERROR [1] Call to undefined function content_54c8eb853ddea1_17050224() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

]][END:1422453638.209-54C8EB8633128]

[LOG:1422453688.265-54C8EBB840A31][2015-01-28 17:01:28][PID:26671][ERROR][[
E_ERROR [1] Call to undefined function content_54c8ebb83328d3_77246333() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

]][END:1422453688.265-54C8EBB840A31]

[LOG:1422453749.532-54C8EBF581FF2][2015-01-28 17:02:29][PID:26671][ERROR][[
E_ERROR [1] Call to undefined function content_54c8ebf57438e3_37767313() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

]][END:1422453749.532-54C8EBF581FF2]

[LOG:1422453793.189-54C8EC212E3C2][2015-01-28 17:03:13][PID:26668][ERROR][[
E_ERROR [1] Call to undefined function content_54c8ec21219dc2_62844183() (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 295)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---



Доп. поле отключено. Тестовый юзер тот же.

**Comment by aVadim483** [comment]
Но "все сломалось", наверное, после какого-то действия? Или работало, работало и вдруг сломалось?

**Comment by inliquid** [comment]
В том-то и дело что непонятно. Делалаось что-то по мелочи, ничего особенного...

**Comment by inliquid** [comment]
Менял конфиг дефолтного скина с start-kit на brand, попробоал вернуть - не помогло.
Может можно как-то дополнительную информацию собрать в чем ошибка?

**Comment by inliquid** [comment]
Пока проблема гарантированно воспроизводится - можно попробовать собрать данные. Но мне придется в ближайшее время все-таки выключить этот параметр (если проблема не будет локализована). Поэтому если есть идеи - прошу поделиться.

**Comment by aVadim483** [comment]
Смог воспроизвести ошибку. Это ошибка Smarty. Обновление Smarty до 3.1.21-dev проблему решает. Но это - dev-версия, поэтому включать ее в стабильный релиз не очень хочется. Если для Вас использование кеширования Smarty критично, то можете обновиться самостоятельно

**Comment by inliquid** [comment]
Ок пока что поживу без кеширования.

**Comment by inliquid** [comment]
> Обновление Smarty до 3.1.21-dev проблему решает. Но это - dev-версия

Что-то я не пойму. В движке версия 3.1.19. Версия 3.1.21 - стабильная, и вышла 18 октября. http://www.smarty.net/download

**Comment by aVadim483** [comment]
Я скачивал именно эту версию - 3.1.21, и там в исходниках номер значится 3.1.21-dev, и тут http://smarty-php.googlecode.com/svn/trunk/distribution/change_log.txt тоже:
```
===== 3.1.21-dev ===== (xx.xx.2014)
 18.10.2014
 - ...
```
У разработчика, видимо, система версионирования такая - "стабильная", но при этом "девелоперская".

**Comment by inliquid** [comment]
Странно, вот я скачал по ссылке выше:
 ===== 3.1.22-dev ===== (xx.xx.2014)
 ===== 3.1.21 ===== (18.10.2014)
 18.10.2014
 - composer moved to github
 - add COMPOSER_RELEASE_NOTES

Т.е. как бы "рыба" идет я так понял сразу пустая под следующую версию. в общем поставил этот смарти, потестирую с ним. Пока вроде ок.

**Comment by inliquid** [comment]
Версия 3.1.21 работает хорошо, багов больше не появлялось.

**Comment by andrey-v** [comment]
Smarty обновлен до версии 3.1.21
