### ISSUE TITLE
Вставка ссылки на логин пользователя через редактор

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#306]
1. Поскольку, появилась настройка отображаемого имени, и в качестве отображаемого имени может использоваться не логин, нужно сделать так, чтобы при вставке ссылки на пользователя выводилось также DisplayName.
2. Совершенно не понятно, зачем при этом для всех пользователей слева выводится одна и та же картинка. Нужно либо выводить аватар пользователя, либо не выводить ничего.

**Comment by andrey-v** [comment]
1. Исправлено
2. В версии 1.1. вывод имени пользователя [перенесён в шаблон](https://github.com/altocms/altocms/blob/ver1.1/common/templates/skin/start-kit/tpls/snippets/snippet.user.tpl) и будет зависеть от реализации конкретной темы оформления. Теперь вместе с именем пользователя можно вывести не только его лого, а вообще что угодно )
