### ISSUE TITLE
Некорректный выбор исходного изображения движком для нарезки изображений

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#308]
Кажется нашел баг, который может являться причиной того что изображения в некоторых случаях получаются низкого качества. 

Дело в том, что мне нужно было подсунуть аватарку блога определенного размера, и чтобы разобраться как движок их выбирает пришлось поэкспериментировать.

Итак имеем:
1) Папку templates\skin\brand\assets\images\avatars, в которой нарезаны следующие изображения для аватарки блога
avatar_blog_100x100.png
avatar_blog_24x24.png
avatar_blog_48x48.png
avatar_blog_64x64.png

2) В шаблоне я руками добавил такой вызов:
`{$oBlog->getAvatarPath(120)}`
изображения такого размера как следует из п.1 нету.

3) Получил вот такое изображение:
![1](https://cloud.githubusercontent.com/assets/6797881/5888513/4034407c-a412-11e4-9eb5-a72611f3196f.png)

Т.е. изображение получилось очень пиксельное. Я честно говоря не придал этому значения сначала.

4) Далее мне нужно было понять, подхватывает ли движок из папки assets изображения конкретного размера и я скопировал avatar_blog_100x100.png -> avatar_blog_120x120.png, размер не менялся.

И вот что я после этого получил

![2](https://cloud.githubusercontent.com/assets/6797881/5888503/c837ea6a-a411-11e4-8608-d4114ca080eb.png)

При этом, я создавал в папке uploads а не assets изображение очень большого размера 1500x1500 - и движок его подхватывал для нарезки 120x120.

В данном же сценарии, похоже что движок берет изображение 24x24 или 48x48 в качестве основы.

**Comment by andrey-v** [comment]
Если нужно что бы аватарка блога нарезалась размером 120x120 тогда в папке assets темы оформления должна лежать исходная картинка заранее большего размера, например та же 1500x1500. Если её там нет, значит такой размер аватарки не предусмотрен темой оформления и всё.

Если сейчас в каталоге assets лежат, например, файлы:
*avatar_blog_24x24.png*
*avatar_blog_64x64.png*
*avatar_blog_100x100.png*
*avatar_blog_500x500.png*

то они будут использоваться следующим образом:
*avatar_blog_500x500.png* - для нарезки картинок 500-101px
*avatar_blog_500x500.png* - для нарезки картинок 500-101px
*avatar_blog_500x500.png* - для нарезки картинок 500-101px

**Comment by inliquid** [comment]
1) Почему если положить большой файл соотвествующего наименования в uploads, движок нарезает из этого файла аватарку?
2) разве не логично для нарезки брать за основу максимальное разрешение а не минимальное?
3) И наконец, логика движка была изменена таким образом чтобы пользователь, или создатель шаблона не думал о том чтобы нарезать картинки под все изображения. Я просто указываю какие параметры мне нужны и движок режет сам из этого изображения. То что ты говоришь это олдовая ЛС-овская тема и она противоречит данной концепции. (Именно поэтому я и столкнулся с проблемой, иначе бы так и делал как ты говоришь - нарезал, поверь мне не сложно)

Ну и напоследок, проблема потери качества все еще есть, а у меня такое ощущение что я совершенно зря распинаюсь.

**Comment by andrey-v** [comment]
1. Еще раз сейчас попробовал - не берет он основную из uploads (. Вообще-то не важно, в папку uploads не стоит вручную копировать файлы.

2. По второму - логика проста: в качестве основы для обрезки берётся картинка большего размера, если её нет то плохо. Если брать меньшую то по любому уже будет потеря качества, как ни старайся даже если разница в 10-20 пискселей, хотя согласен, что брать нужно ближайшую.

3. Нет-нет, я может не понятно написал, для нарезки не нужно делать наборы картинок 24/64/100/500 и т.д. как было в LS Достаточно одну, но б**о**льшего размера - остальные (любого совершенно, но меньшего размера) из нёё нарежутся автоматом, и нет тут ни намёка на ls-овский подход.

**Comment by inliquid** [comment]
1 - странно, посмотрю еще.

Вопрос, почему не сделать чтобы по умолчанию бралось не первое попавшееся а изображение с максимальным разрешением, если требуется нарезать картинку бОльшего чем есть разрешения?

**Comment by andrey-v** [comment]
А разница? Если отличаются изображения на 10-20 пикселей как у тебя (100-120), то согласен, такой подход может и оправдан, а если на 50px или 100px. Тогда, какое изображение не бери все равно плохо будет. 

Да и растяжка в 10 пикселей на некоторых изображениях может вполне бросаться в глаза, но этого не исправить же :(

**Comment by inliquid** [comment]
Выше пример, разница огромна, она берет походу минимальное резрешение...

**Comment by inliquid** [comment]
И еще вопрос - что будет если файл загружен пользователем, не получится ли так что допустим первые обращения будут к тем местам шаблона, где нужно низкое разрешение 100, 200px, а когда мне потребуется нарезать из аватарки бОльшее разрешение, скажем 1000 px использоваться будет уже не оригинал?

**Comment by andrey-v** [comment]
Нет, не получится. Все картинки режутся от оригинала, и только в случае дефолтных аватаров пользователя/блога из темы - от большей картинки.

**Comment by andrey-v** [comment]
Да, кстати. 
Если в папку assets положить картинку аватара блога вообще без размеров (такую: **avatar_blog.jpg**), то принудительно будет резатся она не взирая на её размер - и в большую и в меньшую сторону, вот.

**Comment by inliquid** [comment]
аватары пользователей - такая же система?

**Comment by andrey-v** [comment]
Да
