### ISSUE TITLE
Обновления с ГитХаба: не пойму

### ISSUE THREAD

**Issue by lexuspro** [altocms/altocms#310]
Добрый вечер, уважаемые! Подписан на уведомления с гита на все происходящие изменения, правки движка чтобы оперативно вносить их в шаблон.

Однако, что за чертовщина, не пойму. 
основная репозитория на гите тут - https://github.com/altocms/altocms
На против самой папки/файла справа я отслеживаю когда в последний раз вносились изменения, верно?
Уже не в первый раз происходит такая ситуация, когда в этом разделе обсуждений/вопросов/задач происходит правка какого-то файла и к вопросу привязывается ссылка на подробную страницу с подсвеченным кодом что конкретно правилось, но почему это я не могу отслудить в главной репозитории движка?.

Пример, сейчас решается задача выводов сниппетов в редакторе Андреем, при переходе по его ссылкам я вижу папки /templates/skin/start-kit/tpls/snippets и все что там изменялось, 
https://github.com/altocms/altocms/tree/5cc5900059bf1b5177f7c38df5e8990e11b581d5/common/templates/skin/start-kit/tpls/snippets
но почему этих папок нет при скачивании архива или хотя бы в той же главной репозитории движка  https://github.com/altocms/altocms ?
Я что-то не так делаю? Напишите, пожалуйста, как мне лучше всего следить за изменениями.

**Comment by andrey-v** [comment]
Не ту ветку скачиваете, переключитесь на версию 1.1
![image](https://cloud.githubusercontent.com/assets/1106990/5889353/66070ff8-a432-11e4-8442-086d604a44b7.png)

**Comment by lexuspro** [comment]
Вот оно в чем дело. Я мозг месяц целый ломал где, что, куда.) 
Уже сейчас можно смело править на будующую версию, верно?

**Comment by andrey-v** [comment]
Делать рабочие проекты на нем еще рано, но ориентироваться на него, уже нужно начинать  :smile:.
