### ISSUE TITLE
При редактировании комментария теряется класс у ссылки на профиль пользователя 

### ISSUE THREAD

**Issue by andrey-v** [altocms/altocms#311]
https://github.com/altocms/altocms/commit/ad0ebca02cff7d5d0bf74df57fdff554c68cbcb3#commitcomment-9429644

**Comment by aVadim483** [comment]
И я параллельно: https://github.com/altocms/altocms/issues/309

Я подумал: а может быть хоть какой-то вред чисто теоретически, если класс разрешить у любого тега? Если нет, то к чему это искусственное ограничение?

**Comment by andrey-v** [comment]
Классы hidden, disabled используемые нарочно смутят других пользователей, например.

**Comment by inliquid** [comment]
Не сработало.

**Comment by inliquid** [comment]
Ап

**Comment by andrey-v** [comment]
Работает, посмотри нет ли у тебя настроек jevix, которые перекрывают базовые, например в папке *app/config* или в плагинах?

**Comment by inliquid** [comment]
Именно там у меня все натсройки и выполняются. Я руками добавлял эту строчку в конфиг в app.

**Comment by inliquid** [comment]
Ты уверен что проверял при сохранении именно html тега - т.е. в комментарии, в котором `<ls>` уже превратился в `<a>` и снова сохраняется после редактирования?
