### ISSUE TITLE
Не работает подписка на блоги по запросу

### ISSUE THREAD

**Issue by andrey-v** [altocms/altocms#313]
Перенесено с https://github.com/altocms/altocms/issues/295

**Comment by inliquid** [comment]
Андрей еще просьба подумать над моим предложением в исходном тикете об объединении типов подписки по запросу и по приглашению.

**Comment by andrey-v** [comment]
Я помню про неё )

**Comment by andrey-v** [comment]
>Андрей еще просьба подумать над моим предложением в исходном тикете об объединении типов подписки по запросу и по приглашению.

Администратор блога с типом подписка "По запросу" может приглашать пользователей.
