### ISSUE TITLE
Ошибка при подстановке id чужого блога в строку URL

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#315]
Вылетело когда на старой вкладке другим юзером попытался открыть страницу администрирования. В таких ситуациях движок должен делать редирект на 404.

[LOG:1422206616.022-54C52698057C6][2015-01-25 20:23:36][PID:32282][ERROR][[
E_ERROR [1] Call to a member function getUrlFull() on a non-object (/var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php(157) : eval()'d code on line 32)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

]][END:1422206616.022-54C52698057C6]

Шаблоны start-kit и brand.

**Comment by andrey-v** [comment]
А сама строка url какая? Страница администрирования блога?

**Comment by inliquid** [comment]
Да /blog/admin/<id>

**Comment by andrey-v** [comment]
Ошибка в плагине *blogusers* он не завершает экшен ошибкой когда она имеет место быть.

**Comment by klaus-spb** [comment]
Андрей не пояснишь немного ?

Я в плагине переопределяю EventAdminBlog, в котором уже есть проверка на права пользователя. Мне тоже нужно проверять права ? Немного не понимаю что нужно править в плагине
```php
protected function EventAdminBlog() {
		parent::EventAdminBlog();
```

**Comment by andrey-v** [comment]
Поясню, когда выполняется родительский экшен 
```
parent::EventAdminBlog();
```
то он выполняется с ошибкой, всё правильно. Но твой экшен *EventAdminBlog()*  еще не закончился, за вызовом родительского метода есть еще строки и они выполнятся, а так как твой экшен завершился без ошибки то он отобразит шаблон админки блога, но в этом шаблоне не будет переменных которые должен был сформировать родительский метод, ведь он вылетел по ошибке.

**Comment by andrey-v** [comment]
Ты переопределяешь родительский метод, но в нем вызываешь НЕ переопредлённый и ни как не анализируешь завершился он успешно или с ошибкой. В твоём коде он просто отрабатывается и неважно как с ошибкой/без. Исполнение всего остального кода от этого не зависит.

**Comment by andrey-v** [comment]
Тут можно либо скопировать проверки из родительского метода, либо проверить текущий экшен (с учетом реврайта) так
```php
protected function EventAdminBlog() {
parent::EventAdminBlog();
if (Router::GetAction() == Router::getInstance()->Rewrite('error')) {
    return parent::EventNotFound();
}
// Остальной код
```
Если родительский метод завершился с ошибкой, то название текущего экшена сменится на 'error'.
