### ISSUE TITLE
Некорректный текст приглашения в блог в личных сообщениях 

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#318]
Можно создать тип блога со свободной подпиской и пригласить пользователя. Текст примерно такого содержания "пользователь А приглашает вас подписаться на закрытый блог ..." 
Языковую переменную для "закрытого блога" нужно поменять на переменную, выводящую просто "блог". 

Я так понял в отличие от e-mail эти сообщения формируются не из выделенных tpl?

**Comment by andrey-v** [comment]
Связанные задачи получились - #313

**Comment by andrey-v** [comment]
>Я так понял в отличие от e-mail эти сообщения формируются не из выделенных tpl?

Нет, из текстовки **blog_user_invite_text**
