### ISSUE TITLE
Движок должен создавать директории установленные для _run и _tmp если они не существуют

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#319]
Пример - я хочу разместить содержимое в рамдиске, который очищается после перезагрузки (включая поддиректории).

**Comment by andrey-v** [comment]
[Они создаются](https://github.com/altocms/altocms/blob/master/engine/classes/core/Loader.class.php#L252-L261). Если же нет, то вполне возможно, что просто нет прав на создание этих каталогов у пользователя от имени которого запускается скрипт

**Comment by andrey-v** [comment]
```F::File_CheckDir``` не только проверяет каталога на существование, но и создаёт его если это возможно.
