### ISSUE TITLE
Некорректно работает форма регистрации при переходе через ввод кода приглашения

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#320]
При переходе к регистрации через ввод кода приглашения форма не проверят валидность данных и не сообщает об ошибках. Обратная связь просто отваливается.

Шаблоны - Brand, start-kit.

**Comment by inliquid** [comment]
Эта проблема очень актуальна. Если включен режим "по приглашениям", то этот фактически является заслоном не позволяющим юзерам нормально регистрироваться. Т.е. к примеру пользователь вводит ник в котором есть запрещенные символы, или слишком короткий пароль, и т.д. а форма просто не отрабатывает и все. Без каких-либо подсказок. Это делает запуск сайта не возможным в таком режиме. Посмотрите, плз - наверняка там ерунда которая правится за 2 мин...

**Comment by andrey-v** [comment]
Исправлено
