### ISSUE TITLE
Нет возможности повторно отправить запрос о дружбе

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#322]
В настоящее время в шаблонах start-kit и Brand есть некая проблема, если пользователь отказался дружить с другим пользователем, то ему всегда будет отображаться это сообщение об отказе, как и второму пользователю, а кнопка добавления в друзья становится недоступна. Т,е. никакой технической возможности повторно отправить заявку нет ни у первого ни у второго пользователя. Но вдруг пользователь передумал или вообще случайно не туда нажал? Мне кажется можно выводить сообщение об отказе, причем только тому, кто отказался, но при этом нужно давать возможность повторно отправить заявку.

**Comment by andrey-v** [comment]
Да всё работает. 
1. Если я отказался от дружбы с пользователем, то повторно ему разрешать простся не нужно - зачем этот спам?
2. Если я передумал (случайно нажал отказ / мой визави меня в личке переубедил и т.д.), то я всегда могу зайти в его профиль, а в теме experience и просто в списке пользователей, нажать кнопку "Добавить в друзья". Без разницы, что я его ранее отказался от дружбы с ним, но я передумал и  он станет моим другом, вот.

**Comment by inliquid** [comment]
Андрей, что ты такое говоришь ничего из того что ты написал у меня нет. Еще раз.

>если пользователь отказался дружить с другим пользователем, то ему всегда будет отображаться это сообщение об отказе, как и второму пользователю, а кнопка добавления в друзья становится недоступна.

**Comment by inliquid** [comment]
Хммм.. раньше выводилось "Этот пользователь отказался с вами дружить", а теперь выводит кнопку с текстом, это что какой-то хук добавлен или что? Этого не было 100% как минимум еще один человек учествовал в тестировании и четко помнит все детали.

**Comment by andrey-v** [comment]
Попробовал ещё раз:
1. Прошу админом у пользователя дружбы. Для этого захожу в профиль пользователя и нажимаю кнопку "Дружить"
2. В *prefix_friend* создаётся запись со статусами from=1 to=16 
3. Пользователем отклоняю дружбу админа
4. Статусы меняются на  from=1 to=8
5. Захожу пользователем в профиль админа и нажимаю "Добавить в друзья"
4. Статусы меняются на  from=1 to=2

Пользователи в списках друзей друг у друга
```php
    /**
     * Статусы дружбы между пользователями
     */
    const USER_FRIEND_OFFER     = 1;
    const USER_FRIEND_ACCEPT    = 2;
    const USER_FRIEND_DELETE    = 4;
    const USER_FRIEND_REJECT    = 8;
    const USER_FRIEND_NULL      = 16;
```

**Comment by inliquid** [comment]
Причем кнопка вообще не вписывается, вот что выводится
![1](https://cloud.githubusercontent.com/assets/6797881/6047931/d4185446-acbd-11e4-80ac-bd2011e60777.png)

А должна быть

![2](https://cloud.githubusercontent.com/assets/6797881/6047962/0556a418-acbe-11e4-8934-ebf65a5258b2.png)

Вот откуда она берется?

И я гарантирую что было так как я написал. 

И еще, сейчас обнаружил второй тупиковый кейс - если удалить из друзей, то возможности заново отправить запрос тоже нет, но уже без подсказок. Причем при удалении никаких подтверждений не спрашивал.

**Comment by inliquid** [comment]
Добавлю еще что сейчас все изменилось не потому что я тогда не обратил внимание. За мной это вообще редко случается. Я просто повторил весь кейс, но БД перед этим была руками вычищена...
