### ISSUE TITLE
Критический расход ресурсов при работе с изображениями, который приводит к DoS

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#323]
Отсутствие возможности запретить анимированные gif приводит к атаке типа DoS, достаточно в качестве аватарки блога (!!!) подсунуть более менее качественную. Если точнее  то у меня нарезается из нее изображение 1500x1500 и 500x500. В результате после одного такого запроса загрузка ЦПУ - 100%, и нехватка свободной памяти после чего вылетает mysqld и сайт становится недоступен. 
Например при использовании такой:
http://gifgood.ru/1-472
И это всего с 1 запроса на не самой дешевой VPS. Страшно представить что сделает простой скрипт.  

Хмм... это если _run и _tmp в ОЗУ... А если на ХДД, то клинит ядро. Даже ssh после этого недоступен, только жесткий ребут с панели управления. Никогда такого не встречал))))

Андрей, плз предупреди если будешь тестить, чтобы я если что перезапустил...

**Comment by inliquid** [comment]
попробовал на втором тестовом инстансе тарифный план с 2ГБ ОЗУ. (Исходный - 1ГБ)
При обработке указанной гифки где-то сек на 15 нагрузка на ЦПУ 100%, потребление ОЗУ взлетает в 2 раза по сравнению с используемым системой, т.е. все вместе включая мемкеш, mysql, nginx, php-fpm потребляет не больше 750МБ, но в момент обработки этой гифки потребление примерно 1.5 ГБ (!). После обработки память освобождается.

**Comment by inliquid** [comment]
Сама гифка ~800кб

**Comment by inliquid** [comment]
memory_limit	128M

**Comment by aVadim483** [comment]
Не совсем понял, в чем проблема. Загрузил в качестве аватара блога картинку, которая дана в качестве образца, т.е. отсюда: http://gifgood.ru/1-472

Никаких проблем не возникло

**Comment by inliquid** [comment]
По-моему я понятно объяснил. На моем сайте это приводит
1. К расходу всего доступного объема памяти на VPS в 1 ГБ и как следствие 
1.1. при размещении _tmp и _run в ОЗУ сначала секунд на 30 ложатся все процессы, так как загрузка ЦПУ превышает 100%, в конечном итоге умирает mysql из-за нехватки памяти
1.2. при стандарном размещении _tmp и _run лочатся виртуальные процессоры и умирает ядро
2. При запуске того же самого на 2 ГБ ОЗУ и 2х ядрах (по сравнению с 1 ГБ и 1 ядром) я вижу что на 15 сек встают процессы (загрузка ЦПУ 100%), расход памяти взлетает с 750 МБ до 1.-1.5 ГБ. И это только лишь на одну гифку на 800 кб.

Кейс гарантированно воспроизводится на моем сайте рип нарезке из исходной изображений размером. 500x500 и 1500x1500. Могу продемонстрировать.

**Comment by aVadim483** [comment]
При работе с каким изображением такое происходит? С тем, на которое ссылка дана? Или с каким-то другим?

**Comment by inliquid** [comment]
И с ним, и в общем с другими с того сайта - тоже.

**Comment by inliquid** [comment]
Показывать? =)

**Comment by aVadim483** [comment]
Размер этой картинки 500х333, размер файла 800К, но у меня никаких проблем с ней не возникает. Хилых серверов у меня нет, чтобы проверить, самый слабый - это локально на ноуте, и все ОК.

Покажите другую, мож, пойму в чем проблема

**Comment by inliquid** [comment]
Напишу в личку на сайте.

**Comment by aVadim483** [comment]
Замечу, что в 1.1 предусмотрено задание параметров на загрузку отдельных видов изображений, поэтому эту проблему можно будет запретить анимацию, но мне сама проблема непонятна, хотелось бы разобраться

**Comment by andrey-v** [comment]
Дело не в исходном изображении, а в тех размерах в который эта гивка резайзится при загрузке. скорее всего она ресайзится в огромную картинку. Посмотри что за файлы создаются в каталоге загрузки uploads для этой гивки. Очень кажется, что там многометровые картинки лежат (

**Comment by inliquid** [comment]
У меня в настройках блога выводится изображение 500x500 - при его нарезке такая же история. Получше но все равно все встает.
Совершенно фантастический расход памяти - при том в php.ini настроено 128 МБ. Как это вообще возможно, там идет вызов к какой-то сишной библиотеке через imagick?

**Comment by andrey-v** [comment]
Сейчас посмотрел, у тебя ещё и в шапке блога 1500x1500 а для анимированной гифки - это многовато, за картинку в шапке в 10 метров пользователи обидятся ). 

>Как это вообще возможно, там идет вызов к какой-то сишной библиотеке через imagick?
Не знаю, но скорее всего именно графическая библиотека так себя ведёт.

**Comment by inliquid** [comment]
Тут есть 2 нюанса 
1. Я уже давно прошу выборочное отключение анимации. =) 
2. Может быть в том числе и некорректная работа с изображениями на уровне библиотек. Очень странно что память может быть отъедена так вот запросто одной гифкой.

Ну пусть будет не 1 аватарка а 10 меньшего размера, все равно потенциальная проблема. Представим что сайт стал посещаем и юзеры решили что движущиеся картинки им обязательно нужны...

**Comment by andrey-v** [comment]
>Я уже давно прошу выборочное отключение анимации.

Как это выборочно? Для страниц(ы), формата картинки, размеров?

**Comment by andrey-v** [comment]
>Ну пусть будет не 1 аватарка а 10 меньшего размера, все равно потенциальная проблема. Представим что сайт стал посещаем и юзеры решили что движущиеся картинки им обязательно нужны...

В меньшие размеры гифка режется быстро и выходной файл получается небольшим - для картинки из первого коммента
- 48x - 64кб
- 64x - 100кб
ну от этого же не уйдешь - это гифка. Можно выводить заглушку и при клике подгружать гифку, наверняка есть какие-то jquery плагины для этого.

**Comment by inliquid** [comment]
Выборочно это чтобы допустим для пользовательских аватарок анимация разрешена а для остального нет. Чтоб можно было менять. Вот к примеру захочет юзер фон для блога анимированный в твоем плагине - что произойдет?

**Comment by inliquid** [comment]
Cлушай ну в любом случае это не бог весть какая криптография - изменить размер пусть даже анимированной гифке. Зачем ей 750 МБ ОЗУ (!!!) и 100% ядра современного Xeon`а на Sandy Bridge аж на 30 сек?

**Comment by aVadim483** [comment]
>там идет вызов к какой-то сишной библиотеке через imagick?

"Imagick является встроенным php-расширением для создания и изменения изображений используя API ImageMagick".

>при его нарезке такая же история

Давай определимся с терминологией и выполняемыми действиями. "Нарезка" - я так понимаю, это когда изображение режется на части. А тут что происходит? При загрузке аватар (любых) по умолчанию происходит уменьшение изображение и/или его обрезка. А тут у тебя многократное увеличение гифки делается, что ли? Дай ссылку на конкретную картинку и объясни, что ты с ней пытаешься сделать, когда получаешь такой эффект?

**Comment by inliquid** [comment]
1. Пользователь загружает аватар блога. Движок вырезает середину по меньшей стороне превращаяя ее в квадрат и генерирует квадратную гифку.
2. Пользователь открывает блог (после сохранения настроек блога движок его перенаправляет на url блога), в коротом из шаблона вызывается getAvatarUrl(1500), в результате движок генерит из исходной уже обрезанной гифки еще одну размером 1500x1500 соотвественно или уменьшая, или увеличивая. (У дизайнеров это называется "нарезать" картинки из исходной - разного разрешения)
3. Аналогичный сценарий происходит в шаблоне редактирования блога, если пользователь возвращается в настройки блога с уже новой аватаркой, только там вызывается getAvatarUrl(500) на основании `$config['module']['blog']['avatar_size'] ` - такова логика шаблона start-kit.

**Comment by inliquid** [comment]
Может нужно добавить в конфиг некий парамтр на ограничение потребления памяти, аналогично этому примеру
http://stackoverflow.com/questions/9993085/php-imagick-memory-leak

**Comment by inliquid** [comment]
Вот тоже занятный тред https://bugs.php.net/bug.php?id=59878

**Comment by inliquid** [comment]
Обновил php до 5.5.20, с ним обновилась и библитека imagick
Теперь выводится вот такое сообщение когда память кончается
Exception: memory allocation failed `/var/www/example.com/uploads/images/00/00/01/2015/01/30/afbadba8.gif-1500x1500.gif' @ error/gif.c/WriteGIFImage/1630

**Comment by aVadim483** [comment]
В общем, проблема понятна - в Imagick течет память. При работе с гиф идет обработка каждого кадра в цикле. Могу предположить, что в каждой итерации цикла память утекает. Вероятно, при сильном увеличении картинки память течет значительно сильнее, чем при ее уменьшении. Настолько сильно, что выжирает все на свете.

Что в принципе можно сделать для предотвращения таких ситуаций:
1) Задавать лимиты через Imagick::setResourceLimit() - но с этим надо еще разбираться, как это работает, на что влияет, какие лимиты являются оптимальными и проч.
2) Запретить увеличивать изображения больше оригинала - не знаю, насколько это разумно, хотя, в каких-то случаях, наверное, и оправдано
3) Дать возможность запрещать гиф-анимацию в конфигурации
4) Дать возможность запрещать гиф-вообще

**Comment by inliquid** [comment]
1) Задавать лимиты через Imagick::setResourceLimit() - но с этим надо еще разбираться, как это работает, на что влияет, какие лимиты являются оптимальными и проч.

Я могу протестить у себя. Скажите только где прописать.

2) Запретить увеличивать изображения больше оригинала - не знаю, насколько это разумно, хотя, в каких-то случаях, наверное, и оправдано

Думаю это неоправданное ограничение, с обычными картинками все хорошо. Не говоря уж о том что мне это сломает всю логику =)

3) Дать возможность запрещать гиф-анимацию в конфигурации
4) Дать возможность запрещать гиф-вообще

Вот эти опции были бы весьма уместны даже безотносительно утечек - я бы не хотел чтобы пользователи могли устанавливать движущиеся шапки и фоны. Максимум - аватарки пользователей.

**Comment by inliquid** [comment]
На самом деле я так и не понял, течет ли память, по указанной ссылке (второй) какие-то противоречивые результаты. Давайте чтобы было корректней просто пока остановимся на том что для достаточно простых операций (с пользовательской точки зрения) - Imagick выделяет слишком дофига этой самой памяти. Но как я вижу по завершении, память все-таки освобождается (возможно не вся, но тут пока не понятно). 

Установка лимитов, в частности `$im->setResourceLimit(imagick::RESOURCETYPE_MEMORY, 256);` насколько я понял должна ограничить выделение RAM, и при превышении imagick должен писать в /tmp

Вообще из того что я тут вижу кажется имеет смысл задавать следующие лимиты

 imagick::RESOURCETYPE_MAP (integer)
    Set maximum amount of memory map in bytes to allocate for the pixel cache. 
imagick::RESOURCETYPE_MEMORY (integer)
    Set maximum amount of memory in bytes to allocate for the pixel cache from the heap. 
 imagick::RESOURCETYPE_DISK (integer)
    Set maximum amount of disk space in bytes permitted for use by the pixel cache. 
 imagick::RESOURCETYPE_FILE (integer)
    Set maximum number of open pixel cache files. 

> imagick::RESOURCETYPE_AREA (integer)
    Set the maximum width * height of an image that can reside in the pixel cache memory. 
- Этот думаю нет смысла задавать, т.к. ограничения по максимальному размеру картинки берет на себя движок

И еще для целей производительности думаю имеет смысл вот этот тоже задавать параметр:
 imagick::RESOURCETYPE_THREAD (integer)
    Set maximum parallel threads. This constant is available if Imagick has been compiled against ImageMagick version 6.7.8 or higher.

**Comment by inliquid** [comment]
такая же проблема при загрузке аватара 5000x5000, обычного png, в тот момент когда движок пытается УМЕНЬШИТЬ его до 1500x1500. Imagick выедает 1ГБ (!) ОЗУ VPS и приводит к завершению работы mysql из-за нехватки памяти.

**Comment by aVadim483** [comment]
В общем, по этой теме сделано:

1) Возможность включать/отключать анимацию для разных типов изображений, а также, при необходимости, вообще менять сохраняемый формат картинки (напр., сохранять все только в jpeg)
2) Добавлен еще один модификатор размера изображения - 'max'. Например, '1500x1500max' - аналогично '1500x1500fit', но изображение будет меняться только в том случае, если хотя бы один размер превышает заданный. Если изображение меньше заданных размеров, то оно не меняется.

По поводу параметров imagick::RESOURCETYPE_XXX направление мысли, наверно, правильное, но я не придумал, как это можно впихнуть в конфиг. Просто в коде прописывать эти параметры - неверный подход, т.к. у вес железо разное, требования и возможности могут очень сильно отличаться. Так что оставлено на плагины или хуки.
