### ISSUE TITLE
[ver1.1] Не заливается аватарка.

### ISSUE THREAD

**Issue by aleksanderd** [altocms/altocms#324]
POST http://site.ru/uploader/upload-image/ 200 OK
Response:
~~~
<textarea>{&quot;sPreview&quot;:&quot;http:\/\/site.ru\/uploads\/profile_avatar\/00\/00\/02_preview.jpg&quot;,&quot;sMsgTitle&quot;:&quot;&quot;,&quot;sMsg&quot;:&quot;&quot;,&quot;bStateError&quot;:false}</textarea>
~~~
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data at [main.js line 26](https://github.com/altocms/altocms/blob/master/common/templates/frontend/libs/js/core/main.js#L26)

**Comment by aleksanderd** [comment]
в uploads/profile_photo/00/00 появляется 01_preview.jpg и пустая папка 01

**Comment by aleksanderd** [comment]
обертка в `<textarea>` присходит [тут](https://github.com/altocms/altocms/blob/ver1.1/engine/classes/modules/viewer/Viewer.class.php#L755)
хз, зачем оно, но подозреваю что тип ответа все таки должен быть [json вместо jsonIframe](https://github.com/altocms/altocms/blob/ver1.1/common/classes/actions/ActionUploader.class.php#L300)

по крайней мере это решает проблему - все заливается ок...

**Comment by andrey-v** [comment]
Да, вы правы, там должно быть "json".
