### ISSUE TITLE
Обработка ошибок модуля Uploader

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#326]
1. Ни одна из ошибок не переведена (такой технической возможности нет)
            UPLOAD_ERR_OK                   => 'Ok',
            UPLOAD_ERR_INI_SIZE             => 'The uploaded file exceeds the upload_max_filesize directive in php.ini',
            UPLOAD_ERR_FORM_SIZE            => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form',
            UPLOAD_ERR_PARTIAL              => 'The uploaded file was only partially uploaded',
            UPLOAD_ERR_NO_FILE              => 'No file was uploaded',
            UPLOAD_ERR_NO_TMP_DIR           => 'Missing a temporary folder',
            UPLOAD_ERR_CANT_WRITE           => 'Failed to write file to disk',
            UPLOAD_ERR_EXTENSION            => 'A PHP extension stopped the file upload',
            self::ERR_NOT_POST_UPLOADED     => 'File did not upload via POST method',
            self::ERR_NOT_FILE_VARIABLE     => 'Argument is not $_FILE[] variable',
            self::ERR_MAKE_UPLOAD_DIR       => 'Cannot make upload dir',
            self::ERR_MOVE_UPLOAD_FILE      => 'Cannot move uploaded file',
            self::ERR_COPY_UPLOAD_FILE      => 'Cannot copy uploaded file',
            self::ERR_REMOTE_FILE_OPEN      => 'Cannot open remote file',
            self::ERR_REMOTE_FILE_MAXSIZE   => 'Remote file is too large',
            self::ERR_REMOTE_FILE_READ      => 'Cannot read remote file',
            self::ERR_REMOTE_FILE_WRITE     => 'Cannot write remote file in tmp dir',
            self::ERR_NOT_ALLOWED_EXTENSION => 'Not allowed file extension',
            self::ERR_FILE_TOO_LARGE        => 'File is too large',
            self::ERR_IMG_NO_INFO           => 'Cannot get info about image (may be file is corrupted)',
            self::ERR_IMG_LARGE_WIDTH       => 'Width of image is too large',
            self::ERR_IMG_LARGE_HEIGHT      => 'Height of image is too large',

2. Если эта ошибка возникает при загрузке аватара пользователя/в топике - всплывающее сообщение довольно быстро исчезает. 

3. Если ошибка возникает при загрузке аватара блога то отображается общее сообщение об ошибке из которого вообще ничего не понятно
![2](https://cloud.githubusercontent.com/assets/6797881/5988250/ec172fe8-a968-11e4-9910-065711edaab5.png)

4. Не очень понятно почему используется 2 варианта вывода сообщений об ошибках - такой как представлен на скриншоте и на базе всплывающих красных окон. Необходима унификация.

**Comment by andrey-v** [comment]
я считаю, что это всё вопросы (кроме первого) кастомизации движка под конкретную задачу проекта. А конкретно:

1. В некоторых местах движка есть предопределённые текстовки и, согласен, локализовать их действительно нужно

2. Зашито [в стороннем jQuery-плагине](https://github.com/altocms/altocms/blob/master/common/templates/frontend/libs/vendor/notifier/jquery.notifier.js#L9), но легко меняется.

3. Вопрос "понятности" тоже субъективный, но всё настраивается в текстовках.

4. Два разных способа вывода потому что один - сообщения результата ajax-запроса, а второй возникает при перезагрузке страницы - две разные технологии обработки запроса, но в любой совершенно теме оформления можно переопределить родной *ls.notice* и *ls.error* (либо добавить скрипт вывода всплывающих сообщений в тело шаблона) и выводить сообщения как угодно - это вообще не проблема, а дизайнерское решение. 

Задачу закрою, а локализацию текстовок перенесу в новую #330

**Comment by inliquid** [comment]
> Вопрос "понятности" тоже субъективный, но всё настраивается в текстовках.

Что значит субъективный? Я гружу файл запрещенного типа в одном случае я вижу причину почему он не загрузился, пусть дажен на английском и мельком, а в описанном случае просто "не удалось загрузить аватар". Какая еще субъективность? Об этом речь.

Вообще сообщения об ошибках в альто это нечто...

**Comment by inliquid** [comment]
>Два разных способа вывода потому что один - сообщения результата ajax-запроса, а второй возникает при перезагрузке страницы - две разные технологии обработки запроса, но в любой совершенно теме оформления можно переопределить родной ls.notice и ls.error (либо добавить скрипт вывода всплывающих сообщений в тело шаблона) и выводить сообщения как угодно - это вообще не проблема, а дизайнерское решение. 

Это не вопрос. =) Должна быть унификация. Точка. А оправдания почему вы не станете это делать если честно мне не интересны. Дизайнерские решения тут не при чем, это глобальный косяк в юзабилити, о котором я уже писал в сообществе.

**Comment by inliquid** [comment]
> Зашито в стороннем jQuery-плагине, но легко меняется.

Отличное оправдание. Разработчик говорит все нормально, пользователю просто кажется что квадратным рулем рулить неудобно... =) Окай...

**Comment by aVadim483** [comment]
Спасибо за столь скрупулезное тестирование. Но к сожалению, юзабилистов у нас в команде нет, а более важные задачи по разработке - есть. Предложите свой вариант сообщений, если считаете, что нынешние варианты плохи. Благо для этого даже программером не надо быть - все тексты вынесены в отдельные файлы и лежат в открытом доступе.

**Comment by inliquid** [comment]
Ну по-моему есть очевидный путь. Если уж сообщения выводятся jQuery лпагином в правом верхенм углу, то пусть и в этом случае выводится сообщение об ошибке с указанием исходной причины (например запрещенное расширение). Причем если сообщение об ошибке какое-то критическое - то оно не должно исчезать, просто должно закрываться крестиком как обычное окно. Я же предлагал уже. Чем плох такой вариант?
Поьлзователь привыкает к какому-то определенному поведению, а тут сообщение выводится где-то в шаблоне, да к тому же еще не факт что он до него долистает (наверх).

**Comment by aVadim483** [comment]
Т.е. предложение делится на составные части:

1) Все сообщения выводить однотипно, в тексте страницы никаких сообщений не вставлять не нужно, все их выводить исключительно через всплывающие окна - в принципе, вариант, можно над ним подумать.

2) Сообщения делить на критические и некритические, некритические убирать автоматически, а критические не убирать, пока юзер явно сам это не сделает - в системе нет деления на критические/некритические сообщения, есть только уведомления и ошибки. Вот между ними и есть возможность выбирать.

3) Текст сообщений должен быть всегда и всем понятен - тут согласен с Андреем, что "понятность" сообщений есть субъективизм, и тут, повторюсь, гораздо конструктивней будет не просто "я не понял, надо переделать", а предложить конкретный вариант сообщения.

**Comment by inliquid** [comment]
1 и 2 - да именно об этом я и говорил
3 - вместо "не удалось загрузить" выводить исходную ошибку модуля Uploader.
