### ISSUE TITLE
При выборе кастомного типа блога, при его создании и редактировании описание под input`ом не переключается

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#328]
Всегда отображается описание для встроенного "открытого" типа. Скины - Brand и start-kit.

**Comment by andrey-v** [comment]
Исправлено,
для того, что бы выводилось описание кастомного блога, нужно ещё создать тектосвку с его описанием в языковом файле в каталоге *app/templates/language/*. Она должна быть вида blog_create_type_**blogtype**_notice и [принудительно добавить её в скрипт](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience/tpls/actions/blog/action.blog.add.tpl#L26), аналогично текстовкам открытого и закрытого блога.

**Comment by inliquid** [comment]
Жесть О_О

**Comment by inliquid** [comment]
Не работает. Тестовка подставляется в javascript, однако все равно не выводится под инпутом и не работает переключение. Можешь проверить у меня на основном сервере.

**Comment by inliquid** [comment]
ап.

**Comment by inliquid** [comment]
Разобрался. Ты забыл сказать что нужно вот это сделать в шаблоне:

https://github.com/altocms/altocms/commit/90cd76838ecb914f17989ff423e3b26d6f59ea47
