### ISSUE TITLE
[ver1.1] Конфиг плагина уровня APP игнорируется, если определен конфиг в самом плагине

### ISSUE THREAD

**Issue by aleksanderd** [altocms/altocms#331]
Субж.

Например, в конфиге плагина (`common/plugins/ПЛАГИН/config/config.php`) пишешь:
~~~php
$config['key1'] = 'val1';
~~~
а в конфиге приложения/плагина (`app/plugins/ПЛАГИН/config/config.php`) пишешь:
~~~php
$config['key2'] = 'val2';
~~~
и key2 не будет в результате... убрать конфиг с папки плагина, то key2 - будет.

Немножко подебажил: конфиг из app/plugins/ПЛАГИН/config/* читается и даже вот [тут](https://github.com/altocms/altocms/blob/ver1.1/engine/classes/core/Loader.class.php#L173) слияние проходид нормуль, и [тут](https://github.com/altocms/altocms/blob/ver1.1/engine/classes/core/Config.class.php#L549) $aConfigData содержит все что нада... но дальше я треснул ибо там сторожа какие то неведомые - так и не понял где что теряется. Но возникло подозрение что дело в самом ключе конфига 'plugin.ПЛАГИН' - если он есть, то уже усё - хоть запереопределяйся :(

В моем случае запуск не с веба, а с консоли.

**Comment by aVadim483** [comment]
Была банальная опечатка
