### ISSUE TITLE
[ver1.1] Ресурсы(картинки) топика: удаление и тд

### ISSUE THREAD

**Issue by aleksanderd** [altocms/altocms#332]
Ку!

Из консоли разбирался как добавлять картинки к топику, кое как добавил. Но с удалением топика у меня получилось вот так:
~~~php
E::ModuleTopic()->DeleteTopic($tid);
E::ModuleTopic()->DeleteTopicAdditionalData($tid);
E::ModuleMresource()->DeleteMresourcesRelByTarget('topic-multi-image-uploader', $tid);
~~~

Решил проверить как удаляется топик из веба пользователем и удивился что ресы он не удалаяет :о Это так задумано?

Еще не понял как работает cover картинка... нигде она не отображается - это в шаблонах не задано или что?

**Comment by aleksanderd** [comment]
Похоже, я многого не понимаю :( Вроде, догнал, что фотки в принципе могут быть общими, и не обязательно должны удаляться с топиком... хотя спросить об этом при удалении не помешает, имхо.

Но все равно не понял как с ними(фотками) работать программно. Например, там есть AddTopicPhoto, но она вроде как не используется при реальной заргрузке. Нашел ее только в EventAjaxPhotoUpload, но её вызова тоже не происходит при загрузке из веба.

Догадываюсь, что часть API тянется еще с Livestreet'а, а часть - реализует новый метод/подход. Подскажите, как по новой идеалогии рулить картинками топика и ресурсами вообще. А то по исходникам - не всегда очевидно.

Мне нужно то: прицепить к топику картинку из урла или файла, и сделать ее обложкой топика.
У меня, изучая исходники, получилось так:
~~~php
// тут был создан и добавлен топик E::ModuleTopic()->AddTopic($oTopic)
                $sTargetId = $oTopic->getId();
                $sTargetType = 'topic-multi-image-uploader';
                $sTargetUrl = E::ModuleMresource()->NormalizeUrl(
                    E::ModuleUploader()->GetTargetUrl($sTargetId, $sTargetType));

                // загружаем картинку
                if ($file = E::ModuleUploader()->UploadRemote($aItem['img']['value'])) {
                    $path = E::ModuleUploader()->GetUploadDir($sTargetId, $sTargetType) . '/';
                    $xStoredFile = E::ModuleUploader()->Store($file, $path);
                    $uuid = $xStoredFile->getUuid();
                    $oResource = E::ModuleMresource()->GetMresourcesByUuid($uuid);
                    if ($oResource) {
                        $oResource->setUrl($sTargetUrl);
                        $oResource->setType($sTargetType);
                        $oResource->setUserId($aConfig['user_id']);
                        $oResource = array($oResource);
                        E::ModuleMresource()->AddTargetRel($oResource, $sTargetType, $sTargetId);
                    }
                }
~~~

Работает, но чет мне кажется должно быть сильно проще и изящнее... К тому же, дальше возник вопрос с обложкой: чтобы задать cover нада знать ID ресурса, чтобы создать ресурс - ID топика... В случае создания топика(программно, без веб-сабмита), получается, нада либо ресурс временный создавать перед созданием топика, либо топик обновлять, после создания ресурса...

В общем, буду рад любым примерам использования ресурсов, фоток и тд, с учетом "новых технологий" :)

Спасибо!

**Comment by andrey-v** [comment]
>Похоже, я многого не понимаю :( Вроде, догнал, что фотки в принципе могут быть общими, и не обязательно должны удаляться с топиком... хотя спросить об этом при удалении не помешает, имхо.

Здесь ошибка. Картинка удаляется при удалении топика если она была в тексте топика и не удаляется, если была в фотосете


Картинка добавляется так
```php
        $oResource->setType(ModuleMresource::TYPE_PHOTO_PRIMARY);
        E::ModuleMresource()->UpdatePrimary($oResource, $sTargetType, $sTargetId);
```

>Работает, но чет мне кажется должно быть сильно проще и изящнее... К тому же, дальше возник вопрос с обложкой: чтобы задать cover нада знать ID ресурса, чтобы создать ресурс - ID топика... В случае создания топика(программно, без веб-сабмита), получается, нада либо ресурс временный создавать перед созданием топика, либо топик обновлять, после создания ресурса...

Порядок здесь такой (он же используется при добавлении картинки в фотосет не ещё не созданного топика).
- создается временный ключ (target_tmp), который хранится в куке у пользователя.
- при загрузке картинок в ещё не существующий топик создается ресурс (prefix_mresource с нужным типом и target_id=0) и целевой объект (prefix_mresource_target) 
- у целевого объекта target_id=0 и target_tmp равен ранее созданному.
- после сохранения топика вызывается метод E::ModuleMresource()->LinkTempResource($sTargetId, $sTargetType, $sTargetTmp) который и прикрепляет временные картинки к созданному объекту.
- после target_tmp из куки пользователя удаляется.

**Comment by aleksanderd** [comment]
Спасибо!

>Здесь ошибка. Картинка удаляется при удалении топика если она была в тексте топика и не удаляется, если была в фотосете

Я то как раз в теле топика картинку не упоминал - просто загрузил ее(снизу от редактора). Проверил с картинкой в теле - все норм удаляется.

По обложе попробую, а то все смотрел вот на [это](https://github.com/altocms/altocms/blob/ver1.1/common/classes/actions/ActionContent.class.php#L338) и не мог понять почему не работает. Если не путаю, там вроде ID фотки в extra сохраняется. А тут, получается, "каверность" - свойство ресурса, что, имхо, правильнее. Это вот как раз "новый метод" который еще в самой CMS не особо то используется? Или я чего то не знаю, и подобная избыточность/неоднозначность чем то обоснована?

Еще немного сбивает с толку AddTopicPhoto и сама сущность Photo. И таблица есть topic_photo, которая пустая, что бы я ни делал. Это тоже методы работы с ресурсами или какой то дополнительный слой абстракции над ними, специально для фоток?

Про target_tmp я примерно догадывался, но у меня добавления топика скриптом без юзера и аплоада. Так что ни к чему так то времянки создавать. 

В этом смылсе, основная трабла была в том, что нада в сущности топика прописать ID главной фотки($oTopic->setPhotosetMainPhotoId). Если использовать это:
~~~php
        $oResource->setType(ModuleMresource::TYPE_PHOTO_PRIMARY);
        E::ModuleMresource()->UpdatePrimary($oResource, $sTargetType, $sTargetId);
~~~
в моем коде выше(наприме сразу после E::ModuleMresource()->AddTargetRel($oResource, $sTargetType, $sTargetId); )
Будет этого достаточно? Или setPhotosetMainPhotoId для топика всё-таки тоже необходим?

Спасибо!

**Comment by aleksanderd** [comment]
upd.

Так и не могу до конца разобраться с субжем. Что такое фотосет? Он к топику привязан или к пользователю вообще? 

Ибо я вот пробую(стд через веб): создаю топик, заливаю картинку, но в теле она не упоминается - просто при редактировании топика её тумбу снизу видно. И когда я создаю другой топик - у него снизу тоже есть эта картинка :о Это норм?

Ну и еще, если удалить топик, картинка(если в теле не упоминается) в ресурсах останется - ну это вроде выяснили. Но, если удалить её руками(например, в форме нового топика - она там есть), то она вроде как удаляется, но запись в таблице `mresource_target` остется :o

Про cover. Имеет ли `E::ModuleMresource()->UpdatePrimary(...)` какое то отношение к обложке топика? Ибо id ресурса всё равно хранится в поле extra топика...

Спасибо!

**Comment by aleksanderd** [comment]
еще заметил:
при установке обложки в `ActionUploader::EventCover` имеем:
~~~php
$oResource->setType(ModuleMresource::TYPE_PHOTO_PRIMARY);
E::ModuleMresource()->UpdatePrimary($oResource, $sTargetType, $sTargetId);
~~~
а в `UploadPrimary`:
~~~php
        $sql = "UPDATE ?_mresource SET type = ?d WHERE mresource_id IN (
          SELECT mresource_id FROM ?_mresource_target WHERE target_type = ? AND target_id = ?d
        )";
        $bResult = $this->oDb->query($sql, ModuleMresource::TYPE_PHOTO, $sTargetType, $iTargetId);

        $bResult = ($bResult !== false && $this->UpdateType($oResource));
~~~

то есть напрямую идет update на ModuleMresource::TYPE_PHOTO, и тут же вызов UpdateType, который делает update на установленный ранее ModuleMresource::TYPE_PHOTO_PRIMARY

загадочно...

**Comment by aleksanderd** [comment]
еще, при удалении картинки из формы топика(снизу) сами файлы(орг и кропы) не удаляются тоже :(

я хз, может это только у меня какие то глюки?

**Comment by andrey-v** [comment]
Здесь, первый запрос снимает флаг превью с ресурсов топика, а второй устанавливает TYPE_PHOTO_PRIMARY на новом ресурсе. Остальное буду смотреть.

**Comment by aleksanderd** [comment]
понял, спасибо

по последнему: если удалять картинку из топика в котором она заливалась - то вроде ок удаляется... а вот если удалить топик, и потом из формы нового топика удалить "безхозную" картинку, то кропы как минимум остаются...

еще, в LinkTempResource вызывается $oResource->setType($sTargetType), а $sTargetType - это `topic-multi-image-uploader` что делает тип ресурса равным 1 и это мне тоже не очень понятно...
в итоге, еще разок приходится менять типа ресурса на primary...

**Comment by andrey-v** [comment]
>Ибо я вот пробую(стд через веб): создаю топик, заливаю картинку, но в теле она не упоминается - просто при редактировании топика её тумбу снизу видно. И когда я создаю другой топик - у него снизу тоже есть эта картинка :о Это норм?

Исправлено - d4971441299921d8c7af3ca38f8866b0289708df

**Comment by aVadim483** [comment]
Все проблемы решены, что тут обсуждались?

**Comment by aleksanderd** [comment]
похоже на то...
