### ISSUE TITLE
Права администратора и модератора блога игнорируются

### ISSUE THREAD

**Issue by TheDreik** [altocms/altocms#333]
Например, если убрать галочку в админке с возможности редактировать комментарии администратору или модератору блога, эта возможность у него не пропадает.

**Comment by andrey-v** [comment]
Ошибка не воспроизводится. Такой случай возможен только если пользователь-модератор блога является и адмнистратором сайта, а у него привилегий больше. Попробуйте у себя повторить ошибку, у меня всё работает замечательно:
![image](https://cloud.githubusercontent.com/assets/1106990/6650511/1df7ae96-ca27-11e4-92ae-276b84e41b30.png)

**Comment by andrey-v** [comment]
Всё равно не воспроизводится
