### ISSUE TITLE
Exception: Method of the event not found: EventResizePhoto

### ISSUE THREAD

**Issue by sersar** [altocms/altocms#335]
В файле altocms/common/plugins/ls/classes/actions/ActionSettings.class.php надо удалить 
        $this->AddEventPreg('/^profile$/i', '/^resize-foto/i', '/^$/i', 'EventResizePhoto');
        $this->AddEventPreg('/^profile$/i', '/^remove-foto/i', '/^$/i', 'EventRemovePhoto');
        $this->AddEventPreg('/^profile$/i', '/^cancel-foto/i', '/^$/i', 'EventCancelPhoto);
Иначе ошибка.

**Comment by yuri25** [comment]
Выскакивает такая ошибка: Exception: Method of the event not found: EventResizePhoto  
Может поправите это? Для чего то нужны эти строки?
