### ISSUE TITLE
Автоматическая обработка загружаемых в топик изображений

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#336]
Почему ВНЕЗАПНО загружаемые в топик изображения начали ужиматься до 750 пикселей по ширине и к ним теперь добавляется полоса из нескольких белых пикселей снизу??????
http://185.22.62.30/uploads/images/00/00/05/2015/02/11/0u2fccc903-246a4817-505d8a71.jpg

Оригинальное изображение имеет размер 1024x576 ->

![1](https://cloud.githubusercontent.com/assets/6797881/6138003/a12c16d2-b18e-11e4-9d37-11cc33e6a99a.jpg)

В конфигах даже цифры такой нет нигде - 750. Тоже касается и админки.

**Comment by inliquid** [comment]
Раньше изображения загружались в своем оригинальном размере. Но видимо на каком-то из последних обновлений движка вылезло ЭТО.

**Comment by inliquid** [comment]
На всякий случай - не знаю кто чем открывает, с каким цветом фона.

![1](https://cloud.githubusercontent.com/assets/6797881/6138270/a50e81ac-b190-11e4-81b4-44963207b62f.png)

**Comment by inliquid** [comment]
Попробовал отключить все плагины - все равно картинки в топике ужимаются до 750. Пробовал отключать параметр конфига autoresize - тоже не влияет.

Прошу обратить внимание на этот баг. Для меня это блокирующая проблема...

**Comment by inliquid** [comment]
Смарти тоже откатывал назад до стоковой версии - тоже ноль эмоций.

**Comment by aVadim483** [comment]
Посмотрю, проверю

**Comment by aVadim483** [comment]
Вероятно, это связано со значением "Максимальный размер изображения", которое задается при загрузке. Если ширина зоны теста топика 750px, то размер картинки подгоняется под эту ширину и это все объясняет

**Comment by inliquid** [comment]
Просто этого соврешенно точно не было раньше, я много раз проверял что загружается именно оригинал, какого бы размера он не был (если этот размер не ограничен системными настройками в админке - по умолчанию 5000x5000, я уменьшил до 3000x3000). А насчет полоски пикселей - обнаружил что появляется не всегда, а только при определнных размерах. Возможно из-за того что размер округляется в бОльшую а не в меньшую сторону. Еще как вариант делать фон по умолчанию прозрачным, тогда это будет не заметно даже на темном фоне.

**Comment by inliquid** [comment]
Вы правы, если удалить в поле "максимальны размер" 
http://gyazo.com/bd63dbebeb9ac9f9a07b15848c9ddaa2

значение 100, оставив его пустым, то загружается оригинал. Вопрос только почему раньше это поле не заполнялось или не учитывалось?

Нельзя ли сделать параметр конфигурации чтобы автозаполнения этого поля не происходило?
+ проблема с полоской пикселей остается...

**Comment by inliquid** [comment]
Убрал пока в шаблоне значение по умолчанию
 ```<input type="text" name="img_width" value="" class="form-control"/>```
не знаю насколько это корректно, но работает.

**Comment by inliquid** [comment]
Мне казалось этот параметр должен просто для тега img устанавливать width/height относительно родительского блока, не затрагивая оригинальное изображение, а получается по сути реализация #298. Разве нет?

**Comment by aVadim483** [comment]
С полоской в 1 пиксель мне все понятно, это алгоритм ресайза изображения не вполне корректный, и в некоторых случаях такое происходит (связано действительно с округлением). Будет исправлено к стабильному релизу версии 1.1

Что касается максимального размера, то тут надо голову ломать над юзабилити. Нередко юзер грузит картинку, чтобы ее выровнять вправо/влево, и ему не нужно, чтоб она занимала всю ширину топика. И тут указание процента очень удобно - не нужно юзеру ничего знать о пикселях и прочих премудростях. В половину ширины (или 50%) - так гораздо понятней.

И тягать в таких случаях картинку в тыщи пикселов, чтоб в атрибуте тега указать всего 50% от ширины в 700px - не очень хорошая затея, т.к. дает паразитный трафик. А можете рассказать, зачем нужен оригинал в 3000px при ширине топика 750px?

Почему внезапно этот эффект возник, то тут все просто - сначала это работало, потом во время какого-то обновления сломалось, мне написали о баге, я исправил, и опять заработало после одного из коммитов.

**Comment by inliquid** [comment]
3000 это общесистемное ограничение для аплоадера оно затрагивает и изображения топиков, и шапку и фон, и фотосет. Из картинок топика могут нарезаться превью, в частности сейчас превью имеет ширину 880, и если исходное изображение - 750 пикселей, то при растягивании до 880 иногда это заметно. Кроме того есть еще идеи вывода изображений, а вообще я бы ограничил загрузку в топик разрешением 1000 пкс (с возможностью в дальнейшем менять). Если конечное изображение имеет бОльшее разрешение чем физические размеры области оно обычно лучше отображается. К примеру хорошо ставить размеры изображений аватарок 100x100 при масштабировании в 64x64.

**Comment by inliquid** [comment]
В общем, сравнив конфиги продуктивного и тестового сервера, выяснил что тут вылез еще один нюанс - внезапно заработало ограничение в системном конфиге - размер загружаемых в топик и фотосет изображений. По умолчанию стоит 700, и если поле оставлять пустым то картинка ужимается до этого значения.

**Comment by andrey-v** [comment]
Теперь ширину изображений в топике определяет параметр "До какого размера ужимать картинки" - 70d6908f03f4aba07d2f3bfa5d0670060224767a
