### ISSUE TITLE
В медиаресурсах сохраняется обычная ссылка

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#337]
Вот например, я оставляю ссылку на яндекс:

![1](https://cloud.githubusercontent.com/assets/6797881/6169301/c75be1ca-b2dd-11e4-9670-801294fbfe25.png)

**Comment by inliquid** [comment]
Короче не знаю почему мне почудилось что оно заработало, видимо это был какой-то глюк. Нет, ничерта не работает. Поле пустое, и теперь картинки сохраняются шириной 700. Сделайте что-нибудь плз. Скажите хоть какой коммит был, чтобы эту "фичу" обратно сломать...

**Comment by aVadim483** [comment]
Да, просто ссылки тоже сохраняются. Это не баг, а фича. И может быть миллион причин, зачем админу сайта надо знать, кто какие ссылки на сайте оставляет
