### ISSUE TITLE
Дата создания топика при переносе из черновиков

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#338]
Если убрать топик в черновики, отредактировать, а потом опубликовать, его дата создания не меняется. Это не логично, т.к. убрав топик в черновики, предполагается что я буду еще над ним работать и версия уже будет обновленной. Это не простое редактирование. Если так, то последующая публикация очевидно должна пойти текущей датой и попасть наверх, а так выходит что я могу убрать топик в черновик, работать над ним пару месяцев, опубликовать, и он таки  останется где-то там внизу, где его никто не прочитает.

**Comment by aVadim483** [comment]
Я правильно понимаю, что речь идет о ситуации, когда топик был сначала **опубликован**, а потом убран в черновики?

**Comment by inliquid** [comment]
да

**Comment by aVadim483** [comment]
Тогда я считаю такое поведение логичным - мы имеем дату **первичной** публикации. Если юзер при создании топика его не публиковал, а в черновики отправил, а потом три месяца правил в тяжелых раздумьях, и лишь после этого решил опубликовать, то здесь получим именно эту дату.

Кроме того, если дату менять при каждой публикации, то юзер может каждый день убирать в черновик и публиковать, вечно держа топик в "новых". И плюс - не забываем об уведомлениях, которые идут подписчикам при публикации.

Так что все логично, на мой взгляд. Не идеально, но наиболее оптимально

**Comment by inliquid** [comment]
1. Для того чтобы исправить опубликованный топик не меняя дату у юзера есть другой инструмент - редактирование.
2. Выше я уже объяснил что если человек *убирает* топик в черновики, значит ему нужно над ним поработать, и работа может идти долго.
3. Как результат - топик публикуется среди старых записей и пользователь *вынужден* его пересоздавать.
4. Пользователь *ожидает* публикации текущей датой, потому что ровно это происходит если пост еще не был ни разу опубликован. Он воспринимает текущее поведение как непродуманную логику, или как баг.

Как итог инструмент "убрать в черновик" превращается в редактирование. Пользователь вынужден удалять и пересоздавать топик.

Что касается вечно держать в новых - ничто не мешает пользователю пересоздавать топики столько раз сколько они хотят. Вообще, кагбэ дело в том что в этом и смысл - чтобы пользователи создавали НОВОЕ, именно с этой целью мы даем им ИНСТРУМЕНТ. А будет это "новое" таким же как вчера или чем-то принципиально отличным - завивисит от них.

**Comment by aVadim483** [comment]
1. Против этого никто не спорит.

2. Опыт показывает, что человек может убирать и из черновика **уже опубликованный** топик по разным причинам. В т.ч. и для всякого рода манипуляций, когда речь идет о большом сообществе, где используются всяческие "пузомерки", бушуют страсти и проч.

Поэтому и было решено, что под "публикацией топика" всегда понимается именно **первичная** публикация, со всеми вытекающими. 

3. Топик __публикуется__ только единожды, все остальные варианты - это не публикация, а __восстановление__ из черновиков.

4. Если топик ни разу не был опубликован, то ожидания юзера вполне оправдаются - дата публикации будет именно текущая.

Я уж не говорю о том, что публикация должна (по логике работы системы) сопровождаться уведомлениями для подписанных юзеров. Но слать им уведомления несколько раз о публикации одного и того же топика - это явно перебор.

Итого: Гонять топик в черновики и обратно можно сколько угодно раз, но публикация может быть только однократной - это первичная публикация. Считать публикацией любое (в т.ч. и неоднократное) доставание топика из черновиков - это, на мой взгляд, неверный подход.
