### ISSUE TITLE
[ver1.1] Не происходит регистрация пользователей

### ISSUE THREAD

**Issue by can0r** [altocms/altocms#342]
После отправки формы возникает коротенькое "wait...", пропадает и всё - больше ничего не происходит.

Версия последняя на данный момент из гитхаба, конфиг nginx+php-fpm(этот же держит у меня 1.0.9).

P.S. Уже можно лепить баги по 1.1 сюда, или она пока совсем сырая?

**Comment by andrey-v** [comment]
Исправлено,


>P.S. Уже можно лепить баги по 1.1 сюда, или она пока совсем сырая?

Да, конечно можно
