### ISSUE TITLE
Кеширование метода GetCommentsByFilter

### ISSUE THREAD

**Issue by isUndefined** [altocms/altocms#345]
Предлагаю добавить кеширование для метода Comment_GetCommentsByFilter().

**Comment by andrey-v** [comment]
Работа с этим методом так строится,
1. Когда вызывается этот метод, то он возвращает только массив идентификаторов комментариев, а не объекты-комментарии. Этот запрос и так кэшируется на уровне MySql.

2. В этом методе вызывается (GetCommentsAdditionalData)[https://github.com/altocms/altocms/blob/ver1.1/common/classes/modules/comment/Comment.class.php#L135-L136] который из идентификаторов комментариев формирует объекты-комментарии с дополнительными данными.

3. В строке 136 получаем сами комментарии по их ид., так вот эти данные и (кэшируются)[https://github.com/altocms/altocms/blob/ver1.1/common/classes/modules/comment/Comment.class.php#L221-L281].

Всё что можно в этой цепочке уже закэшировано.
