### ISSUE TITLE
Ошибка в описани Фотографий массовым загрузчиком

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#349]
При создании Топика, когда добавляешь Фотографии массовым загрузчиком, то после того как они загрузились не могу добавить к каждой фото Описание в поле 
![screenshot_55](https://cloud.githubusercontent.com/assets/7164280/6440011/97897180-c0e1-11e4-9b04-2ae66e1f9b63.jpg)

.

**Comment by andrey-v** [comment]
>не могу добавить к каждой фото Описание в поле 

Что именно не получается, не доступно текстовое поле, не сохраняется описание, не выводится описание? Сейчас попробовал повторить ошибку... вроде всё работает.

**Comment by lsnull** [comment]
я же скриншот выложил. В эти поля не получается написать описание. Просто не кликабельное поле. Нажимаю мышкой и нет реакции для ввода текста

**Comment by andrey-v** [comment]
Искал ошибку в хроме, а она воспроизводится в firefox )
Исправил
