### ISSUE TITLE
Ошибка отображения фотографий в топике

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#350]
Не отображаются в Топике фотографии, которые были загруженны в топик через Массовый загрузчик. Вот этот:
![screenshot_59](https://cloud.githubusercontent.com/assets/7164280/6440073/22b8f9c4-c0e2-11e4-954c-edd67c5d5950.jpg)
Сами фото видно которые добавились и загрузил через загрузчик, но к сожелению после публикации Топика их нет...

**Comment by andrey-v** [comment]
Добавлен чекбокс автоматического добавления фотосета в топик. Если его включить, то все фото добавятся после текста топика, если отключить, то фотосет нужно будет добавлять в топик вручную с помощью сниппета ```<alto:photoset/>```
![image](https://cloud.githubusercontent.com/assets/1106990/6455311/8f931b16-c163-11e4-8d61-868858a99f73.png)

**Comment by lsnull** [comment]
качал альфу дня два назад. мне обновит с гитхаба и скачать свежую альфу ?
![screenshot_63](https://cloud.githubusercontent.com/assets/7164280/6459309/25d39ea2-c196-11e4-848e-8e47e78b44b0.jpg)

**Comment by aVadim483** [comment]
Альфа перенесена сегодня ночью в мастер-ветку, обновляться из нее нужно

**Comment by lsnull** [comment]
вот как... А как правильно обновится можете ссылку дать с альфа на обновленную альфа без потерей...?

**Comment by aVadim483** [comment]
Да прямо на странице проекта https://github.com/altocms/altocms есть ссылка в правом сайдбаре "Download ZIP" - https://github.com/altocms/altocms/archive/master.zip
