### ISSUE TITLE
Проблема с редактором в Админке (Редактирование страниц)

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#352]
Не корректно отображается и работает редактор в Админ панели в разделе (Редактирование страниц):
![screenshot_62](https://cloud.githubusercontent.com/assets/7164280/6440443/920b5800-c0e5-11e4-899d-e72f33871a52.jpg)
А так же не могу загрузить изображение функция загрузки изображения в редакторе не отвечает.

**Comment by andrey-v** [comment]
Сниппеты исправлены - 5a3654a3b3fccddf7f02ee0777f06e8b746e0cbd
