### ISSUE TITLE
Не работают опросы и загрузка изображений в модальном окне в редакторе топика

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#353]
Не работают опросы в топике, бесконечно долгая полоска вверху экрана и колесо ajax загрузки, не работает загрузка изображений непосредственно в редакторе топика, не дает выбрать в модальном окне пункты меню: из интернета, топки, этот топик. Активный только пункт «С этого компьютера» и только загрузка с компьютера.

**Comment by andrey-v** [comment]
А в консоли браузера есть какие нибудь ошибки?
