### ISSUE TITLE
Не отображается фотосет в Топике

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#354]
При загрузки фото массовым загрузчиков (фотосет) в топик, после сохранения Топика в нем не отображаются загруженные фотографии.

**Comment by andrey-v** [comment]
Исправил уже в задаче https://github.com/altocms/altocms/issues/350

![image](https://cloud.githubusercontent.com/assets/1106990/6459126/8d48839e-c19c-11e4-9124-9ca0da7c6d1e.png)

**Comment by lsnull** [comment]
У меня нет этой функции для выбора отображать или нет...
![screenshot_63](https://cloud.githubusercontent.com/assets/7164280/6459272/de0ccbfc-c195-11e4-85ed-87c361e1e016.jpg)
может в админке гдето нужно включить или в конфиге ? Но реавльно нет

**Comment by andrey-v** [comment]
Я сегодня ночью исправил, обновитесь )

**Comment by andrey-v** [comment]
А ещё фотосет в топик можно частями вставлять 
![image](https://cloud.githubusercontent.com/assets/1106990/6459389/324d0e08-c19f-11e4-92d0-8af7dd0ca427.png)

**Comment by lsnull** [comment]
Спасибо большое. Щас обновлюсь. Думаю Можно закрывать тему.
