### ISSUE TITLE
Отображение фото в топике

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#355]
Фотография с описанием в топике выходит за рамки. Загрузка даной фото происходила через текстовый редактор.
![screenshot_61](https://cloud.githubusercontent.com/assets/7164280/6458977/80a3b294-c192-11e4-8686-72ea8ed1d7b8.jpg)

**Comment by andrey-v** [comment]
Исправлено

**Comment by lsnull** [comment]
Ох как оперативно! Спс.
