### ISSUE TITLE
Отображение аватар и превью

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#356]
После конвертации с ЛС 1.0.3 на Альто 1.0 и после чего на 1.1а, вот что происходит с images
![screenshot_65](https://cloud.githubusercontent.com/assets/7164280/6469970/4446910c-c1e9-11e4-8103-f77a5123ae74.jpg)
и так же на Аватарах
![screenshot_66](https://cloud.githubusercontent.com/assets/7164280/6470038/a56acff2-c1e9-11e4-970a-07492b07240c.jpg)
После названия картинки (авы, превью ...) к примеру http://site.com/uploads/images/00/00/01/2013/06/22/avauser.jpeg добавляется после "-222x.jpg" ну и с другими и другим значением.

**Comment by andrey-v** [comment]
>После названия картинки (авы, превью ...) к примеру http://site.com/uploads/images/00/00/01/2013/06/22/avauser.jpeg добавляется после "-222x.jpg" ну и с другими и другим значением.

Это как раз и правильно, так устанавливаются нужные размеры для картинки, которые движок сам должен нарезать из исходной - http://altocms.ru/420.html
Неправильно то, что почему-то он так не делает, хотя, судя по картинке, исходные изображения присутствуют.

>После конвертации с ЛС 1.0.3 на Альто 1.0 и после чего на 1.1а
А как конвертация проводилась? попробую у себя воспроизвести ошибку.

**Comment by lsnull** [comment]
стоял ЛС 1.0.3 было уже там много публикаций. Я удалил все папки. Базу естественно не трогал. Загрузил Альто... Начал установку, выбрал конвертацию БД с ЛС на Альто 1.0, так как сразу с ЛС на Альто 1.1 нетс. После того как установил, загрузил через ФТП поверх 1.0 альты, файли,папки уже "Альфа" 1.1а с заменой и так же продолжил установку с конвертацией БД с 1.0 на 1.1

**Comment by andrey-v** [comment]
Понял, попробую воспроизвести у себя

**Comment by lsnull** [comment]
Спасибо за отзывчивость. Буду ожидать вашего ответа...

**Comment by lsnull** [comment]
Добрый вечер. Вы не проверяли у себя ?

**Comment by andrey-v** [comment]
Да, пробовал:
- создал чистую ls-1.0.3;
- создал блог и для него установил логотип, установил логотип и фото пользователя;
- удалил все файлы, а папку uploads сохранил в другое место;
- в папку сайта скопировал файлы **Alto 1.1a** (а не 1.0.10.2!);
- запустил установку и выбрал конвертацию БД из ls в Alto 1.0 (имя БД автоматически не прописывается, его нужно указать самому, если этого не сделать, то этап установки пройдёт, но ошибки ни какой не высветится);
- удалил куки для этого сайта в браузере и запустил установку ещё раз;
- теперь выбрал конвертацию из Alto 1.0 в Alto 1.1a;
- ранее сохранённую папку uploads скопировал поверх существующей;
- удалил install и вернулся на сайт.

После таких манипуляций логотип блога и картинки пользователей выводятся правильно. Повторите у себя в той последовательности в которой сделал я, если опять не получится то пишите, будем разбираться.

**Comment by lsnull** [comment]
Хорошо, щас попробую.

**Comment by andrey-v** [comment]
администратора создал ещё в ls, а потом пропускал.

**Comment by lsnull** [comment]
сделал все так же....
![screenshot_72](https://cloud.githubusercontent.com/assets/7164280/6501120/0714aff0-c31d-11e4-9843-a37307707c49.jpg)
Проблема осталась как в аватарах так и в превью блога и отоброжения ранее загруженых фото в топик. ((

**Comment by andrey-v** [comment]
попробуйте в браузере открыть картинку по адресу без добавочного -32x32-crop.jpg

**Comment by lsnull** [comment]
Открывается...

**Comment by andrey-v** [comment]
В логах что-нибудь есть - *.../_tmp/logs/error.log*

**Comment by lsnull** [comment]
Нет

**Comment by andrey-v** [comment]
Странно, а права на запись у каталога upload и тех что внутри него есть?

**Comment by lsnull** [comment]
Это не может из за того, что в общем дали шаблон атлас. И под него нужно было mainpreview с исправленным конфигом с другимми разрешениями для изображений. Не могло это как то повлиять?

**Comment by lsnull** [comment]
В upload все есть... все фото есть и дело в том, что некоторые превью Блогов есть а некоторых нет. Так же и Аватары. И фото в Блогах

**Comment by lsnull** [comment]
Если бы -32x32-crop.jpg не дописывалось, то точно бы отоброжалось все. )

**Comment by andrey-v** [comment]
Попробуйте дефолтную тему и с отключенными плагинами

**Comment by lsnull** [comment]
всмысле? Можно по подробней?

**Comment by andrey-v** [comment]
В админке отключить плагины и включить тему experience simple/

**Comment by lsnull** [comment]
А они оказались автоматически отключены после установки о.О. При отключенных плагинах выбрал шаблон который вы сказали, все так и осталось? Или надо где то после чистить кеш?

**Comment by andrey-v** [comment]
Шаблон не поменялся?

**Comment by lsnull** [comment]
шаблон сменил в Админке Альто, плагины и включал и отключал ( Все равно http://losper.net/

**Comment by andrey-v** [comment]
Вы посмотрели права на запись у каталога upload и тех что внутри него?

**Comment by lsnull** [comment]
мне щас нужно бежать . давайте в часиков 22-23.00 спишимся если это возможно у нас по +2 ?

**Comment by andrey-v** [comment]
попробуем )

**Comment by lsnull** [comment]
спасибо! Просто если что я попробую занаво загрузить Бкап Базы с ЛС и вернуть все те файлы и резервную копию ЛС, Там в админке в самой ЛС отключить все плагины и сменить шаблон на Стандартный. После чего сделать всю данную манипуляцию.

**Comment by lsnull** [comment]
Я на месте. Ни каких идей и предложений новых нет ? ) Мне приступить к планированому действию?

**Comment by lsnull** [comment]
В общем вернул базу ЛС. Загрузил Бекап файлов ЛС. Зашел в админку aceapminpanel :) Отключил там все плагины, сбросил через Админку кеш и настройки. Удалил после все плагины через Админку на ЛС. Выбрал шаблон по умолчанию. Сохранил. Зашел на сайт все авы и фото с превью Отоброжаются нормально. БД стала меньше по таблицам буквально на -8 не особо значительно. Но изминения в Базе произошли. После повторил все манипуляции, точ в точ как вы мне описывали ранее. Та же проблему а меня осталась с отображением "images" Что делать? (((

**Comment by andrey-v** [comment]
Давайте ещё раз попробуем.
1. Вы не посмотрели (а может посмотрели, но мне не отписали) есть ли права на запись в каталог uploads и те, что лежат внутри него. Вполне возможно, что права слетели и движок просто не может записать в папку изображение нового размера... Он берёт исходное, режет его, но сохранить не может, такое бывает, проверьте, пожалуйста.

2. В БД, в таблице prefix_blog в поле blog_url путь к какой картинке указан?

**Comment by lsnull** [comment]
Да, Права на запись стоят 755

**Comment by lsnull** [comment]
Что получается:
![screenshot_86](https://cloud.githubusercontent.com/assets/7164280/6525297/98f5ab0a-c40c-11e4-9eda-503eb03241a6.jpg)
Но ссылки у них вот какие:

**Comment by andrey-v** [comment]
Можете скинуть мне доступы на ftp на адрес *andreyv@gladcode.ru*
Ошибка у меня упорно не воспроизводится хотя на вашем сайте её вижу. Посмотрю на месте, так наверное быстрее будет.

**Comment by lsnull** [comment]
Скинул. Вы видели?

**Comment by andrey-v** [comment]
Да, я вам даже ответное письмо написал, что вы мне забыли пароль от ftp дать. Все настройки в присланном вами письме есть, а вот пароля нет (

**Comment by lsnull** [comment]
а на какую почту вы мне писали? )

**Comment by andrey-v** [comment]
losper@*** 08.03.2015 7:32

**Comment by lsnull** [comment]
помогите с https://github.com/altocms/altocms/issues/390 у меня на сайте досихпор ошибка. Отправил вам пасс

**Comment by andrey-v** [comment]
>Отправил вам пасс

Отправил ответное письмо, посмотрите дошло ли...

**Comment by andrey-v** [comment]
Всё, посмотрел меняйте пароль ))). 
Всё замечательно там, единственное, что меня смущает так это права на каталоги 755. Вполне возможно, что каталоги создавались от имени рута или иного пользователя (когда вы копировали файлы из LS) а скрипты alto запускаются от имени другого пользователя и, соответственно, владельцы папок разные. 

Сейчас, когда вы заменили картинки блогов и пользователей воспроизвести ситуацию сложно, но если будет время попробуйте с правами на каталог 777, это не есть хорошо, но позволит вычислить причину ошибки.

**Comment by lsnull** [comment]
Я понял. Спасибо большое.! Попробую.

**Comment by aVadim483** [comment]
Похоже, тут проблема решена, поэтому закрываю тикет

**Comment by lsnull** [comment]
Вроде как решена ;) Спасибо.
