### ISSUE TITLE
Отоброжение списка фото в топике

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#358]
Вот еще после загрузки фото через массовый загрузчик и сохранения топика с фотографиями , не корректно отображается список фото в Топике в обеих Шаблонах: Experience v.1.0.3 и Experience Simple v.1.0.0 :

![screenshot_70](https://cloud.githubusercontent.com/assets/7164280/6471389/2837b55e-c1f3-11e4-8fa2-75b9869e6fef.jpg)

![screenshot_69](https://cloud.githubusercontent.com/assets/7164280/6471390/28392600-c1f3-11e4-98a4-9a0609c3646b.jpg)

**Comment by lsnull** [comment]
Вчера так все было оперативненько =(  Вы сегодня отдыхаете?

**Comment by andrey-v** [comment]
![image](https://cloud.githubusercontent.com/assets/1106990/6499885/8f9ed526-c313-11e4-900a-9892485f4e37.png)
