### ISSUE TITLE
engine/libs/DbSimple3/lib/DbSimple/Database.php

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#360]
Конвертировал с ЛС на Альто 1.0 \ После почистил в браузере кеш. Пытаюсь запустить повторно установку, что бы конвертировать БД уже с Альто 1.0 до 1.1. Не вышло, реакции "0" все равно стит на последнем этапе "Удалите install для завершения" - ну что то типо такого там написанно, но  на этапе последнем стоит.  Зашел через Хром, решил с него попторить установку. Установка началась, конвертировал БД с Альто 1.0 до 1.1. Удалил install, установка завершена и в Хроме сайт загрузился. Но в Мазиле досих пор даже после 3 попыток чистить Кэш, Куки, Настройки Сайтов, безполезно вот что выдает и на сервере происходит с Мозилы если пытаюсь зайти.
Эта ошибка у меня одного выскакиевает? 

![screenshot_74](https://cloud.githubusercontent.com/assets/7164280/6516204/b0862976-c398-11e4-8ab7-7859fb88ff2b.jpg)

После чего на хостинге ложится Проц. Когда в мазиле хочу зайти на сайт.

![screenshot_73](https://cloud.githubusercontent.com/assets/7164280/6516327/afefcdfe-c399-11e4-8057-0c803d782fb2.jpg)
 P.S. Мой хост выдерживал "Битрикс24". Поэтому один Альто не должен так грузить проц. Хостинга...

**Comment by andrey-v** [comment]
> Не вышло, реакции "0" все равно стит на последнем этапе "Удалите install для завершения" - ну что то типо такого там написанно, но на этапе последнем стоит.

Нужно в браузере удалить куку PHPSESSID

**Comment by lsnull** [comment]
А как мне именно этот кук удалить в Мазиле ? Я не хочу все удалять со всех сайтов )

**Comment by andrey-v** [comment]
![image](https://cloud.githubusercontent.com/assets/1106990/6540368/2b4dc020-c4ab-11e4-9535-aa7fb9598d5f.png)

**Comment by lsnull** [comment]
спасибо )
