### ISSUE TITLE
dropdown-user-menu

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#361]
Не отображаются значки в Chrome

![screenshot_75](https://cloud.githubusercontent.com/assets/7164280/6516920/ba127bd8-c39e-11e4-911c-450cf490094d.jpg)

**Comment by andrey-v** [comment]
У меня работает, а на вашем сайте проверить не могу, у вас рекапча не настроена и не даёт зарегистрироваться.
![image](https://cloud.githubusercontent.com/assets/1106990/6520576/8f29030c-c3d9-11e4-8310-81edad2c0901.png)

**Comment by lsnull** [comment]
Щас рукапчу отключу
