### ISSUE TITLE
Фото в топике

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#362]
Скачал Альфу ночью с Гитхаба. Вроде как я понимаю было инсправлено отоброжение фото в блоге. Но вот, что вышло после того, как создал новый Топик с Фотографиями в Новосозданный Блог. 

![screenshot_80](https://cloud.githubusercontent.com/assets/7164280/6518504/918eee06-c3af-11e4-9a5e-62f9e608e526.jpg)
могу даже дать ссылку

**Comment by andrey-v** [comment]
Опять вылезла (
Исправил, проверьте у себя пожалуйста.

**Comment by lsnull** [comment]
Не совсем могу понять, в хроме вроде все норм. А вот в Мазиле осталось по прежнему. Чистил Кэш, Куки, Временные(автономные) файлы в нем. Это У меня с Браузером Глюк? Провереть можете у меня?

**Comment by andrey-v** [comment]
Всё хорошо.

**Comment by lsnull** [comment]
Я уже снес ту установку. Поэтому все норм ;)

**Comment by lsnull** [comment]
Спасибо, все работает. Тему закрываю.
