### ISSUE TITLE
Управление пользователями через Админку.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#364]
Если создать пользователя, после чего его Удалить и создать другого, то ID будет оставатся по счету созданных пользователей. 
К примеру:
У меня был 1 пользователь "Админ". Я создал второго пользователя, после чего ему был автоматом присвоен ID 2, так как ID 1 был присвоен Администратору (первому зарегистрированному на сайте).  Удалил второго пользователя, которого создавал и создал другого, после чего я обратил внимание на то,  что ID было присвоено теперь не ID 2 а ID 3, но пользователей всего 2-а.

![screenshot_83](https://cloud.githubusercontent.com/assets/7164280/6523449/9339572a-c3f8-11e4-82fe-5ccb05063d84.jpg)

**Comment by aVadim483** [comment]
ID всегда создается новый, это так и будет так. В теории ID даже не обязательно последовательно могут присваиваться. Но всегда - новый, независимо от того, сколько записей в базе.

**Comment by lsnull** [comment]
Я понял. Жаль что подругому не выйдет. Было бы очень удобно. Спасибо за ответ
