### ISSUE TITLE
Не могу удалить через Админку 2-го Администратора

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#365]
Создал случайно пользователя Demo как Администратором. Теперь Не могу его удалить. Так как хотел создать как пользователь, для тестирования. Не хотелось бы ручками базу чистить и другим не опытным будет еще проблемотичней ;)
![screenshot_84](https://cloud.githubusercontent.com/assets/7164280/6523486/f6e67050-c3f8-11e4-8bc6-588b2aad3cff.jpg)

**Comment by aVadim483** [comment]
Сначала надо сделать его неадминистратором

**Comment by lsnull** [comment]
Прошу прощения за не внимательность. Увидел крестик напротив - исключить ;) Еще раз прошу прощения. Спасибо.
