### ISSUE TITLE
Движок позволяет голосовать за черновик

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#367]
Например при доступе по прямой ссылке. Это открывает широченное поле для накруток.

**Comment by inliquid** [comment]
Неа. Все равно позволяет проголосовать.

**Comment by inliquid** [comment]
![1](https://cloud.githubusercontent.com/assets/6797881/6546292/b5181bf6-c5bf-11e4-86be-2e4402d2330f.png)

**Comment by andrey-v** [comment]
Может обновление не прошло, попробуй нщё раз проверить. У меня работает
![image](https://cloud.githubusercontent.com/assets/1106990/6549439/09302c1a-c624-11e4-879c-7da387451913.png)

**Comment by inliquid** [comment]
Ты смотришь автором черновика. В этом случае и так нельзя проголосовать. А попробой включить прямые ссылки и дай эту ссылку другому юзеру.

**Comment by inliquid** [comment]
Ап)
