### ISSUE TITLE
Онлайн

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#372]
Я так понимаю это та же проблема что и в ЛС с Онлайн?
Времени прошло уже не мало с последнего визита. На странице пользователя видно что Оффлайн. Это очень сильно путает новых пользователей.
![screenshot_96](https://cloud.githubusercontent.com/assets/7164280/6543922/b2709514-c53c-11e4-877f-015e697bec12.jpg)
При этом всем. Какой бы я часовой пояс не показывал у меня не правильно отображается время.

**Comment by andrey-v** [comment]
Да, это наследие LS. Страница ни когда не показывала тех кто онлайн, а только 15 последних посетителей сайта (

**Comment by lsnull** [comment]
Спасибо. Тема закрыта.
