### ISSUE TITLE
Белая полоса при ужатии картинок

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#373]
Я об этом писал в рамках другой проблемы, но думаю имеет смысл ее выделить отдельно. Если загружаемая картинка, например в топик превышает установленный максимальный размер, то при ее ужатии иногда остается белая полоса - снизу, или сбоку
Пример:
https://cloud.githubusercontent.com/assets/6797881/6138270/a50e81ac-b190-11e4-81b4-44963207b62f.png

Думаю это довольно просто исправляется и связано с какой-нибудь операцией округления в большую сторону.

Тоже самое иногда происходит с аватарками, и с другими картинками.

А вот исходная проблема где я об этом написал https://github.com/altocms/altocms/issues/336

**Comment by aVadim483** [comment]
Такая проблема в 1.0 действительно есть и связана с тем, что в используемой библиотеке изменение изображений всегда работало только через масштабирование. 

В 1.1 эта проблема решена

**Comment by inliquid** [comment]
А нельзя исправить? Или подскажите мне где именно проблема, в какой библиотеке - я сам сделаю.

**Comment by aVadim483** [comment]
Для обработки изображений используется эта библиотека:
/engine/libs/PHPixie/

В предыдущей версии при использовании Imagick ресайз выполнялся только через масштабирование (метода scale), поэтому и проблемы с округлением возникали.

В используемой в 1.1 библиотеке это делается непосредственно через метод resize с заданием точных новых размеров.

Подгонять это к 1.0 и тестировать, к сожалению, нет времени.
