### ISSUE TITLE
CSS Настраиваемого шаблона

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#376]
Если менять ширину сайта в пикселях с 1030 на другую, то не корректно отоброжается фотосет в Топике и вот еще:
![screenshot_102](https://cloud.githubusercontent.com/assets/7164280/6548211/16f8216a-c5fa-11e4-9a4a-a65e7c60c686.jpg)

и еще при смене Ширины шаблона настраиваемого

![screenshot_103](https://cloud.githubusercontent.com/assets/7164280/6548286/294aabec-c5fc-11e4-8f93-b41b6445489b.jpg)

**Comment by andrey-v** [comment]
Фотосет поправил, а вот сила и рейтинг просто физически не помещаются в маленькую сетку. Здесь, раз уж вы уменьшили ширину сайта, то поправьте вёрстку. В Experience Simple используется 24-x колоночная сетка
* [В файле профиля](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/tpls/actions/profile/action.profile.pre.tpl#L10) - 17 колонок на левую часть шапки с именем пользователя.
* [В плагине рейтинга](https://github.com/altocms/altocms/blob/master/common/plugins/rating/templates/skin/experience-simple/tpls/user/profile.header.inject.tpl#L1) 3 колонки на силу
* [Там же](https://github.com/altocms/altocms/blob/master/common/plugins/rating/templates/skin/experience-simple/tpls/user/profile.header.inject.tpl#L11) 4 колонки на рейтинг

Можете поправить на 15-4-5, например. Всё будет зависить от выбраной вами ширины сайта

**Comment by andrey-v** [comment]
![image](https://cloud.githubusercontent.com/assets/1106990/6550146/35e201a8-c632-11e4-9674-c4365e404a43.png)
Попробуйте обновить страницу Ctrl+F5. У мозилы бывает, что  ресурсы не подгружаются.

**Comment by lsnull** [comment]
Спасибо большое. Оперативно!
