### ISSUE TITLE
CSS Создать Топик

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#377]
![screenshot_104](https://cloud.githubusercontent.com/assets/7164280/6548323/fb0946f2-c5fc-11e4-9884-a4d9fb8b55f5.jpg)

**Comment by lsnull** [comment]
Спасибо большое. Оперативно!

**Comment by lsnull** [comment]
Все равно
![screenshot_105](https://cloud.githubusercontent.com/assets/7164280/6552964/2db2abd2-c654-11e4-906f-1ebb30dc01d9.jpg)

**Comment by lsnull** [comment]
![screenshot_132](https://cloud.githubusercontent.com/assets/7164280/6567512/127ea6b8-c6d1-11e4-8d86-265f6a16e1dd.jpg)
До этого вроде было норм. Вечером еще обновлялся было норм. Теперь чет подскочил )

**Comment by lsnull** [comment]
Не исправлено ((

**Comment by andrey-v** [comment]
Вернул как было
![image](https://cloud.githubusercontent.com/assets/1106990/6593069/f124595c-c7e5-11e4-8683-8e86614f111b.png)
