### ISSUE TITLE
Превью фото с фотосета

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#380]
Выбрал Фото как превью, в итоге растянуло на всю ширину и высоту, что потерялось качество фото.
![screenshot_111](https://cloud.githubusercontent.com/assets/7164280/6556860/fd1e68a6-c678-11e4-82f6-ab59a1d2af5a.jpg)

**Comment by andrey-v** [comment]
Сейчас в топике картинка превью принудительно приводится к ширине колонки контента. Движок умеет масштабировать картинки как угодно, но вот масштабировать картинку только если её размеры превышают определённый - нет.

С другой стороны выводить оригинал без масштабирования тоже не стоит...

Зато исправил ошибку смены превью (когда превьюшка просто не менялась) и убрал принудительный вывод первой картинки фотосета в качестве превью

**Comment by lsnull** [comment]
Благодарен вам за эту доработку! Щас проверю...

**Comment by lsnull** [comment]
не работает... =\

**Comment by andrey-v** [comment]
>не работает... =\ 

Что именно?

**Comment by lsnull** [comment]
Выше отредактировал сообщение, где указал )

**Comment by andrey-v** [comment]
>Выше отредактировал сообщение, где указал )

Не вижу, так что же всё таки не работает?

**Comment by lsnull** [comment]
(Зато исправил ошибку смены превью), превью не отключается =(

**Comment by andrey-v** [comment]
На вашем сайте старый js-скрипт, что-то всё таки не обновилось
![image](https://cloud.githubusercontent.com/assets/1106990/6567207/9044d2a4-c6d4-11e4-85bd-b41939db0ab5.png)

**Comment by lsnull** [comment]
Щас пропробую еще раз обновить
