### ISSUE TITLE
Превью фото

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#381]
Выбрал Превью, теперь не могу его отключить. Либо Выбрать другое фото Как превью. Но к примеру я не хочу выбирать превью из загруженных фото. По умолчанию его вроде нет? Но если выбрал то все....
![screenshot_112](https://cloud.githubusercontent.com/assets/7164280/6556913/66bc4ab2-c679-11e4-9db5-2434abf85198.jpg)
Проверьте плз...

**Comment by lsnull** [comment]
У меня не заработало отключение

**Comment by andrey-v** [comment]
Всё должно работать, проверьте, обновились ли [вот эти](https://github.com/altocms/altocms/commit/a5be161225d0fd12676f78cf3d8f08dd7d742b1b) файлы.

**Comment by andrey-v** [comment]
На вашем сайте старый скрипт, что-то всё таки не обновилось
![image](https://cloud.githubusercontent.com/assets/1106990/6566947/4c77ee56-c6d1-11e4-9224-b903562f9f3a.png)
