### ISSUE TITLE
Добавление нового типа блога

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#382]
Не вводятся буквы и цифры с символами

![screenshot_113](https://cloud.githubusercontent.com/assets/7164280/6557648/3f875e72-c67f-11e4-86bd-64b352c736fd.jpg)

**Comment by inliquid** [comment]
Это не баг. Там появятся значения если в поле названия указать имя языковой переменной.

**Comment by lsnull** [comment]
так я в это поле ничего ввести не могу

**Comment by lsnull** [comment]
не для новичка. не каждый поймет... но спс за ответ

**Comment by inliquid** [comment]
Я сам поначалу долго не мог врубиться...
