### ISSUE TITLE
Редактирование после Добавленные поля

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#383]
После создания поля textarea не меняется при редактировании на input ((
![screenshot_116](https://cloud.githubusercontent.com/assets/7164280/6558439/dbbec488-c684-11e4-9aef-b98c472fca32.jpg)
И еще не мало раздражительный момент
Отключил вот Ссылку на оригинал, так как есть эта возможность при выборе доп. поле + можно сделать описание к этому полю.
![screenshot_118](https://cloud.githubusercontent.com/assets/7164280/6558540/62415304-c685-11e4-83ea-e990cfdb151e.jpg)
Но После того когда создал еще одно поле, она опять автоматически включается:
![screenshot_117](https://cloud.githubusercontent.com/assets/7164280/6558563/8a15bba4-c685-11e4-8cf9-cc63ea1f64a6.jpg)
С фотосетом не пробовал.
Буду благодарен!

**Comment by andrey-v** [comment]
>После создания поля textarea не меняется при редактировании на input ((

Исправил, но работать будет только в том случае если у поля ещё нет ни одного значения, иначе смена типа поля невозможна.

>Но После того когда создал еще одно поле, она опять автоматически включается

Забыли сохранить тип контента
![image](https://cloud.githubusercontent.com/assets/1106990/6567168/f6f3a6c0-c6d3-11e4-8265-6d46aebcedbb.png)

**Comment by lsnull** [comment]
Понял вас. Спасибо!
