### ISSUE TITLE
Редактирование Меню

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#386]
Не могу отредактировать
![screenshot_122](https://cloud.githubusercontent.com/assets/7164280/6559591/af1a4ec2-c68c-11e4-8149-ff630712400e.jpg)

**Comment by andrey-v** [comment]
Если нажать эту кнопку есть ошибки в консоли браузера
![image](https://cloud.githubusercontent.com/assets/1106990/6567254/7f4454a6-c6d5-11e4-8ca1-6b9a499aa6dc.png)

**Comment by andrey-v** [comment]
Не смотрели ещё?

**Comment by yuri25** [comment]
Я у себя попробовал отредактировать только названия топиков, все названия изменяются кроме "Обсуждаемые" - В админке они например "Горячие" - на главной остаются "Обсуждаемые"

**Comment by lsnull** [comment]
ссылка не редактировалась
