### ISSUE TITLE
Сайт после установки не открывается

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#387]
Только что скачал, установка без проблем. После удаления папки install и при переходе на главную сайт просто не открывается, висит и все. Висит очень долго, как будто зациклилось что то. Ошибки 502 я не дождался, висит уже минут 10.

**Comment by yuri25** [comment]
Вот дождался, времени прошло очень много 504 Gateway Time-out

**Comment by yuri25** [comment]
Перезалил папки common и engine с работающего сайта (немного пораньше скачивал и устанавливал) - не помогло:(

**Comment by yuri25** [comment]
Еще раз скачал, поставил заново - все работает. Что это было... возможно криво скачал... Можно тикет закрыть.

**Comment by andrey-v** [comment]
А файл лога ошибок *_tmp/logs/error.log*  что нибудь пишет?

**Comment by yuri25** [comment]
Сейчас все установилось и пока даже папки такой нету _tmp/logs   а в первый раз я не догадался там посмотреть... скорее всего криво скачал или залил криво.

**Comment by andrey-v** [comment]
Давайте тогда закроем, потому что ошибка не воспроизводится, а без логов сложновато будет догадаться что же такое случилось. Если повторится о обязательно напишите, будем выяснять что это было.

**Comment by yuri25** [comment]
Хорошо Андрей

**Comment by yuri25** [comment]
Вот сейчас, снова скачал с гита, снова не открывается главная ни в какую. В папке _tmp отсутствуют  папки logs и templates. Там только папка cache пустая и все....
