### ISSUE TITLE
css smile fo script alto cms

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#388]
![screenshot_123](https://cloud.githubusercontent.com/assets/7164280/6560364/27af6b92-c692-11e4-82fa-7a0263bfd20e.jpg)
Если отключить width and max-width то все будет норм.

**Comment by andrey-v** [comment]
Плагин смайлов был ещё в сентябре прошлого года исправлен...
Скачайте новую версию вот тут - http://altocms.ru/addons/download/item/89/
![image](https://cloud.githubusercontent.com/assets/1106990/6592226/f1edca80-c7db-11e4-9f0f-e10bfb2c5b25.png)

**Comment by klaus-spb** [comment]
Там правки вносились для шаблона experience, а это шаблон называется иначе и стили берутся из default  и могут быть такие проблемы.

Но в любом случае это проблемы плагина и в ближайшее время их исправлю https://github.com/klaus-spb/alto-plugin-smiles

**Comment by andrey-v** [comment]
Тогда закрываю, но вроде и так работает )
