### ISSUE TITLE
Удаление комментария

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#389]
Нажимаю удалить комментарий. Но после  комментарий как обычно виден. Только пропадает функция "Удалить" После обновлении страницы видно только изминение в том что теперь в место корзинки стало восстановить (другой значек). Даже мне как Админу тяжело увидеть  какие удаленны а какие нет.
![screenshot_124](https://cloud.githubusercontent.com/assets/7164280/6560549/a73ed2a2-c693-11e4-87c1-1bceb511e827.jpg)

**Comment by aVadim483** [comment]
@andrey-v В css, наверно, надо поправить, чтоб удаленный комментарий выделялся

**Comment by lsnull** [comment]
Лучше бы что бы комментарий вообще удалялся а на восстановление довалось к примеру 24 часа или 30мин. И база за одно меньше будет.

**Comment by andrey-v** [comment]
В Альто комментарии идут деревом, а не списком. Если удалять комментарий совсем (пусть даже скрывать его) то что делать с комментариями которые были ответами на удаляемый? Кроме того и алгоритм по которому это дерево комментариев строится подразумевает возможность удаления узла дерева только с удалением подчинённой ветки, либо с переносом подчинённой ветки другому узлу.

**Comment by lsnull** [comment]
тогда удалять с ответами, так как это будет логичней, либо  с переносом подчинённой ветки другому узлу.  либо Делать еще проще, выводить запись о том, что "Пользователь или администрация удалила Комментарий в этой ветке" что то в таком роде )
