### ISSUE TITLE
Fatal Error "Ошибка при удалении блога"

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#390]
Был блог с топиком. Удалил сразу блог при этом было выбрано удалить статьи. После удаления вылезла ошибка
![screenshot_125](https://cloud.githubusercontent.com/assets/7164280/6560702/aa579086-c694-11e4-9b2f-c805326b979f.jpg)

После обновлении страницы и сброса Кэша
![screenshot_126](https://cloud.githubusercontent.com/assets/7164280/6560751/1571f686-c695-11e4-8a74-f161f978aba6.jpg)

Хелп. Ошибка на главной странице даже. Правый блок не отоброжается
Заменил все файлы с lib на сервер с заменой, почистил  _tmp , все равно ошибки.

**Comment by andrey-v** [comment]
Удалите папку закэшированных шаблонов *_tmp/templates*

**Comment by lsnull** [comment]
именно папку?

**Comment by andrey-v** [comment]
[Вот этот](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/tpls/widgets/widget.stream_comment.tpl) файл обновите и проверьте ещё раз.

**Comment by lsnull** [comment]
пеперь 
![screenshot_129](https://cloud.githubusercontent.com/assets/7164280/6563765/43593ad4-c6ac-11e4-8b05-30cefb9f693c.jpg)

**Comment by andrey-v** [comment]
Ещё раз замените файл

**Comment by lsnull** [comment]
Ура :) Так а из за чего ошибка была? Я понял что это касалось того файла но как так вышло не понял. Работает!

**Comment by andrey-v** [comment]
Была какая-то проблема с кэшем. Список комментариев брался не из БД, а из кэша который почему-то не обновился при удалении блога.

**Comment by lsnull** [comment]
Спасибо большое! Вы лучшие ;)
