### ISSUE TITLE
Описание имени файла для  при загрузке

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#392]
![screenshot_128](https://cloud.githubusercontent.com/assets/7164280/6561691/e506c312-c69b-11e4-83e8-26c3adea4c3c.jpg)

**Comment by andrey-v** [comment]
Исправлено
![image](https://cloud.githubusercontent.com/assets/1106990/6592059/97ad1974-c7d9-11e4-8946-2f451e28d557.png)
