### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#394]
Это из аз плагина или же в самом движке причина? Как по мне так на плагин ничего не указывает )
![screenshot_131](https://cloud.githubusercontent.com/assets/7164280/6567068/79e37984-c6ca-11e4-9978-4222ca4e8357.jpg)

**Comment by andrey-v** [comment]
Это плагин, плагины пока на совместимость с альфой не тестировались

**Comment by aVadim483** [comment]
Да, это плагин категорий. Причем, ему почему-то не хватает поля, которое изначально должно быть. Сверьтесь с SQL-запросом, который в комплекте с плагином идет, и поправьте базу. Возможно, заработает. Пишу "возможно", т.к. Андрей верно заметил - плагины с самим движком версии 1.1 еще не тестировали

**Comment by lsnull** [comment]
Была проблема в ошибки если загружал Картинку для категории. Без картинки все нормально загрузилось
