### ISSUE TITLE
Тип контента: добавление

### ISSUE THREAD

**Issue by aleksanderd** [altocms/altocms#395]
Создал свой тип контента с системным именем news_item.
В меню добавления содержимого оно появилось, но дает 404 (путь `/content/news_item/add/`).
Это шаблон нада править или путь норм? Какой должен быть путь для добавления/редактирования/итд топиков пользовательского типа?

Спасибо!

**Comment by aVadim483** [comment]
Воспроизвел кейс. Такое может быть, если нет ни одного блога, куда может быть добавлен топик такого типа. Нужно в каком-то типе блога либо явно разрешить создание топиков такого типа, либо разрешить все (снять "галки" со всех типов)

**Comment by aleksanderd** [comment]
понял, сделал, заработало!
спасибо!

**Comment by lsnull** [comment]
В блоге выбрать не Открытый блог а Тот какой Тип создавали для блога
