### ISSUE TITLE
Текст в комментарии

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#396]
Я сталкивался с этой проблемой в своем шаблоне на ЛС, но уже не помню как и где точно я правил, что бы избавится от этого случая как сейчас:
![screenshot_133](https://cloud.githubusercontent.com/assets/7164280/6582184/45ac3a44-c764-11e4-9ef6-530f99bbd929.jpg)

**Comment by aVadim483** [comment]
А как в принципе должна решаться такая проблема? Скрывать "хвост" строки? Принудительно ее перенести ведь мы не можем

**Comment by lsnull** [comment]
как это? не реально сделать перенос продолжение строки на другую ??

**Comment by aVadim483** [comment]
Пардон, ступил: 
word-wrap: break-word;

**Comment by lsnull** [comment]
CSS самому править и каждый раз после каждого обновления или как ? ))

**Comment by aVadim483** [comment]
Тикет назначен Андрею, он посмотрит и поправит в "коробке"
