### ISSUE TITLE
Блоги

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#397]
![screenshot_1](https://cloud.githubusercontent.com/assets/7164280/6585910/243e8140-c77e-11e4-9a77-7994909e6b24.jpg)

**Comment by andrey-v** [comment]
Виджет свёрстан заново, исправлены отступы и длинные названия блогов теперь уходят под троеточие...
![image](https://cloud.githubusercontent.com/assets/1106990/6591764/95101b3e-c7d5-11e4-98a9-a671f61481aa.png)

**Comment by lsnull** [comment]
можно добавить подсказку а точнее вывод полного названия при наведении мышки на сокращенное название Блога, в таком плане как на скриншоте:
![screenshot_2](https://cloud.githubusercontent.com/assets/7164280/6607660/26cc647e-c849-11e4-940d-5f4c63a89a59.jpg)
