### ISSUE TITLE
Управление статическими страницами

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#398]
Не могу понять затею данной функции - подстраницу
![screenshot_3](https://cloud.githubusercontent.com/assets/7164280/6608299/78b60f38-c84e-11e4-9e43-82603a44768f.jpg)
На сайте страницы Правила в Дополнительно, не видно... 
![screenshot_4](https://cloud.githubusercontent.com/assets/7164280/6608308/8de5bbb0-c84e-11e4-938a-48873b47510e.jpg)
Или до меня не дошло ? )))

**Comment by aVadim483** [comment]
Давайте все ж на гитхаб писать баги, а не просто вопросы по движку
