### ISSUE TITLE
Типы блогов

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#399]
После того как создал, после не могу отредактировать Типы Блога, когда осознал в чем проблема. Приходится удалять и заново создавать. Так и должно быть это нормально? )))
![screenshot_5](https://cloud.githubusercontent.com/assets/7164280/6608641/7cd1c406-c851-11e4-9911-668c69e2dc1a.jpg)

**Comment by aVadim483** [comment]
Описывайте, пожалуйста, проблему более четко и конкретно: что именно у Вас не работает?

**Comment by lsnull** [comment]
Я же описал подробно даже скриншот выложил. Что еще нужно ? )

**Comment by andrey-v** [comment]
Да, так и должно быть. Идентификатор блога фигурирует в нескольких местах в БД, может плагинах и кэшируется. Изменения этого ид сейчас может привести к сбоям, потому это поле принудительно сделано не редактируемым.

**Comment by lsnull** [comment]
спасибо за ответ ;) Теперь понял.
