### ISSUE TITLE
Типы контента

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#400]
Не могу создать доп Тип контента и Типы блогов. Если быть точнее, то Они в админке создаются а вот если заходить по ссылке то страница не действительна(недоступна)
![screenshot_8](https://cloud.githubusercontent.com/assets/7164280/6609125/8a6cd4e8-c856-11e4-8ebb-faed5e1ca5b5.jpg)

Вотна сайте уже реализованы. Но Тип "Продажи был ранее реализован до последних обновлений и он работает. В чем проблема?
![screenshot_9](https://cloud.githubusercontent.com/assets/7164280/6609144/c71ffe56-c856-11e4-8248-0ecff59685b5.jpg)

**Comment by aVadim483** [comment]
https://github.com/altocms/altocms/issues/395

**Comment by lsnull** [comment]
Ладно. Я так понял, нужно сделать красивое описания и подробней.
создал Блог по ссылке "vote", создал Типы блогов с идентификатором "vote" , создал Типы контента с идентификатором "vote". Если по ссылке в шапке заходить, то пишет "Сюда еще никто не успел написать " 
![screenshot_10](https://cloud.githubusercontent.com/assets/7164280/6628927/674310f6-c912-11e4-91f6-62f03933e258.jpg)
Если попытаться создать Опрос через :
![screenshot_11](https://cloud.githubusercontent.com/assets/7164280/6628959/ce49c4d4-c912-11e4-9794-b5ce1233fc8c.jpg)
или через :
![screenshot_12](https://cloud.githubusercontent.com/assets/7164280/6628966/eaefde48-c912-11e4-9da4-d2c62c1f38e5.jpg)
Вот что выходит:
![screenshot_13](https://cloud.githubusercontent.com/assets/7164280/6628977/fd401d92-c912-11e4-9b3c-981053827110.jpg)

До этого делал  "продажи" все работает. Опросы делал по тому же подобию. Не работает!

**Comment by lsnull** [comment]
Разобрался. В блоге выбрать не Открытый блог а Тот какой Тип создавали для блога:
![screenshot_14](https://cloud.githubusercontent.com/assets/7164280/6629690/91b6484c-c919-11e4-84fb-e0c93cd556b9.jpg)
