### ISSUE TITLE
CSS Проголосовало

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#403]
![screenshot_18](https://cloud.githubusercontent.com/assets/7164280/6630436/a20dd748-c921-11e4-9934-e8eda4267406.jpg)

**Comment by andrey-v** [comment]
Не баг. Вывод рейтинга в Альто так построен, что сумма баллов топика видна только проголосовавшему, другим эта цифра не отображается. Но в шаблонах experience и experience simple [был добавлен параметр](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/settings/config/config.php#L33-L38) *$config['view']['show_rating']* котоый позволяет выводить НЕ голосовавшему пользователю статистику голосования.
![image](https://cloud.githubusercontent.com/assets/1106990/6633890/e16f1886-c960-11e4-8110-8406edd88018.png)

**Comment by lsnull** [comment]
так у меня не троеточие а какие то запятые(рисочки) . Как сделать этот параметр видным для всех как (выводить НЕ голосовавшему пользователю)?
