### ISSUE TITLE
Последний созданный блог выводится два раза

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#407]
Первый раз в общем списке, второй - в самом конце списка.

**Comment by andrey-v** [comment]
Стоят какие нибудь плагины, которые перекрывают *common/classes/actions/ActionBlogs.class.php* или *common/classes/modules/blog/Blog.class.php* ?

**Comment by inliquid** [comment]
Андрей, поторопился =)

**Comment by andrey-v** [comment]
Так я и не закрыл эту задачу, я закрыл дубль  )
А вот то что список блогов выводится как попало это, я думаю, не проблема индексов. Приведу пример здесь, может кто встречал эту ошибку подскажут, в общем

есть два запроса:
```SELECT  `blog_id` FROM prefix_blog ORDER BY blog_rating LIMIT 20, 20;```
и
```SELECT  `blog_id`, `blog_description` FROM prefix_blog ORDER BY blog_rating LIMIT 20, 20;```

Эти запросы возвращают **разный** результат...
Добавление индекса по полю *blog_rating* решило проблему, но что-то мне кажется, что дело было не в индексе, а вот в чём?

**Comment by klaus-spb** [comment]
как бы это странно не было, попробуй так
```sql
SELECT `blog_id` FROM prefix_blog ORDER BY blog_rating desc LIMIT 20, 20;
```
и
```sql
SELECT `blog_id`, `blog_description` FROM prefix_blog ORDER BY blog_rating desc LIMIT 20, 20;
```

**Comment by andrey-v** [comment]
```desc``` ничего не даёт, всё равно получаются разные наборы строк.

**Comment by andrey-v** [comment]
Да, если перезалить таблицу в другую БД ошибка не воспроизводится.

**Comment by klaus-spb** [comment]
да ну как же, только что на себе проверял, без строго указания Desc тоже разные результаты были

**Comment by inliquid** [comment]
Погодите сейчас после добавления индекса эта проблема ушла. Проблема в другом.

**Comment by klaus-spb** [comment]
ну не может индекс влиять на сортировку, только на скорость выборки

**Comment by andrey-v** [comment]
>да ну как же, только что на себе проверял, без строго указания Desc тоже разные результаты были

Может на других страницах  LIMIT 0, 20, например. Изначальный запрос из метода GetBlogsByFilter ведь был с desk-ом

**Comment by andrey-v** [comment]
>ну не может индекс влиять на сортировку, только на скорость выборки

Вот-вот. Я такую ситуацию вообще первый раз вижу

**Comment by inliquid** [comment]
Проблема в том что блоги имеющие одинаковый нулевой ретинг дублируются в результатах поиска на странице блогов. Соответственно вот такие запросы делает движок как я понял
1. Первая страница блогов
SELECT b.blog_id FROM alto_blog AS b WHERE 1 = 1 AND (b.blog_type IN ('diary', 'community')) ORDER BY blog_rating DESC LIMIT 0, 20

2. Вторая страница блогов
SELECT b.blog_id FROM alto_blog AS b WHERE 1 = 1 AND (b.blog_type IN ('diary', 'community')) ORDER BY blog_rating DESC LIMIT 20, 20


В них выводятся дублирующие записи. Но у всех одна особенность рейтинг = 0.

**Comment by inliquid** [comment]
Индекс может влиять, еще как. Надо знать как БД себя ведет при выполнении запроса. 
Сортировка то не меняется! У всех этих блогов рейтинг = 0.

**Comment by klaus-spb** [comment]
ну тогда понятно. Если рейтинг одинаковый и нулевой, то при каждом запросе может меняться порядок. Нужно вводить сортировку по еще одному полю, второстепенную, например
```sql 
ORDER BY blog_rating DESC, blog_id asc 
```

**Comment by andrey-v** [comment]
>В них выводятся дублирующие записи. Но у всех одна особенность рейтинг = 0.

В таком случае проблему решит дополнительная сортировка в рамках рейтинга, а не индекс. Вот так ORDER BY blog_rating DESC, blog_title ASC, например.

**Comment by inliquid** [comment]
может blog_count_topic - как-то справделивей чтли

**Comment by andrey-v** [comment]
@inliquid попробуй в файле *common/classes/actions/ActionBlogs.class.php* в строке 111, где фильтр устанавливается заменить
```
        $aResult = $this->Blog_GetBlogsByFilter(
            $aFilter, array($sOrder => $sOrderWay'), $iPage, Config::Get('module.blog.per_page')
        );
```
на
```
        $aResult = $this->Blog_GetBlogsByFilter(
            $aFilter, array($sOrder => $sOrderWay, 'blog_count_topic' => 'ASC'), $iPage, Config::Get('module.blog.per_page')
        );
```

**Comment by inliquid** [comment]
Хотя стоп, топиков то тоже может быть 0

**Comment by klaus-spb** [comment]
Ну сделайте сортировку по трем полям =)

**Comment by andrey-v** [comment]
Да,
$aResult = $this->Blog_GetBlogsByFilter(
    $aFilter, array($sOrder => $sOrderWay, 'blog_id' => 'asc' ), $iPage, Config::Get('module.blog.per_page')
 );

**Comment by inliquid** [comment]
$aResult = $this->Blog_GetBlogsByFilter(
            $aFilter, array($sOrder => $sOrderWay, 'blog_title' => 'ASC'), $iPage, Config::Get('module.blog.per_page')
        );
Посмотри вроде ок?
Или лучше id?

**Comment by inliquid** [comment]
думаю id лучше, и думаю индексы в любом случае быть должны

**Comment by andrey-v** [comment]
Можно и по тайтлу в алфавитном порядке, ведь они не могут совпадать, а для пользователя так наглядней будет

**Comment by andrey-v** [comment]
Спасибо за помощь, 
задачу закрываю

**Comment by andrey-v** [comment]
f01ab0a19d42295874dec933c72d2551a55e46a4 6870f4a0e6c06de256647f3db5ba2735470c48de

**Comment by inliquid** [comment]
А индексы?
