### ISSUE TITLE
В списке блогов отображаются не все блоги

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#408]
В  дополнение к предыдущему тикету. Подробности отправлю Андрею в личку.
memcached - используется.

**Comment by andrey-v** [comment]
Тоже что и #407

**Comment by inliquid** [comment]
И здесь тоже =)

**Comment by inliquid** [comment]
Проблема в том что нет индексов по полям по которым происходит сортировка. Поэтому БД может вернуть что угодно.

- blog_rating
- blog_count_user

**Comment by inliquid** [comment]
Хмм.. однако проблема дубликатов при выводе все равно осталась. Все кеши сбросил, query cache на mysql отключил.
