### ISSUE TITLE
Черновики не сортируются по дате

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#409]
Черновики выводятся произвольно, сортировки по дате нет.
Шаблоны start-kit и brand.

**Comment by andrey-v** [comment]
Черновики, как и обычные топики если принудительно не задана сортировка, то выводятся по дате публикации. Если же черновик ни разу не был опубликован, то такие топики идут после бывших в публикации, но перемещённых в черновики.

Сортировка задаётся [здесь](https://github.com/altocms/altocms/blob/1.0.x/common/classes/modules/topic/mapper/Topic.mapper.class.php#L309) и она одинакова для всех топиков.

Если же для конкретного проекта нужно сменить логику вывода, то в методе получения персональных топиков [после формирования фильтра](https://github.com/altocms/altocms/blob/1.0.x/common/classes/modules/topic/Topic.class.php#L1512-L1516) нужно добавить правило сортировки для черновиков
```php
// Если запрашиваются черновики, то добавим принудительную
// сортировку в обратном порядке по дате добавления черновика
if (!$iPublish) {
    $aFilter = array_merge(
        $aFilter,
        array('order' => 't.topic_date_add DESC')
    );
}
```

**Comment by inliquid** [comment]
Ок спасибо.
