### ISSUE TITLE
фото в Фотосете

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#412]
Загрузил 30 фотографий. Но отображается значительно меньше...Не пойму все загрузились или нет. Должна быть функция "Показать все" ?
![screenshot_2](https://cloud.githubusercontent.com/assets/7164280/6653425/2e45264c-ca9b-11e4-8665-df8ee3eea064.jpg)

**Comment by aVadim483** [comment]
Да, должна быть кнопка

**Comment by andrey-v** [comment]
Кнопка там есть, но она закрыта фотосетом, там ошибка вёрстки. скоро исправлю.
