### ISSUE TITLE
css в пофиле

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#413]
![screenshot_3](https://cloud.githubusercontent.com/assets/7164280/6654129/b87094c4-cab8-11e4-8a1a-a15214e1e127.jpg)

**Comment by aVadim483** [comment]
Это же плавающая панель, она позиционируется относительно экрана, а не относительно других элементов, поэтому на разных страницах она может быть поверх каких-то других элементов, это нормально

**Comment by lsnull** [comment]
Ну если это нормально и опустить чуть ниже неохото. Пусть будет так. Дело за вами.
