### ISSUE TITLE
Отловил интересную ошибку при работе с фотосетом

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#414]
Вчера отловил интересную ситуацию. Браузер Chrome. Сначала картинки перестали устанавливаться как превью. Т.е., выбираешь произвольную картинку в уже созданном топике как превью, а устанавливается все равно первая. Тогда я решил первую удалить.

Сначала
[14/Mar/2015:22:39:52 +0300] "GET /content/edit/91/ HTTP/1.1" 200

Потом
[14/Mar/2015:22:39:56 +0300] "POST /content/photo/delete/ HTTP/1.1" 200

В этото момент браузер подвис со строкой "waiting...."

А вот что в логах

[LOG:1426361996.341-55048E8C53660][2015-03-14 22:39:56][PID:20445][ERROR][[
E_NOTICE [8] Undefined offset: 0 (/var/www/example.com/common/classes/actions/ActionContent.class.php on line 1072)
--- call stack ---
ActionContent->EventAjaxPhotoDelete() in /var/www/example.com/common/classes/actions/ActionContent.class.php on line 1096
ActionContent->EventPhotoDelete()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1426361996.341-55048E8C53660]

[LOG:1426361996.342-55048E8C53983][2015-03-14 22:39:56][PID:20445][ERROR][[
E_ERROR [1] Call to a member function getId() on a non-object (/var/www/example.com/common/classes/actions/ActionContent.class.php on line 1072)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

**Comment by inliquid** [comment]
Продолжение проблем с фотосетом. Был создан пост с фотосетом. В процессе загрузки изображения добавлялись/удалялись постепенно. Сначала выбранное в качестве превью изображение из фотосета нормально установилось, сам видел своими глазами его в шаблоне на главной (там берется именно превью). Спустя некоторое время обратил внимание что в качестве превью установилось другое, первое по очереди изображение. Возможно конечно что автор поста в этот промежуток времени обновлял публикацию хоть раз (не признается).

Затем я сам стал пытаться установить первоначальное изображение как превью. И теперь имею такую ситуацию - то изображение которое устанавливалось первый раз поставить как превью не удается, хоть кнопка и срабатывает. В этом случае почему-то устанавливается именно первая залитая в фотосет картинка. Любую другую - можно установить. Проблема воспроизводится.

**Comment by andrey-v** [comment]
Вторая ошибка не воспроизводится, попробуй у себя ещё раз и проверь в браузере меняется ли значение  у тега с id = *topic_main_photo*.
![image](https://cloud.githubusercontent.com/assets/1106990/6662866/88f6525a-cbd1-11e4-85cb-517435cdccd3.png)
