### ISSUE TITLE
Url поста должен обновляться

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#415]
1. В черновиках. Иначе получаем ситуацию что допустим я пишу черновик  с заголовком 
"Вася Пупкин ворует из бюджета", обстоятельства меняются я меняю заголовок на "Вася Пупкин добропорядочный гражданин", в url остается таким же как и был при первом сохранении.

2. В обычных постах. Думаю необходимо менять url при любом изменении заголовка. У пользователя нет возможности его менять. Однако получается что url будет всегда содержать первоначальную версию, даже если пользователь передумал и не хочет чтобы ее видели.

**Comment by aVadim483** [comment]
Но тогда ломаются закладки у юзеров, страницы выпадают из индексации. Получается, что авторы статей куролесят, а страдают владельцы сайтов и другие юзеры.

Если и делать это, то только опционально, чтоб если что - не движок плохой, а админ глупый

**Comment by inliquid** [comment]
Согласен, но опция в конфиге должна быть. Насчет закладок и т.д., приведу пример как сделано в esoTalk :))) 
Там в URL сначала идет номер темы, например /conversations/20-a-vot-o-chem-hotel-ressakazat При переименовывании номер остается прежним, а если я (или поисковый бот) захожу по старой ссылке, то получаю редирект на новую с кодом 302.

**Comment by aVadim483** [comment]
Сама идея не плохая, но у нас абсолютно не применима.

Если б URL жестко движком задавался, то не вопрос, можно редиректить, но у нас URL формируется по шаблонам, который настраивается произвольным образом. И я уже миллион историй и доводов наслушался почему надо вот так формировать, а не иначе, начиная от результатов всяких экспериментов, заканчивая тем, что "мне так не нравится и все".

Так что, увы, не катит. Но опция в конфиге - это реально

**Comment by aVadim483** [comment]
Но надо понимать, что тут есть "подводный камень" - если URL был задан вручную, а потом меняется заголовок, то при таком подходе заданный ручной УРЛ будет заменен автоматически. И может случиться так, что столкнувшись со всеми этими мелкими проблемами, админы будут отключать опцию. Т.е., в итоге, она окажется невостребованной

**Comment by inliquid** [comment]
В моем случае она точно будет востребована.
