### ISSUE TITLE
Снова после установки не открывается сайт.

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#416]
Вот сейчас, снова скачал с гита, снова не открывается главная ни в какую. В папке _tmp отсутствуют папки logs и templates. Там только папка cache пустая и все....

**Comment by andrey-v** [comment]
Что браузер пишет - 404?

**Comment by yuri25** [comment]
Выдавал 502 bad gateway. Я снова переустановил сайт. Вот описанная проблема проявилась когда я изменил в первом случае стандартный префикс базы данных с prefix_ на fix_   Сейчас установил ничего не меняя, т.е. оставил по умолчанию prefix_   - установка прошла нормально и сайт открылся. Проверьте пожалуйста. Мне кажется что это связано именно с изменением стандартного префикса таблиц базы на какой нибудь другой...

**Comment by andrey-v** [comment]
Проверил, с другим префиксом устанавливается замечательно.
Логи по прежнему пустые?

**Comment by aVadim483** [comment]
Если выдает ошибку 502, то это уже логи самого вебсервера надо смотреть

**Comment by yuri25** [comment]
В общем что то наверное кеш браузера или какое то расширение браузера глючило. В гугловском хроме выдало Exception: Class "ModuleLogger" not found!
E_USER_WARNING [512] Can not make dir "/..../youwo.ru/_tmp/logs" (/...../youwo.ru/engine/include/functions/File.php on line 237)E_WARNING [2] mkdir(): Отказано в доступе (/....../youwo.ru/engine/include/functions/File.php on line 235)Exception: Class "ModuleLogger" not found!

Хотя установка в яндексовом хроме прошла успешно и сай

**Comment by andrey-v** [comment]
Тикет закрыл, но всё равно если два раза установка пошла с ошибкой это не хорошо... Давайте если ещё раз повторится как-то поплотнее эту ситуацию рассмотрим. Мне не нравится эта ошибка, но и повторить её я не могу.
