### ISSUE TITLE
Время на сайте.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#417]
Уже подымал  этот вопрос.
Не правильно показывает время.
При выборе часового пояса +2 - выдает на час больше : +3
![screenshot_4](https://cloud.githubusercontent.com/assets/7164280/6658319/28305f46-cb6e-11e4-81c9-d1df169c9cfc.jpg)
Вот :
![screenshot_5](https://cloud.githubusercontent.com/assets/7164280/6658328/98244b96-cb6e-11e4-8259-26baecc98357.jpg)

**Comment by andrey-v** [comment]
Скажите, а ошибка повторяется? Сейчас ни локально, ни у вас на сайте не могу её повторить (Вот картинка с вашего сайта)
![image](https://cloud.githubusercontent.com/assets/1106990/7789018/c7b2c3ce-025a-11e5-9966-7ada17f515f3.png)

**Comment by andrey-v** [comment]
Здесь было обсуждение - http://altocms.ru/1079.html
