### ISSUE TITLE
не корректно отоброжается

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#419]
![screenshot_7](https://cloud.githubusercontent.com/assets/7164280/6658951/9281f45a-cb81-11e4-9078-ad093abca3fe.jpg)

**Comment by andrey-v** [comment]
Исправил
![image](https://cloud.githubusercontent.com/assets/1106990/6687641/d5a23e60-ccbd-11e4-89cd-704020e958df.png)

**Comment by lsnull** [comment]
спасибо
