### ISSUE TITLE
_tmp/cache

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#420]
Когда чистишь кеш, то все добавленные меню сбрасывается
и приходится заново добавлять!!
![screenshot_8](https://cloud.githubusercontent.com/assets/7164280/6659144/1d9490f2-cb87-11e4-9721-1450cf5663ee.jpg)

**Comment by andrey-v** [comment]
Если удалить эту папку, то у вас сбросятся *вообще все* настройки сделанные через админку, а не только меню.

**Comment by aVadim483** [comment]
Думаю, рано закрыли, проверим

**Comment by lsnull** [comment]
А это разве нормально? Ведь tmp - это были временные файлы. Через админку не всегда чистится все. Я же не саму папку удаляю а файлы в подпапках которые находятся в самой _tmp

**Comment by aVadim483** [comment]
Нет, не нормально, потому я и открыл заново, чтобы посмотреть, проверить, что там твориться при удалении файлового кеша

**Comment by andrey-v** [comment]
Исправлено, b12f37575753530970a87bb9e76355dd30c92990
