### ISSUE TITLE
Обновил только что Альто 1.1 и проблемы на сайте

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#422]
Прошу вас проверить в чем проблемма.
Некоторые Топики открываются так:
![screenshot_10](https://cloud.githubusercontent.com/assets/7164280/6668971/1d016dae-cbff-11e4-82e1-be77cdafd9ff.jpg)
Но некоторые нормально. До этого все работало до обновления

А так же пропали фото и фотосет в Топике

![screenshot_11](https://cloud.githubusercontent.com/assets/7164280/6669074/bbb604e6-cbff-11e4-84d8-bbb4e8e187d1.jpg)
В общем вот что произошло:
Топики которые с Фотосетом были, отоброжаются без правого блока и нижнего а так же нет футера, комментариев и доп функций.
А те Топики, которые без Фотосета Нормально открываются и нормально работает сайт.

**Comment by klaus-spb** [comment]
Кстати да, у меня вчера тоже при очередном обновлении пропал фотосет. Добавил новый и он остался. А старый куда-то убежал. Может изменилась работа с ресурсами, да и альфа, я не стал обращать внимание.

Это нормально или нет?

**Comment by lsnull** [comment]
да у меня и не только в топиках фотосеты пропали но и Правый блок. я запарюсь редактировать...

**Comment by lsnull** [comment]
В общем вот что произошло:
Топики которые с Фотосетом были, отоброжаются без правого блока и нижнего а так же нет футера, комментариев и доп функций.
А те Топики, которые без Фотосета Нормально открываются и нормально работает сайт.

**Comment by klaus-spb** [comment]
В общем нужно выполнить один запрос базе
```sql
update `prefix_mresource_target` set target_type = 'photoset'
where target_type = 'topic-multi-image-uploader'
```

**Comment by lsnull** [comment]
Заработало. Спасибо тебе дружище. Но я надеюсь в скором ребята пофиксят этот баг ;)

**Comment by aVadim483** [comment]
Парни, наш косяк, признаю. Он проявляется у тех, кто до сегодняшнего дня ставил альфу и делал фотосеты.

**Comment by andrey-v** [comment]
Проблема тут в чём: было решено переименовать неудобное название *topic-multi-image-uploader* в привычное *photoset*, что и было сделано. Сейчас, при установке альфы и работе с ней этой ошибки не будет, ошибка возникнет только у того, кто работал с альфой до этого обновления и после (в БД остались старые ссылки). Вносить исправления, учитывающие этот переход и продолжать цепляться за старое название не очень правильно.

Исправление тут простое и его выше предложил @klaus-spb за что ему и спасибо), но каких-то изменений в движке по этому поводу не будет.

**Comment by lsnull** [comment]
спасибо ребята!
