### ISSUE TITLE
Проблемы с картинками и количеством публикаций

### ISSUE THREAD

**Issue by xen-chut** [altocms/altocms#423]
В общем только поставил вашу систему, понравился шаблон кстати дефолтный и в админке тоже симпотичный, спасибо, молодцы!

А теперь по багам.
порядок был такой: установил, зашел под аккаунтом админа, в настройках сменил название сайта, описание, если визуальный редактор был выключен, я его включил, точно не помню, затем посмотрел шаблоны, остановился на дефолтном, при написании первого поста в этот блог, отметил "Принудительно вывести на главную", нажал внизу "добавить изображения", залил три картинки, добавил их в пост выбрав в уже загруженных пункт "Этот топик", причем среди трех загруженных картинок почему-то возникла **битая четвертая картинка**, удивился, посмотрел в коде, увидел вот такой код:

```
<a href="#" data-url="http://invr.aldev/content/edit/1/http%3A/utmagazine.ru/posts/6056-kto-zarabatyvaet-v-krizis&amp;hash=73fc59be7e74b43c683eb8050ae2f726" onclick="return false;">
                        <img src="http://invr.aldev/content/edit/1/http%3A/utmagazine.ru/posts/6056-kto-zarabatyvaet-v-krizis&amp;hash=73fc59be7e74b43c683eb8050ae2f726" class="img-thumbnail" alt="image">
                    </a>
```

удивился еще больше. Потому что в топике **есть ссылка что идет после edit/1/**
Подумал что баг.

Удалить нельзя ни одно из изображений из этого окна выбора, хотя хотелось бы удалить эту битую картинку, потому что ее больше нигде не видно, ни в исходном коде топика, ни в загруженных изображениях, нигде.

Нажал опубликовать, посмотрел что получилось, получилось что у меня превью картинка отмеченная как превью, чуток текста, и картинка добавленная вручную и затем кат, нажал редактировать под топиком, но картинка которая была выбрана как превью все еще имеет надпись "Отметить как превью", опять **баг**.
Ок думаю, скрипт при нажатии проверит что она все-таки превью и удалит, нажал опять "Отметить как превью", появилось сообщение "Это изображение больше не превью к статье", ну думаю и то хорошо. 
Смотрю что получилось - никаких изменений, превью как висело так и весит, обновил кеш браузера, сбросил кеш cms через админку, превью так и висит, выбираю вторую картинку как превью, она заменяет текущее превью, пытаюсь убрать превью совсем - не убирается. **Выходит снова баг**.

Пошел смотреть что там в профиле админа видно на сайте, а видно вот что у него:
1 статья  - правильно
7 картинок - не правильно, я всего три заливал, ну пусть 4 с учетом той странной битой.
8 публикаций - неправильно, зачем считать картинки как публикации?
в картинках есть опять эта битая картинка, с тем же кодом, только добавился  rel="prettyPhoto[pp_gal]" 

Скриншот:
![alt](http://c2n.me/3enWXTv.jpg)

плюс:
Что за иконка папки слева? это дефолтный логотип для пользователей? вроде нет, что же тогда справа? Непонятно. Кстати та же иконка появилась у блога без превью.
Еще почему-то в шаблонах слова топик и статья означают одно и тоже, да, это и есть одно и тоже, но зачем использовать два разных слова для одной сущности?

В статье у превью (которое не удаляется никак) такой код:

```
<a href="#" class="pull-left" data-url="http://invr.aldev/uploads/photoset/00/00/01/0u10dc3f60-49d354c1-d36d1340.jpg-682x682-pad.jpg" onclick="return false;">
                        <img src="http://invr.aldev/uploads/photoset/00/00/01/0u10dc3f60-49d354c1-d36d1340.jpg-682x682-pad.jpg" alt="image" align="left">
                    </a>
```

Зачем превью является ссылкой которая никуда не ведет, даже внутрь топика? Что было бы очень даже хорошо, кстати.

Открыл саму картинку оказалось что картинка увеличилась с 654*304 до 1468*682, т.е. по высоте, не очень понятно куда такая широкая картинка.

У каждой картинки в топике такой ксс:

```
.topic-text img, .comment-text img {
  cursor: pointer;
}
```

Зачем pointer у каждой простой img когда они даже не обрамлены ссылкой, тоже не понятно совсем. 

Было бы круто лепить автоматически ссылку на оригинал изображения, если оригинал больше чем ужатая версия в статье.

Или например, если я использую фотосет при добавлении фото, и теже фотки в статье, чтобы ссылки на оригинал как раз ставились, можно даже если фотосет скрыт (иначе польза от них не очень ясна).

Вот такое получилось первое знакомство с вашей CMS, первое впечатление, первые пожелания и первый багрепорт.

Желаю вам удачи с вашим детищем!

Может мне пока с сайта версию скачать, которая стабильная? И где можно об отличиях почитать, и вообще документацию найти? И куда если что вопросы задавать? Извиняюсь что здесь спрашиваю, других мест не нашел.

**Comment by andrey-v** [comment]
Спасибо за багрепорт
- отмена превью была сделана раньше
- функционал удаления картинок в менеджере изображений запланирован на будущее в задаче #471
