### ISSUE TITLE
При вставке изображения через редактор кнопка отмена ничего не делает. 1.0.10.2

### ISSUE THREAD

**Issue by xen-chut** [altocms/altocms#425]
Скачал отсюда стабильную версию:
https://sourceforge.net/projects/altocms/files/latest/download?source=directory

Установил, все по умолчанию, только включил визуальный редактор, создаю топик, добавил фотосет, в редакторе жму в то место куда хочу вставить картинку, жму "вставить\редактировать изображение", жму "Отмена" ничего не происходит, жму "Из интернета" - Отмена и снова ничего не происходит.

Видимо тут нельзя использовать фотки из фотосета?

И еще момент, когда редактирую статью, в фотосете на первой фотке написано отмечено как превью к статье, но этого превью на сайте нигде не видно и нет функции убрать превью. Как сделать чтобы превью появилось на сайте? Очень прошу ткните в документацию нигде не могу найти толком ничего.

**Comment by andrey-v** [comment]
Исправлено раньше - https://github.com/altocms/altocms/issues/404
просто новый релиз с исправлениями ещё не вышел.

**Comment by xen-chut** [comment]
скачал с гитхаба, кноки отмена работают, спасибо. А когда примерно планируется релиз 1.1?

**Comment by andrey-v** [comment]
Для полноценной работы с превью топиков используйте вот этот плагин - http://altocms.ru/addons/item/90/

**Comment by andrey-v** [comment]
>А когда примерно планируется релиз 1.1?

Сейчас планируется выпуск бета-версии 1.1.
