### ISSUE TITLE
Поиск возвращает результаты, к которым у пользователя нет доступа

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#426]
Например пользователь видит посты размещенные в закрытом от него блоге. Хотя на страницу топика движок перейти не дает и в блоге тоже ничего не показывается.
Параметр "индексировать контент" в настройках типов блогов ничего не дает и в целом я считаю он некорректен. Либо объясните в чем его смысл. Потому что индексация в любом случае должна быть избирательной в зависимости от того есть у пользователя доступ или нет.

**Comment by aVadim483** [comment]
>Параметр "индексировать контент" в настройках типов блогов ничего не дает

Я правильно понял: статьи блога оказываются в результатах поиска, независимо от того, как установлен этот параметр?

**Comment by inliquid** [comment]
Да, правильно. Хотя как я и писал выше очень странно если пользователь который не должен видеть содержимое блога увидит его таким образом через поиск. Или что поиск вообще не будет работать даже для тех кому это разрешено, из-за того что я не хочу чтобы кому не надо видели содержимое. Поэтому смысл параметра вообще не понятен.

**Comment by aVadim483** [comment]
Смысл параметра очень прост. Поиск - это весьма дорогая (с точки зрения вычислительных ресурсов) операция - там используются регулярные выражения и никакие индексы вообще не работают. Поэтому и был введен этот параметр, чтобы в упрощенном виде задавать, какие тексты нужно обрабатывать, а какие нет.

Согласен, что решение не идеальное, а, скорее, компромиссное. Возможно, в будущих версиях придется менять сам подход к определению доступности контента тому или иному юзеру. Но пока так.

**Comment by inliquid** [comment]
Т.е. я правильно понимаю что вы просто исправите ошибку с параметром "индексировать контент", а остальное поведение не изменится, поиск если параметр включен будет возвращать все содержимое для всех?

**Comment by aVadim483** [comment]
Я детально еще не анализировал все варианты, но с большой вероятностью - да

**Comment by inliquid** [comment]
Просто и Интересны и Новые - отлично фильтруют содержимое согласно тому имеет ли пользователь доступ на чтение.

**Comment by inliquid** [comment]
И еще вопрос - есть ли защита от флуда, чтобы поисковыми запросами нельзя было положить сайт? Например чтобы первые 5 запросов от одного пользователя без ограничений, а последующие не чаще чем раз в 10 сек обрабатывались.

**Comment by andrey-v** [comment]
Добавлен режим вывода результатов поиска "Только из доступных блогов", включается в конфиге в параметре *'module.search.accessible'*. Вывод результатов поиска сделан аналогично выводу топиков на главной. По умолчанию режим отключён.

**Comment by inliquid** [comment]
А где он добавлен-то?

**Comment by andrey-v** [comment]
Забыл пуш сделать, сори. Спасибо, что заметил )

**Comment by inliquid** [comment]
А 1.0.x будет?

**Comment by andrey-v** [comment]
Позже, наверное
