### ISSUE TITLE
Точка в строке поиска приводит к непредсказуемым результатам

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#428]
Например если искать по имени веб-сайта. По факту выводится куча постов, непонятно по каким критериям отобранных.

**Comment by aVadim483** [comment]
С точкой все не очень просто, т.к. она может быть и знаком пунктуации, и частью адреса сайта. Вообще при формировании поискового запроса все знаки, которые не являются буквами или цифрами, удаляются, и поиск идет строго по словам. Поэтому, когда в запросе встречается выражение **site.com**, оно разбивается на два слова - **site** и **com**. Отсюда и непредсказуемость результата для юзера.

Чтоб решить проблему, добавил дополнительную логику - если строка задана в двойных кавычках, то она ищется, как есть, без разбивки на отдельные слова. Т.е., чтобы искать в текстах **site.com**, нужно заключить это в двойные кавычки: **"site.com"**

**Comment by inliquid** [comment]
У меня ищет не "site" и "com" а при таком запросе ".com" с точкой.

**Comment by inliquid** [comment]
Причем туда и слэш попадает если есть почему-то

![1](https://cloud.githubusercontent.com/assets/6797881/7667457/4cd684f0-fc11-11e4-8f28-3fa64dddb85a.png)

**Comment by inliquid** [comment]
Хотя щас при другом запросе первая часть с точкой идет... не понятно.

**Comment by aVadim483** [comment]
Слеш в запрос поиска не попадает, это уже немного другое - при подсветке результата захватывается лишний символ

**Comment by aVadim483** [comment]
В 1.1 логика поиска переработана, в 1.0 исправляться, скорее всего, не будет
