### ISSUE TITLE
Необходимо добавить кнопку отмена в диалог добавления комментария рядом справа от "предпросмотр" и "добавить"

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#430]
Пользователи недоумевают как закрыть это окошко если передумали отвечать.

**Comment by andrey-v** [comment]
Я думаю это уже на уровне конкретного проекта/темы, но добавить просто (пример для старт-кита) - [в файле дерева комментариев](https://github.com/altocms/altocms/blob/master/common/templates/skin/start-kit/tpls/comments/comment.tree.tpl#L104) добавить такую кнопку
```
<button type="button"
        onclick="$(this).parent().css('display', 'none'); return false;"
        class="btn btn-default pull-right">
    {$aLang.text_cancel}
</button>
```
