### ISSUE TITLE
Работа движка после обновления 20.03.15

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#431]
Уже была подобная тема где был ответ от klaus-spb с запросом в БД.  https://github.com/altocms/altocms/issues/422
Но создал я только что топик и... Тоже самое.  Если что, то Andrevy думаю знает мой блог и при просмотре первого же Топика можно  увидеть эту проблемму
![screenshot_14](https://cloud.githubusercontent.com/assets/7164280/6742731/f640b6e0-ce9a-11e4-8d14-0d4db77d2872.jpg)
Не отображается правые блоки, комментарии не работают и другое...

**Comment by andrey-v** [comment]
Сайт недообновился. Подробнее отписал в топик - http://altocms.ru/1052.html

**Comment by lsnull** [comment]
Обновил, тоже само

**Comment by andrey-v** [comment]
Создал у вас на сайте топик, загрузил фото в текст топика, загрузил фото в фотосет, сохранил топик в черновики - всё без ошибок.

**Comment by andrey-v** [comment]
В логах, вот тут - _tmp/logs/error.log что нибудь есть?

**Comment by lsnull** [comment]
Чуть позже буду у пк. Попробуйте пока только фото через редактор загрузить и описание если потребует. Фотосет не грузите. Опубликуйте не сохраняя в черновик.

**Comment by andrey-v** [comment]
Всё работает

**Comment by lsnull** [comment]
Почему тогда здесь http://losper.net/test-alto-cms-11a.html ни так? (((
а в логах куча всего. Вам отправить файл логов?

**Comment by andrey-v** [comment]
да, давайте на andreyv@gladcode.ru

**Comment by lsnull** [comment]
Отправил

**Comment by andrey-v** [comment]
Попробуqте вот этот файл [заменить с гитхаба](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/tpls/fields/field.photoset-show.tpl)

**Comment by lsnull** [comment]
Работает. Это опять файл не перезаписался или вы только что правку сделали?

**Comment by andrey-v** [comment]
Правку сделал

**Comment by lsnull** [comment]
Спасибо.
