### ISSUE TITLE
Не могу удалить Топик из Блога

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#432]
При шажатии на Корзину - Удалить, подымается в начало Топика и все... Действие не происходит
![screenshot_15](https://cloud.githubusercontent.com/assets/7164280/6744001/ab388eb0-ceaa-11e4-8498-f540f56a0d9e.jpg)

**Comment by andrey-v** [comment]
Опять же ни на версии с гитхаба, ни у вас на сайте ошибка не воспроизводится. Картинка с вашего сайта, попробуйте ещё раз и посмотрите в консоли браузера ошибки, может не загрузились какие-то скрипты. Или попробуйте обновить закэшированные скрипты в браузере (ctrl+F5)
![image](https://cloud.githubusercontent.com/assets/1106990/6764026/9a58ad44-cfab-11e4-9f16-2f026c269f55.png)

**Comment by andrey-v** [comment]
@lsnull Не смотрели, работает сейчас удаление топика на вашем сайте?

**Comment by lsnull** [comment]
щас скажу
