### ISSUE TITLE
Получить короткую ссылку на статью

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#437]
Значок налазит на разные стили и становится поверх окон
![screenshot_19](https://cloud.githubusercontent.com/assets/7164280/6745363/c8875e24-cebe-11e4-81a8-be31308873ea.jpg)

**Comment by andrey-v** [comment]
Исправлено - f61390f32ed762e336748256a1fe7c1f4f25afcc

**Comment by lsnull** [comment]
Спасибо ;)
