### ISSUE TITLE
Нерабочая кнопка "+" в блогах, статьях, комментариях в админке

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#438]
Думаю просто забыли убрать ее.

**Comment by aVadim483** [comment]
Нет, оставлена для унификации вида, но в статусе disabled

**Comment by inliquid** [comment]
Из 4 страниц в контенте: 
- блоги, 
- статьи, 
- комментарии, 
- страницы, 

она работает только в "страницах". убрана даже из медиаресурсов. какая унификация?
