### ISSUE TITLE
Загрузка фото

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#439]
После обновления. 
Может на чистую и будет все работать. Но у меня после обновления вот такой трабл
![screenshot_21](https://cloud.githubusercontent.com/assets/7164280/6759016/6aa7d536-cf45-11e4-8699-9b8915767d81.jpg)

**Comment by andrey-v** [comment]
Заработало?

**Comment by lsnull** [comment]
Ага. Все норм.
