### ISSUE TITLE
Непонятный подчет фото.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#440]
Куда деваются фото? Если загрузить фото через загрузчик в редакторе и добавить эти фото в топик. После отредактировать  тех больше мы не найдем?
Как их и где удалить через Сайт? Что бы не рыть вручную в папке Upload...
Некоторые фото не отображает и не все  показывает.
![screenshot_25](https://cloud.githubusercontent.com/assets/7164280/6762667/56654644-cf6d-11e4-8487-74296b16e820.jpg)
![screenshot_24](https://cloud.githubusercontent.com/assets/7164280/6762666/5663cada-cf6d-11e4-83eb-6f0220c27d19.jpg)

**Comment by andrey-v** [comment]
Нет, ну здесь не количество картинок отображается, а количество объектов:
11 блогов, 2 аватара, 59 топиков, 1 вопрос-ответ, 1 продажа, а сколько в 59-и топиках картинок тут не считается.
