### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#441]
Очень часто вылазит ошибка.
![screenshot_26](https://cloud.githubusercontent.com/assets/7164280/6762715/3dd4b0e6-cf6e-11e4-845b-a046ad7a1f8c.jpg)
В логах нет, понять не могу... Поработайте с плагинами в админке и должна вылести. Загрузил плагин Цитировать комментарий. После выбрал и удалил и ошибка и не только с такой манипуляцией. Избавится от нее получается только удалив в ручную кеш из _tpl
![screenshot_27](https://cloud.githubusercontent.com/assets/7164280/6762728/90e17b2a-cf6e-11e4-94d5-d18401db9347.jpg)

**Comment by andrey-v** [comment]
Проверьте, есть ли у вас SimpleXml. Сделать это можно через админку
![image](https://cloud.githubusercontent.com/assets/1106990/6764197/50435ae6-cfb6-11e4-81d5-06c157372767.png)

**Comment by lsnull** [comment]
![screenshot_32](https://cloud.githubusercontent.com/assets/7164280/6764490/3fadd73e-cfba-11e4-9423-3e5e5dc0bb39.jpg)
![screenshot_33](https://cloud.githubusercontent.com/assets/7164280/6764492/3fd91e12-cfba-11e4-982e-d7ab34e4e6be.jpg)
![screenshot_34](https://cloud.githubusercontent.com/assets/7164280/6764491/3fd8a34c-cfba-11e4-9d42-da1fe28817ef.jpg)

**Comment by lsnull** [comment]
Отключил Плагин "MenuTest" и снова ошибки 

E_NOTICE [8] Array to string conversion
See details in error.log
E_WARNING [2] explode() expects parameter 2 to be string, array given
See details in error.log

**Comment by lsnull** [comment]
Уже запарили эти ошибки. С вкл и отключением плагина. Чищу кеш и она осталась. В ручную удалю файлы - настройки слетят. ппц

**Comment by aVadim483** [comment]
Плавающая ошибка. Иногда проскакивает, но не могу выловить закономерность

**Comment by andrey-v** [comment]
Она возникает при ошибке [в этой строчке](https://github.com/altocms/altocms/blob/master/engine/classes/modules/plugin/entity/Plugin.entity.class.php#L72), но вот почему сбоит simplexml ?

**Comment by lsnull** [comment]
Захожу на сайт - ошибка:
E_NOTICE [8] Array to string conversion
See details in error.log 

[LOG:1426975099.056-550DE97B0D95B][2015-03-22 00:58:19][PID:201651][ERROR][[
E_NOTICE [8] Array to string conversion (/home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php on line 237)
]][END:1426975099.056-550DE97B0D95B]

И в добавок о времени. У меня еще 23:58 но ни как не 00:58 а часовой пояс стоит правильный

**Comment by andrey-v** [comment]
Сбросьте мне на почту andreyv@gladcode.ru дамп таблицы БД **prefix_storage** и ваш файл **/home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php**
Посмотрю, но у вас либо не встало обновление, либо читаются старые битые настройки.

**Comment by lsnull** [comment]
Вот как раз файл home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php
я правил вчера поздно вечером брал с гидхаба - думал пропадет ошибка. Но нет. Щас все вам скину на почту. 5 мин. И можете просмотреть почтовый ящик. Спасибо Андрей за поддержку и помощь.

**Comment by andrey-v** [comment]
>E_NOTICE [8] Array to string conversion (/home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php on line 237)

Ошибка исправлена
@lsnull, у вас она всё равно будет висеть потому что конфиг меню сохранён уже с ошибкой. Для того что бы ошибка у вас ушла нужно сбросить всё меню в дефолтное состояние. Все настройки меню которые вы делали до этого пропадут, но и ошибка больше повторятся не должна. Сбросить меню можно в админке для каждого меню нажав кнопку **Сбросить меню в начальное состояние**
![image](https://cloud.githubusercontent.com/assets/1106990/6771220/6d9793ca-d0ea-11e4-907d-be680ad3105e.png)

Если ошибка продолжает выводится, то нужно в БД в таблице prefix_storage удалить строки относящиеся к меню. У этих записей поле *storage_key* начинается с *custom.config.menu*

**Comment by lsnull** [comment]
сбрасывал - это я первое что сделал а после кеш чистил не помогло

**Comment by andrey-v** [comment]
Ошибка с simplexml возникает только тогда. когда файл plugin.xml ошибочный. Это может быть когда:
* Синтаксическая ошибка в тексте xml, например пустая строчка в самом начале файла, тогда в логах будет ошибка *E_WARNING [2] simplexml_load_string(): Entity: line 25: parser error : XML declaration allowed only at the start of the document*
* Изменилась кодировка файла. FTP-клиенты могут при передаче портить кодировку файла. В этом случае в логах такая ошибка *E_WARNING [2] simplexml_load_string(): Entity: line 25: parser error : Input is not proper UTF-8, indicate encoding !*

Проверьте логи, что там написано?

**Comment by andrey-v** [comment]
> попробуйте обновить сайт с гитхаба, а потом сбросить меню. Я час назад исправил две ошибки в модуле меню.

**Comment by lsnull** [comment]
я же вам отправлял файл с ошибками там как раз уже была она и последние ошибки были уже в нем

**Comment by lsnull** [comment]
на счет "Синтаксическая ошибка" я не совсем понял как это проверить и исправить.
а вот Изменилась кодировка файла. Думаю мало вероятно так как раньше сама она не менялась же... НУ и две папки которые вы фиксите я загрузил без перезапаиси так как старые  просто переименовал.

**Comment by lsnull** [comment]
Вернул старые папки common и engine где то 3-х дневной давности и ошибка пропала... о.О
