### ISSUE TITLE
Время на сайте.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#442]
Дорогие мои!
Очень вас прошу... Исправьте время на сайте. Проблемы видимо с часовыми поясами. Выбрал Свой , но разница в час.
![screenshot_28](https://cloud.githubusercontent.com/assets/7164280/6762914/7a6c1932-cf72-11e4-8ecc-0fcbc5075421.jpg)

**Comment by andrey-v** [comment]
Исправим.
Задачу закрою, так как она дублирует  вот эту открытую - #417
