### ISSUE TITLE
Статические страницы

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#443]
Так и должно быть?
![screenshot_29](https://cloud.githubusercontent.com/assets/7164280/6763035/a822ec04-cf75-11e4-9039-574392dd1941.jpg)
![screenshot_30](https://cloud.githubusercontent.com/assets/7164280/6763034/a822dd9a-cf75-11e4-9d24-2c651e71a903.jpg)
Даже если все включить,
![screenshot_31](https://cloud.githubusercontent.com/assets/7164280/6763042/0b0c6980-cf76-11e4-9d3b-ad3579209111.jpg)
Оставил. Можете глянуть на моем сайте. Тестовую не видно нигде.
Мой сайт в Инфо профиля на Alto
все равно ее не видно

**Comment by andrey-v** [comment]
В главное меню выводятся только страницы первого уровня. Если нужно многоуровневое меню, то его можно сделать в админке проставив в элементах меню ссылки на статические страницы.
![image](https://cloud.githubusercontent.com/assets/1106990/6765688/fea624de-cffb-11e4-831d-b986789bdda5.png)
