### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#444]
У меня одного ошибки после того как в админки управляю Меню или плагинами ? Щас Отредактировал меню и ошибка вылезла

E_NOTICE [8] Array to string conversion
See details in error.log 

2015-03-21 19:32:41
E_NOTICE [8] Array to string conversion (/home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php on line 387)

**Comment by andrey-v** [comment]
Скорее всего да. Была ошибка при которой в БД писалось не верное значение. Ошибка была исправлена, но у вас в БД настройки меню по прежнему остались с ошибкой и эти настройки не могут прочитаться. Попробуйте в админке те элементы меню которые вы редактировали **повторно** просто ещё раз изменить. Новые значения затрут ошибочные старые.

**Comment by lsnull** [comment]
я вас понял. Уже сделал. Спасибо

**Comment by lsnull** [comment]
2015-03-21 19:32:41
E_NOTICE [8] Array to string conversion (/home/a12051/public_html/engine/classes/modules/menu/entity/Item.entity.class.php on line 387)
