### ISSUE TITLE
Лайтбокс просмотра фотосета на мобильных устройствах

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#445]
проблема в том что он очень маленький, а при нажатии на кнопку "развернуть" - огромный (т.к. картинка достаточно большая)

**Comment by inliquid** [comment]
![imag0021](https://cloud.githubusercontent.com/assets/6797881/6766379/a3b22ae0-d015-11e4-9830-688776f073bc.jpg)

**Comment by aVadim483** [comment]
Нужно либо подбирать другой скрипт, либо делать специальную адаптацию под мобильные

**Comment by aVadim483** [comment]
Переносим на следующую версию
