### ISSUE TITLE
При выборе получателей личного сообщения из списка друзей возвращается некорректное значение

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#446]
А именно, вставляется то что возвращает getDisplayName(). Тогда как у меня в движке настроено что этот метод выводит имя. Должен же вставляться логин, иначе не работает.

Скины start-kit и brand.

![1](https://cloud.githubusercontent.com/assets/6797881/6766482/35ff36a6-d019-11e4-9920-636575b7c52f.png)

**Comment by inliquid** [comment]
Ничего не изменилось

![1](https://cloud.githubusercontent.com/assets/6797881/6881236/aadcb158-d567-11e4-9d80-e6f49048bfff.png)

**Comment by andrey-v** [comment]
js-cкрипты на сайте не обновились. Новый скрипт подставляет значения из поля value, а старый из текста label-а.

**Comment by inliquid** [comment]
Андрей, сейчас еще раз сбросил кэш
1. Из админки
2. Руками перезапустил мемкэш, почистил временные директории
3. Сбросил содержимое кэша браузера
4. Нажал Ctrl-F5 (еще раз до кучи)

Результат - как было так и осталось. Так что видимо есть какие-то еще причины почему срабатывает не так как надо.

**Comment by andrey-v** [comment]
Где я могу посмотреть? Или это на локалке?

**Comment by inliquid** [comment]
На сайте) Щас я тебя добавлю

**Comment by andrey-v** [comment]
В шаблоне старт-кит скрипт template.js дублировал код ls.talk - Исправлено
