### ISSUE TITLE
Кеш

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#447]
Почистил кешь в _tmp - слетели настройки

**Comment by aVadim483** [comment]
Выражайтесь, пожалуйста, яснее, какие настройки у вас слетели? Которые через админку задавали? В конфиге? Настройки движка? Плагина?

**Comment by andrey-v** [comment]
Проверил, при удалении _tmp настройки сделаные в админке восстанавливаются. Проверьте у себя на сервере применялись ли обновления [вот в этих файлах](https://github.com/altocms/altocms/commit/b12f37575753530970a87bb9e76355dd30c92990)

**Comment by lsnull** [comment]
Я вчера обновил вечером. А этот файл на который вы дали ссылку вообще 5 дней назад был обновлен. 
aVadim483 плагины, меню...

**Comment by aVadim483** [comment]
@lsnull настройки, заданные через админку или в конфиге? или и то, и другое? это очень важные "мелочи", которые помогают лучше понять проблему

**Comment by lsnull** [comment]
через админку

**Comment by aVadim483** [comment]
Проверьте, сейчас все нормально должно работать при ручной очистке кеша
