### ISSUE TITLE
Выбор отслеживаемых пользователей в подписках в "активности"

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#449]
Пользователи дублируются в "друзьях" и не_друзьях после обновления страницы. По логике должно быть как в "ленте" - если человек является другом, то галочка ставится в "друзьях", все остальные выводятся в отдельном блоке.
![3](https://cloud.githubusercontent.com/assets/6797881/6770889/9efdc7e6-d0df-11e4-9fd3-a609a9f1626c.png)

**Comment by andrey-v** [comment]
Да, была ошибка, в шаблон просто не передавалась переменная со списком друзей пользователя, хотя в самом шаблоне она использовалась.
