### ISSUE TITLE
стиль в Experience v.1.0.3

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#450]
Решил включить этот шаблон, так как у меня ошибка на сайте уже в теме #441 и решил попробовать проверить на другом шаблоне. Но и заобно выявил некоторые нюансы в css. 
![screenshot_41](https://cloud.githubusercontent.com/assets/7164280/6771855/b7b28186-d0f4-11e4-8129-c7483594dfa7.jpg)
В списке блогов вывод описания. Если раз навести на кратное описание Блога после слегка отвести мышку и повторно навести на стрелочку, то пропадает окно с описанием Блога
![screenshot_43](https://cloud.githubusercontent.com/assets/7164280/6771872/81719a52-d0f5-11e4-8832-55f469dd4e85.jpg)
![screenshot_42](https://cloud.githubusercontent.com/assets/7164280/6771873/8171953e-d0f5-11e4-9e93-e576bcb2310b.jpg)
Получить короткую ссылку на статью
![screenshot_44](https://cloud.githubusercontent.com/assets/7164280/6771882/de8faaee-d0f5-11e4-9a59-dee85d9c9a7c.jpg)

**Comment by andrey-v** [comment]
1. ширина тултипа не динамическая а фиксированная, если её нужно изменить, то сделать это можно добавив в файл **common/templates/skin/experience/themes/default/css/custom.css** стиль
```
.toolbar-write .popover-content {
  width: 222px;
}
```

**Comment by andrey-v** [comment]
2. Тултип блога. Не могу понять в чём проблема. При наведении на стрелочку он появляется и исчезает если мышь убрать со стрелочки. Где не так?
