### ISSUE TITLE
Стиль в Experience Simple v.1.0.0  на Alto 1.1.x

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#451]
Обновился Ночью...
Проблемы со стилем:
![screenshot_48](https://cloud.githubusercontent.com/assets/7164280/6772174/e415f27a-d0ff-11e4-92ab-0fe358700256.jpg)
![screenshot_47](https://cloud.githubusercontent.com/assets/7164280/6772175/e44385e6-d0ff-11e4-887e-9b028423ba88.jpg)
И вот еще
![screenshot_53](https://cloud.githubusercontent.com/assets/7164280/6772379/2e7966da-d105-11e4-8ada-85e20ee4867b.jpg)

**Comment by andrey-v** [comment]
А как эти просматриваемые там появились?

**Comment by lsnull** [comment]
Даже незнаю. Но довольно неплохо если внедрить раз небыло.

**Comment by andrey-v** [comment]
Такой кнопки там нет, через адмнку её сделать нельзя. Этот элемент добавляет какой-то ваш плагин, который не адаптирован к шаблону Experience Simple

**Comment by lsnull** [comment]
Я понял. Приду дамой разберу плагин.
