### ISSUE TITLE
Проблеммы с комментарием в Топиках

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#452]
Написал коммент.
Решил отредактировать... При редактировании Enter не работает. Нажал ентер выдал мне пробел в место новой строки. Решил Дописать текст. Сохранил. Текст добавленный есть и с новой строки. Но при редактировании Не видно было что пишешь на новой строке. При этом после сохраненного после редактирования комментария, не видно функции удалить и редактировать а так же других:
![screenshot_59](https://cloud.githubusercontent.com/assets/7164280/6772528/54f3a6e6-d109-11e4-8c41-6178146b6113.jpg)

 После того как обновил страницу - эти функции появились.
![screenshot_58](https://cloud.githubusercontent.com/assets/7164280/6772531/5d334faa-d109-11e4-9179-56dd3f8d4951.jpg)

Еще будет лаконично, если при редактировании и ответа на коммент будет отсутствовать кнопка "Оставить комментарий" либо "Отправить" так как две кнопки одновременно путают, лично я два раза при редактировании нажал не на "Отправить" а на "Оставить комментарий". И вышло что я создал новый коммент.
![screenshot_56](https://cloud.githubusercontent.com/assets/7164280/6772504/d7ee3f80-d108-11e4-8ed5-c8ca0ec8207e.jpg)

**Comment by andrey-v** [comment]
Ошибку исправил, но вот насчёт кнопок не уверен, скорее всего это вопрос для обсуждения в сообществе.

**Comment by aVadim483** [comment]
Возможно, действительно лучше во время редактирования комментария убирать кнопки "Оставить комментарий" и "Свернуть все ветки", т.к. во время этого процесса они лишние, но добавить кнопку "Отмена" на случай, если юзер передумал редактировать коммент.

А после отправки коммента или после отмены возвращать эти две кнопки. Подумаем
