### ISSUE TITLE
Вывод окна с инфо

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#454]
Вчера ночью обновился…
Но у меня такого нет в списках Блога и Пользователей…
Это у меня одного такое?
![screenshot_62](https://cloud.githubusercontent.com/assets/7164280/6779292/4eb36fe6-d163-11e4-9e28-46c432f80d4e.jpg)
![screenshot_61](https://cloud.githubusercontent.com/assets/7164280/6779293/4ecdc3a0-d163-11e4-94f1-c870b5defc17.jpg)

**Comment by andrey-v** [comment]
Исправлено

**Comment by lsnull** [comment]
Спасибо
