### ISSUE TITLE
Не все фото загружаются

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#456]
Не грузит PNG формат фото.
![screenshot_66](https://cloud.githubusercontent.com/assets/7164280/6797665/674d0742-d20d-11e4-8201-e3fc4470972a.jpg)
![screenshot_67](https://cloud.githubusercontent.com/assets/7164280/6797667/674f2090-d20d-11e4-8aec-3ce332b7a5e6.jpg)
![screenshot_65](https://cloud.githubusercontent.com/assets/7164280/6797666/674d3a46-d20d-11e4-84ea-9ca9004829d5.jpg)

**Comment by aVadim483** [comment]
У меня PNG с дефолтными настройками грузится без проблем. Проверяйте настройки, смотрите, что меняли, возможно, с какими-то конкретными настройками возникают проблемы

**Comment by andrey-v** [comment]
Повторите с jpeg, если пройдёт, то у вас или настройки Альто сбились или вебсервер не хочет такие картинки.

**Comment by lsnull** [comment]
Jpeg пробовал - грузит. А сервер до этого и альто грузили. Я проверю конечно настройки.  глазами утром пробежался, но не заметил особых подозрений. Учту... через часа 3 постараюсь ответить.

**Comment by lsnull** [comment]
Перепробовал возможные варианты - безрезультатно
