### ISSUE TITLE
Опять фотосет!

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#457]
По умолчанию ставит фото из фотосета в текст описания Топика!!
Снять превъю из фотосета невозможно!
Загрузил фото через редактор и нужно было в фотосет. Выдает с него фото в описание. Нафига оно мне если там уже есть необходимая картинка загруженная через Редактор!
Сделайте отключение превью и включение.

**Comment by aVadim483** [comment]
Пожалуйста, без эмоций, только сухое и точное описание проблемы. Что такое "текст описания топика"? Нет такого в движке из коробки
