### ISSUE TITLE
Некорректное формирование ТОПа

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#459]
При формировании ТОПа, если рейтинг топиков одинаковый, они показываются вразнобой без сортировки по дате, даже не по алфавиту, непонятно как. В этом случае должна быть вторичная сортировка по дате.

**Comment by andrey-v** [comment]
Проблема аналогичная #407 и решается также, а вот как лучше выводить вторичную сортировку по дате, алфавиту, рейтингу?

**Comment by inliquid** [comment]
Я думаю здесь логично делать вторичную сортировку по дате. Т.е. если рейтинг одинаковый получаем просто ленту постов.

**Comment by aVadim483** [comment]
Да, обратная сортировка по дате

**Comment by andrey-v** [comment]
@inliquid  а где именно так происходит, вроде везде где выводится топ уже добавлена вторая сортировка - (здесь)[https://github.com/altocms/altocms/blob/1.0.x/common/classes/modules/topic/Topic.class.php#L1360] и (здесь)[https://github.com/altocms/altocms/blob/1.0.x/common/classes/modules/topic/Topic.class.php#L1754]

**Comment by inliquid** [comment]
Отпишу в личку.

**Comment by inliquid** [comment]
Вероятно та же проблема при выводе постов с сортировкой по комментариям

**Comment by aVadim483** [comment]
Вопрос решен?

**Comment by inliquid** [comment]
Нет.

**Comment by aVadim483** [comment]
Включен ли кеш и какое значение конфига Config::Get('sys.cache.solid')?

**Comment by inliquid** [comment]
Кэш включен, solid=false.

Там насколько я помню смотрел была сортировка по id топика. Эта схема будет сбоить как минимум в одном случае - если сначала пишется черновик а потом публикуется, когда уже успели опубликовать другие топики.

Но у меня вроде и без черновиков шло вразнобой.

![unnamed](https://cloud.githubusercontent.com/assets/6797881/7220511/73c2dbee-e6d2-11e4-9b66-a7c91d0ee220.png)

**Comment by aVadim483** [comment]
А вот насчет черновиков - это верно, если сначала черновик, то сортировка по ID будет некорректной

**Comment by aVadim483** [comment]
В 1.1 внесены правки, чтобы сортировка работала корректно даже если публикация идет через черновики. В 1.0 это сделать проблематично, т.к. требуется выполнение корректировочного SQL-запроса
