### ISSUE TITLE
css в шаблоне Experience Simple v.1.0.0

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#461]
![screenshot_69](https://cloud.githubusercontent.com/assets/7164280/6815355/6890e3e2-d291-11e4-8434-ca81631e6214.jpg)
![screenshot_68](https://cloud.githubusercontent.com/assets/7164280/6815356/68b6506e-d291-11e4-8c28-3b61471032d9.jpg)

**Comment by andrey-v** [comment]
@lsnull, проверьте, пожалуйста с последним обновлением

**Comment by bodhihappy** [comment]
у меня такой проблемы нет. Чистый Alto 1.1-beta, качал вчера. Шаблон Experience Simple v.1.0.0, плагины из коробки.

**Comment by lsnull** [comment]
наклепайте тегов больше и увидете.
--
Отправлено через Mail. Меня можно найти на losper.net
пятница, 17 апреля 2015г., 14:31 +03:00 от bodhihappy <notifications@github.com>:

**Comment by andrey-v** [comment]
Ошибки не воспроизводятся, скорее всего исправлены последними коммитами 
![image](https://cloud.githubusercontent.com/assets/1106990/7818232/12423db4-03e3-11e5-94c3-e99fecdee802.png)
