### ISSUE TITLE
После последних 2х исправлений "активность" вообще отвалилась!

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#465]
[LOG:1427487917.790-5515BCADC0E67][2015-03-27 23:25:17][PID:1776][ERROR][[
Exception: Undefined method module: ModuleUser
--- call stack ---
Engine->GetModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 612
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 773
Engine->__call()
Engine->ModuleUser()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1298
E::__callStatic() in /var/www/example.com/common/classes/widgets/WidgetActivityUsers.class.php on line 35
E::ModuleUser() in /var/www/example.com/common/classes/widgets/WidgetActivityUsers.class.php on line 35
WidgetActivityUsers->Exec() in /var/www/example.com/engine/classes/modules/viewer/plugs/function.widget_exec.php on line 111
smarty_function_widget_exec() in /var/www/example.com/engine/classes/modules/viewer/plugs/function.widget.php on line 71
smarty_function_widget() in /var/www/example.com/engine/classes/modules/viewer/plugs/function.wgroup_show.php on line 51
smarty_function_wgroup_show() in /var/www/example.com/engine/classes/modules/viewer/plugs/function.wgroup.php on line 65
smarty_function_wgroup() in /var/www/example.com/_tmp/templates/brand-light/compiled/light^8a2a3e5513b8e54306b3c528eb6c9de4c609b5e1.file.common.sidebar.tpl.php on line 26
content_5515bc7f415595_95564357() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 188
Smarty_Internal_TemplateBase->fetch() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_template.php on line 304
Smarty_Internal_Template->getSubTemplate() in /var/www/example.com/_tmp/templates/brand-light/compiled/light^894b7ff8f118ffd17a6ae0e89950d13920d9219b.file.action.stream.follow.tpl.php on line 398
content_5515bca4eee882_61491645() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 188
Smarty_Internal_TemplateBase->fetch() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 394
Smarty_Internal_TemplateBase->display() in /var/www/example.com/engine/classes/modules/viewer/Viewer.class.php on line 594
ModuleViewer->Display()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Router.class.php on line 743
Router->__call() in /var/www/example.com/engine/classes/core/Router.class.php on line 200
Router->Viewer_Display() in /var/www/example.com/engine/classes/core/Router.class.php on line 200
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1427487917.790-5515BCADC0E67]

**Comment by aVadim483** [comment]
Отключите все плагины и проверьте

**Comment by aVadim483** [comment]
У Вас, похоже, виджет от версии 1.1, а ядро от версии 1.0. Конечно, это не будет работать

**Comment by inliquid** [comment]
Вообще-то у меня вот это

https://github.com/altocms/altocms/commit/626dcd397967dd0bf9c1a973d19c8f5eae4b8c5c


Никаких виджетов от 1.1 у меня в принципе быть не может.

**Comment by aVadim483** [comment]
Значит, Андрей по ошибке внес в 1.0 конструкцию, которая только в 1.1 может работать:
E::ModuleViewer()->Assign('aStreamFriends', $aStreamFriends['collection']);

Для 1.0 это должно быть так:
E::Viewer_Assign('aStreamFriends', $aStreamFriends['collection']);

**Comment by inliquid** [comment]
Я конечно извиняюсь но разве не на предыдущую строчку ругалось? (Exception: Undefined method module: ModuleUser)

**Comment by aVadim483** [comment]
А, ну да, там тоже ошибка, должно быть так:
$aStreamFriends = E::User_GetUsersFriend($oUserCurrent->getId());

**Comment by andrey-v** [comment]
Извиняюсь, моя ошибка была, исправил.
