### ISSUE TITLE
неправильно отображается картинка в фотосете

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#470]
Скачивал часа 4 назад примерно по этой ссылке https://github.com/altocms/altocms/releases/tag/1.1-b

К топику добавил 5 фотографий, галку поставил отображать фотосет, также сделал тестовый опрос. В фотосете превью крайнее отображается вытянутым в ширину, скрин прилагаю.

![topic-1](https://cloud.githubusercontent.com/assets/253228/6881965/1381ebd8-d586-11e4-825f-f1a459cbfe68.jpg)

**Comment by andrey-v** [comment]
Это фича ) используемого плагина галереи, если не нужно что бы последнее изображение растягивалось по ширине до края страницы, то нужно [здесь](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/assets/js/theme.js#L422) установить **fillLastRow = false*

**Comment by andrey-v** [comment]
А для шаблона Experience изменять настройку нужно [здесь](https://github.com/altocms/altocms/blob/master/common/templates/skin/experience/themes/default/js/theme.js#L465)

**Comment by yuri25** [comment]
Очуметь:) Так сразу то и не догадаешься что это фича... Теперь даже не знаю как сделать лучше... Оставлю фичу:)
