### ISSUE TITLE
Невозможно задать максимальную длину сообщения

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#472]
$config['module']['talk']['max_length']  = 15000; 
- не работает, по-прежнему ограничение остается в 3000 смиволов

$config['module']['comment']['max_length'] = 15000;
- тоже как-то странно себя ведет, хотя его поведение близко к правильному - пропустил около 14к символов

(и кстати в текстовках жестко зашито количество)

**Comment by aVadim483** [comment]
https://github.com/altocms/altocms/commit/4af1705f6ccc4859d55786173e2cff7c2fc879c7

**Comment by aVadim483** [comment]
Сообщения исправил, но ошибка с длиной не воспроизводится - при контроле данные берутся из конфига, как и положено

**Comment by inliquid** [comment]
Я так понимаю ошибку коммит не исправляет? Загружу, проверю что изменилось, но сразу могу сказать - совершенно однозначно я не мог написать личное сообщение более 3 тыс символов независимо от значения в конфиге.

**Comment by aVadim483** [comment]
>Я так понимаю ошибку коммит не исправляет?

Ошибку я вообще воспроизвести не смог. 
```
$iMin = intval(Config::Get('module.talk.min_length'));
$iMax = intval(Config::Get('module.talk.max_length'));
if (!F::CheckVal(F::GetRequestStr('talk_text'), 'text', $iMin, $iMax)) {
    if ($iMax) {
        $this->Message_AddError($this->Lang_Get('talk_create_text_error_len', array('min'=>$iMin, 'max'=>$iMax)), $this->Lang_Get('error'));
    } else {
        $this->Message_AddError($this->Lang_Get('talk_create_text_error_min', array('min'=>$iMin)), $this->Lang_Get('error'));
    }
    $bOk = false;
}
```
По коду видно, что значения для проверки берутся из конфига

**Comment by inliquid** [comment]
А по факту не работает. Мне наверно заняться больше нечем - сижу из головы баги придумываю.

**Comment by inliquid** [comment]
![1](https://cloud.githubusercontent.com/assets/6797881/7228672/423d259c-e764-11e4-93ec-37cb3fc633c8.png)
![2](https://cloud.githubusercontent.com/assets/6797881/7228671/423d1dc2-e764-11e4-92d9-6e1fc5b63724.png)

**Comment by aVadim483** [comment]
Можно иронизировать сколько угодно, но на сегодняшний день я не могу воспроизвести ошибку. И чисто в теории проблем может быть две: либо влияние сторонних плагинов, либо некорректно формируется конфиг.

**Comment by inliquid** [comment]
Можно узнать как вы воспроизводите? У меня есть сильно подозрение что сообщение отправили а комментарий в переписку не написали.

**Comment by aVadim483** [comment]
Как пишете, так я и проверяю: раз сказано, что проблема с сообщением, то сообщение и проверяю. Вот упомянули теперь про комментарий к переписке - проверил комментарий. И да, было зашито жестко в коде, еще со времен ЛС. Исправил.

ЗЫ Вот потому я и прошу максимально подробно расписывать алгоритм, как воспроизвести ошибку.

**Comment by inliquid** [comment]
Теперь при превышении длины такая ерунда вылезает и "System error #1001"

[LOG:1430073106.115-553D2F121C00A][2015-04-26 21:31:46][PID:12982][ERROR][[
Exception: Undefined method module: ModuleMessage
--- call stack ---
Engine->GetModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 612
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 773
Engine->__call()
Engine->ModuleMessage()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1298
E::__callStatic() in /var/www/example.com/common/classes/actions/ActionTalk.class.php on line 666
E::ModuleMessage() in /var/www/example.com/common/classes/actions/ActionTalk.class.php on line 666
ActionTalk->SubmitComment() in /var/www/example.com/common/classes/actions/ActionTalk.class.php on line 625
ActionTalk->AjaxAddComment()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

**Comment by aVadim483** [comment]
Издержки поддержки двух веток одновременно. Пофиксил

**Comment by inliquid** [comment]
Спасибо. Работает.
