### ISSUE TITLE
меню сайта после обновления сегодня

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#474]
Интересно получается меню Новое (за 24 часа выводит подсказку) но показывает за все время. Пытался сделать период за 24\1\7\все Нифига!
После удалил подменю и получил в ответ ошибку
E_WARNING [2] preg_match() expects parameter 2 to be string, array given
See details in error.log
E_NOTICE [8] Array to string conversion
See details in error.log 

Обновил Альту 1.1 до актуальной и получил меню вот такое и ошибку:
![screenshot_73](https://cloud.githubusercontent.com/assets/7164280/6887607/512051b8-d66d-11e4-9261-0f37fee33f76.jpg)
уже подустал с этими ошибками и меню. Не хочу все сбрасывать по умолчанию и заново создавать.

Как убрать я не понимаю. А в меню в самой админке осталась функция :
![screenshot_74](https://cloud.githubusercontent.com/assets/7164280/6887678/a009a34a-d66f-11e4-8bd2-786158fc5efd.jpg)
После нажатии на Редактировать, что в скрине выше, выдает:
![screenshot_75](https://cloud.githubusercontent.com/assets/7164280/6887680/bb0ea0e6-d66f-11e4-958c-69273fdae535.jpg)

**Comment by andrey-v** [comment]
Исправил, для исправления ошибки у вас попробуйте в админке заново создать подменю для элемента меню "новые" и удалить созданное подменю. Если не получится, то, увы, придётся полностью сбрасывать меню топиков.

**Comment by lsnull** [comment]
Спасибо. Буду дома проверю.
