### ISSUE TITLE
Пункт меню в сообщениях "только новые" не работает

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#475]
Выводятся все сообщения
![1](https://cloud.githubusercontent.com/assets/6797881/6887959/43089770-d677-11e4-94e6-8acbdbb5a823.png)

**Comment by inliquid** [comment]
Не работает именно с плагином mailing((

**Comment by inliquid** [comment]
Из конфига mailing
// подставляется в Talk, необходио так же для непоказа автору рассылки писем без ответов
Config::Set('IP_SENDER', '255.255.255.255');

Действительно, отправляемые массово через личку сообщения не видны если адресат не ответит.

**Comment by aVadim483** [comment]
Значит, плагин работает некорректно

**Comment by inliquid** [comment]
Не могли бы вы прояснить откуда такая уверенность что проблема в плагине а не в движке (плагине совместимости).

**Comment by inliquid** [comment]
Смотрите, я в плагине ничего криминального не вижу. Ничего такого что могло бы сломать работу такой функции как вывод только новых. Вот как работает фильтр рассылок по отвеченным неотвеченным:

<?php

/* ---------------------------------------------------------------------------
 * @Plugin Name: Mailing
 * @Plugin Id: mailing
 * @Plugin URI:
 * @Description: Mass mailing for users
 * @Author: stfalcon-studio
 * @Author URI: http://stfalcon.com
 * @LiveStreet Version: 1.0.1
 * @License: GNU GPL v2, http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * ----------------------------------------------------------------------------
 */

/**
 * Mailing Plugin Hook class for LiveStreet
 *
 * Mapper for talk
 */
class PluginMailing_ModuleTalk_MapperTalk extends PluginMailing_Inherit_ModuleTalk_MapperTalk {

    /**
     * Возвращает список идентификаторов писем, удовлетворяющих условию фильтра
     * + не выводит письма из рассылки для отправителя если на них нету ответов
     *
     * @param  array $aFilter
     * @param  int $iCount
     * @param  int $iCurrPage
     * @param  int $iPerPage
     * @return array
     */
    public function GetTalksByFilter($aFilter,&$iCount,$iCurrPage,$iPerPage) {
        $sql = "SELECT
                                        tu.talk_id
                                FROM
                                        ".Config::Get('db.table.talk_user')." as tu,
                                        ".Config::Get('db.table.talk')." as t,
                                        ".Config::Get('db.table.user')." as u
                                WHERE
                                        tu.talk_id=t.talk_id
                                        AND tu.talk_user_active = ?d
                                        AND u.user_id=t.user_id
                                        { AND tu.user_id = ?d }
                                        { AND t.talk_date <= ? }
                                        { AND t.talk_date >= ? }
                                        { AND t.talk_title LIKE ? }
                                        { AND u.user_login = ? }
                                        { AND t.user_id = ? }
                    AND NOT (t.talk_user_ip = '".Config::Get('IP_SENDER')."'
                        AND t.talk_count_comment = 0
                        AND tu.user_id = t.user_id)
                                ORDER BY t.talk_date_last desc, t.talk_date desc
                                LIMIT ?d, ?d
                                        ";

                $aTalks=array();
                if (
                        $aRows=$this->oDb->selectPage(
                                $iCount,
                                $sql,
                                ModuleTalk::TALK_USER_ACTIVE,
                                (!empty($aFilter['user_id']) ? $aFilter['user_id'] : DBSIMPLE_SKIP),
                                (!empty($aFilter['date_max']) ? $aFilter['date_max'] : DBSIMPLE_SKIP),
                                (!empty($aFilter['date_min']) ? $aFilter['date_min'] : DBSIMPLE_SKIP),
                                (!empty($aFilter['keyword']) ? $aFilter['keyword'] : DBSIMPLE_SKIP),
                                (!empty($aFilter['user_login']) ? $aFilter['user_login'] : DBSIMPLE_SKIP),
                                (!empty($aFilter['sender_id']) ? $aFilter['sender_id'] : DBSIMPLE_SKIP),
                                ($iCurrPage-1)*$iPerPage,
                                $iPerPage
                        )
                ) {
                        foreach ($aRows as $aRow) {
                                $aTalks[]=$aRow['talk_id'];
                        }
                }
                return $aTalks;
    }
}

**Comment by inliquid** [comment]
Т.е. по логике, ну да допустим я хочу изменить именно этот критерий для обычной выдачи. Но почему он приводит к тому что другой критерий "только новые" перестает работать?

**Comment by klaus-spb** [comment]
Ахаха, вы целиком заменили функцию выбора комментариев, притом в вашей функции нет признака "только новые" (only_new) и удивляетесь почему выборка "только новые" перестала работать
```php
public function GetTalksByFilter($aFilter, &$iCount, $iCurrPage, $iPerPage) {
        if (isset($aFilter['id']) && !is_array($aFilter['id'])) {
            $aFilter['id'] = array($aFilter['id']);
        }
        $sql
            = "SELECT
					t.talk_id
				FROM 
					?_talk_user AS tui
                  JOIN ?_talk AS t ON t.talk_id=tui.talk_id
                  JOIN ?_talk_user AS tu ON tu.talk_id=t.talk_id
                  JOIN ?_user AS u ON u.user_id=tu.user_id
				WHERE 
					tui.talk_user_active = ?d
					{ AND tui.user_id = ?d }
					{ AND tui.talk_id IN (?a) }
					{ AND ( tu.comment_count_new > ?d OR tu.date_last IS NULL ) }
					{ AND t.talk_date <= ? }
					{ AND t.talk_date >= ? }
					{ AND t.talk_title LIKE ? }
					{ AND t.talk_text LIKE ? }
					{ AND u.user_login = ? }
					{ AND u.user_login IN (?a) }
					{ AND t.user_id = ? }
				ORDER BY t.talk_date_last desc, t.talk_date desc
				LIMIT ?d, ?d
					";
        $aTalks = array();
        $aRows = $this->oDb->selectPage(
            $iCount,
            $sql,
            ModuleTalk::TALK_USER_ACTIVE,
            (!empty($aFilter['user_id']) ? $aFilter['user_id'] : DBSIMPLE_SKIP),
            ((isset($aFilter['id']) && count($aFilter['id'])) ? $aFilter['id'] : DBSIMPLE_SKIP),
            (!empty($aFilter['only_new']) ? 0 : DBSIMPLE_SKIP),
            (!empty($aFilter['date_max']) ? $aFilter['date_max'] : DBSIMPLE_SKIP),
            (!empty($aFilter['date_min']) ? $aFilter['date_min'] : DBSIMPLE_SKIP),
            (!empty($aFilter['keyword']) ? $aFilter['keyword'] : DBSIMPLE_SKIP),
            (!empty($aFilter['text_like']) ? $aFilter['text_like'] : DBSIMPLE_SKIP),
            ((!empty($aFilter['user_login']) && !is_array($aFilter['user_login']))? $aFilter['user_login'] : DBSIMPLE_SKIP),
            ((!empty($aFilter['user_login']) && is_array($aFilter['user_login']))? $aFilter['user_login'] : DBSIMPLE_SKIP),
            (!empty($aFilter['sender_id']) ? $aFilter['sender_id'] : DBSIMPLE_SKIP),
            ($iCurrPage - 1) * $iPerPage,
            $iPerPage
        );
        if ($aRows) {
            foreach ($aRows as $aRow) {
                $aTalks[] = $aRow['talk_id'];
            }
        }
        return $aTalks;
    }
```

**Comment by aVadim483** [comment]
По логике - это метод, который делает выборку **по фильтру** для разных случаев, в т.ч. и при выводе только новых. Вы ломаете SQL-запрос и удивляетесь, почему он работает не так, как раньше.

**Comment by inliquid** [comment]
получается у меня нет технической возможности изменить фильтр не сломав "только новые"?

**Comment by klaus-spb** [comment]
есть такая возможность, скопируйте функцию выбора из движка и добавьте в неё необходимые новые фильтры

**Comment by inliquid** [comment]
Может я чего-то не понимаю, но опять же - по логике, вот я написал функцию, движок поменялся, обновился, появились новые фичи. а я получается в любой новой версии их ломаю. разве не должно это решаться разными методами, чтобы изолировать выборки друг от друга?

**Comment by klaus-spb** [comment]
Так вы не написали функцию. Вы переопределили штатную функцию и заменили её своей. Вы могли написать свою функцию и пользоваться ею. Но вы же захотели чтобы штатная функция стала работать иначе, поэтому её поменяли на свою. 

Я даже запутался, вы хотите свою функцию или изменить штатную?

**Comment by inliquid** [comment]
Смотрите, Николай, мне нужно сделать другую выборку, так чтобы массовые рассылки через ЛС не отображались пока на них пользователь не ответит. Разумная фича. Получается другого пути как переопределить штатную функцию нет. При этом ломается вывод новых. (Я на самом деле просто думаю что в той версии ЛС, для которой это писалось этого не было) А то что функция штатная, ну так они все в той или иной степени штатные. Разве не лучше чтобы для "только новых" был отдельный метод, который бы нельзя было таким образом сломать?

**Comment by klaus-spb** [comment]
Нет, не лучше. Есть один единый запрос для всех выборок по письмам ,в том числе и для новых. Для этого запроса есть определенное количество критериев. Вы хотите свой критерий и продублировать функцию и добавить в неё одну две строки никакого труда не составит. Да существует вероятность что когда-то в фильтр добавятся еще какие-то критерии, но это не особо вероятно.Вот именно для этого и необходима поддержка плагинов.

Есть конечно вариант строить фильтр как в топиках отдельной функцией, которую удобно дополнять. Но письма это не топики, в выборке писем свой критерий добавляет наверно только плагин mailing.
