### ISSUE TITLE
Некорректная выборка новых личных сообщений

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#477]
Похоже мне все-таки удалось сломать вывод "только новых". Не знаю что произошло, может сообщений в ходе тестов стало много и это повлияло (бОльшая их часть сгенерилась как рассылки). Короче говоря теперь у меня без плагинов mailing и lsdigest некорректно формируется вывод "только новых". 

1) Плагины удалил вообще физически и их конфиг
2) Проверил при деактивации плагины потерли все доп поля к prefix_user и свои таблицы
3) Сбросил кеши
- админка
- вручную

4) Перезаписал поверх последнюю версию репозитория с гитхаба

Вот что имею сейчас 

Пользователь 1
![2](https://cloud.githubusercontent.com/assets/6797881/6940777/a22032b0-d882-11e4-9ec2-91e944cc9c56.png)

Пользователь 2
![3](https://cloud.githubusercontent.com/assets/6797881/6940779/ab84eddc-d882-11e4-88e1-b8ea5f448cef.png)

**Comment by inliquid** [comment]
Андрей можешь посмотреть на тестовом сайте.

**Comment by aVadim483** [comment]
Когда выбираете "Только новые", то отображается список писем. Если кликнуть по какому-то письму (открыть его), а потом опять выбрать "Только новые", то это письмо так и остается в списке? Или оно пропадает?

**Comment by inliquid** [comment]
Еще раз прошелся по списку, кое-что пропало но не все. Сейчас в "только новых" отображаются те сообщения, которые были отправлены от имени юзера через массовую рассылку. Если смотреть в базе, то единственное отличие это поле talk_user_ip -> 255.255.255.255.

Меня еще беспокоит что на скриншотах выше видно что у пользователя отображается не только рассылка прочитанная, в обоих случаях

1) оба сообщения из списка  - не рассылка

https://cloud.githubusercontent.com/assets/6797881/6940777/a22032b0-d882-11e4-9ec2-91e944cc9c56.png

2) 2 и 3 сверху - не рассылка

https://cloud.githubusercontent.com/assets/6797881/6940779/ab84eddc-d882-11e4-88e1-b8ea5f448cef.png 

Кстати если все сообщения прочитаны то кнопка "только новые" вообще недоступна. Но стоит написать хоть одно письмо и перейти на эту вкладку - картинка повторяется. 

Причем рассылочные сообщения не отображаются в "только новых" у получателей. Только у отправителя. (по крайней мере сейчас)

**Comment by aVadim483** [comment]
Чтобы этот функционал работал правильно, необходимо корректно формировать записи в двух взаимосвязанных таблицах: prefix_talk и prefix_talk_user.

У Вас стоял плагин, который работал с базой как-то по-своему, и, скорее всего, не совсем корректно формировал записи в этих базах. Если это тестовый сайт, то самый правильный подход будет - очистить полностью обе эти таблицы, и поработать с сообщениями, создавая и читая часть из них, чтобы попытаться воспроизвести ошибку. Если ошибка не воспроизводится, значит, корень проблем именно в том плагине.

**Comment by inliquid** [comment]
эти таблицы плагин не трогал, единственное отличие что у массово отправляемых сообщений IP отправителя задан как 255.255.255.255. еще раз хочу обратить внимание что не скриншотах есть прочитанные сообщения, которые были написаны руками.

**Comment by aVadim483** [comment]
Хорошо, проверим, если получится воспроизвести ошибку

**Comment by inliquid** [comment]
Вот пример рассылочных сообщений 
![1](https://cloud.githubusercontent.com/assets/6797881/6963486/9fa2a89e-d948-11e4-9bfb-0da5691b186d.png)


Но я думаю дело не в них. На боевом сервере сейчас просто скопировал в плагин функцию из ядра копипастом и все равно выводятся сообщения в "только новых" не рассылочные а самые обычные, давно прочитанные.
Отключить там плагин я не могу, возможно чуть позже залью на тестовый и проверю именно на этих данных.

**Comment by aVadim483** [comment]
Да, смог воспроизвести баг, пофиксил

**Comment by inliquid** [comment]
А почему только 1.1? Там же всего 2 строчки, так?
