### ISSUE TITLE
Проблема с разграничением доступа в типах блогов

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#479]
Ставлю в типе блога настройку "кто может читать" -> "все пользователи" (было "любые посетители сайта"), разлогиниваюсь и все равно читаю и содержимое блога и отдельные топики. Хотя на главной странице топики из запрещенных к просмотру блогов уже не показываются.

**Comment by inliquid** [comment]
Очень нужна эта функция - закрыть доступ к сообществу для на зарегистрированных и не авторизованных пользователей.

**Comment by aVadim483** [comment]
Вот
![default](https://cloud.githubusercontent.com/assets/2246758/7061549/34a31a84-de9c-11e4-947f-fa4259059cc9.JPG)

Или вот:
$config['general']['close']['mode']     = false; // использовать закрытый режим работы сайта, сайт будет доступен только авторизованным пользователям

**Comment by aVadim483** [comment]
По поводу настроек блога - проверим

**Comment by inliquid** [comment]
Не-не, мне нужно закрыть доступ не к сайту а к одному (пока одному) сообществу, т.е. блогу.

**Comment by aVadim483** [comment]
А, значит, я второй коммент просто неверно понял. Насчет доступа только авторизованным - да, баг есть, поправлю

**Comment by inliquid** [comment]
А когда можно ждать исправления на 1.0? 
И выяснил еще что RSS транслирует все закрытые записи.

**Comment by inliquid** [comment]
Вадим скажите пожалуйста когда можно ждать исправления
- Доступ к топику по ссылке (насколько я понял последний коммит закрывает только содержимое блога, но если кто-то опубликует url, или перебором url особенно если используется id - можно открыть страницу топика)
- Доступ к содержимом через RSS
- Все это на версии 1.0.x

Мне очень это, даже костыли в шаблоне не спасают - во-первых печему-то не удается закрыть страницу вывода содержимого топика, а во-вторых остается RSS.

**Comment by aVadim483** [comment]
Коммит закрывает содержимое и при просмотре топиков списком, и при просмотре конкретного топика, если юзер по прямому УРЛу проходит.

По RSS проблему понял, буду смотреть. По версии 1.0 - обновим по мере возможности

**Comment by aVadim483** [comment]
исправлено для 1.0

**Comment by inliquid** [comment]
Тип блога с доступом только зарегистрированным. В newall/ пост появился, а вот после публикации при переходе на страницу топика вот такое

![1](https://cloud.githubusercontent.com/assets/6797881/7756623/229cdcaa-0005-11e5-9265-e9447dc90c1f.png)


Собственно, страница топика не открывается.

**Comment by inliquid** [comment]
Сам блог тоже не отображается.

**Comment by aVadim483** [comment]
Внес исправления, проверил на разных правах доступа - работает
