### ISSUE TITLE
Подписка на блог с типом подписки "по запросу" не работает

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#480]
Администраторы и модераторы не получают запроса.

[LOG:1428105298.968-551F2852EC4F3][2015-04-04 02:54:58][PID:2372][ERROR][[
E_NOTICE [8] Object of class ModuleBlog_EntityBlogUser could not be converted to int (/var/www/example.com/common/classes/modules/talk/Talk.class.php on line 85)
--- call stack ---
ModuleTalk->SendTalk() in /var/www/example.com/common/classes/modules/talk/Talk.class.php on line 85
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1867
PluginBlogusers_ActionBlog->Talk_SendTalk() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1867
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2333
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428105298.968-551F2852EC4F3]

[LOG:1428105299.022-551F28530548E][2015-04-04 02:54:59][PID:2372][ERROR][[
E_RECOVERABLE_ERROR [4096] Argument 1 passed to ModuleNotify::SendBlogUserRequest() must be an instance of ModuleUser_EntityUser, array given (/var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391
ModuleNotify->SendBlogUserRequest()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
PluginBlogusers_ActionBlog->Notify_SendBlogUserRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2333
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428105299.022-551F28530548E]

[LOG:1428105299.035-551F285308743][2015-04-04 02:54:59][PID:2372][ERROR][[
E_WARNING [2] trim() expects parameter 1 to be string, array given (/var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 702)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler()
trim() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 702
PHPMailer->AddAnAddress() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 646
PHPMailer->AddAddress() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 262
ModuleMail->SetAdress()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 554
PluginAutoblog_ModuleNotify->Mail_SetAdress() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 554
ModuleNotify->Send() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 403
ModuleNotify->SendBlogUserRequest()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
PluginBlogusers_ActionBlog->Notify_SendBlogUserRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2333
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428105299.035-551F285308743]

[LOG:1428105299.061-551F28530ED94][2015-04-04 02:54:59][PID:2372][ERROR][[
E_USER_WARNING [512] Cannot send email (/var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320)
--- call stack ---
Func::SysWarning() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320
ModuleMail->Shutdown() in /var/www/example.com/engine/classes/core/Engine.class.php on line 430
Engine->ShutdownModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 412
Engine->ShutdownModules() in /var/www/example.com/engine/classes/core/Engine.class.php on line 314
Engine->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 199
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428105299.061-551F28530ED94]

**Comment by inliquid** [comment]
Не сработало


[LOG:1428153182.494-551FE35E78B9C][2015-04-04 16:13:02][PID:12982][ERROR][[
E_RECOVERABLE_ERROR [4096] Argument 1 passed to ModuleNotify::SendBlogUserRequest() must be an instance of ModuleUser_EntityUser, array given (/var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391
ModuleNotify->SendBlogUserRequest()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
PluginBlogusers_ActionBlog->Notify_SendBlogUserRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2334
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428153182.494-551FE35E78B9C]

[LOG:1428153182.530-551FE35E815D3][2015-04-04 16:13:02][PID:12982][ERROR][[
E_WARNING [2] trim() expects parameter 1 to be string, array given (/var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 702)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler()
trim() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 702
PHPMailer->AddAnAddress() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 646
PHPMailer->AddAddress() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 262
ModuleMail->SetAdress()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 554
PluginAutoblog_ModuleNotify->Mail_SetAdress() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 554
ModuleNotify->Send() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 403
ModuleNotify->SendBlogUserRequest()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
PluginBlogusers_ActionBlog->Notify_SendBlogUserRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1872
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2334
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428153182.530-551FE35E815D3]

[LOG:1428153182.562-551FE35E8933C][2015-04-04 16:13:02][PID:12982][ERROR][[
E_USER_WARNING [512] Cannot send email (/var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320)
--- call stack ---
Func::SysWarning() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320
ModuleMail->Shutdown() in /var/www/example.com/engine/classes/core/Engine.class.php on line 430
Engine->ShutdownModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 412
Engine->ShutdownModules() in /var/www/example.com/engine/classes/core/Engine.class.php on line 314
Engine->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 199
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428153182.562-551FE35E8933C]

**Comment by inliquid** [comment]
Вернее не до конца, по крайней мере теперь в личку нужным людям пришел запрос.

**Comment by andrey-v** [comment]
В модуле жёсткая проверка на тип стоит, а како

**Comment by inliquid** [comment]
После последних коммитов если я пытаюсь открыть блог с типом "по запросу" незарегистрированным пользователем, получаю эту ошибку

[LOG:1432497472.311-55622D404BD66][2015-05-24 22:57:52][PID:2373][ERROR][[
E_ERROR [1] Call to a member function isAdministrator() on a non-object (/var/www/example.com/common/classes/modules/blog/Blog.class.php on line 978)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

**Comment by inliquid** [comment]
Если зарегистрированным, то ошибки нет.

**Comment by aVadim483** [comment]
Исправлено этим коммитом: https://github.com/altocms/altocms/commit/3179daa0663ef3b04ad6773569681f172f7dd58d

**Comment by inliquid** [comment]
Как же исправлено, когда при попытке подписаться на блог у которого есть 1 администратор, 1 модератор

[LOG:1433972590.924-5578AF6EE18DB][2015-06-11 00:43:10][PID:12902][ERROR][[
E_RECOVERABLE_ERROR [4096] Argument 1 passed to ModuleNotify::SendBlogUserRequest() must be an instance of ModuleUser_EntityUser, array given (/var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 391
ModuleNotify->SendBlogUserRequest()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1904
PluginBlogusers_ActionBlog->Notify_SendBlogUserRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1904
ActionBlog->SendBlogRequest() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 2366
ActionBlog->AjaxBlogJoin()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

**Comment by aVadim483** [comment]
...я пытаюсь **открыть** блог...
...при попытке **подписаться** на блог...

Не находите, что это разные действия и разные ошибки?

**Comment by inliquid** [comment]
А вы целиком не пробовали читать проблему?
Я не имею обыкновения в каждом комментарии повторять всю предысторию.

**Comment by inliquid** [comment]
Кстати после обновления страницы юзер получил доступ к блогу даже несмотря на то что никто запрос не подтверждал.

**Comment by inliquid** [comment]
Ой нет прошу прощения. Это я не тем юзером посмотрел. Зато письмо с запросом почему-то пришло в личку тому пользователю, который хотел получить разрешение на доступ.

**Comment by aVadim483** [comment]
>Argument 1 passed to ModuleNotify::SendBlogUserRequest() must be an instance of ModuleUser_EntityUser, array given

Эта ошибка тоже исправлена. Проверил работу блога с подпиской по запросу и с показом контента только подписчикам - ошибок сейчас не возникает, логика работает. Если что-то не так, то опишите подробно по шагам алгоритм, который приводит к ошибке.

**Comment by inliquid** [comment]
Скорее всего отличие моего сценария в том что я специально назначил в блог помимо
- собственно владельца
- 1 администратора
- 1 модератора

чтобы проверить всем ли придет уведомление.

**Comment by inliquid** [comment]
Проверю еще с последним коммитом.

**Comment by inliquid** [comment]
Пользователь, имеющий доступ к топикам закрытого блога не видит их же в избранном другого пользователя.

**Comment by aVadim483** [comment]
Последний коммент вынес в отдельный тикет https://github.com/altocms/altocms/issues/611
