### ISSUE TITLE
Не минифицируются ни CSS ни JS файлы

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#481]
Только что обнаружил удивительную вещь, минификации объединяемых файлов нет вообще, несмотря на настройку. Все идет ровно в том виде, как оно лежит на диске, включая комментарии, форматирование, и т.д.

**Comment by aVadim483** [comment]
Не минифицируются файлы, которые имеют двойные расширения .min.css и .min.js, т.к. по названию предполагается, что они уже минифицированы.

**Comment by inliquid** [comment]
Речь идет о самых обычных файлах, без двойных расширений. Например base.css, style.css и т.д.

**Comment by aVadim483** [comment]
Выяснилось, что не минифицировались файлы, когда при объединении в один среди них были уже минифицированные, а если точнее - файлы с расширением min.js или mib.css. 

Например, если в один файл объединяются script1.js и script2.mini.js, то результирующий файл не минифицировался.

В 1.1 это исправлено, в 1.0+ исправляться не будет

**Comment by inliquid** [comment]
В версии 1.1 поведение не изменилось. Прошу снова открыть баг.
