### ISSUE TITLE
Перестал работать фотосет

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#486]
Функция загрузки изображений в фотосет просто "отвалилась" - при любой попытке добавить изображение - "Системная ошибка".

В логах

[LOG:1428439909.993-55244365F285A][2015-04-07 23:51:49][PID:19002][ERROR][[
E_WARNING [2] move_uploaded_file(): Unable to move '/tmp/phpVmJusx' to '/var/www/example.com/_tmp/cache/uploads/471ef03c.JPG' (/var/www/example.com/engine/include/functions/File.php on line 1017)
--- call stack ---
move_uploaded_file() in /var/www/example.com/engine/include/functions/File.php on line 1017
AltoFunc_File::MoveUploadedFile()
call_user_func_array() in /var/www/example.com/engine/include/Func.php on line 349
Func::__callStatic() in /var/www/example.com/common/classes/modules/uploader/Uploader.class.php on line 269
F::File_MoveUploadedFile() in /var/www/example.com/common/classes/modules/uploader/Uploader.class.php on line 269
ModuleUploader->UploadLocal()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/topic/Topic.class.php on line 2678
PluginTopicintro_ModuleTopic->Uploader_UploadLocal() in /var/www/example.com/common/classes/modules/topic/Topic.class.php on line 2678
ModuleTopic->UploadTopicPhoto()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionContent.class.php on line 911
PluginTopicintro_ActionContent->Topic_UploadTopicPhoto() in /var/www/example.com/common/classes/actions/ActionContent.class.php on line 911
ActionContent->EventAjaxPhotoUpload()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

И так на каждый файл. В /tmp при этом ничего не было.

Вылечилось перезапуском мемкеша и чисткой директорий _tmp и _run

**Comment by aVadim483** [comment]
>Unable to move '/tmp/phpVmJusx' to '/var/www/example.com/_tmp/cache/uploads/471ef03c.JPG' 

PHP функция move_uploaded_file() по каким-то причинам не смогла переместить загруженный файл из системной tmp-директории. Раз директория /tmp была пустой, то очевидно, что переместить файл было невозможно из-за его отсутствия. А почему вдруг после загрузки файла его не оказалось в /tmp, и как на это могла повлиять перезагрузка мемкеша - совершенно непонятно, я не могу найти тут связи. Но проблема явно на стороне сервера, поэтому тикет закрываю.

**Comment by inliquid** [comment]
Так. Чистка мемкеша и директорий _tmp _run это просто альтернатива сброса кеша из админки. Поскольку мне неведомом что при этом происходит и в некоторых ситуациях этого почему-то оказывается недостаточно, я иногда прибегаю к такому способу чтобы быть увереным в том что кеш чист. Больше ничего не делалось на сервере. 

Т.о. сброс кеша привел к тому что ошибка ушла. проблема ЯВНО в движке.

**Comment by aVadim483** [comment]
Я опираюсь на описание проблемы, которое Вы дали:
>В /tmp при этом ничего не было.

При загрузке файла с помощью PHP он грузится в /tmp (или в иную директорию, которая назначена настройками сервера). Это делает НЕ движок, это делает PHP. И, как правило, доступа к этой директории из PHP-скриптов нет, а из движка уж точно даже попыток не делается, кроме системной функции **move_uploaded_file()**. Т.е., судя по описанию проблемы, PHP (не движок) почему-то размещал загруженные файлы в системной директории /tmp, а после перезагрузки мемкеша стал это делать. Как увязать эти вещи - я даже в теории не могу предположить.

Либо упущены еще какие-то детали проблемы, о которых мы с Вами пока не догадываемся
