### ISSUE TITLE
Error in "Create Topic" in Englisch

### ISSUE THREAD

**Issue by AlexL777** [altocms/altocms#487]
Hello developers of Alto CMS,
I installed their CMS with great interest and I am a failure notice. And if I want to create the front end in the English language a topic, this error message is displayed.

**E_WARNING [2] Can not modify header information - headers already sent by (output started at /www/htdocs/w0103f82/cms/altocms/common/templates/language/actions/admin/en.php:1)
See details in error.log**

I am a German users of AltoCMS and blogging in German, would like to continue using this CMS. Maybe you can watch this error message again and fixed it.
I would be very grateful in advance.

**Comment by klaus-spb** [comment]
May be you make changes in this file and save it not in "UTF8 (without BOM)" ?

**Comment by aVadim483** [comment]
Do you resolve your problem?

**Comment by aVadim483** [comment]
I think it's allright, so I close the issue
