### ISSUE TITLE
Ошибка SQL при переходе к топикам, на которые подписан юзер

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#488]
Проводил тесты ленты (на тестовом сервере) подписываясь произвольно пользователем на ленту.
Вот что вылезло (это при заходе в ленту соответственно)
```
[LOG:1428663569.510-5527AD117C835][2015-04-10 13:59:29][PID:2373][ERROR][[
E_WARNING [2] mysqli::query(): (22003/1690): BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)' (/var/www/example.com/engine/libs/DbSimple3/lib/DbSimple/Driver/Mysqli.php on line 116)
--- call stack ---
mysqli->query() in /var/www/example.com/engine/libs/DbSimple3/lib/DbSimple/Driver/Mysqli.php on line 116
DbSimple_Driver_Mysqli->_performQuery() in /var/www/example.com/engine/libs/DbSimple3/lib/DbSimple/Database.php on line 570
DbSimple_Database->_query() in /var/www/example.com/engine/libs/DbSimple3/lib/DbSimple/Database.php on line 193
DbSimple_Database->selectPage()
call_user_func_array() in /var/www/example.com/engine/libs/DbSimple3/lib/DbSimple/Connect.php on line 120
DbSimple_Connect->selectPage() in /var/www/example.com/common/classes/modules/subscribe/mapper/Subscribe.mapper.class.php on line 271
ModuleSubscribe_MapperSubscribe->GetTracks() in /var/www/example.com/common/classes/modules/subscribe/Subscribe.class.php on line 311
ModuleSubscribe->GetTracks()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/userfeed/Userfeed.class.php on line 119
ModuleUserfeed->Subscribe_GetTracks() in /var/www/example.com/common/classes/modules/userfeed/Userfeed.class.php on line 119
ModuleUserfeed->Trackread()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionUserfeed.class.php on line 126
ActionUserfeed->Userfeed_Trackread() in /var/www/example.com/common/classes/actions/ActionUserfeed.class.php on line 126
ActionUserfeed->EventTrackNew()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1428663569.510-5527AD117C835]```

**Comment by inliquid** [comment]
SQL лог



[LOG:1428664496.894-5527B0B0DA5BB][2015-04-10 14:14:56][PID:2372][ERROR][[
SQL Error: BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)' at /var/www/example.com/common/classes/modules/subscribe/mapper/Subscribe.mapper.class.php line 271
---
Array
(
    [code] => 1690
    [message] => BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)'
    [query] => SELECT SQL_CALC_FOUND_ROWS
                                        *
                                FROM
                                        alto_track trc
                                WHERE
                                        1 = 1
                                          AND trc.target_type = 'topic_new_comment'

                                          AND trc.user_id = 3


                                          AND trc.status = 1
                                          AND exists   (  SELECT 1
                                                          FROM   alto_topic_read as tr,
                                                                 alto_topic as t
                                                          WHERE   t.topic_id = trc.target_id
                                                          AND t.topic_id = tr.topic_id
                                                          AND (t.topic_count_comment - tr.comment_count_last) > 0
                                                          AND  tr.user_id = trc.user_id
                                                          )
                                ORDER by  date_add desc
                                LIMIT 0, 10 ;

    [context] => /var/www/example.com/common/classes/modules/subscribe/mapper/Subscribe.mapper.class.php line 271
)

]][END:1428664496.894-5527B0B0DA5BB]

**Comment by klaus-spb** [comment]
а попробуйте в запросе поменять 
```sql
AND (t.topic_count_comment - tr.comment_count_last) > 0
```
на 
```sql
AND (cast(t.topic_count_comment as signed) - cast(tr.comment_count_last as signed)) > 0
```

**Comment by inliquid** [comment]
Ага сработало. Сделаешь pull request?

**Comment by klaus-spb** [comment]
Если Вадим даст добро, поскольку на postgre эта конструкция может не работать, а проверить мне не на чем

**Comment by inliquid** [comment]
Postgres разве из коробки поддерживается?

**Comment by aVadim483** [comment]
Все гораздо проще - нужно прямо в базе привести эти два поля к одному виду. Точнее,. поле comment_count_last в таблице prefix_topic_read привести к int(11) unsigned:
```
ALTER TABLE  `prefix_topic_read` 
CHANGE  `comment_count_last`  `comment_count_last` INT( 11 ) UNSIGNED NOT NULL DEFAULT  '0';
```
И никаких доработок кода не потребуется. Это мелкий баг БД

И да, весь SQL-код в коробке приведен к виду, который переваривается Постгрессом, и поддержка Постгресс-драйвера из коробки присутствует. Так что поддержка Постгресса из коробки есть, за исключением установки движка.

**Comment by inliquid** [comment]
>Точнее,. поле comment_count_last в таблице prefix_topic_read привести к int(11) unsigned:

Что-то я не очень понял, в чем отличие?

![1](https://cloud.githubusercontent.com/assets/6797881/7140972/42361874-e2d7-11e4-9b85-2e6f6c7959de.png)

**Comment by aVadim483** [comment]
А это точно с этой базой были проблемы? Я посмотрел - у меня там было int(10). И это как раз и может вызывать подобную ошибку.

Второй вариант, отчего такое может быть - значение prefix_topic.topic_count_comment по каким-то причинам меньше, чем prefix_topic_read.comment_count_last, и, в результате, получается отрицательное число

**Comment by aVadim483** [comment]
Если имеет место второй вариант, то должно помочь такое исправление:
```
AND (t.topic_count_comment > tr.comment_count_last)
```
И оно будет универсальным с точки зрения диалектов SQL (т.е. с любым SQL-движком будет работать)

**Comment by inliquid** [comment]
С этой базой совершенно точно. Могла быть причина в том, что удалялись пользователи?

**Comment by aVadim483** [comment]
Не готов ответить наверняка, но возможно. В любом случае, если исправления, которые я выше дал, помогут, то внесу их в движок

**Comment by inliquid** [comment]
Я не могу больше проверить т.к. с тех пор как исправление от Николая сработало - уже все снова отмечено как прочитанное и пока больше не вылезала такая проблема. то случилось на тестовом сервере, на основном пока такого не было ни разу.

**Comment by aVadim483** [comment]
Понял, попробую смоделировать у себя

**Comment by inliquid** [comment]
На последней версии 1.0.x проблема осталась


E_WARNING [2] mysqli::query(): (22003/1690): BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)'
See details in error.logSQL Error: BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)' at /var/www/example.com/common/classes/modules/subscribe/mapper/Subscribe.mapper.class.php line 271 --- Array ( [code] => 1690 [message] => BIGINT UNSIGNED value is out of range in '(`alto`.`t`.`topic_count_comment` - `alto`.`tr`.`comment_count_last`)' [query] => SELECT SQL_CALC_FOUND_ROWS * FROM alto_track trc WHERE 1 = 1 AND trc.target_type = 'topic_new_comment' AND trc.user_id = 9 AND trc.status = 1 AND exists ( SELECT 1 FROM alto_topic_read as tr, alto_topic as t WHERE t.topic_id = trc.target_id AND t.topic_id = tr.topic_id AND (t.topic_count_comment - tr.comment_count_last) > 0 AND tr.user_id = trc.user_id ) ORDER by date_add desc LIMIT 0, 10 ; [context] => /var/www/example.com/common/classes/modules/subscribe/mapper/Subscribe.mapper.class.php line 271 ) 


Можно такое же исправление добавить в репозиторий?
