### ISSUE TITLE
Необходимо исключить влияние тормозного yandex share

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#489]
Из-за того что yandex share дико тормозит и отвечает по полминуты, периодически не происходит переходов по ссылке на комментарий #comment<NNN>, или происходит с паузой. Необходимо как-то исключить его влияние, если возможно.

**Comment by inliquid** [comment]
Удалось частично решить проблему. Ну хотя как решить, чуть менее отвратительно работает - если отключить счетчики внутри блока yashare, т.е. это фактически частичный отказ от него.
 
Но теперь выявилась другая проблема - все равно не получается нормально перейти к комментарию, например из виджета "прямой эфир" по ссылке #commentNNN. Раньше я думал проблема в том, что висит загрузка яндекса, она не дает. Но похоже что дело в чем-то еще. Если после перехода по ссылке на комментарий, поставить курсор в адресную строку и нажать enter, то переход получается нормальным. Но при заходе по ссылке например с главной - только иногда. А большую часть времени, открывается или какой-то участок ленты комментариев, не всегда на искомом. Или вообще середина топика. Такое ощущение что не успевает прогрузиться чтоли содержимое... но в любом случае середина топика это странно.

**Comment by inliquid** [comment]
В общем какая-то странная тема с переходом на комментарий. Сейчас cмотрю с другого компа — такого поведения не наблюдаю, различие одно — тот комп за которым я сейчас довольно-таки топовый по производительности, а предыдущий слегка послабее (но тоже не каменный век — низковольный i7 + 8 ГБ RAM) ((((

**Comment by inliquid** [comment]
Нет производительность тут не при чем, сейчас на том же компе снова наблюдаю этот эффект. Похоже просто в какой-то момент что-то "ломается". Что начинает мешать работу перехода по ссылке на комментарий. Какой-то Js?

**Comment by aVadim483** [comment]
В общем, проблема не в том, что Yandex share тормозит, а в том, что переход на комментарий по якорю #commentNNN не происходит, так?

**Comment by inliquid** [comment]
Yandex share на самом деле тормозит если используется версия с подгрузкой счетчиков, но страница успевает загрузиться, просто долго висит индикатор обновления (крутилка).
А так, все верно, почему-то в какой-то момент начинаются глюки с переходом по якорю на комментарий.

**Comment by shtrih** [comment]
Ну, ссылки на внешние скрипты, которые не очень важны для работы сайта, можно было бы добавлять с атрибутом `async`. Однако, в текущей реализации такой возможности нет.

**Comment by inliquid** [comment]
Неа пробовал, не помогает.

**Comment by aVadim483** [comment]
В будущих версиях будет поддержка атрибутов `async` и `defer`. Сейчас яндексовский share.js втыкается в самый конец страницы, поэтому, если он по каким-то причинам тормозит, то формально загрузка страницы как бы еще идет, но по факту HTML уже полностью загружен. Повлиять на share.js мы, увы, не можем.

Что касается переходя к якорю #commentNNN, то иногда я замечал такую проблему, но пока не смог ее гарантировано воспроизвести, поэтому пока не могу сказать, в чем там причина, и куда копать для ее решения.
