### ISSUE TITLE
Не работает определение активного плагина

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#491]
Почему-то не работает эта конструкция

`{if E::ActivePlugin("myplugin")}
Блабла
{/if}
`

**Comment by aVadim483** [comment]
в 1.0 проблем не обнаружено, в 1.1 исправлено - https://github.com/altocms/altocms/commit/1598bccf1e1dcdc9056c9f8c0958c71fe8a9e1e6

**Comment by inliquid** [comment]
лол
