### ISSUE TITLE
Глюк вывода изображений в фотосет

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#499]
Периодически наблюдаю такую картинку.

![3](https://cloud.githubusercontent.com/assets/6797881/7209647/3ece8bde-e553-11e4-835b-53157d73f7e1.png)

Браузер FF. но я в основном только им пользуюсь.

**Comment by andrey-v** [comment]
Сетка фотосета формировалась раньше, чем успевали подгружаться изображения и ширина элементов фотосета рассчитывалась ошибочно.
