### ISSUE TITLE
Вылезла странная ошибка связанная с отправкой почты

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#500]
Встречается всего несколько раз, 17 апреля. С сервером ничего не делали, вообще не трогали. Движок тоже. Я никаких проблем с работой сайта не заметил. В syslog все чисто.

[LOG:1429301585.687-55316951A7B09][2015-04-17 23:13:05][PID:24444][ERROR][[
E_WARNING [2] mail(): Could not execute mail delivery program '/usr/sbin/sendmail -t -i ' (/var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 542)
--- call stack ---
call_user_func() in /var/www/example.com/engine/libs/Smarty/libs/Smarty.class.php on line 1547
Smarty::mutingErrorHandler()
mail() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 542
PHPMailer->mail_passthru() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 979
PHPMailer->MailSend() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 883
PHPMailer->PostSend() in /var/www/example.com/engine/libs/phpMailer/class.phpmailer.php on line 802
PHPMailer->Send() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 231
ModuleMail->Send()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 558
PluginAutoblog_ModuleNotify->Mail_Send() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 558
ModuleNotify->Send() in /var/www/example.com/common/classes/modules/notify/Notify.class.php on line 144
ModuleNotify->SendCommentReplyToAuthorParentComment()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1354
PluginBlogusers_ActionBlog->Notify_SendCommentReplyToAuthorParentComment() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1354
ActionBlog->SubmitComment() in /var/www/example.com/common/classes/actions/ActionBlog.class.php on line 1206
ActionBlog->AjaxAddComment()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

[LOG:1429301585.774-55316951BD197][2015-04-17 23:13:05][PID:24444][ERROR][[
E_USER_WARNING [512] Cannot send email (/var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320)
--- call stack ---
Func::SysWarning() in /var/www/example.com/engine/classes/modules/mail/Mail.class.php on line 320
ModuleMail->Shutdown() in /var/www/example.com/engine/classes/core/Engine.class.php on line 430
Engine->ShutdownModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 412
Engine->ShutdownModules() in /var/www/example.com/engine/classes/core/Engine.class.php on line 314
Engine->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 199
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

Прошло 2 дня - пока больше таких сообщений не появлялось.

**Comment by aVadim483** [comment]
Класс phpMailer не смог отправить почту по этой причине: 
Could not execute mail delivery program '/usr/sbin/sendmail -t -i '

По-моему, это были какие-то проблемы сервера

**Comment by inliquid** [comment]
В том то и дело что ничего не было. Проблема самопоявилась и самоустранилась. В порядке фантазии могу только предположить что связано с одновременным обращением к sendmail двух php-fpm потоков. (другого пока ничего не приходит)

**Comment by aVadim483** [comment]
В файле class.phpmailer.php в строке 542:
```
$rt = @mail($to, $this->EncodeHeader($this->SecureHeader($subject)), $body, $header, $params);
```
Т.е. если б не перехват ошибок, то оно вообще не вылезло бы в лог, вернуло бы false и все. И, честно говоря, не очень хорошо представляю, как там оно на системном уровне устроено, и что происходит, если конкурентные запросы к sendmail идут. Поэтому нет никаких мыслей, куда копать.

Но вот что стоит "взять на подумать", так это отработку таких ситуаций на уровне движка. - в идеале, если письмо не отправлено, то его, возможно, стоит сохранить и повторить попытку позже.

**Comment by inliquid** [comment]
Отлично - не знаем в чем причина, закрыть! Раньше хоть время тянули, прежде чем закрывать. Создавалось иллюзия что кто-то что-то делает)))

**Comment by aVadim483** [comment]
В чем причина - непонятно, как воспроизвести - непонятно. Проблема приключилась только однажды и больше не повторяется. Все предположения только на уровне фантазий. Хотя гугление навскидку дает еще одно (не фантазийное) предположение, что это может быть связано с нехваткой памяти на сервере: http://goo.gl/04o2TO

И какой смысл держать тикет открытым?
