### ISSUE TITLE
Необходимо исключить из отложенной отправки некоторые события

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#503]
В частности
- Сообщения, отправляемые на оба адреса (старый и новый) в рамках процедуры смены email
- Приглашения на сайт

Эти события должны формировать сообщения к немедленной отправке даже если включен режим отложенной.

**Comment by andrey-v** [comment]
С процедурой смены email согласен, а на счет немедленной отправки приглашений, не уверен. Если это нужно, то (здесь)[https://github.com/altocms/altocms/blob/1.0.x/common/classes/modules/notify/Notify.class.php#L252-L261] можно добавить параметры *null, true* что бы получилось так:
```
public function SendInvite(ModuleUser_EntityUser $oUserFrom, 
                           $sMailTo, 
                           ModuleUser_EntityInvite $oInvite) {

    return $this->Send(
        $sMailTo,
        'invite.tpl',
        E::ModuleLang()->Get('notify_subject_invite'),
        array(
             'sMailTo'   => $sMailTo,
             'oUserFrom' => $oUserFrom,
             'oInvite'   => $oInvite,
        ),
        null,
        true
    );
}
```
и отправка инвайтов будет происходить моментально
