### ISSUE TITLE
Не отображается содержимое во всплывающем окне при наведении на ник пользователя в списке

### ISSUE THREAD

**Issue by can0r** [altocms/altocms#504]
Последняя версия с гит, скин Experience Simple v.1.0.0
![default](https://cloud.githubusercontent.com/assets/7248003/7228660/203fcb16-e764-11e4-9030-8309c355e15e.png)

**Comment by can0r** [comment]
После переключения темы на другую и обратно заработало.

**Comment by aVadim483** [comment]
А переключение тем как выполнялось, в админке? Или просто руками в конфиге?

**Comment by can0r** [comment]
Через админку.

**Comment by aVadim483** [comment]
Воспроизвести эту ошибку так и не получилось (возможно, по какой-то причине кеш не сбросился). Поэтому тикет закрою, но если вылезет опять - пишите
