### ISSUE TITLE
Штатный код сниппета "Спойлер"

### ISSUE THREAD

**Issue by can0r** [altocms/altocms#505]
Последняя версия с гит, скин Experience Simple v.1.0.0, визуальный редактор.
1. При использовании предпросмотра спойлер не срабатывает.
2. Невозможно корректно редактировать текст внутри спойлера после вставки. Переход строки происходит только по Shift+Enter; если нажать Enter между нескольких строк - разбивает содержимое на несколько спойлеров; на одной строке по Enter курсор переходит из спойлера на следующую строку.
3. Невозможно использовать кнопки редактирования на содержимом спойлера("B","I" и остальные).

**Comment by andrey-v** [comment]
2. тут вы для себя на вашем проекте должны решить как будет вести себя редактор: либо делать абзацы тегом ```<p>``` либо переводы строк делать тегом ```<br>```.
- В первом случае любой enter будет преобразован в новый абзац;
- Во втором случае, а такую настройку сделать легко - в файле **(common/templates/frontend/libs/js/engine/settings.js)[https://github.com/altocms/altocms/blob/master/common/templates/frontend/libs/js/engine/settings.js#L121-L125]** указать для tinymce 
```
forced_root_block:  false,
force_p_newlines:   false,
force_br_newlines:  true,
```
Enter не будет разбивать спойлер, а будет переводить строку тегом ```<br>```.

**Comment by andrey-v** [comment]
2 и 3 исправлено
