### ISSUE TITLE
Русские символы при регистрации

### ISSUE THREAD

**Issue by vlad2189** [altocms/altocms#506]
Убедительная просьба!  Добавить возможность при регистрации нового пользователя, использовать русские символы. 

![reg](https://cloud.githubusercontent.com/assets/4673020/7264502/ca3a2d38-e894-11e4-83ff-039d6d0da165.png)

**Comment by inliquid** [comment]
Это настраивается в конфиге.

**Comment by vlad2189** [comment]
Я так полагаю, что вот этот параметр отвечает за настройку:
$config['module']['user']['login']['charset'] = '0-9a-z_\-';  

Тогда вопрос и как же включить русские символы  ?

**Comment by inliquid** [comment]
$config['module']['user']['login']['charset'] = '0-9a-zа-яё_-';

**Comment by vlad2189** [comment]
Спасибо! Но было бы не плохо если это уже было бы прям из "коробки"

**Comment by aVadim483** [comment]
Будет прямо из коробки

**Comment by inliquid** [comment]
Согласен, я даже когда-то топик на эту тему открывал)
