### ISSUE TITLE
Только что обновил на актуальную - ОШИБКА!

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#507]
Писец полный
Жопой чуил что если обновлю, что то будет не хорошее...
Загрузил содержимое  по фтп с заменой файлов.
Получил в ответ загадку и "СТОП САЙТ."
Сайт не работает:
![screenshot_105](https://cloud.githubusercontent.com/assets/7164280/7281765/45c686e6-e934-11e4-9b67-56b077dcbf51.jpg)

**Comment by lsnull** [comment]
Проблема в файле Mresource.mapper.class.php . Только не могу понять что ему не нравится в БД или я ошибаюсь?

**Comment by aVadim483** [comment]
В сообщении об ошибке говорится о том, что индексный файл базы сломался

**Comment by lsnull** [comment]
так до обновления ничего не ломалось. все работало отлично. У меня стояла 1.1b но за 2-3 дня вы внесли правки в коде. Вот скачал свежую и обновил, после чего получил как вы говорите Сломанную Базу.

**Comment by aVadim483** [comment]
Попробуйте обновиться еще раз

**Comment by lsnull** [comment]
Щас попробую

**Comment by lsnull** [comment]
Спасибо, обновил. Вроде все отлично работает.
