### ISSUE TITLE
Стиль "создать"  в js окне

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#508]
Если длинное название, то не корректно отображаются списки
![screenshot_106](https://cloud.githubusercontent.com/assets/7164280/7283132/02468dc2-e93d-11e4-89a0-1cae75db34d1.jpg)

**Comment by acstrelcova** [comment]
![1](https://cloud.githubusercontent.com/assets/7937467/7284287/35114302-e945-11e4-88d3-6f92b7ae7004.jpg)
пару вариантов возможного решения

**Comment by lsnull** [comment]
как вариант неплохо. главное стобы описание-подсказку мгновенно высвечивало

**Comment by lsnull** [comment]
Почему то в шаблоне 
Experience v.1.0.3  все нормально отоброжается. Без обрезаний
![screenshot_108](https://cloud.githubusercontent.com/assets/7164280/7305457/973213f6-ea06-11e4-9ef1-2a685fbe7d65.jpg)

**Comment by andrey-v** [comment]
Исправлено

**Comment by lsnull** [comment]
Андрей благодарю тебя.
