### ISSUE TITLE
Это проблемма в Шаблоне или Плагине ?

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#509]
Это в  Experience
![screenshot_110](https://cloud.githubusercontent.com/assets/7164280/7328070/1329f990-eadb-11e4-9099-51976410dde5.jpg)
а так отображается в Experience Simple v.1.0.0
![screenshot_109](https://cloud.githubusercontent.com/assets/7164280/7328071/132eb458-eadb-11e4-9109-95abb96f3725.jpg)

**Comment by andrey-v** [comment]
В плагине, плагины пока для шаблона Experience Simple не адаптировались. 
Перенёс задачу в репозиторий плагина

**Comment by lsnull** [comment]
Чуть ошибся. Скриншоты поменять нужно. Наоборот.
