### ISSUE TITLE
Менеджер меню просто убивает после удаления не исчезает на сайте

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#514]
К сожалению я не сделал скриншоты и повторять подобно не буду, так как это долго. А просто постараюсь вам описать досконально проблему.

Создал меню с подменю. "Опросы" и "Голосования" + еще одно меня "Опросы и Ответы".
Пообщавшись с сотрудницей. Решили объединить в "Опросы и Голосования"

Зашел в Менеджер меню ( Редактирование меню) в Меню "Разделы"  что бы отредактировать подменю. Удалил Голосование и опросы, так как редактировать их нельзя после  того как создал. Это конечно 1 ньюанс о котором мы говорили и пришли к тому что не получится сделать так что бы можно было редактировать. Но это не главное. После того как я удалил и создал Одно подменю с названием "Опросы и Голосования" сохранил и когда зашел то в шапке раздела увидел те подменю которые удалил полностью с админки. Они не пропали пока я не нажал на кнопку Удалить  подменю
![screenshot_127](https://cloud.githubusercontent.com/assets/7164280/7338730/155a01cc-ec5e-11e4-803e-284195284b19.jpg)
 и не очистилось все и после заново создал д пункта.

После заметил что не в том порядке выглядит список и решил в админке переставить их местами. Но на сайте порядок остался прежним.

![screenshot_126](https://cloud.githubusercontent.com/assets/7164280/7338732/27817cc2-ec5e-11e4-982e-efe1ae4499c7.jpg)
![screenshot_125](https://cloud.githubusercontent.com/assets/7164280/7338733/2782a3c2-ec5e-11e4-915e-a5610994007c.jpg)
И еще после обновления страницы после сохранения позиций:
![screenshot_128](https://cloud.githubusercontent.com/assets/7164280/7338786/a82b836c-ec5f-11e4-98ab-caddf3fd5eeb.jpg)
в админке позиций все слетает обратно. Возвращается позиция на прежнее место таким порядком, каким были созданы ранее.
 Очень прошу вас разобраться с этим функционалом и исправить основной баг. Спасибо вам большое !

**Comment by andrey-v** [comment]
Исправлено. При обновлении могут быть ошибки из-за уже ошибочных записях в БД. Если они появились, то нужно сбросить кэш и, может быть, вручную удалить записи о меню из таблицы prefix_storage базы данных

**Comment by lsnull** [comment]
опять, только что та же проблемма.
Создал подменю. Сделал скрытым а после решил удалить. В итоге подменю отображается как скрытое непонятно вообще так это должно или это тоже  баг:
![screenshot_139](https://cloud.githubusercontent.com/assets/7164280/7552271/72550d58-f6b4-11e4-858b-16d3d177baa3.jpg)
![screenshot_140](https://cloud.githubusercontent.com/assets/7164280/7552273/725cb85a-f6b4-11e4-86a5-0d3dc5c15661.jpg)
![screenshot_138](https://cloud.githubusercontent.com/assets/7164280/7552272/725c76ec-f6b4-11e4-9128-6c7abf0155ca.jpg)
