### ISSUE TITLE
Ошибка БД

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#519]
При нажатии на пользователя из списка в админке:
![screenshot_129](https://cloud.githubusercontent.com/assets/7164280/7390444/0ffd5f38-ee81-11e4-8035-6e1d5ddc045f.jpg)
получаю ошибку:
![screenshot_130](https://cloud.githubusercontent.com/assets/7164280/7390448/195c7cc6-ee81-11e4-825c-badbfa50851a.jpg)

**Comment by aVadim483** [comment]
База конвертировалась с LS?

**Comment by andrey-v** [comment]
У вас база конвертировалась с LS и почему-то не отработали [вот эти строки](https://github.com/altocms/altocms/blob/master/install/db/convert_1.0.3_to_alto.sql#L283-L285) скрипта преобразования БД.

**Comment by lsnull** [comment]
да конвертировалась

**Comment by lsnull** [comment]
"У вас база конвертировалась с LS и почему-то не отработали вот эти строки скрипта преобразования БД."
Добавил в базу этот запрос. Теперь в профиле ошибки (((((
![screenshot_134](https://cloud.githubusercontent.com/assets/7164280/7478521/21966702-f364-11e4-9663-3086973dd515.jpg)
Как бы мне нормально базу конвертировать? Что бы работало корректно. Могу ли я еще раз как то конвертировать? Или запросом? Ошибку бы эту исправить в первую очередь ))

**Comment by aVadim483** [comment]
А в логах какие ошибки?

**Comment by lsnull** [comment]
я прошу прощение. ошибка была из за плагина referals. отключил его и все нормально
