### ISSUE TITLE
404 ошибка при установки ЧПУ для статьи

### ISSUE THREAD

**Issue by vinznsk** [altocms/altocms#521]
Шаги повторения:

1. В админке настраиваем ЧПУ "blog/%blog_url%/%topic_url%.html"
2. Переходим на статью
3. Устанавливаем собственный адрес страницы 
![222](https://cloud.githubusercontent.com/assets/702948/7404597/dba8db76-ef17-11e4-8923-09b3eef48c8e.png)

4. Нажимаем "сохранить"

Результат: 
![333](https://cloud.githubusercontent.com/assets/702948/7404614/2360ff66-ef18-11e4-9699-6eea66e6964c.png)

Причем простой вариант: %topic_url%.html - работает

**Comment by aVadim483** [comment]
fixed

**Comment by vinznsk** [comment]
Подтверждаю, проблема решена, только вот теперь ошибка на сайте 

E_NOTICE [8] Undefined index: redirect (заменил файл Router.class.php)

**Comment by aVadim483** [comment]
исправлено
