### ISSUE TITLE
досих пор прыгает стиль в шаблоне Experience Simple v.1.0.0

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#522]
Выпадающее меню
![screenshot_132](https://cloud.githubusercontent.com/assets/7164280/7454478/b02f4396-f27c-11e4-906c-9a06f340a1f4.jpg)
![screenshot_131](https://cloud.githubusercontent.com/assets/7164280/7454479/b0306fd2-f27c-11e4-8825-86622b618f3a.jpg)
может сделать отдельный стиль и привязать? А то  с каждым обновлением все больше отступы и шрифт.

**Comment by acstrelcova** [comment]
В главном меню (люди, блоги) размер шрифта 14px. Логично предположить, что в выпадающем меню разделы, которые не поместились, тоже должны быть 14px. Вот предложенный мною код
.dropdown-menu.dropdown-content-menu > li > a {
font-size: 14px !important;
line-height: 2 !important;
}

Возможно при создании топика используется тот же css класс..
