### ISSUE TITLE
Перестала работать кнопка "перенести в черновики" для администраторов блога

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#524]
Раньше, если модератор, или администратор нажимал на кнопку "перенести в черновики" чужого топика, этот топик благополучно переносился в черновики автора. Не уверен что так было задумано с самого начала, но мне такое поведение понравилось. Когда я это обнаружил, я даже стал предлагать пользователям эту фичу как альтернативу удалению. Сегодня обнаружил что фича сломалась. Если обычный пользователь, являющийся администратором или модератором блога нажимает на кнопку "перенести в черновики", получается вот это 

![1](https://cloud.githubusercontent.com/assets/6797881/7455953/2abe65ea-f289-11e4-8097-623e765a594c.png)

**Comment by inliquid** [comment]
Так нашел чем причина, дел ов том что я поставил полю выбора блога свойство disabled чтобы нельзя было его перемещать туда-сюда. Не знаю как это влияет и можно ли что-то сделать чтобы и disabled поле выбора блога и перемещение в черновики работали одновременно?

**Comment by aVadim483** [comment]
Сейчас должно нормально сохраняться, если поле у блога disabled (тогда сохраняется в тот же блог, где и был создан топик). Разумеется, это только при редактировании, при создании топика поле выбора блога не может быть disabled
