### ISSUE TITLE
Проблемы на странице профиля после плагина Рефералы

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#525]
"У вас база конвертировалась с LS и почему-то не отработали вот эти строки скрипта преобразования БД."
Добавил в базу этот запрос. Теперь в профиле ошибки (((((
![screenshot_134](https://cloud.githubusercontent.com/assets/7164280/7478521/21966702-f364-11e4-9663-3086973dd515.jpg)
Как бы мне нормально базу конвертировать? Что бы работало корректно. Могу ли я еще раз как то конвертировать? Или запросом? Ошибку бы эту исправить в первую очередь ))

**Comment by aVadim483** [comment]
Очевидно, что это ошибка плагина
