### ISSUE TITLE
Рейтинг

### ISSUE THREAD

**Issue by acstrelcova** [altocms/altocms#526]
В качестве предложения - включить по умолчанию модуль рейтинга, сейчас не совсем очевидно его присутствие в движке.

**Comment by andrey-v** [comment]
Как считаете, включить нужно плагин [rating](https://github.com/altocms/altocms/tree/master/common/plugins/rating) или достаточно [simplerating](https://github.com/altocms/altocms/tree/master/common/plugins/simplerating)

**Comment by acstrelcova** [comment]
Думаю достаточно simplerating

**Comment by aVadim483** [comment]
@andrey-v в simplerating, мне кажется, надо изменить настройки по умолчанию. Сейчас там при голосовании за топик его рейтинг увеличивается, но т.к. он меньше 1, то юзер видит 0. Что не может не вызывать вопросов у неискушенного юзера. Если уж он simple, то должен быть максимально понятен и прозрачен
