### ISSUE TITLE
Проблемма с загрузкой фото в Топике через Фотосет.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#527]
Ошибку не могу показать так как это надо увидеть на действии, как реагирует и ведет себя.
Ошибки в логах нет.
Не могу понять.
Вкратце опишу так:
Добавил к примеру 3 фото, нажимаю Загрузить. Одна фото просто пропадает а остальные стоят на месте. И все ни какой реакции.

**Comment by lsnull** [comment]
опять из за плагина dev

**Comment by aVadim483** [comment]
Опять? А из-за плагина Dev уже были какие-то проблемы?

**Comment by lsnull** [comment]
вот только эта проблема была замечена из за плагина dev. Но это у меня, может у других  норм. Но все два плагина рефералы и dev влияют на некорректную работу движка ((

**Comment by aVadim483** [comment]
А попробуйте по очереди отключать/включать плагины, чтобы понять, из-за какого конкретно плагина возникают проблемы. Или это проявляется исключительно тогда, когда оба плагина включены?

**Comment by lsnull** [comment]
когда включен плагин dev

**Comment by aVadim483** [comment]
Я бы попросил еще раз перепроверить по такому алгоритму:
1) Отключить все плагины, в т.ч. и плагин Dev
2) Убедиться, что все работает корректно без проблем
3) Включить плагин Dev (только его)
4) Проверить, проявилась ошибка или нет

**Comment by aVadim483** [comment]
Поверили по шагам, как описано выше?

**Comment by aVadim483** [comment]
Поскольку ответа нет, тикет закрываю

**Comment by lsnull** [comment]
я же ответил и небыло возможности зайти

**Comment by lsnull** [comment]
че за бред
