### ISSUE TITLE
не корректно отоброжается стиль с мобильного устройства

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#529]
"Читать дальше"

**Comment by andrey-v** [comment]
А что там не так?
![image](https://cloud.githubusercontent.com/assets/1106990/7544351/e82c3bae-f5d4-11e4-8295-b0732b779277.png)

**Comment by lsnull** [comment]
У меня местами проблеммы. losper.net

**Comment by aVadim483** [comment]
Ну так надо описать конкретно, какие именно проблемы

**Comment by lsnull** [comment]
С отображением кнопки "Читать дальше"

**Comment by aVadim483** [comment]
Еще раз: если Вы действительно хотите, чтобы проблема была решена, то надо описывать ее максимально подробно, а не заставлять вытягивать подробности клещами. Что не так с отображением? Она не отображается? Отображается не в том месте? Цвет не такой? Вышел на Ваш сайт - кнопки на месте, отображаются корректно, проблем не увидел.

Если проблемы все же есть, то дайте подробное описание с скришотами.

**Comment by lsnull** [comment]
Просто с мобильного сюда нельзя загрузить изображение а скриншот был с телефона сделан. Поэтому мне пришлось целую комбинацию сделать что бы было понятней. 
![screenshot_2015-05-08-17-24-53](https://cloud.githubusercontent.com/assets/7164280/7550084/63607d3a-f65c-11e4-932b-649cb9afa49d.png)
хотя все  нормально вроде описал "не корректно отоброжается стиль кнопки Читать дальше с мобильного устройства" значит же отображается но не корректно я же не писал что кнопки нет. или не работает или еще что то нелепое.

**Comment by aVadim483** [comment]
Специальной мобильной версии шаблона нет, это адаптивная верстка, т.е. она подстраивается под ширину окна браузера. Поэтому не обязательно с мобильного экрана скриншоты делать, как правило, достаточно окно браузера уменьшить, чтобы его ширина в пикселях стала сопоставимой с шириной экрана мобильного устройства.

Проблема теперь понятна.

**Comment by lsnull** [comment]
Спасибо )

**Comment by aVadim483** [comment]
@andrey-v надпись на кнопке надо обрезать, а при определенной ширине вообще попробовать заменить ее на символ шевро вправо

**Comment by andrey-v** [comment]
Исправлено, при размере меньше 400px кнопка меняется на меньшую по размеру.
![image](https://cloud.githubusercontent.com/assets/1106990/7745105/488154b8-ffb1-11e4-9a3a-b45af875c60b.png)
