### ISSUE TITLE
У многих шаблонов не работают демо сайты, а у некоторых вообще нет

### ISSUE THREAD

**Issue by Dayron913** [altocms/altocms#530]
http://altocms.ru/addons/item/35/
http://altocms.ru/addons/item/35/
http://altocms.ru/addons/item/24/
http://altocms.ru/addons/item/47/
http://altocms.ru/addons/item/46/
http://altocms.ru/addons/item/46/
http://altocms.ru/addons/item/83/
http://altocms.ru/addons/item/71/
http://altocms.ru/addons/item/55/

У Вас хорошая cms, но такое не вызывает доверия

**Comment by shtrih** [comment]
Шаблоны в каталог добавляются сторонними разработчиками. Поддержка актуальности, работоспособности и совместимости с будущими версиями CMS, ложится на плечи разработчиков шаблонов, а не на разработчиков CMS. С этим ничего не поделаешь.

**Comment by inliquid** [comment]
Не согласен с предыдущим комментарием. Площадка берет комиссию и хоть как-то должна ее оправдывать. Нельзя брать деньги и говорить что содержимое не наша ответственность.

**Comment by shtrih** [comment]
Оправдывает своим существованием.
