### ISSUE TITLE
Ошибка загрузки изображения

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#531]
Как в Топик так и в Профиль. С первого раза загружает без проблем, после решил заменить на другое фото, загружаю и получаю ошибку. В логах поглядел и вот что только нашел:

E_STRICT [2048] Declaration of PluginLs_ModuleViewer::GetSmartyObject() should be compatible with ModuleViewer::GetSmartyObject($aVariables = NULL) (/home/a12051/public_html/common/plugins/ls/classes/modules/viewer/Viewer.class.php on line 14)

Отключал плагин LS Compatibility. Не помогло.

**Comment by aVadim483** [comment]
Ошибку с плагином Ls пофиксил. Но чтоб точно такая же ошибка возникала при отключении плагина - это не может быть в принципе. Если нет плагина, то и отсылки к классу PluginLs_ModuleViewer быть не может.

Короче, нужно обновляться и проверять.

**Comment by lsnull** [comment]
что то с PNG изображениями ему не нравится ((( А в логе ошибки нет

**Comment by aVadim483** [comment]
Ну вот, опять: предлагаете угадывать? Не грузится png вообще? Грузится, но с искажениями? Выдает ошибку во всплывающем окне? Грузится, но через два раза на третий? Какие-то изображения грузятся без проблем, а какие-то конкретные изображения нет?

Уж извиняйте за занудство, но иначе никак

**Comment by lsnull** [comment]
с первого раза  загружаю фото в формате PNG и в верхнем правом углу вылазить уведомление "Ошибка загрузки изображения" Так же с первых попыток и для Топика через редактор и для фото Профиля. не могу загрузить фото и картинки в формате PNG

**Comment by aVadim483** [comment]
Загрузились PNG-картинки в топик и в фотосет без проблем: http://demo.altocms.com/new/21.html
И фото профиля тоже: http://demo.altocms.com/new/profile/admin/

**Comment by lsnull** [comment]
А вот у меня как... (((
![screenshot_157](https://cloud.githubusercontent.com/assets/7164280/7631362/c3f7c676-fa49-11e4-9c11-ef94fc4b239d.jpg)
![screenshot_156](https://cloud.githubusercontent.com/assets/7164280/7631363/c3fbaec6-fa49-11e4-9abd-02a37e1be8e2.jpg)

**Comment by lsnull** [comment]
Вообще непонятно что творится

![screenshot_158](https://cloud.githubusercontent.com/assets/7164280/7631745/cc0e33cc-fa4e-11e4-846e-c28157916072.jpg)

**Comment by aVadim483** [comment]
А другие форматы загружаются - jpg, gif? И в логах пусто?

**Comment by lsnull** [comment]
Загружались. Но теперь пишет  "Систематическая Ошибка" если Jpeg к примеру пытаюсь загрузить в Блог. Аву еще не пробовал сменить. С недели две др новых обновлений грузились все форматы.

**Comment by lsnull** [comment]
Щас попробую обновиться на сегодняшнюю актуальную.

**Comment by aVadim483** [comment]
Пожалуйста, внимательно прочитайте мои вопросы и ответьте на них:

1) До этого Вы писали, что не грузятся фотографии в топик. Теперь пишете, что не можете загрузить аватар блога. Значит ли это, что проблема в топики фотографии теперь загружаются? Или Вы даже не проверяли?

2) Изображения могут загружаться: в тело топика, в фотосет, в комментариях, в профиле пользователя, аватар пользователя, аватар блога. Где именно возникает ошибка с загрузкой фотографий - во всех случаях? В каких-то конкретных? Где-то проходит загрузка или нет?

3) Пробовали ли Вы загружать разные файлы или пытаетесь загрузить один и тот же файл?

4) Появляются ли какие-то новые сообщения об ошибках в логах, если происходит ошибка загрузки изображения, или нет?

**Comment by lsnull** [comment]
1) Проверял.
2) В тело топика и в фотосет, загружаются все кроме PNG
3) Разные пробовал, не загружается только формат "png" в логах нет ничего.
4) Новых не появлялось , только два которые на скриншоте и все.

**Comment by lsnull** [comment]
щас обновил. вроде аватар загрузился в ПНГ

**Comment by aVadim483** [comment]
Создайте тестовый топик, можно в черновиках, и проверьте загрузку в топик и в фотосет, а также в свой профиль. Топик потом удалите, в своем профиле вернете прежнюю фотографию, это же не трудно
