### ISSUE TITLE
Описание фото в фотосете

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#532]
Загрузил фото через Фотосет в Топик и добавил к ним описание, после публикации через время решил отредактировать Топик и заметил, что описание Фото  в поле где было, отсутствует. Но когда просматриваешь Фото в топике как пользователь или гость, Описание есть. Проблема в том, то я не помню к примеру где было и какое было описание если захочу отредактировать.  Такое ощущение что описание к фото и небыло.

**Comment by vinznsk** [comment]
Да, у меня такая же проблема. При открытии на редактирование, описания в фотосете очищаются.

**Comment by andrey-v** [comment]
@lsnull, сейчас на вашем сайте проверил сохранение описания к картинке фотосета. Всё работает. Но такая ошибка может быть в случае когда после добавления описания к картинке вы сразу нажмёте сохранение топика. Дело в том, что описание сохраняется по аяксу при потере фокуса текстовым полем с описанием.

**Comment by andrey-v** [comment]
Проверьте, пожалуйста ещё раз и убедитесь, что описание сохранилось
![image](https://cloud.githubusercontent.com/assets/1106990/7665148/179d4232-fbb3-11e4-8433-49edee0a47b5.png)

**Comment by vinznsk** [comment]
Да, подтверждаю) Если дожидаться появления данного сообщения, то нормально сохраняется. Только вот не всегда оно сразу появляется.

**Comment by andrey-v** [comment]
Исправлено, alt у картинок отображается (если конечно сохранилось описание)
![image](https://cloud.githubusercontent.com/assets/1106990/7676273/7096afb6-fd4a-11e4-89d3-7407b217cef6.png)
![image](https://cloud.githubusercontent.com/assets/1106990/7676287/942ab2c4-fd4a-11e4-8001-518d45ef7f89.png)
