### ISSUE TITLE
Неправильная пагинация в медиаресурсах

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#533]
В админке выводятся не все медиаресурсы. Сейчас выводится последняя страница 38, но это лишь примерно половина содержимого сайта.

**Comment by inliquid** [comment]
Перебором руками дошел до 46 страницы - он последняя.

**Comment by andrey-v** [comment]
Да, действительно. Ошибка и в 1.0 и в 1.1. Количество изображений считает по таблице *prefix_mresources_target*, а выводит из *mresources_target* и если объект (там топик, комментарий...) был удалён, то количество не совпадает.
