### ISSUE TITLE
Вывод количества в "Новых" +

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#537]
Пишет +2 Новых но ничего нет и после когда добавляю Другие Статьи или пишут Пользователи, То плюсуются еще +2 которых нет  В итоге не правильное значение.
у меня только так? Как исправить?
![screenshot_153](https://cloud.githubusercontent.com/assets/7164280/7598468/14efa5e6-f903-11e4-9b7c-b4f17fba99f0.jpg)

**Comment by aVadim483** [comment]
Что значит "ничего нет"? Когда переходите на вкладку "Новые", то вообще в ленте нет ни одного топика?

**Comment by inliquid** [comment]
У меня тоже неправильно считает, уже обращал внимание (сверял с параметров конфиге). Правда такого чтобы покказывало что есть топики когда их нет не припомню.

**Comment by aVadim483** [comment]
Вот, добавил новый топик: http://demo.altocms.com/new/index/new/
В новых +1 и в ленте 1 топик, как положено.

**Comment by klaus-spb** [comment]
Насколько я могу судить топики из персональных блогов считаются повторно при подсчете топиков в коллективных блогах.
А проблема похоже в GetNamedFilter в Topic.class.php из-за фильтра коллективных блогов. Задан 'personal' => false, но такой параметр не фильтруется. Могу ошибаться

**Comment by klaus-spb** [comment]
Собственно вот, http://demo.altocms.com/new/index/new/ если опубликовать в персональном, то стало 3 вместо 2

**Comment by aVadim483** [comment]
Суть понял, проверю

**Comment by aVadim483** [comment]
В общем, там получается так: счетчик показывает общее число новых топиков, как в общих блогах, так и в персональных, а в ленте выводятся только из общих. Значит, нужно либо в счетчике показывать только общие, либо выводить в ленте все.

**Comment by inliquid** [comment]
Моя проблема с этим не была связана у меня нет "персональных" блогов. Но считалось некорректно.

**Comment by lsnull** [comment]
Если честно я не совсем понял ) Но считает не корректно. Так как быть, самому править или это пофиксите?
Вот щас пишет +4 а на самом деле в Новых всего 3 новых Топика. То бывает показывает +4 Новых а когда заходишь в "Новые" , то там всего 2-а.... я хз как правильно это сказать умными словами )

**Comment by klaus-spb** [comment]
Вадим нет, в новых выводятся и персональные. На демо же виден мой топик из персонального

Там все сложно
Вот фильтр записей в коллективных доступных блогах в GetCountTopicsByFilter

```php
Array
(
    [topic_publish] => 1
    [topic_new] => 2015-05-12 21:00:00
    [blog_type] => Array
        (
            [1] => open
            [*] => Array
                (
                    [0] => 1
                    [1] => 2
                )

        )

)
```
Тут вроде все логично, тип блога, идентификаторы доступных блогов. НО blog_type пишется в отдельную переменную https://github.com/altocms/altocms/blob/master/common/classes/modules/topic/Topic.class.php#L1263 делается потом unset. А поскольку у нас есть запись с * то идентификаторы блогов пишут в другую переменную https://github.com/altocms/altocms/blob/master/common/classes/modules/topic/Topic.class.php#L1265 И так как идентификаторы у нас заполнены проходит проверка https://github.com/altocms/altocms/blob/master/common/classes/modules/topic/Topic.class.php#L1285
```php
if ($aBlogsId) {
                $aFilter['blog_id'] = $aBlogsId;
                $aFilter['blog_type_exclude'] = $aBlogsType;
                $iCount = $this->GetCountTopicsByFilter($aFilter);
                $iResult += $iCount;
            }
```
Т.е. вот к примеру есть сайт где есть только один персональный топик. Первая выборка вернет personal 1 запись. И в список записей из коллективных не попадет. Но мы попадем в данное условие и в итоге будет плюсовать сюда же записи из персональных блогов. blog_type у нас магически превращается в blog_type_exclude
```php
Array
(
    [topic_publish] => 1
    [topic_new] => 2015-05-12 21:00:00
    [blog_id] => Array
        (
            [0] => 1
            [1] => 2
        )

    [blog_type_exclude] => Array
        (
            [1] => open
        )

)
```

Думаю человеку писавшему виднее. Потому что у меня уже крыша подтекает с фильтрами фильтров

**Comment by lsnull** [comment]
Все топики и персональные и просто опубликованные в Блог из списка предоставленных для пользователей. Но они все открыты. А подсчет неверный

**Comment by aVadim483** [comment]
@klaus-spb Да, это я поспешил с выводами. А фильтры становятся все сложнее, т.к. условий всяческих становится все больше и больше - тут и типы блогов, и типы контента, и вариативность прав доступа...

Но поправил маппер блогов, сейчас на демосайте счетчик показывает верно. Добавил пару топиков - в общий блог и в персональный, считает корректно.

**Comment by aVadim483** [comment]
@lsnull Да, на демосайте тоже был неверный подсчет. После последних обновлений проблема решилась (неверно выполнялась выборка блогов, из которых юзер мог читать топики)
