### ISSUE TITLE
Первые проблеммы при сегодняшнем обновлении

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#538]
Просто жесть...
В админке не видно настройки Категорий и категории. Но на сайте они отоброжаются.
Не корректно отображается стиль на скриншоте в вып. меню. При создании Типа топика.
![screenshot_161](https://cloud.githubusercontent.com/assets/7164280/7632337/c5ec5bb2-fa54-11e4-9a55-5309c1aac13a.jpg)

После того как создал Подменю в меню topics/ испортились названия других подменю и не корректно отображается название другого. (умножилось) и изменились ссылки на "Array"
![screenshot_160](https://cloud.githubusercontent.com/assets/7164280/7632318/8836968e-fa54-11e4-9d85-2d8613460d2f.jpg)

**Comment by aVadim483** [comment]
После обновления очищали кеш?

**Comment by lsnull** [comment]
Ага

**Comment by lsnull** [comment]
Синий цвет пропал. Но все другое осталось прежним

**Comment by aVadim483** [comment]
>В админке не видно настройки Категорий

Вообще такого пункта меню не видите в админке "Категории блогов"?

**Comment by aVadim483** [comment]
Видите в админке этот пункт меню?
![default](https://cloud.githubusercontent.com/assets/2246758/7634879/63b32edc-fa66-11e4-8f6b-bb6c42514249.JPG)

**Comment by lsnull** [comment]
![screenshot_167](https://cloud.githubusercontent.com/assets/7164280/7634921/a2671a76-fa66-11e4-9813-0a071a238ca6.jpg)

**Comment by lsnull** [comment]
Я только заметил на скриншоте, что отсутствует Фраза.

**Comment by aVadim483** [comment]
Какой-нибудь кеш на сайте используется?

**Comment by lsnull** [comment]
Кеш отключен вроде как. По умолчанию отключен? Если да то и у меня тогда.

**Comment by lsnull** [comment]
Я устал уже ) Можно как то оставить базу mysql актуальную. И заново установить Альто 1.1b???

**Comment by lsnull** [comment]
Вернул обратно на свежее обновление, почистил кеш. Но Выделение подменю синим осталось.

**Comment by lsnull** [comment]
вот еще. 
![screenshot_168](https://cloud.githubusercontent.com/assets/7164280/7635548/4b955da8-fa6a-11e4-8eae-5739b56212c2.jpg)

**Comment by aVadim483** [comment]
синий пропал... синий остался... вернул обратно на свежее обновление... - я уже теряю нить, чего Вы делеате и какие у Вас проблемы пропадают, а какие остатются

**Comment by lsnull** [comment]
№1 В админке не видно Фразы "Категории"  плагин 1.1.4 новее не ставил , так как стиль его не соответствует размерам шаблона как шрифта так и вывода аватары раздела .

№2  Выпадающее меню "Еще" отображается практически нормально если не считать то, что размер шрифта в выпадающем меню больше чем по всем меню шаблона.

№3 ( сбросил все меню по умолчанию. Только так фразы появились.
Но это ненормально, что такой манипуляцией я смог исправить после обновления.)
После мне все занаво пришлось дабовлять как фильры так и теги для ссылок в меню и собственного  подменю

**Comment by aVadim483** [comment]
п.1 - с версией 1.1.5 плагина "Категории" проблем не обнаружено. Версия 1.1.4 уже неактуальна, тестировать с ней не имеет смысла.

п.2 - проверил у себя, проверил у вас на сайте - размер шрифта во всех пунктах верхнего меню - 14px, размер в выпадающем списке - тоже 14px, т.е. проблем тоже не обнаружено.

п.3 - в админке вошел в "Редактирование меню", добавил на тестовом сайте еще один пункт в подменю "Обсуждаемые" - пункт добавился, ошибок не возникло. Опишите, пожалуйста, подробно по шагам, что делаете, и что получается в результате. И обязательно - перед изменением меню удалите лог файл (или скопируйте его в другое место) и после изменений меню проверьте, не появляются ли новые ошибки в логе. Если появляются, то обязательно о них сообщите

**Comment by aVadim483** [comment]
Я правильно понимаю, что пункты 2 и 3 работают сейчас без проблем?
