### ISSUE TITLE
Все теже баги с Меню и Подменю в Админке и выводом на сайте.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#539]
После удаления Подменю в Созданном меню в Админке. на сайте отображаются все равно. Пока в админке не сделаешь сброс Меню. Нет смысла создавать Меню и подменю так как практически все время там проблемы и нужно все сбрасывать и заново создавать кучу ссылок. Лично я устал от этого. Опять щас нужно все заново вручную вбивать.

**Comment by lsnull** [comment]
Оказалось еще  проблемка. Нажал удалить 
![screenshot_162](https://cloud.githubusercontent.com/assets/7164280/7632491/5897c248-fa56-11e4-9853-b860f77749c4.jpg)
Обновляю Админку а Меню появились снова. Только не по ссылке  к примеру my.site/filter/poll а совсем непонятной с Arry и без Фильтра

**Comment by aVadim483** [comment]
Дублирование https://github.com/altocms/altocms/issues/538
Поэтому закрываю
