### ISSUE TITLE
Баг на баге. После удаления подменю в меню HELP! Не работают ссылки Меню!.

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#540]
Удалил через Админку в "Менеджер меню" .topics  (/settings-menumanager/edit/topics/), Подменю,  Через Удалить все" Так как если вручную удалять по одному они появлялись обратно. Но теперь вот такая проблема
![screenshot_164](https://cloud.githubusercontent.com/assets/7164280/7632560/ffe4a0d4-fa56-11e4-8cce-5b476cd3a6b9.jpg)

![screenshot_165](https://cloud.githubusercontent.com/assets/7164280/7632601/6210c526-fa57-11e4-861d-7a6b7bba7670.jpg)

Нужна срочная помощь
Кароче там полный ппц. Все стало Arry
![screenshot_166](https://cloud.githubusercontent.com/assets/7164280/7632661/e38727ee-fa57-11e4-8b2e-52c7b83b01f6.jpg)

не работает меню - ссылки! Сайт рабочий. HELP!!!

http://losper.net

**Comment by lsnull** [comment]
Вообщем, молчание. Придется попробовать сделать обратно замену файлов с ранней скаченой актуальной версии.

**Comment by lsnull** [comment]
Заменил. Обновил кеш но Проблема не исчезла. Походу что то уже и с базой. Я не знаю и не сильно в этом разбираюсь. Но жду вашей помощи и исправления. Спасибо!

**Comment by aVadim483** [comment]
Вы несколько тикетов оформили, я занимаюсь ими по порядку. У меня нет копии Вашего сайта, чтобы моментально получить результат, на воспроизводство и анализ проблем требуется время. Тем более, что описания проблем у Вас довольно путанные, не всегда все сразу понятно

**Comment by aVadim483** [comment]
Дублирование https://github.com/altocms/altocms/issues/538
Поэтому закрываю
