### ISSUE TITLE
Иногда слетает пользовательская сессия

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#541]
Раньше тоже такое случалось но я был не уверен что случайно не разлогинился. Сейчас совершенно точно. Было не менее 2 пользовательских сессий. Разлогинился с телефона в результате слетела авторизация на ПК.

**Comment by inliquid** [comment]
Кеш включен (мемкеш), solid=false. Максимальное число пользовательских сессий на пользователя = 50.

**Comment by aVadim483** [comment]
>Разлогинился с телефона в результате слетела авторизация на ПК.

Т.е. проблема не просто в том, что как-то самопроизвольно сессия умирает, а в том, что если разлогиниваешься на одном клиенте, то умирают все остальные сессии юзера, я правильно понял?

**Comment by inliquid** [comment]
Насчет всех не знаю, могу сказать только что точно слетела конкретная сессия на ПК.

**Comment by aVadim483** [comment]
Исправлено для 1.1 и для 1.0

**Comment by inliquid** [comment]
При выходе

[LOG:1432236294.976-555E3106EE3A2][2015-05-21 22:24:54][PID:25098][ERROR][[
Exception: Undefined method module: ModuleCache
--- call stack ---
Engine->GetModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 612
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Engine.class.php on line 773
Engine->__call()
Engine->ModuleCache()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 1298
E::__callStatic() in /var/www/example.com/common/classes/modules/user/User.class.php on line 780
E::ModuleCache() in /var/www/example.com/common/classes/modules/user/User.class.php on line 780
ModuleUser->CloseSession() in /var/www/example.com/common/classes/modules/user/User.class.php on line 720
ModuleUser->Logout()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionLogin.class.php on line 172
PluginAntibot_ActionLogin->User_Logout() in /var/www/example.com/common/classes/actions/ActionLogin.class.php on line 172
ActionLogin->EventExit()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1432236294.976-555E3106EE3A2]

**Comment by aVadim483** [comment]
fix

**Comment by inliquid** [comment]
Нет, все равно слетает.

**Comment by inliquid** [comment]
Может переоткроете баг?

**Comment by inliquid** [comment]
Напоминаю что баг остался.
