### ISSUE TITLE
Система уязвима к флуду поисковых запросов

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#544]
Нет никакой защиты от флуда поисковых запросов. Систему очень легко таким образом положить. Необходимо в обработке поискового запроса добавить проверку на частоту таких запросов от текущего пользователя. Например чтобы первые 5 запросов шли без ограничения, последующие 5 не чаще 1 раза в 5 секунд, но при превышении этого лимита для каждых следующих 5 запросов интервал бы увеличивался на 5 сек вплоть до 1 минуты. Если последний запрос был позднее чем за 30 минут от текущего момента ограничение можно снять. Данные можно хранить только в кеше.

**Comment by aVadim483** [comment]
Проблема понятна. Но вот такое ее решение вряд ли приемлемо, потому что:
1) Кеш используют далеко не все
2) Вы прописали алгоритм, который устраивает Вас лично, но не факт, что он будет устраивать большинство владельцев сайтов

**Comment by inliquid** [comment]
А какая проблема с этим алгоритмом, почему он может не устроить? Параметры (интервалы, частота запросов) можно определять через конфиг. Я привел пример того как устроено в некоторых других системах. Если есть более изящные способы, реализуйте их, мне по большому счету все равно.

**Comment by aVadim483** [comment]
>А какая проблема с этим алгоритмом, почему он может не устроить?

Потому что люди делают очень разные сайты и при этом имеют очень разные представления о том, что такое хорошо, а что такое плохо. Вот мне, например, этот алгоритм кажется чрезмерно замороченным:

N1 запросов без ограничений
N2 запросов не чаще N3 раз в N4 секунд
При превышении - для каждых N5 следующих запросов добавляется интервал N6 секунд, вплоть до значения N7 секунд
Если период более N8 секунд, то ограничения снимаются

Итого 8 дополнительных параметров в конфиге, которые я должен настраивать. При этом некоторые из них вообще особого смысла не имеют. Например: запросы без ограничений и 1 запрос в 5 секунд - не думаю, что нормальный человек способен менее, чем за полминуты, шесть раз подряд отправить запрос, получить и проанализировать результаты выдачи, понять, что это не то, и отправить новый запрос.

Поэтому сам посыл - как-то ограничить число поисковых запросов на определенном отрезке времени - мне кажется верным, но алгоритм из коробки должен быть более простым. Например, не более N1 запросов за N2 секунд. Все прочие навороты - это уже под конкретный сайт, под конкретного владельца, т.е. - плагином.

**Comment by inliquid** [comment]
Я не говорил выносить ВСЕ параметры. Вадим еще раз повторюсь если вам не нравится то как я предложил (по доброте душевной решил поделится и предложить направление, даже не направление а готовый алгоритм) - сделайте так как считаете нужным. 

Безусловно, другие системы делали идиоты, и вы предложите куда более правильно. А то что другим пользователям это покажется неправильным мягко говоря чушь. Неправильным им покажется когда они узнаю как ваша CMS легко DoS`ится.

**Comment by aVadim483** [comment]
1) Сколько из предложенных Вами параметров (и какие) Вы предлагаете вынести в конфиг, а какие стоит жестко вшивать в код и почему?

2) Скажите, пожалуйста, в каких CMS из топ-10, которую делали не идиоты, реализован предложенный Вами алгоритм с восемью параметрами прямо из коробки

3) Ни Ваш алгоритм, ни мой от DoS'а не может спасти в принципе.

**Comment by inliquid** [comment]
Вадим я нашел вам простой алгоритм, из нелюбимого вами движка =)


/**
 * Determines whether or not the user is "flooding" the search system, based on the number of searches
 * they have performed in the last minute.
 *
 * @return bool|int If the user is not flooding, returns false, but if they are, returned the number
 * 		of seconds until they can perform another search.
 */
public function isFlooding()
{
	if (C("esoTalk.search.searchesPerMinute") <= 0) return false;
	$time = time();
	$period = 60;

	// If we have a record of their searches in the session, check how many searches they've performed in the last minute.
	$searches = ET::$session->get("searches");
	if (!empty($searches)) {

		// Clean anything older than $period seconds out of the searches array.
		foreach ($searches as $k => $v) {
			if ($v < $time - $period) unset($searches[$k]);
		}

		// Have they performed >= [searchesPerMinute] searches in the last minute? If so, they are flooding.
		if (count($searches) >= C("esoTalk.search.searchesPerMinute"))
			return $period - $time + min($searches);
	}

	// However, if we don't have a record in the session, query the database searches table.
	else {

		// Get the user's IP address.
		$ip = (int)ip2long(ET::$session->ip);

		// Have they performed >= $config["searchesPerMinute"] searches in the last minute?
		$sql = ET::SQL()
			->select("COUNT(ip)")
			->from("search")
			->where("type='conversations'")
			->where("ip=:ip")->bind(":ip", $ip)
			->where("time>:time")->bind(":time", $time - $period);

		if ($sql->exec()->result() >= C("esoTalk.search.searchesPerMinute"))
			return $period;

		// Log this search in the searches table.
		ET::SQL()->insert("search")->set("type", "conversations")->set("ip", $ip)->set("time", $time)->exec();

		// Proactively clean the searches table of searches older than $period seconds.
		ET::SQL()->delete()->from("search")->where("type", "conversations")->where("time<:time")->bind(":time", $time - $period)->exec();
	}

	// Log this search in the session array.
	$searches[] = $time;
	ET::$session->store("searches", $searches);

	return false;
}


Один конфиг параметр. 

Потом в поиске
	if ($searchString and ($seconds = $this->isFlooding())) {
		$this->error("search", sprintf(T("message.waitToSearch"), $seconds));
		return false;
	}

В итоге если в минуту больше N запросов пользователю приходится подождать минуту прежде чем система разрешит снова искать.

**Comment by aVadim483** [comment]
И вот мое предложение из комментов выше: "...алгоритм из коробки должен быть более простым. Например, не более N1 запросов за N2 секунд..."

Сколько отличий найдете?

**Comment by inliquid** [comment]
Да я не против!
