### ISSUE TITLE
Проблемы с доступом при использовании RSS

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#545]
Используется блог  с доступом только зарегистрированным пользователям. Проверяю доступ незалогиненных гостей.

1. При переходе на RSS ссылку блога /rss/blog/nameofblog - возвращается ошибка 404. При этом например при попытке открыть страницу топика такого блога напрямую возвращается "нет доступа". Ошибка 404 в понимании пользователя (и в моем кстати тоже) свидетельствует что нас сайте какие-то проблемы. Считаю что должна возвращаться также "нет доступа" или пустая RSS страница без содержимого блога.

2. При открытии RSS страницы комментариев топика, я могу прочитать все комментарии такого топика, расположенного в недоступном мне блоге, например
/rss/comments/147/
где 147 - номер топика.

3. Следующий кейс довольно нетривиальный. Наткнулся когда пытался разобраться с тем почему перестали все комментарии выводиться в /rss/allcomments/
Разобраться не успел, возможно ошибка остается, но дальнейшее выяснение уткнулось в следующую ошибку:

Есть комментарии к топикам в 2х типах блогов - к первому имеют доступ любые пользователи, ко второму только зарегистрированные, оба комментария должны отобразиться в ленте 
/rss/allcomments/

Однако вот что вылезает

[LOG:1432389341.163-556086DD27CD9][2015-05-23 16:55:41][PID:12982][ERROR][[
E_ERROR [1] Call to a member function getTitle() on a non-object (/var/www/example.com/common/classes/actions/ActionRss.class.php on line 167)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---

**Comment by aVadim483** [comment]
https://github.com/altocms/altocms/commit/b45ed194e3611b571d92e3e06703945abfc747da этим коммитом исправляется ошибка

**Comment by inliquid** [comment]
Да ошибка ушла, но появилась новая.

4. /rss/allcomments/ -> отображается комментарий в недоступном для чтения незарегистрированным пользователям топике.

**Comment by inliquid** [comment]
5) Виджет "прямой эфир" тоже показывает эти комментарии. Боюсь ошибиться, но вроде до последних изменений этого не было.
