### ISSUE TITLE
Действие браузера при обновлении блока

### ISSUE THREAD

**Issue by orthograf** [altocms/altocms#550]
Файл: common/templates/skin/experience-simple/tpls/actions/profile/action.profile.created_photos.tpl

При нажатии в меню блока на кнопку обновления информации о кол-ве изображений пользователя (строка 40), страница "прыгает" вверх... 

![screenshot_1](https://cloud.githubusercontent.com/assets/6673241/7891763/1114b850-0671-11e5-921a-759f63220af2.jpg)

Как вариант решения:
<code>onclick="return false"</code>

**Comment by andrey-v** [comment]
Исправлено
