### ISSUE TITLE
Не загружаются картинки в фотосет

### ISSUE THREAD

**Issue by klaus-spb** [altocms/altocms#551]
Пробовал и у себя на тестовом сайте и на http://demo.altocms.ru/new/

При редактировании топика можно загрузить картинки, но при сохранении они все исчезают, будто их и не было.

**Comment by aVadim483** [comment]
Николай, не получается воспроизвести баг: http://demo.altocms.ru/new/29.html

Какой браузер?

**Comment by klaus-spb** [comment]
Ой, это у меня что-то с головой. После добавления фотографий не нажимал кнопку "Загрузить фото".
Хотя знаете, как-то это не интуитивно. Может стоит кнопку назвать "Подтвердить загрузку" и выделить цветом? Эта кнопка точно не лишняя?

**Comment by inliquid** [comment]
А я нажимал и ничего не работало. Но Вадим сказал что все не правда.

**Comment by klaus-spb** [comment]
@inliquid если нажимать то все работает. Другой момент, что я вроде опытный интернет пользователь, а вот так сразу нажать не догадался.

**Comment by inliquid** [comment]
Я тоже в итоге разобрался. Оказывается загрузка начиналась где-то там наверху, т.к. картинок было несколько, я даже этого не видел. В целом мое мнение я изложил здесь -http://altocms.ru/1038.html#comment22263
