### ISSUE TITLE
Не выбирается блог при публикации типа топика с дополнительным полем

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#552]
Поставил плагин "Карты в топиках и статьях" вот этот http://altocms.ru/addons/item/106/   Создал тип топика с дополнительным полем "Карта". При публикации данного типа топика не дает выбрать блог для публикации. В выпадающем меню ничего нет. Это на шаблоне Experience Simple.   На других шаблонах выпадает только в "Blog by admin" хотя есть другие блоги. При публикации обычного топика в меню выпадают все "Мой персональный блог", "Blog by admin", "test".

**Comment by klaus-spb** [comment]
А вы в настройках типа блога задали, что в нем может публиковаться данный тип топика?

**Comment by yuri25** [comment]
Блин мой косяк:) закройте пожалуйста issue
