### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by TalalFarhat** [altocms/altocms#553]
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80

**Comment by aVadim483** [comment]
As said in message you can find info about error in server log.

**Comment by TalalFarhat** [comment]
i have WampServer..
[resolved]
Wamp icon in notification area => Apache => httpd.config
search for "mod_rewrite", and uncomment it..
thank you
