### ISSUE TITLE
Опечатка в коде?

### ISSUE THREAD

**Issue by orthograf** [altocms/altocms#555]
В шаблонах (строки от 7 по 12)
<code> experience-simple/tpls/comments/comment.single.tpl</code> 
и
<code> experience/tpls/comments/comment.single.tpl</code> 
- точно нет ошибок?

<code>{if $sDateReadLast==''}
    {$sTargrtType = $oComment->getTargetType()}
    {if $sTargrtType == 'topic'}
        {assign var="sDateReadLast" value="{$oComment->getTarget()->getDateRead()}"}
    {/if}
{/if}</code> 

<code>$sTargrtType</code>

**Comment by aVadim483** [comment]
https://github.com/altocms/altocms/commit/de1d91d3df2f6ed0260ab0c3d17c6f266d6ebd91
