### ISSUE TITLE
Администрирование комментариев (SQL Error)

### ISSUE THREAD

**Issue by orthograf** [altocms/altocms#556]
При переходе к комментариям в админке (/admin/content-comments/):

2015-06-10 15:13:23
<code>SQL Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1, 1' at line 20 at site.ru/common/classes/modules/comment/mapper/Comment.mapper.class.php line 1167
SELECT SQL_CALC_FOUND_ROWS comment_id FROM prefix_comment WHERE 1 = 1 ORDER BY comment_id DESC LIMIT -1, 1 ;</code>

P.S.: Движок скачан отсюда час назад.

**Comment by aVadim483** [comment]
fixed
