### ISSUE TITLE
В профиле отображаются не все друзья

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#558]
В шаблонах start-kit и brand, 2 места вывода друзей в профиле
1. в виде набора аватарок
2. списком

И там и там одинаковая ситуация - отображается только 15 пользователей

![2](https://cloud.githubusercontent.com/assets/6797881/8108542/c4e11cd8-1059-11e5-88ca-fe42096146f2.png)

**Comment by inliquid** [comment]
В списке (/profile/\<имя\>/friends) оказалось все просто - пропущена пагинация. А вот в выводе аватарками в блоке друзья, оказалось что список с ограничением в 15 шт. передается из экшена. Соотвественно я так понимаю там нужно завести новую переменную и передавать в нее полный список.

**Comment by andrey-v** [comment]
В конфигурационном параметре *$config['module']['user']['friend_on_profile']    = 15;* Установи то число выводимых друзей, которое нужно.

**Comment by inliquid** [comment]
Не-не так не пойдет =)
Этот параметр влияет и на число друзей выводимых в виде набора аватарок и списком. Если у меня предположим 100 друзей? Я вот не хочу чтобы они все в длинный список выводились.

К списку я добавил пагинацию - работает нормально. А вот перечень друзей в виде аватарок тоже всего 15 штук, там в экшене надо сделать чтобы они все возращались и отдельной переменной передавались в шаблон. 

Короче, 
1. Указанный параметр должен влиять только на список друзей (и нужно добавить пропущенную пагинацию)
2. Нужно чтобы в шаблоне из другой переменной брался полный список и из него формировался вывод в виде набора аватарок.

**Comment by aVadim483** [comment]
Этот параметр задает число выводимых друзей, безотносительно, списком ли или еще в каком виде. Согласен, что не самый лучший вариант, но оно сделано так. Но по любому полный список - тоже не вариант, т.к. в общем случае их может быть сотни, поэтому нужны ограничители и разбивка на странице.

**Comment by inliquid** [comment]
А вы поняли про то что я написал что в профиле 2 места где выводятся друзья?
1. Картинка, как в самом начале - там просто идет набор аватрок.
2. Список /profile/<имя>/friends - здесь ПРОПУЩЕНА пагинация.

**Comment by inliquid** [comment]
Так вот я как раз и говорю что ограничение по количеству выводимых в списке друзей должно отличаться от этого набора аватарок. Поскольку для последнего никакой пагинации точно не предусмотрено, то должен возвращаться и использоваться еще и полный список друзей.

**Comment by aVadim483** [comment]
То, что для /profile/<имя>/friends пагинация в экшене формируется, но просто в шаблоне пропущена - с этим все ясно, это надо поправить. И там разбивка на страницы идет по значению, которое задано в секции __module.user.per_page__ конфига.

А вот число выводимых друзей на основной странице профиля (аватарками) - там это число как раз и регулируется параметром, про который написал Андрей - __module.user.friend_on_profile__. Если хотите там выводить абсолютно всех друзей, то задайте значение, которое гарантировано перекрывает число юзеров на ресурсе.

**Comment by inliquid** [comment]
Все понял, туплю.
