### ISSUE TITLE
Перестала работать ссылка на блог

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#559]
У меня реализована кнопка "добавить пост" с помощью конструкции /topic/add/?blog_id=, которая работала из коробки замечательно (это идет со времен ls я так понимаю). К сожалению в последних версиях для закрытых блогов, и блогов недоступных неавторизованным она перестала работать - возвращается ошибка 404.

**Comment by orthograf** [comment]
<code>content/add/?blog_id=</code>
- пробовали?

**Comment by inliquid** [comment]
Щас я смотрю что вообще ссылка формируется /content/topic/add?блабла
Тем не менее /topic/add/?blog_id= продолжает нормально работать на не последней версии на сайте где пока нет закрытых блогов, самую последнюю пока не накатывал т.к. там есть неприятный баг с логином новых пользователей.

**Comment by inliquid** [comment]
Вот как формируется в шаблоне
`{router page='topic'}add/?blog_id={$oBlog->getId()}`

**Comment by andrey-v** [comment]
Такая ссылка *topic/add/?blog_id=3* будет работать только при включённом плагине совместимости ls, если плагин не активирован  (https://github.com/altocms/altocms/blob/master/common/plugins/ls/config/config.php#L15), то ссылка работать не будет. 
Правильная ссылка */content/add/?blog_id=*

Плагин ls случайно не был выключен, когда ссылка не сработала?

**Comment by inliquid** [comment]
Неа, плагин активирован. Можешь на тестовом сайте глянуть по кнопке "добавить пост". На основном все работает.

**Comment by aVadim483** [comment]
У меня на тестовом сайте под 1.10.х со всеми последними изменениями и с установленным плагином Ls ссылка /topic/add/?blog_id=NNN работает нормально для закрытого блога. Либо какие-то нюансы и/или дополнительные настройки не учтены и/или сторонние плагины.

**Comment by inliquid** [comment]
Версия 1.0.x. Как и во всех предыдущих отчетах.

**Comment by aVadim483** [comment]
Пардон, в цифирях ошибся, я имел ввиду именно версию 1.0.10.х
