### ISSUE TITLE
Слетел логин при активации нового пользователя

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#560]
Слетел логин при активации нового пользователя. Теперь при переходе по ссылке активации пользователь оказывается не залогинен, и ему приходится еще дополнительно выбирать "войти" и т.д.

**Comment by inliquid** [comment]
Коллеги, нельзя ли с этим что-то сделать? Только из-за этого бага я не перехожу на последнюю версию 1.0.x......

**Comment by aVadim483** [comment]
Наверняка можно. Только я не считаю, что это баг, это, скорее, проблема юзабилити, поэтому и приоритет не очень высокий

**Comment by inliquid** [comment]
Просто до коммита с исправлением разлогинивания на всех устройствах работало.

**Comment by inliquid** [comment]
Если новому пользователю приходится делать дополнительные шаги вероятность того что он после регистрации как-то поучаствует в жизни портала снижается на каждом таком препятствии вдвое.

**Comment by bambarbia-kergudu** [comment]
А что именно не работает, на чистой версии 1.1.4 после активации акка переходом по ссылке из письма или после ручного копирования ссылки в адресную строку юзер автоматом залогинен.

**Comment by inliquid** [comment]
Версия 1.0.x
