### ISSUE TITLE
Сортировка избранного

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#564]
1. Во-первых иногда почему-то топики в избранном оказываются отсортированы не по дате публикации, возможно используется дата создания а не публикации (например если топик писался через черновики - это мое предположение)
2. На самом деле конечно никакой сортировки по дате там быть не должно. При добавлении в избранное топики должны затем выводиться в порядке их добавления начиная с последнего добавленного. Представьте у вас в избранном 100 топиков, но вот вы вдруг находите интересный топик который раньше не видели, датированный достаточно давно, и добавляете в избранное чтобы к нему вернуться. Но при переходе в избранное вам теперь придется копаться в ваших 100+ топиках, потому что последний добавленный топик где-то там посреди растворился. Как аналог - закладки в браузере. Представьте что будет если они начнут сортироваться по дате создания вебсайта.

**Comment by inliquid** [comment]
По п. 1 - точно сортируются не по дате публикации, а по дате создания. Черновики сразу теряются если писались несколько дней.

**Comment by aVadim483** [comment]
По п.2 - согласен, логика в этом есть. Учтем в будущих версиях.
