### ISSUE TITLE
Проверять наличие модуля mod_headers

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#567]
Если в настройках сайта включено gzip-сжатие css/js-файлов, но модуль `apache2` `mod_headers` не используется (по умолчанию он отключен), то возникает проблема, когда сайт оказывается без стилей и/или без javascript-файлов.
Нужно проверять, активирован ли данный модуль и 
* либо не сохранять включение настройки gzip-сжатия с выводом информационного сообщения о том, что нужно сначала включить модуль;
* либо сохранять настройку, но отдавать несжатые файлы, пока модуль не будет включён (но опять же, придётся где-то выводить сообщение, чтобы админ включил модуль)

**Comment by shtrih** [comment]
Как вариант, можно по умолчанию генерировать сжатые и несжатые файлы, но, в зависимости от заголовка `Accept-Encoding` клиента, отдавать сжатые или несжатые файлы:
http://httpd.apache.org/docs/2.4/mod/mod_deflate.html#precompressed

**Comment by andrey-v** [comment]
Спасибо, исправления внёс
![image](https://cloud.githubusercontent.com/assets/1106990/8271679/d8060532-182c-11e5-96db-e90da168eeaf.png)
