### ISSUE TITLE
Пустой список блогов при создании топика

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#570]
Если создать новый тип контента и попытаться создать топик этого типа, то выпадающий список блогов будет пустым. 

Узнал причину в исходниках. После добавления типа контента, надо его ещё разрешить в меню «Типы блогов» (потому что по умолчанию у всех типов блогов выбран тип «Статья»).
Решением будет проверка, разрешён ли данный тип контента в каком-либо блоге, и если нет, то либо не показывать селект вообще и выводить сообщение, что нужно настроить тип блогов, либо добавить неактивный пункт списка:
```smarty
    {if !$bPersonalBlog && sizeof($aBlogsAllow)}
        <option value="" disabled="disabled">Ни у одного типа блогов не разрешен этот тип контента.</option>
    {/if}
```

**Comment by aVadim483** [comment]
@andrey-v Андрей, а там действительно по умолчанию у всех типов блогов жестко задан тип контента? По умолчанию должна быть разрешена публикация чего угодно
