### ISSUE TITLE
Не работает загрузчик картинок к топику

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#571]
При редактировании топика, при попытке загрузить картинку, отправляется POST-запрос по адресу `/uploader/multi-image/`, однако код ответа `404`, выдаётся стандартная 404-страница, файлы не обрабатываются.

**Comment by andrey-v** [comment]
А у вас случайно не установлен плагин [брендирования блогов](http://altocms.ru/addons/download/item/98/)? Дело в том, что этот плагин ещё не адаптирован для версии 1.1 и в нем используется экшен ActionUploader, который в 1.1 подменяет собой одноимённый экшен движка, что вызывает похожую ошибку.

Если нет, то можете подробнее описать как возникает ошибка, потому что в актуальной 1.1 я проверил:
- загрузку картинок при редактировании топика админом;
- загрузку картинок при редактировании топика пользователем;
- загрузку картинок при редактировании черновика топика админом/пользователем;
и ошибку не поймал.

**Comment by shtrih** [comment]
Брендирование, да.

**Comment by andrey-v** [comment]
Этот плагин пока не совместим с версией 1.1, вам придётся его отключить.

**Comment by shtrih** [comment]
@andrey-v, А вообще странно. В плагине же указана требуемая версия системы 1.0, но плагин активировался без проблем. Оно не должно проверятсья? Или это в TODO?
