### ISSUE TITLE
Старый баг проявился снова - невозможно загрузить ни одно изображение

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#573]
В очередной раз отловил старый баг, который _никто не стал исправлять_

https://github.com/altocms/altocms/issues/486

[LOG:1434997745.031-558853F107965][2015-06-22 21:29:05][PID:9633][ERROR][[
E_WARNING [2] move_uploaded_file(): Unable to move '/tmp/phpof4K76' to '/var/www/example.com/_tmp/cache/uploads/cd897cbf.png' (/var/www/example.com/engine/include/functions/File.php on line 1017)
--- call stack ---
move_uploaded_file() in /var/www/example.com/engine/include/functions/File.php on line 1017
AltoFunc_File::MoveUploadedFile()
call_user_func_array() in /var/www/example.com/engine/include/Func.php on line 349
Func::__callStatic() in /var/www/example.com/common/classes/modules/uploader/Uploader.class.php on line 269
F::File_MoveUploadedFile() in /var/www/example.com/common/classes/modules/uploader/Uploader.class.php on line 269
ModuleUploader->UploadLocal()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/modules/topic/Topic.class.php on line 2512
PluginTopicintro_ModuleTopic->Uploader_UploadLocal() in /var/www/example.com/common/classes/modules/topic/Topic.class.php on line 2512
ModuleTopic->UploadTopicImageFile()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/abstract/LsObject.class.php on line 44
LsObject->__call() in /var/www/example.com/common/classes/actions/ActionAjax.class.php on line 1152
PluginCorrect_ActionAjax->Topic_UploadTopicImageFile() in /var/www/example.com/common/classes/actions/ActionAjax.class.php on line 1152
ActionAjax->EventUploadImage()
call_user_func_array() in /var/www/example.com/engine/classes/abstract/Action.class.php on line 198
Action->ExecEvent() in /var/www/example.com/engine/classes/core/Router.class.php on line 445
Router->ExecAction() in /var/www/example.com/engine/classes/core/Router.class.php on line 187
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1434997745.031-558853F107965]

Это происходит при попытке загрузить любое изображение. 

Скорее всего после чистки кэша движка из админки проблема временно уйдет, как и в прошлый раз. Сейчас проверю.

Да - все тоже самое.

**Comment by inliquid** [comment]
Возможно продолжение - при переходе в админку

[LOG:1435001140.557-5588613487F67][2015-06-22 22:25:40][PID:9251][ERROR][[
Exception: unable to write file /var/www/example.com/_tmp/templates/admin-default-fiolet/compiled/wrt55886134879bf1_72710433
Templates stack:

--- call stack ---
Smarty_Internal_Write_File::writeFile() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_template.php on line 213
Smarty_Internal_Template->compileTemplateSource() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 155
Smarty_Internal_TemplateBase->fetch() in /var/www/example.com/engine/libs/Smarty/libs/sysplugins/smarty_internal_templatebase.php on line 394
Smarty_Internal_TemplateBase->display() in /var/www/example.com/engine/classes/modules/viewer/Viewer.class.php on line 594
ModuleViewer->Display()
call_user_func_array() in /var/www/example.com/engine/classes/core/Engine.class.php on line 636
Engine->_CallModule() in /var/www/example.com/engine/classes/core/Router.class.php on line 743
Router->__call() in /var/www/example.com/engine/classes/core/Router.class.php on line 200
Router->Viewer_Display() in /var/www/example.com/engine/classes/core/Router.class.php on line 200
Router->Shutdown() in /var/www/example.com/engine/classes/core/Router.class.php on line 188
Router->Exec() in /var/www/example.com/index.php on line 23
--- end ---

]][END:1435001140.557-5588613487F67]


В указанной папке файл создан но имеет 0 длину:


root@mail:/var/www/example.com/_tmp/templates/admin-default-fiolet/compiled# ls -la
total 100
drwxr-xr-x 2 www-data www-data   160 Июн 22 22:25 .
drwxr-xr-x 3 www-data www-data    60 Июн 13 22:22 ..
-rw-r--r-- 1 www-data www-data 36049 Июн 22 21:35 fiolet^22d48c71a0290fdcf96f64fa66e831d03b5fd1d9.file.reset.tpl.php
-rw-r--r-- 1 www-data www-data  1536 Июн 22 21:35 fiolet^25df543725dcf52b71fee0c36a8f69d3e8c93259.file.inject.admin.menu.tpl.php
-rw-r--r-- 1 www-data www-data  1598 Июн 22 21:35 fiolet^7f0961d14e2b6c859778e83ec31c0fa4a3dd20dc.file.modal.empty.tpl.php
-rw-r--r-- 1 www-data www-data 33615 Июн 22 21:43 fiolet^c323ad7adea0f83ee36269dd056b6145a45b91c4.file.errors.tpl.php
-rw-rw-rw- 1 www-data www-data 20480 Июн 22 22:25 wrt55886128a4d710_93973806
-rw-rw-rw- 1 www-data www-data     0 Июн 22 22:25 wrt55886134879bf1_72710433


root@mail:/var/www/example.com/_tmp/templates/admin-default-fiolet/compiled# ls -la wrt55886134879bf1_72710433
-rw-rw-rw- 1 www-data www-data 0 Июн 22 22:25 wrt55886134879bf1_72710433

**Comment by inliquid** [comment]
Вот собственно зачем нужен перезапуск мемкеша и ручная чистка _tmp и _run.

**Comment by aVadim483** [comment]
Невозможно исправить баг, природа которого совершенно непонятна. Вы приводите две ошибки, и первая из них вызывается при выполнении //системной// функции move_uploaded_file(), вторая - в Smarty. Т.е. ни та, ни другая ошибка не вызывается самим движком. Но их объединяет одно: в обоих случаях невозможно выполнить запись в поддиректорию директории /_tmp/.

Именно поэтому я продолжаю считать, что это какая-то системная ошибка на стороне сервера. Все, что могу посоветовать, так это в следующий раз не сразу все очищать-перезагружать, а поэтапно: сначала мемкеш перезагрузить, проверить, потом папку очистить. Или наоборот - как угодно, но не все сразу. Как это может помочь - не знаю. Но можно будет предположить, что если проблема решается только очисткой директории, то, скорее всего, что-то неладно с дисковой системой. Если же только перезагрузкой мемкеша - то, вероятнее всего, с памятью нелады.

А /_tmp/, кстати, не в памяти висит?

**Comment by inliquid** [comment]
_tmp висит в памяти

**Comment by inliquid** [comment]
Еще раз, давайте следовать элементарной логике. Сайт работает, работает, внезапно ни с того не с сего перестают загружаться изображения. Однако сброс кеша из админки эту проблему решает.

**Comment by aVadim483** [comment]
>Однако сброс кеша из админки эту проблему решает

Во-первых, Вы оба раза писали не просто про сброс кеша, но и про перезапуск мемкеша. Вот поэтому я и советую все ж определиться, что именно влияет на проблему.

Во-вторых, даже если выяснится, что проблема решается просто очисткой файлов в директории, то что это меняет? Это означает лишь, что файловая система вдруг теряет возможность писать на RAM-диск, а если его очистить, то она эту возможность вдруг опять обретает.

Простой пример: сайт работал, работал, и внезапно перестала проходить авторизация. Очистка директории, где хранятся файлы сессий решила проблему. Ситуация почти один в один.

**Comment by inliquid** [comment]
Я еще в первый раз объяснил почему я так писал. Система не теряет никакую возможность туда писать. Очевидно проблема в логике.
И еще - почему нет сообщения о конкретной системной ошибке не дающей записать файл? 
Что это - недостаток свободного пространства? прав доступа? ошибка фс? Сделайте нормальный вывод ошибок хотя бы.

Чуть выше я выложил ошибку из лога где говорится про невозможность создать файл, однако как видно файл создан с нулевой длиной.

**Comment by inliquid** [comment]
И я что-то не понял вот этой претензии "так это в следующий раз не сразу все очищать-перезагружать, а поэтапно: сначала мемкеш перезагрузить, проверить, потом папку очистить."

Основная проблема с загрузкой изображений решилась просто сбросом кешей из админки. Вторую ошибку, когда админка после этого всего не открывалась, я уже решал перезапуском.

**Comment by aVadim483** [comment]
>Система не теряет никакую возможность туда писать

А PHP теряет

http://php.net/manual/ru/function.move-uploaded-file.php - это функция PHP, которая возвращает true, если загруженный файл перемещен, куда требуется, и false в противном случае. Никаких __конкретных__ сообщений она, к сожалению, не выдает. Ошибка Смарти возникает при попытке записать файл функцией PHP file_put_contents(), которая тоже не выдает никакой конкретики - либо записался файл, либо нет.

>Очевидно проблема в логике.

При запуске движок проверяет наличие нужных директорий и их доступность для записи. Предлагаете делать это перед каждой файловой операцией? Боюсь, слишком накладно это будет.

>не понял вот этой претензии

Это не претензия, а совет. В обоих случаях Вы писали, что проблема решается сбросом кеша __и__ перезапуском мемкеша. Вот я и посоветовал, если возникнет такая проблема еще раз, не сбрасывать/перезагружать все чохом, а делать это поэтапно, проверяя, решилась проблема или нет. Но следовать совету или нет - решать Вам.

**Comment by inliquid** [comment]
Еще раз рекомендую перечитать что я писал в обоих случаях. Проблема с загрузкой изображений решалась чисткой кеша.

**Comment by aVadim483** [comment]
Резюмируем: имеем сайт, где директория /_tmp/ расположена на RAM-диске, и в какой-то момент вдруг перестают работать функции PHP, которые пишут файлы на этот диск. Проблема лечится очисткой диска/директории. Как именно очистка происходит - из админки ли, руками ли - никакой роли не играет. На мой взгляд, налицо все признаки того, что проблема на стороне сервера (как варианты: ограничения по числу дескрипторов, по объему диска или что-то в этом роде).

Какие можно принять адекватные меры для решения/предупреждения этих проблем со стороны движка, я не вижу. Посему тикет закрываю.
