### ISSUE TITLE
Поле контента «чекбокс»

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#574]
Запилил простой вариант поля «чекбокс». 
![_032](https://cloud.githubusercontent.com/assets/544063/8302441/fc251e26-199e-11e5-9bf5-eee1bff55ae5.png)
Нужно ли оно в системе или лучше оформить отдельным плагином?

**Comment by aVadim483** [comment]
Чекбокс вообще нужен, конечно. Но добавлять в 1.1 новый функционал уже не будем. Поэтому лучше сейчас оформить плагином, а в следующей версии уже включим в движок.

**Comment by shtrih** [comment]
Добавил в каталог.
