### ISSUE TITLE
Поиск пользователей по IP 

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#578]
1. Не учитывается последний визит при таком поиске, только регистрация.
2. Просьба сделать простое текстовое поле, сейчас оно разбито на 4 сегмента и поэтому не работает копипаст из логов, или текстового файла. Или сделать так чтобы копипаст срабатывал.
3. Нет поддержки IPv6?

**Comment by aVadim483** [comment]
Да, все так, поиск только по регистрации и IPv6 при этом не поддерживается. Равно как нет возможности забанить по IPv6. Хотя собственно определение IPv6 работает и в базу пишется. Но полноценная поддержка - тема очень непростая, поэтому только в будущих версиях.
