### ISSUE TITLE
В папке _tmp/cache/uploads скапливается хлам

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#579]
Обнаружил что указанная папка содержит некоторые загруженные файлы. В каких случаях они все появились я не скажу, но как минимум 1 кейс очевиден. У меня настроено ограничение на загрузку 10 Мб. При этом файлы, которые превышают этот размер там остаются. 

 # ls -la
total 29256
drwxr-xr-x 2 www-data www-data      160 Июн 28 16:46 .
drwxr-xr-x 4 www-data www-data      100 Июн 22 22:40 ..
-rw-r--r-- 1 www-data www-data 10102191 Июн 28 16:33 106084e9.jpg
-rw-r--r-- 1 www-data www-data 17413383 Июн 28 16:20 3f9419cd.jpg
-rw-r--r-- 1 www-data www-data   754334 Июн 23 00:51 b2f868de.jpg
-rw-r--r-- 1 www-data www-data   726122 Июн 25 08:15 b340ed51.jpg
-rw-r--r-- 1 www-data www-data   431990 Июн 25 18:11 c9240958.jpg
-rw-r--r-- 1 www-data www-data   512617 Июн 25 18:08 ff1b1f49.jpg

Первые 2 файла это именно файлы которые не прошли через ограничение по размеру, однако в этой папке они сохранились.

Насчет остальных затрудняюсь сказать. Но очевидно есть еще какой-то пробел в логике который позволяет захламлять эту папку.

Ситуация усугубляется еще тем, что _tmp у меня лежит в оперативной памяти.

**Comment by bambarbia-kergudu** [comment]
Да, проблема актуальна, даже на локальке на тестовом сайте при тестировании функционала папка _tmp уже скушала 10 метров места.

**Comment by inliquid** [comment]
Также в этой папке скапливаются загруженные аватарки блогов.

**Comment by inliquid** [comment]
Подскажите можно как-то задать директорию для этой папки (cache/uploads) отдельно от _tmp? Желательно не весь файловый кеш вынести а только ее?
И в каком месте в коде эта директория задается?

**Comment by aVadim483** [comment]
Задается здесь:
https://github.com/altocms/altocms/blob/1.0.x/engine/include/functions/File.php#L1028-L1031

И там жестко указывается, что это поддиректория файлового кеша, который задается конфиг-параметром `sys.cache.dir`, поэтому просто изменением конфига ее не вынесешь, только правкой кода

**Comment by inliquid** [comment]
Спасибо, немного пришлось извратиться с монтированием, но удалось вынести не трогая код.
