### ISSUE TITLE
По плагину простой системы голосования

### ISSUE THREAD

**Issue by Phobosssss** [altocms/altocms#580]
1. Отсутствует кнопка дислайка комментариев и новостей в шаблоне «Experience Simple v.1.0.0»
2. Если поставить «Количество начисляемых баллов топику» 1, то при голосовании за/против начисляется 1 балл. Если поставить -100 будет отниматься -100, независимо от того, на какую кнопку нажал.

**Comment by andrey-v** [comment]
А у вас точно последняя версия Альто?
Эти ошибки были испаравлены 25 апреля, вот тут - https://github.com/altocms/altocms/issues/497

**Comment by Phobosssss** [comment]
Все верно. Извините за беспокойство!
