### ISSUE TITLE
При регистрации не подавляются лишние пробелы

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#586]
Пробелы перед и после ника должны удаляться trim`ом, иначе юзер регистрируется с пробелами в начале / конце ника и это вызывает проблемы. Например при логине.

Кроме того прошу добавить в админку функцию изменения ника.

**Comment by aVadim483** [comment]
trim, конечно, не помешает, но ведь есть проверка на набор символов в логине. Она не срабатывает?

>Кроме того прошу добавить в админку функцию изменения ника.

Увы, но для 1.0 фичреквесты не принимаются, только баги, да и то не все

**Comment by inliquid** [comment]
У меня разрешены пробелы в нике.

**Comment by inliquid** [comment]
Насчет фич, можно и в 1.1-1.2.

**Comment by aVadim483** [comment]
Фича полезная, согласен, добавил в будущие
