### ISSUE TITLE
StartKit: выпадающее подменю главного меню, при настройке из админки, отображается некорректно

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#591]
![_039](https://cloud.githubusercontent.com/assets/544063/8616095/12c35ed0-2701-11e5-9dba-424d37e017fd.png)

**Comment by aVadim483** [comment]
Исправлено этим коммитом: https://github.com/altocms/altocms/commit/9c03c9b2f5c050054057aefa135afbdc656ad555
Но чтоб изменения применились, нужно заново перестроить меню
