### ISSUE TITLE
Огрехи в Experience Simple

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#593]
1. Тёмная и оранжевые темы имеют нижепредставленные недостатки:
![_040](https://cloud.githubusercontent.com/assets/544063/8618843/a00a35c0-271a-11e5-876c-cfac408a6f8e.png)

2. В выпадающем меню нехватает caret.

![_041](https://cloud.githubusercontent.com/assets/544063/8618868/d7d9b476-271a-11e5-9af3-a9574b988c18.png)
3. Темный цвет текста на темном фоне
![_042](https://cloud.githubusercontent.com/assets/544063/8668847/faff25da-2a17-11e5-96f3-58140af5e34f.png)
4. При больших цифрах рейтинга, его ширина меняется достаточно, чтобы сломать положение соседних блоков:
![_044](https://cloud.githubusercontent.com/assets/544063/8719260/051a23f2-2bb3-11e5-8da1-10480019db79.png)

**Comment by andrey-v** [comment]
Исправлено, а вот рейтинг просто физически не помещается, могу предложить вам убрать (вот в этом файле)[https://github.com/altocms/altocms/blob/master/common/templates/skin/experience-simple/tpls/api/user/id/info/api.user.id.info.default.tpl#L8] Иконку ```html<i class="fa fa-bar-chart-o"></i> ```

**Comment by shtrih** [comment]
Нужно переверстать этот блок.

**Comment by shtrih** [comment]
@andrey-v, Вот получилось сделать немного получше: https://github.com/altocms/altocms/compare/master...shtrih:popover
![_077](https://cloud.githubusercontent.com/assets/544063/9992311/ee9c8222-6079-11e5-9f07-058087dcde57.png)
