### ISSUE TITLE
Ошибка «System error #1001» с блоком «Блоги» 

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#595]
При попытке переключения по вкладкам в блоке «Блоги» в сайдбаре, возникает ошибка «System error #1001», которая появляется сразу же после создания первого блога, подписки на чужой блог и появления своего. На тестовом сайте создано три блога и добавлено две записи (версия Альто с мастерской ветки гитхаба).

**Comment by aVadim483** [comment]
Ошибка 1001 - эта ошибка возникает тогда, когда ajax-запрос получает в ответ совсем не то, что ожидает. Как правило, это ошибка на стороне сервера, и ее можно увидеть в логах сайта.

**Comment by bambarbia-kergudu** [comment]
Во всех шаблонах не хватает папки с файлом "blocks/block.blogs_top.tpl", скопировал из старого дистрибьютива и ошибка пропала, все закладки заработали.

```
Exception: Can not find the template "blocks/block.blogs_top.tpl" in skin "experience-simple". Probably you need to activate plugin "Ls".
Template Dirs: Z:/home/test-site.ru/www/common/templates/skin/experience-simple/; Z:/home/test-site.ru/www/common/templates/skin/experience-simple/themes/; Z:/home/test-site.ru/www/common/templates/skin/experience-simple/tpls/
```
