### ISSUE TITLE
Значения языковых файлов не обрабатываются в ленте последних комментариев и статей

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#596]
Если ленты комментариев или публикаций в сайдбаре пусты, то константа {$aLang.widget_stream_comments_no} не обрабатывается в файлах \common\templates\skin\experience-simple\tpls\widgets\widget.stream_comment.tpl и \common\templates\skin\experience-simple\tpls\widgets\widget.stream_topic.tpl, если набрать текст прямо в коде, то он появляется.

**Comment by aVadim483** [comment]
https://github.com/altocms/altocms/issues/602
