### ISSUE TITLE
Не подгружаются значения языковых файлов при поиске по блогам

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#602]
При вводе запроса в форму поиска на странице Блогов происходит ajax-фильтрация, при этом заголовки таблицы «Название», «Опции», «Читателей», «Рейтинг» в результате поиска пропадают (смотрите скриншот - http://hkar.ru/CsPd). Если ввести текст ручками прямо в коде, то все показывается. В версии 0.9.7.1 таких проблем не было.

Мля, чем дальше в лес, тем больше дров ((.

Похожее происходит и здесь: https://github.com/altocms/altocms/issues/596

**Comment by bambarbia-kergudu** [comment]
На странице Людей такая же ботва

**Comment by bambarbia-kergudu** [comment]
В Активности тоже значения языковых файлов теряются после загрузки ленты по ajax. В общем это происходит везде, где используется динамика.

**Comment by aVadim483** [comment]
Проанализировал сейчас - да, есть проблема. Это результат некоторой оптимизации шаблонизатора. Хотелось уменьшить число действий, которые выполняет шаблонизатор, когда он вызывается для отрисовки по ajax. Но, видимо, немного перестарался.
