### ISSUE TITLE
Смена размеров аватар у пользователей при выводе ajax-результатов поиска

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#607]
Попробую описать баг :)) После ввода имени в строку поиска на странице «Люди» происходит ajax-фильтрация, при этом размеры аватаров у пользователей меняются c 48px на 64px. Почему так происходит (мои догадки): при загрузке страницы «Люди» настройки шаблона берутся из локального файла \common\templates\skin\experience-simple\settings\config\config.php, а при выводе ajax-результатов используются глобальные \common\config\config.php.

Локальные настройки размеров изображений в шаблоне Experience:
```
C::Set('module.uploader.images.profile_avatar.size', array(
    'great'  => '224x224crop', // Виджет "О блоге"
    'huge'   => '150x150crop', // Блог в выпадающем тултипе
    'large'  => '128x128crop', // Шапка профиля блога/пользователя
    'big'    => '85x85crop',   // Список пользователей list_avatar
    'medium' => '48x48crop',
    'small'  => '32x32crop',
    'mini'   => '24x24crop',
    'micro'  => '16x16crop',   // Не используется
));
```

Глобальные настройки размеров изображений:
```
$config['module']['uploader']['images']['profile_avatar'] = array(
    '$extends$' => '___module.uploader.images.default___',
    'size' => array('large' => '96x96crop', 'medium' => '64x64crop', 'small' => '32x32crop'),
    'transform' => array(
        'max_width'  => 250,        // максимальная ширина сохраняемой аватары
        'max_height' => 250,        // максимальная высота сохраняемой аватары
        'aspect_ratio' => '1',      // соотношение ширины и высоты
        'watermark' => array(
            'enable' => false,
        ),
        '@mime(gif)'  => array(
            'animation' => true,
        ),
    ),
);
```

Если задать одинаковый размер medium => '64x64crop'  в обоих файлах настроек, то аватары при поиске не будут больше «скакать».

**Comment by aVadim483** [comment]
Этим коммитом https://github.com/altocms/altocms/commit/1925f99f981acb902cbc96a8962c6b2325ffeec1 решена и эта проблема
