### ISSUE TITLE
Ошибка при загрузке фотографий через окно текстового редактора и невозможность удалять уже залитые фотки в менеджере картинок

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#616]
Если на странице создания нового топика попытаться загрузить картинку через модальное окно текстового редактора (Ctrl + K), то появится сообщение «Ошибка: Нет доступа». Ошибка возникает только в том случае, когда до загрузки выбранных изображений был совершен хотя бы один переход по вкладкам «Из интернета», «Аватары», «Статьи», «Этот топик», а затем обратно на вкладку «С этого компьютера». Если заливать фотографии сразу после открытия модального окна с менеджером картинок, то все проходит нормально. Также нет возможности редактировать или удалять фотографии залитые через модальное окно. В фотосете хотя бы есть возможность удалять фотки выборочно, а здесь, насколько я понял, только вместе с топиком (проблема была упомянута в тикете https://github.com/altocms/altocms/issues/471). Проверял на всех темах.

**Comment by aVadim483** [comment]
Ошибку с модальным окном пофиксил, а задачу с удалением вынес в отдельный тикет
