### ISSUE TITLE
При вставке в топик картинок через менеджер изображений пропадает атрибут width

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#618]
При редактировании топика все отображается нормально, а вот при сохранении топика и просмотре html кода атрибут width со значением вырезается. Что может сломать дизайн, если забыть про css.

Код картинки из такого: 
```<img src="http://test.ru/uploads/images/00/00/01/2015/07/20/0u4b101546-30503f15-4f713f88.jpg"align="right"  width="50%"  />```

Превращается в такой:
```<img src="http://test.ru/uploads/images/00/00/01/2015/07/20/0u4b101546-30503f15-4f713f88.jpg"align="right"  />```

**Comment by shtrih** [comment]
Видимо, это из-за [вот этого правила](https://github.com/altocms/altocms/blob/master/common/config/jevix.php#L42). Даже не знаю, прописать `#text`?

**Comment by aVadim483** [comment]
Да, из-за него. Склоняюсь к тому, чтоб править код jevix'а, добавив возможность задавать проценты

**Comment by aVadim483** [comment]
fixed
