### ISSUE TITLE
В тулбаре не сбрасывается счетчик новых комментариев после просмотра топика

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#619]
Создаем топик, выходим из учетки, оставляем комментарий от имени другого юзера, заходим обратно под автором топика, в тулбаре появится число новых комментариев с последнего визита, кликаем по цифре, перемещаемся автоматом к новому комментарию, обновляем страницу, кол-во комментариев останется прежним, и сколько не перезагружай страницу, счетчик сбросится лишь в том случае, если принудительно нажать кнопку обновления комментариев в тулбаре. Баг замечен во всех темах.

**Comment by bambarbia-kergudu** [comment]
\common\templates\skin\experience-simple\tpls\comments\comment.single.tpl

```{elseif $sDateReadLast <= $oComment->getDate()}```

В этом условии переменная $sDateReadLast, если юзер залогинен, становится статичной, время не меняется, стоит выйти, становится динамичной. Секунды увеличиваются с каждым обновлением страницы. Все должно быть наоборот. Поэтому счетчик и не сбрасывается до принудительного обновления комментариев через кнопку в тулбаре, после которого время в $sDateReadLast меняется.

**Comment by aVadim483** [comment]
Это было не из-за шаблона, а из-за стремления уменьшить обращения к БД. Пофиксил
