### ISSUE TITLE
Ошибка при удалении аватара

### ISSUE THREAD

**Issue by sersar** [altocms/altocms#621]
Загружаю аватар.
Обновляю страницу.
Нажимаю ссылку удалить аватар.
Получаю битую картинку: 
"NetworkError: 404 Not Found - http://alto.dev/uploads/images/00/00/01/2015/07/22/0u58ce87e1-3ca9b8c0-6e7f7bb1.png-128x128-crop.png?0.7495146701212081".
Альто 1.1.1

**Comment by shtrih** [comment]
Подтверждаю в теме «Experience Simple».

**Comment by bambarbia-kergudu** [comment]
Во всех шабах так.
