### ISSUE TITLE
Нехватает информации о папке /app и подпапках

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#622]
# templates/
Что будет, если положить туда шаблон, совпадающий по имени с существующим в папке /templates? Или это только для языковых файлов? 
В подпапке `language` есть ридми «You can place your own language files in this folder». Непонятно что будет, если в языковом файле указать строку с ключом, который уже есть стандартной теме. Он заменится? Могу ли я через такой файл переопределять тексты плагинов? Как?
# config/
Можно ли переопределять стандартные конфиги `jevix.php`, `menu.php`, `widgets.php`, дописывая суффикс `local` по аналогии с `config.local.php`? В теме шаблонов есть своя папка settings/config. Как переопределять конфиги оттуда?
# plugins/
В этой папке находится файл `plugins.dat`, в которую записываются активированные плагины. Можно ли сюда добавлять свои плагины? Я добавляю их в папку `common/plugins/`. Правильно ли это?

**Comment by aVadim483** [comment]
Не сочтите занудой, но все ж хотелось бы гитхаб оставить для багрепортов и фичреквестов, а вот такого рода вопросы лучше на сайт писать.

**Comment by shtrih** [comment]
Ну я думал, что этот вопрос решится добавлением какого-нибудь файла `Readme.md` в папку, что относится непосредственно к репозиторию, потому оно здесь. Ну ок, запилю топик. 

Также нехватает файла [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) в корне проекта, в котором содержатся небольшие инструкции по правильному внесению правок. Например, мне совершенно непонятно, как правильно фиксить стили. А потому я просто не делаю этого. Или описать порядок добавления issue на гитхаб: описание проблемы, прикрепление полного отчета из админки и т.д.
↑ Этот абзац тоже в отдельный топик?
 ---
Вообще я не люблю смотреть документацию в том виде, как она сделана в лс и у вас. Это бардак. Ничего невозможно найти. Информация не структурирована в какой-то список или оглавление, а просто раскидана по всему сайту. Крайне неудобно, брр. Блоги для документации не подходят. Было бы хорошо, если бы линки на посты с описанием движка хотя бы добавлялись в альто-вики. Но нет. 

Никого не хотел обидеть, просто мнение со стороны.

**Comment by shtrih** [comment]
Ну вот и проблема. Хотел перенести этот в топик, но тег `<code>` на сайте используется не по назначению. Это строчный элемент, но на сайте он блочный и вообще сделан как аналог `<pre>`. Тега для написания моноширинным шрифтом отдельных слов нет.

**Comment by aVadim483** [comment]
>Вообще я не люблю смотреть документацию в том виде, как она сделана в лс и у вас

Увы, но это не документация, а полное ее отсутствие :( Так что все верно, и обижаться тут не на что
