### ISSUE TITLE
Запрос к /ajax/image-manager-load-tree/ не выдаёт «Error #1001» при неверном ответе сервера

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#623]
Сейчас, если при ajax-запросе ожидается json, например, а пришло нечто другое (Fatal Error: бла-бла-бла), то фронтенд никак на это не реагирует и бесконечно показывает полосу загрузки, якобы ожидая ответа, хотя уже давно известно, что ответ некорректен.

**Comment by aVadim483** [comment]
Нет, сейчас, как правило, реагирует - выдает всплывающее сообщение "Error #1001". Это сообщение как раз и означает, что в ответ скрипт получил что-то невразумительное. Возможно, где-то пропущена такая обработка, значит, надо знать, где именно.

**Comment by shtrih** [comment]
В моём случае это запрос к `/ajax/image-manager-load-tree/` на странице редактирования топика. Ошибка «Fatal Error: maximum function nesting level of '100' reached». Детали ошибки пока не описываю, попробую сам разобраться.

**Comment by shtrih** [comment]
Заметил то же поведение при запросе к `/ajax/preview/topic/`.

**Comment by shtrih** [comment]
@aVadim483, В коде в принципе ещё много мест, где не определён коллбек `error`. Проще,  внутри `ls.ajax` прописать в дефолтный коллбек сообщение с ошибкой, а в конкретных местах, где нужно по-особому обработать ошибку, передавать свой параметр `more`.
```javascript
var ajaxOptions = {
// …
function (msg) {
    $that.debug("ajax error: ");
    $that.debug.apply(this, arguments);
    ls.progressDone(true);
    ls.msg.error(null, 'System error #1001');
}.bind(this),
// …
```
