### ISSUE TITLE
При отклонении запроса на подписку на закрытый блог юзер все равно становится его читателем

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#626]
После отклонения заявки пользователя на вступление в закрытый блог он все равно ставится участником закрытого блога и видит все топики. Опции одобрения и отклонения заявки в личном письме работают одинаково. Сообщение «Внимание: Просьба пользователя отклонена» - ложь. В список подписчиков юзер тоже не добавляется и становится "шпионом". Для админов это может стать большим сюрпризом )))

**Comment by bambarbia-kergudu** [comment]
Также из-за этого бага возникает другой — в списке Блогов на счетчике показывается меньшее количество подписчиков, а в самом блоге - большее. Происходит это после того, как пользователь на свой запрос получит отказ от админа и при этом перейдет в блог, на который пытался подписаться, и нажмет на кнопку отписаться.

**Comment by inliquid** [comment]
Я уже постил этот баг. https://github.com/altocms/altocms/issues/561

Удивительно что кто-то еще это стал проверять. Обычно никто дальше главной страницы не идет.

**Comment by bambarbia-kergudu** [comment]
Извините, вашего баг-репорта не заметил. Нашел сам, когда верстал. Очень неприятный баг!
