### ISSUE TITLE
Порядок в методах get*Dir/get*Path

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#637]
Навести порядок в функциях, возвращающих пути. Сейчас оба варианта функций могут возвращать пути как со слешем, так и без слеша (в частности, `E::ModuleViewer()->GetTemplateDir()` возвращает путь без слеша, а `Plugin::GetTemplateDir('mytemplate'))` со слешем). 
Нужно проверить и изменить поведение так, чтобы методы, с суффиком `path`, возвращали путь без слеша на конце. Методы, оканчивающиеся на `dir`, должны возвращать путь со слешем на конце. Наверное, то же самое имеет смысл сделать для переменных.

**Comment by aVadim483** [comment]
Вообще есть стремление по возможности не использовать суффикс ```path``` в тех случаях, когда речь идет однозначно про полный путь на диске (тогда используется суффикс ```Dir```) либо про полный урл (тогда суффикс ```Url```). В большинстве случаев имена методов с ```Path``` используются как алиасы методов с Dir/Url для обеспечения совместимости со старыми наработками. Но в целом замечание верное - поведение этой группы функций должно быть однотипным и предсказуемым

**Comment by shtrih** [comment]
Если подумать, то надёжнее и правильнее будет всегда ставить дополнительный слеш при склеивании путей, чем выдумывать какие-то новые нотации и заставлять других следовать им. Я поискал рекомендации на эту тему, но ничего не нашел, так что решил, что лучше не вводить новых строгих правил.
При работе с файловыми функциями, обычно, двойной слеш в пути обрабатывается как одинарный. Однако, в случае с веб-путями в альто, не знаю, насколько это критично.
