### ISSUE TITLE
Левая ссылка

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#638]
Обновился, появилась какая то левая ссылка правее профиля пользователя "Напишите о себе, не стесняйтесь" при нажатии на нее происходит переход сюда http://youwo.ru/profile/admin/settings/  даже если залогинен обычным пользователем. В любом случае и под админом и под пользователем переход по этой ссылке выдает ошибку: "К сожалению, такой страницы не существует. Вероятно, она была удалена с сервера, либо ее здесь никогда не было."

**Comment by aVadim483** [comment]
А какой шаблон?

**Comment by yuri25** [comment]
В exp-simple и переключал на просто experience

**Comment by yuri25** [comment]
D start-kit тоже самое.... может криво обновился? Но я залил полностью все файлы отсюда, потом вернул старый config.local.php и удалил директорию install...

**Comment by orthograf** [comment]
Плагин MenuTest включен?

**Comment by yuri25** [comment]
Точно! Вот я лошара:) Это из за включенного плагина...
