### ISSUE TITLE
Не работает вставка изображения в комментарии

### ISSUE THREAD

**Issue by mixei-one** [altocms/altocms#639]
![_513](https://cloud.githubusercontent.com/assets/9606311/8929926/d51eb5e0-3531-11e5-821c-57227e291dcb.png)
При потытке вставить изображение в комментарии происходит ошибка. На демо сайте это воспроизводится.

**Comment by aVadim483** [comment]
Не получилось воспроизвести, изображение в комментарий вставилось: http://demo.altocms.com/new/30.html

А какой браузер? Какой размер изображения, какой размер файла и с каким расширением? Возможно, какие-то детали играют роль

**Comment by mixei-one** [comment]
На демо сайте и у меня перестала воспроизводиться ошибка, попробовал с теми же изображениями что и вчера (изображения 250кб, JPEG, браузер хром и опера, ОС - ubuntu). Мистика да и только.

**Comment by aVadim483** [comment]
В последние несколько дней было немало коммитов, возможно, одним из них ошибка была исправлена. Я тикет тогда закрываю, если проблема опять проявится - пишите.
