### ISSUE TITLE
Не работает поиск по комментариям и переключение по вкладкам «Статьи» и «Комментарии»

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#647]
Не срабатывает условие ```{if $bIsResults && $aRes.aCounts}```, которое должно выводить навигацию на странице результатов поиска в шаблоне (\tpls\actions\search\action.search.results.tpl), несмотря на то, что совпадения в топиках найдены. Также не работает поиск по комментариям. Для примера оставил в топике три объемных комментария от разных пользователей с текстом в виде рыбы «Нужно, нужно нужно подкачаться». Попробовал найти слово «нужно» запросом /search/comments/?q=нужно, итог - «Удивительно, но поиск не дал результатов».

**Comment by inliquid** [comment]
А поиск по комментариям в принципе отсутствует сейчас. Тоже была тема в сообществе.

**Comment by bambarbia-kergudu** [comment]
Ох, даже так... не знал, видимо, просто забыли почистить шаблоны и код двига от мусора.

**Comment by aVadim483** [comment]
fixed
