### ISSUE TITLE
Разрешена регистрация с одинаковыми логином и паролем.

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#651]
При регистрации нового юзера разрешено использовать одинаковые логин и пароль, хотя в подсказке говорится обратное. Раньше это было запрещено делать, а потом в какой-то момент стало разрешено, если я ничего не путаю, то это досталось Альто от ЛС. Неплохо было бы поправить «фичу» для улучшения безопасности двига.

**Comment by aVadim483** [comment]
done
