### ISSUE TITLE
Experience Simple игнорирует настройки меню подвала

### ISSUE THREAD

**Issue by Segr** [altocms/altocms#663]
Через админку правлю меню подвала (первую и вторую колонку) - на сайте ничего не происходит.

В шаблоне эти меню вставлены напрямую.

**Comment by aVadim483** [comment]
Не получилось воспроизвести. В шаблоне эти меню вставляются так:
```{menu id='footer_site_menu'}```
```{menu id='footer_info'}```
И движок подхватывает соответствующие конфигурации меню, в т.ч. и измененные через админку

**Comment by Segr** [comment]
В этом шаблоне да, именно так -  common/templates/skin/experience-simple/themes/default/layouts/default.tpl

А вот в этих
common/templates/skin/experience-simple/themes/custom/layouts/default.tpl
common/templates/skin/experience-simple/themes/dark/layouts/default.tpl
common/templates/skin/experience-simple/themes/orange/layouts/default.tpl
напрямую зашиты

**Comment by aVadim483** [comment]
Исправлено
