### ISSUE TITLE
Пр добавлении изображения в топик\комментарий добавляется лишний <img src="" title="" align="" width="100%" />

### ISSUE THREAD

**Issue by Azany** [altocms/altocms#666]

**Comment by aVadim483** [comment]
Не смог это воспроизвести. Вот добавил фото в топик и в комментарий: http://demo.altocms.com/new/blog/admin/35/

Все нормально там

**Comment by Azany** [comment]
Забыл уточнить - при вставке ссылки из интернета (вставить как ссылку)

**Comment by aVadim483** [comment]
Да, точно, есть такое

**Comment by aVadim483** [comment]
fixed
