### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'Autoloader.php' 

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#674]
Обновил папки common и engine
Fatal error: require_once(): Failed opening required 'Autoloader.php' (include_path='.:/usr/share/php:/usr/share/pear:/........../engine/classes/core:/......../engine/classes/abstract:/......../engine/classes/core') in /......../engine/libs/Smarty/libs/Smarty.class.php on line 82

**Comment by aVadim483** [comment]
Почему-то пакет Smarty не полностью загрузился. Обновил

**Comment by yuri25** [comment]
О сейчас работает! Закрывайте.
