### ISSUE TITLE
Стиль в комментариях

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#682]
Добавление в избранное
![screenshot_23](https://cloud.githubusercontent.com/assets/7164280/9397385/a5fe11e0-47a4-11e5-9e64-e66ff7190408.jpg)

**Comment by shtrih** [comment]
Обнови систему, это уже пофикшено должно быть

**Comment by lsnull** [comment]
щас проверю

**Comment by aVadim483** [comment]
Проверили?

**Comment by shtrih** [comment]
Вот эта правка https://github.com/shtrih/altocms/commit/f9d82e404270c181466e6ba12a5c55513c1bb2b7#diff-9927abd0b981ca0458a006d6d3165cc5
