### ISSUE TITLE
Notice: Use of undefined constant DEBUG - assumed 'DEBUG' in....

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#686]
Установка не запускается:
Notice: Use of undefined constant DEBUG - assumed 'DEBUG' in /....../engine/classes/core/Config.class.php on line 366
Notice: Use of undefined constant DEBUG - assumed 'DEBUG' in /....../engine/classes/core/Config.class.php on line 390

Эти строки повторяются на экране 28 раз

И два раза вот эта строка:

Fatal error: Class 'C' not found in /..../engine/classes/core/Loader.class.php on line 475

**Comment by aVadim483** [comment]
fixed
