### ISSUE TITLE
Неправильные пропорции при сохранении аватарки

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#687]
Иногда происходит странная история. Несмотря на то что js плагин, который используется в альто для кропа аватарки настроен на одинаковые пропорции, т.е. на выбор квадратной области, иногда вырезается область чуть отличающаяся от квадрата. К примеру, есть недавний пример когда вместо 500x500 у пользователя сохранилась аватарка размером 502x500.

А дальше начинаются вообще чудеса. В выводе комментариев из нее  должен вырезаться опять же квадрат 60x60, но почему-то вырезается что-то типа 50x60. Примерно похожая история в профиле, где размер больше. Искажения изображения очень сильные.

Такой случай происходил уже дважды и он исправлялся только пересохранением руками оригинала аватарки в размере 500x500.

**Comment by aVadim483** [comment]
Небольшие искажения пропорций (например, 502x500) в версии 1.0 теоретически могут быть из-за специфики используемого алгоритма уменьшения изображений. В версии 1.1 алгоритм изменен, и такого быть не должно. Но вот отчего могут быть такие сильные искажения, как 50x60 - я даже представить не могу. Но попробую понять

**Comment by inliquid** [comment]
Эти сильные искажения возникаю когда оригинал сохраняется с небольшими искажениями по одной из сторон. Если их убрать и удалить производные изображения то все вызовы типа 60x60 отрабатывают нормально и искажений больше нет.

**Comment by aVadim483** [comment]
Т.е. сначала квадратная картинка сохраняется 502x500, а потом при уменьшении она же становится 60x50?

**Comment by inliquid** [comment]
Да, только в этом случае. 50x60 это примерно, не сохранил к сожалению точные значения.

**Comment by aVadim483** [comment]
Понял, попробую понять возможную причину
