### ISSUE TITLE
Старая проблема с преобразованием ссылки

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#688]
Не ожидал что это все еще актуально, но факт.
Если в тексте топика добавить ссылку типа http://example.com, (после которой стоит запятая) - она таки преобразуется в ссылку с запятой в конце в href.

**Comment by aVadim483** [comment]
К сожалению, не только запятая, там и другие знаки пунктуации включаются в URL. Это проблема типографа Jevix. Единственная приемлемая альтернатива, которую удалось найти, это Qevix - https://github.com/AlexanderGrom/Qevix/

Qevix добавлен в качестве эксперимента в версию 1.1.6. Если результаты будут положительные, то в будущем он может стать типографом по умолчанию.
