### ISSUE TITLE
Antibot просто ломает форму регистрации

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#693]
Если нормальный юзер, IP которого был внесен давным давно в базу SFS, пытается зарегистрироваться то 
- во-первых не отрабатывают проверки полей (молча без ошибок)
- во-вторых при отправке формы просто бесконечно висит индикатор обновления

Нормальное поведение подразумавает, что при срабатывании защиты в форме должно появляться (незакрываемое!) сообщение об ошибке, текст которого настраивается в языковом файле, и в которое можно передать %ip% юзера.

**Comment by shtrih** [comment]
>Совместимость: AltoCMS 1.0.+
Может, в этом проблема?

**Comment by inliquid** [comment]
У меня версия AltoCMS 1.0.+
