### ISSUE TITLE
Не работают некоторые функции сайта после сегодняшнего обновления 23.10

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#697]
Только что скачал отсюда актуальную версию.
Обновился, почистил кеш и все такое. Отключил все плагины... Ну это я говорю, что бы в очередной раз не раздувался диалог и не задавались эти вопросы в мою сторону.
После чего:
Перестали открываться подменю (выпадающие) и меню пользователя
Не отображается прямой эфир
![screenshot_24](https://cloud.githubusercontent.com/assets/7164280/9532565/0cf3363a-4d15-11e5-974a-41398649c393.jpg)
Дальше в админке заметил, что шаблон не активирован, но работает на сайте тот который задан был в конфиге походу.
![screenshot_25](https://cloud.githubusercontent.com/assets/7164280/9532576/2fd93ac8-4d15-11e5-86b7-715b2c919643.jpg)
Нажимаю Активировать страница перегрузилась и все по прежнему. Так и на сайте с Меню пользователем, нажимаю открыть выпадающее а мне страница перегрузилась и все....
И это наверное только часть...

**Comment by aVadim483** [comment]
Это явно проблемы с javascript. Знаете, как проверить ошибки javascript?

**Comment by lsnull** [comment]
нет. скажите проверю или дать адресс?

**Comment by aVadim483** [comment]
Скажите адрес сайта, я посмотрю

**Comment by lsnull** [comment]
losper.net

**Comment by aVadim483** [comment]
На сайте не грузится бОльшая часть скриптов

**Comment by lsnull** [comment]
немогу понять почему. я 3 раза перезаливал

**Comment by aVadim483** [comment]
Без доступа к хосту я не могу сказать. 

Еще раз удалите все содержимое папок /_tmp/templates, /_tmp/cache и /_run/assets
Если не поможет, то удалите полностью папку с шаблоном и залейте его еще раз (после обновления опять же надо очистить папки, что указал выше)

**Comment by aVadim483** [comment]
В конфигах нигде не встречается комбинация `$config['head']['default']['js']`?

**Comment by lsnull** [comment]
щас гляну конфиг

**Comment by lsnull** [comment]
нет не встречается такая комбинация. удалил содержимое /_tmp/templates, /_tmp/cache и /_run/assets. Все так же...

**Comment by aVadim483** [comment]
Говоря про конфиги и `$config['head']['default']['js']` я имел ввиду ВСЕ конфиги - в /common/config, в /app/config, конфиг скина и конфиги всех активных плагинов

**Comment by lsnull** [comment]
все плагины отключены. /common/config, в /app/config тоже нет. да я и правок никаких не делал

**Comment by lsnull** [comment]
все работало пока я не обновился уже вчера...

**Comment by aVadim483** [comment]
Без доступа к хосту и не видя сайт изнутри больше ничего не могу сказать. Такое впечатление, что какие-то старые конфиг-файлы подхватываются, да и то не полностью

**Comment by lsnull** [comment]
проблемма была в App \ templates \ skin (еще там были experience-simple/settings/config и все остальные конфиги)

**Comment by lsnull** [comment]
Все заработало. Но вот Админку проверьте. по поводу выбора - Активации шаблона для сайта

**Comment by aVadim483** [comment]
Админку проверю
