### ISSUE TITLE
class 'Qevix' does not have a method 'cfgSetAutoReplace' 

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#703]
В админке показывает такое предупреждение:
E_WARNING [2] call_user_func_array() expects parameter 1 to be a valid callback, class 'Qevix' does not have a method 'cfgSetAutoReplace' (/...../epmg.ru/engine/classes/modules/text/Text.class.php on line 161)

**Comment by yuri25** [comment]
Да забыл, еще такое есть: E_WARNING [2] call_user_func_array() expects parameter 1 to be a valid callback, class 'Qevix' does not have a method 'cfgSetTagParamCombination' (/...../epmg.ru/engine/classes/modules/text/Text.class.php on line 161)

**Comment by aVadim483** [comment]
Оказалось, что Qevix не на 100% совместим с Jevix. Я эти ошибки пофиксил, но закрывать тикет не буду, т.к. это временный костыль, нужно будет эти методы обязательно добавить.

**Comment by yuri25** [comment]
Обновил до 1.1.8, прописал в конфиге Qevix, теперь такое выдает в админке, в ошибках системы:

E_WARNING [2] Missing argument 4 for ModuleText::CallbackCheckLinks() (/...../epmg.ru/engine/classes/modules/text/Text.class.php on line 593)
2015-08-31 12:22:17
E_WARNING [2] call_user_func_array() expects parameter 1 to be a valid callback, class 'Qevix' does not have a method 'cfgSetTagCallbackFull' (/....../epmg.ru/engine/classes/modules/text/Text.class.php on line 168)

**Comment by shtrih** [comment]
Фотосет, вставленный в редакторе, выводится неправильно при включённом qevix:
![_064](https://cloud.githubusercontent.com/assets/544063/9604150/5bd9b146-50be-11e5-8a01-60d0d7ed642a.png)

**Comment by bambarbia-kergudu** [comment]
Логи ошибок очень быстро разрастаются из-за предупреждения "class 'Qevix' does not have a method 'cfgSetTagCallbackFull'". Каждое действие на сайте добавляет по две ошибки в лог.

**Comment by shtrih** [comment]
@bambarbia-kergudu а ты отключи пока qevix. До закрытия этой задачи.

**Comment by aVadim483** [comment]
Всем спасибо за фидбэк, на днях ожидается обновление Qevix

**Comment by aVadim483** [comment]
Обновил обработку с помощью Qevix (в текущей дев-версии), теперь ошибок с cfgSetTagCallbackFull и проч. быть не должно. 

Но вот со вставкой фотосета в топик пока проблема - это баг самого Qevix (спотыкается он на атрибутах с дефисом, типа `data-rel="..."`.

**Comment by bambarbia-kergudu** [comment]
Хотел от Jevix'а полностью отказаться, но из-за проблем со сниппетами фотосета придется остаться пока на нем.

**Comment by aVadim483** [comment]
Есть уже новый релиз Qevix, где эта проблема должна быть решена: https://github.com/AlexanderGrom/php-qevix/releases/tag/0.3.1

Из ченджлога: "имена атрибутов теперь могут быть с дефисом". Можешь попробовать самостоятельно обновленный Qevix залить, либо я в конце недели новый релиз выкачу, где он будет обновлен

**Comment by bambarbia-kergudu** [comment]
Отлично, буду копаться ).

**Comment by bambarbia-kergudu** [comment]
Теперь все работает, фотосеты и сниппеты вставляются нормально.
