### ISSUE TITLE
Кислотный ад при обработке некоторых картинок

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#713]
Имеем такой файл на вход. 
![default](https://cloud.githubusercontent.com/assets/6797881/9671017/7d5047be-5298-11e5-8082-0dfdf5b1c744.jpg)

Вот что получаем при обработке движком (топик, комментарий, фотосет - идентично)
![0u3fa34d80-7ef7fa75-5dab552f](https://cloud.githubusercontent.com/assets/6797881/9671023/8a351ebe-5298-11e5-8448-daf5d32117a1.jpg)

**Comment by shtrih** [comment]
Ну тут проблема в библитеке по работе с картинками. Нужно локализовать проблему: понять, какой именно библиотекой обрабатывается картинка, воспроизвести ошибку с использованием только библиотеки, без AltoCms, написать багрепорт авторам библиотеки, если проблема в ней.

**Comment by aVadim483** [comment]
При загрузке этой страницы я получаю интересный эффект: верхняя (темная) картинка сначала загружается (на какое-то мгновение) отображается в точно таком же "кислотном" виде, как нижняя, а потом темнеет. Возможно, причина в каких-то параметрах JPEG. Причину пока не исследовал.

В Альто используется библиотека PHPixie/Image

**Comment by inliquid** [comment]
Естественно используется Imagick. По всей видимости в jpeg не проставлены или используются нестандартные цветовые представления, а при обработке устанавливаются или не те, какие заданы в файле, или какие-то дефолтные, не совпадающие с фактическими. Например rgb вместе cmyk или наоборот.
