### ISSUE TITLE
Сменился приоритет применения настроек в виджетах

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#716]
Пытаюсь изменить количество ссылок в блоке «Прямого эфира». Скопировал блок настроек из файла \www\common\config\widgets.php в файл настроек шаблона \www\common\templates\skin\experience-simple\settings\config\widgets.php, меняю параметр 'limit' => 20, ничего не происходит, изменения видны только после правки в главном файле настроек виджета.

Если нужно вывести список блогов в сайдбаре на всех страницах, приходится в главном файле удалять строки action, иначе список выводится согласно стандартным правилам, настройки виджетов шаблона при этом игнорируются.

Проблема появилась то ли в версии 1.1.2, то ли 1.1.4.

**Comment by aVadim483** [comment]
Видимо, это побочный эффект оптимизации. Проверю

**Comment by aVadim483** [comment]
fixed
