### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#718]
Скачал только что Архив Альто
Загрузил на субдомен и не устанавливается движок.:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@go.losper.net and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by shtrih** [comment]
Этого недостаточно. Посмотри подробности в логах сервера.

**Comment by lsnull** [comment]
Я гребу где эти логи. Такое спросили )))) 
Но Альто у меня стоит. Только я ставил ее, когда была версия 1.1 и обновлял... Это я решил на другой субдомен установить, так как мне база нужна чистая. Но увы не инсталит

**Comment by aVadim483** [comment]
Спросите у хостера, где можно посмотреть серверные ошибки такого-то домена. Ибо хз, что там серверу не нравится

**Comment by lsnull** [comment]
Я понял. Но это уже тогда позже. Так как там нет Тикетов а Только через почту в писменном виде общатся. А это долго да и в выходные они не работают

**Comment by aVadim483** [comment]
Иногда в хостинговой панели есть такой раздел, где можно увидеть ошибки сервера

**Comment by lsnull** [comment]
модскажите плз с http://altocms.ru/1327.html я незнаю куда публиковать это сюда или на сайт.

**Comment by aVadim483** [comment]
Если по этой проблеме больше ничего, то закрываю
