### ISSUE TITLE
Счетчик сайта через админку

### ISSUE THREAD

**Issue by lsnull** [altocms/altocms#719]
я думаю на скриншотах все видно и понятно будет ;)
![screenshot_5](https://cloud.githubusercontent.com/assets/7164280/9706672/c802c20a-54f5-11e5-801d-aac0b74c322f.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/7164280/9706661/888d22c8-54f5-11e5-942b-b740bf73da49.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/7164280/9706662/888e3f78-54f5-11e5-826a-f829fe363e00.png)

**Comment by aVadim483** [comment]
fixed
