### ISSUE TITLE
Удаленное сообщение в личке отображается пользователю

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#720]
Если удалить отправленное в личку сообщение, его получатель продолжает его видеть, но не может на него ответить (блок с комментариями отсутствует). Выглядит как глюк.

**Comment by shtrih** [comment]
Должна быть возможность ответить.

**Comment by bambarbia-kergudu** [comment]
На мой взгляд тут надо слегка пересмотреть логику: если письмо удаляет автор (инициатор беседы), то оно должно удаляться из бд полностью со всеми ответами (сейчас оно остается). Если пользователь удаляется самостоятельно или его удаляет автор, то это должно приводить к отписке от беседы, при этом само письмо остается в бд и все приглашенные к беседе могут продолжать общаться. С удалением автора письма у всех остальных пропадает возможность добавить к беседе кого-либо еще. 

Второй вариант: если автор удалил переписку до появления в ней ответов, то ее можно удалять полностью из бд, а не ждать «согласия» получателя. Ответить он все равно уже не сможет, что наглядно показано в описанном выше багрепорте.

Третий вариант: сделать для автора две функции - возможность отписки от своей же темы и удаления лс. При отписке он просто выходит из беседы (участники теряют админа и возможность приглашения новых участников в беседу, но могут дальше общаться между собой, если собеседников два или более), при удалении - вся переписка полностью удаляется со всеми сообщениями из бд. Если автор отписывается, в начальном сообщении появляться предупреждение об его отписке или сколько человек участвует в беседе.

Пока тестировал, нашел еще один баг: при повторной попытке приглашения самостоятельно удалившегося пользователя в ранних версиях альто появлялось сообщение «Юзер удалил переписку», в шаблоне Simple Experience все оканчивается появлением в ссылке слова undefined, сообщения вообще нет.

Альто 1.1.8

**Comment by inliquid** [comment]
Это все слишком сложная логика, и не нужно. Просто удалять и все. Если автор топика его удаляет, тоже все молча удаляется без каких-либо отписок.

**Comment by aVadim483** [comment]
Здесь сообщения - это не просто сообщения, это - разговор, в котором может участвовать несколько человек (а не два). И если я затеял какую-то беседу, а потом (в силу разных причин) не хочу в ней участвовать, то это еще не значит, что я обязательно должен ее убивать.

Думаю, логичным будет для инициатора разговора иметь две опции - удаления и отписки.

Правда, тут возникают следующие вопросы:
1) Если участников двое и один отписался, то оставшийся может быть удивлен, что не может написать ответ (на то, что в списке собеседников он остался один, он не сразу обратит внимание, если вообще обратит)
2) Если инициатор грохнет тему, то остальные участники точно так же могут быть в недоумении, куда это девался разговор.

И в обоих случаях с большой долей вероятности юзеры решат, что имеет место баг. Видимо, нужно в обоих случаях как-то отмечать действие. В первом - делать запись в теме, что такой-то участник отписался от темы разговора. Во втором - заголовок оставлять, но все сообщения удалять, и при клике выдавать, то тема удалена.

**Comment by inliquid** [comment]
я не просто так написал про топик. в комментарии к топику может быть сто человек поучастовало, и хотело бы продолжить, однако, автор может его удалить. на то оно и удаление.

**Comment by shtrih** [comment]
Я считаю, что удалять что-либо, без ведома других участников беседы, нельзя. Может быть оставить возможность создателю закрыть тему? А всем остальным сделать возможность скрыть беседу. Как только последний участник скрывает разговор — он удаляется.

**Comment by aVadim483** [comment]
Скрыть тему == отписаться

**Comment by bambarbia-kergudu** [comment]
Я склоняюсь к третьему из предложенных мною вариантов. В любом случае у автора беседы должна быть возможность удалить ее полностью, без необходимости отписки других участников. В качестве уведомления об удалении переписки можно отправлять сообщение на мыло участников, чтобы не захламлять бд всякими "метками". Также нужно более явно выделять участников беседы и показывать предупреждение, если в переписке остался один участник.

**Comment by shtrih** [comment]
>более явно выделять участников беседы и показывать предупреждение, если в переписке остался один участник.

Может быть, как-то так?
![_067](https://cloud.githubusercontent.com/assets/544063/9729704/e7093006-5619-11e5-87f0-f04b356bd963.png)
