### ISSUE TITLE
Ошибка при активации плагинов

### ISSUE THREAD

**Issue by yuri25** [altocms/altocms#723]
Обновился с гита... почему то стало выдавать такую ошибку в админке, причем первый плагин активируется а потом любой другой и выдает эту ошибку.
Fatal error: Call to a member function GetCompatible() on a non-object in /..../epmg.ru/engine/classes/modules/viewer/Viewer.class.php on line 841

**Comment by yuri25** [comment]
А вообще я подозреваю что каким то образом связано с плагином LS Compatibility... потому как при его активации впервые выдало эту ошибку и сейчас проверил, активировал все плагины, потом LS Compatibility - и сразу эта ошибка...

**Comment by bambarbia-kergudu** [comment]
@shtrih уже словил эту ошибку - http://altocms.ru/1330.html

**Comment by aVadim483** [comment]
fixed
