### ISSUE TITLE
Форма «Написать заметку» в профиле пользователя видна неавторизованным юзерам

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#724]
Можно попробовать что-то написать, но в ответ бесконечная загрузка (на самом деле `{"sMsgTitle":404,"sMsg":"К сожалению, такой страницы не существует. Вероятно, она была удалена с сервера, либо ее здесь никогда не было.","bStateError":true}`).
Замечено в experience-simple. Другие не проверял.

**Comment by bambarbia-kergudu** [comment]
Блок и не должен показываться никому, кроме авторизованного юзера. При верстке шаблона накосячили.

**Comment by shtrih** [comment]
Ага, потому и добавил топик.

**Comment by aVadim483** [comment]
fixed
