### ISSUE TITLE
Возвращение бага с меню после включения "песочницы" - BLOG_MENU_ALL_GOOD}}{{BLOG_MENU_ALL_GOOD

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#726]
В чистой системе 1.1.8 установил плагин «песочница». Перешел в админке на страницу «Менеджер меню» - «Меню топиков», ссылка плагина «песочница» выводится в конце списка. Перетаскиваю ее на третью позицию, перезагружаю страницу, меню на сайте слетает:

http://s7.hostingkartinok.com/uploads/images/2015/09/5080ad19ecb16d760285202144f8088c.jpg

То же самое происходит при изменении видимости любого из пунктов, то есть с включенной «песочницей» до меню вообще нельзя дотрагиваться.

На странице логов после попытки редактирования меню появляется предупреждение:
```E_WARNING [2] strpos() expects parameter 1 to be string, array given (Z:\home\alto118.ru\www\engine\classes\core\Config.class.php on line 390) ```

Без плагина песочницы пункты меню передвигаются без ошибок.

**Comment by shtrih** [comment]
Лучше сюда, наверное: https://github.com/altocms/alto-plugin-sandbox/issues

**Comment by aVadim483** [comment]
Подозреваю, что это с Config проблема, так что все верно, сюда

**Comment by aVadim483** [comment]
Оказалось, что там была не одна причина, а несколько. Работу с меню улучшена. Версия движка обновлена до 1.1.9 и плагин также обновлен и требует версии не ниже 1.1.9. 

После обновления ошибка не воспроизводится, пункт "Песочница" добавляется при активации плагина, удаляется при деактивации, перемещение/редактирование пунктов меню выполняется без проблем.

Есть только один непонятный баг, который то появляется, то исчезает при перетаскивании пунктов меню: в процессе перетаскивания перетаскиваемый элемент отображается выше места, где он должен быть. Причем, помню, что когда-то боролся с подобным багом и победил, но не помню как.

**Comment by bambarbia-kergudu** [comment]
Спасибо. А где взять версию 1.1.9, чтобы потестить? О релизе ничего нигде не сказано.

**Comment by shtrih** [comment]
Ага, чето тега-то нету: https://github.com/altocms/altocms/tags

**Comment by aVadim483** [comment]
Да, не тегировал еще, пока это текущая дев-версия

**Comment by aVadim483** [comment]
С багом при перетаскивании тоже разобрался. Как только затегирую версию, этот тикет закрою

**Comment by bambarbia-kergudu** [comment]
Спасибо, чуть позже проверю на локалке.

**Comment by bambarbia-kergudu** [comment]
Проблема решена
