### ISSUE TITLE
Отвалилась подгрузка исходного текста при редактировании комментария

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#727]
При редактировании комментария редактируемый текст не подгружается в текстовое поле textarea. Функция сломалась после последних изменений формы в версии 1.1.8.

**Comment by shtrih** [comment]
По редактированию: если разрешить редактирование, то юзеру отображается уже сгенерированный хтмл-код, а не исходный текст комментария. Это связано с тем, что исходный текст комментария не сохраняется.

**Comment by bambarbia-kergudu** [comment]
Да конечному юзеру наплевать, как и что там происходит, ему нужно как было в предыдущией версии - кликнул по редактированию, получил текст, а не пустое поле ))

**Comment by shtrih** [comment]
Не совсем, ведь вылазиет совсем не то, что писал юзер. Плюс, зачастую, с убранными переносами. Например, юзер написал такое:
```html
<alto:spoiler>Text</alto:spoiler>
```
а при редактировании увидел это:
```html
<div class="spoiler"><div class="spoiler-title"><div class="spoiler-slider">Показать содержимое</div</div><div class="spoiler-text">Text</div></div>
```
Разница очевидна.

**Comment by bambarbia-kergudu** [comment]
Я лишь предупредил о том, что в предыдущей версии редактирование комментариев после отправки работало корректно. Сейчас вместо подгрузки текста появляется пустое текстовое поле. То есть для редактирования коммента юзеру нужно сначала скопировать свой коммент, потом вставить в текстовое поле, а потом только начать править ошибки.

**Comment by aVadim483** [comment]
Собственно, сам баг пофиксил. А что касается сниппетов - замечание верное
