### ISSUE TITLE
Неверное перенаправление на странице

### ISSUE THREAD

**Issue by TheDreik** [altocms/altocms#730]
Если символьный код блога участвует в формировании урла и написан с большой буквы, то в топиках этого блога будет ошибка с неверным перенаправление на странице. Лечится на данный момент исправлением символьного кода на маленькую букву.

**Comment by aVadim483** [comment]
Не получилось воспроизвести. Можете привести пример - какой URL и какие получаются у топиков

**Comment by TheDreik** [comment]
Ссылка на статьи сделана так: blog/%blog_url%/%postname%.html
Перенаправление было при таком урле: /blog/Ivanhoe_eternal_drunk/posovetujteindirpg.html
Исчезло при замене символьного кода блога, когда ссылка стала такой: /blog/ivanhoe_eternal_drunk/posovetujteindirpg.html

**Comment by Liandr** [comment]
Подтверждаю.
Стоит шаблон %login%/%topic_id%/%topic_url%
С альто 1.0 работало нормально, в 1.1 не хочет - бесконечный редирект.
Если поставить шаблон %topic_id%.html - всё работает.

**Comment by aVadim483** [comment]
Исправлено, проверил у себя с обоими шаблонами: blog/%blog_url%/%postname%.html и %login%/%topic_id%/%topic_url% - работает корректно

**Comment by Liandr** [comment]
Патч проблему не решил.

**Comment by Liandr** [comment]
%login%/%topic_id%/%topic_url% - не работает, бесконечный редирект.
%topic_id%/%topic_url% - работает нормально

**Comment by aVadim483** [comment]
Еще раз перепроверил - не обнаружил проблем. Вот на демо-сайте сейчас создал топик, задав шаблон %login%/%topic_id%/%topic_url% - http://demo.altocms.com/new/index/new/

**Comment by Liandr** [comment]
Вижу.
Но у меня на последней ревизии ActionBlog.class.php хоть убей не работает.
В любом другом варианте из 2-х переменных работает, т.е.
%login%/%topic_id%
%login%/%topic_url%
%topic_id%/%topic_url%
- все ок.

Использую postgresql-модификацию, но с учётом вышесказанного вряд ли в этом проблема.

**Comment by aVadim483** [comment]
А это с любым логином так? В теории могу предположить, что с каким-то определенным логином возникает URL, который попадает под иную маску движка. 

А Постгресс, конечно, никак тут влиять не может

**Comment by Liandr** [comment]
Да, с любым.
Поэксперементировал сейчас с кодом.
Всё начинает работать, если закомментировать блок
https://github.com/altocms/altocms/blob/ce030deae7e078ddef3bae7f1e13b2c7c151b842/common/classes/actions/ActionBlog.class.php#L804-L808

**Comment by Liandr** [comment]
R::GetPathWebCurrent() возвращает url с ником, приведенном к нижнему регистру, а $this->oCurrentTopic->getUrl() - оригинальный ник (включая буквы с верхним регистром).
Только теперь не понятно, почему данный if не true при шаблоне %login%/%topic_url%
