### ISSUE TITLE
У некоторых пользователей вместо загруженной аватарке ссылка на случайный пост

### ISSUE THREAD

**Issue by TheDreik** [altocms/altocms#731]
Собственно суть в заголовке. Уже у двух пользователей после загрузки автарки src изображения ведёт на какой-нибудь из постов сайта. В обоих случаях посты разные. Логики не заметил. Шаблон start-kit, версия альто последняя с сайта.
Использованные плагины: LS Compatibility, Categories, Alto Banneroid, Рейтинговая система, Similar Topics.

**Comment by shtrih** [comment]
А без плагинов получается повторить?

**Comment by TheDreik** [comment]
Проблема в том, что я не знаю как этого добиться и почему у юзеров так происходит. Когда сам ставлю аватарку - всё нормально.

**Comment by TheDreik** [comment]
Новая инфа - пост вместо аватарки появляется с таким же айдишником, как сама аватарка. А если поста с айдишником как у юзера нет, то аватарка ставится корректно.

**Comment by aVadim483** [comment]
А вот это очень интересно. А есть возможность кратковременно отключить плагины и посмотреть, исправились "кривые" аватары или нет? Т.е. хочется понять - это они так в базу пишутся или по пути из базы на страницу какой-то из плагинов их ломает?

**Comment by TheDreik** [comment]
Попробую попозже отключить всё. Но сразу могу добавить, что в user_profile_avatar у таких пользователей содержится NULL.

**Comment by TheDreik** [comment]
Без плагинов ничего не меняется, проблема остаётся. Такое ощущение, что проблема где-то в структуре БД после её обновления для 1.1.

**Comment by TheDreik** [comment]
В общем кажется корень проблем в оставшейся папке blog-branding от отключённого плагина брендирования блогов. Не имею никакого представления, каким образом само по себе наличие папки ломает отображение аватарок даже при чистой переустановке.

**Comment by TheDreik** [comment]
Докопался до того, что у аватарки этих пользователей не имеют записи в таблице mresource_target

**Comment by TheDreik** [comment]
Всё, я нашёл корень всех проблем.
В \common\classes\modules\uploader\Uploader.class.php::
    public function GetTargetUrl($sTargetType, $iTargetId) {
        if (mb_strpos($sTargetType, 'single-image-uploader') === 0 || $sTargetType = 'photoset' || $sTargetType = 'topic') {

Идут в условиях вместо сравнения приравнивания. Соответственно на этом моменте тип медиаресурса меняется на топик всегда, что определённо в дальнейшем вносит такой хаос. Я только не понимаю как так вышло, что это проявилось лишь у меня на сайте.
