### ISSUE TITLE
Перестали передаваться аргументы хуков

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#732]
Есть 2 плагина, использующих хук `template_topic_content_begin`. У хука есть 2 аргумента. Но после сегодняшнего обновления, аргументы в коллбек хука вообще не передаются. Пробовал переключаться на предыдущую ревизию (f583e360), там проблемы нет.

**Comment by aVadim483** [comment]
А коллбек как оформлен?

**Comment by shtrih** [comment]
```php
public function RegisterHook () {
    $this -> AddHook ('template_topic_content_begin', 'myCallback');
}

public function myCallback($aVars) {
    var_dump($aVars); // NULL
}

**Comment by shtrih** [comment]
Если отключить плагины лс, использующие этот хук, то хук в новом плагине работает нормально.

**Comment by shtrih** [comment]
Судя по всему, первый в списке обработчик отрабатывает нормально, а на втором всё заканчивается.

**Comment by aVadim483** [comment]
Понял, проверю

**Comment by shtrih** [comment]
Вот тут оригинальное значение становится null: `$this->aCurrentHookArguments = null;` 
https://3v4l.org/Ulps4

**Comment by aVadim483** [comment]
Пофиксил. Там вообще не имеет смысла делать присвоение по ссылке. И пока разбирался выяснил интересное поведение php ф-ции arsort(), из-за которого хуки с одинаковым приоритетом выполнялись в обратном порядке. Тоже заодно пофиксил
