### ISSUE TITLE
Вопрос по отдаче файлов

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#735]
Пилю плагин по прикреплению файлов к топику и возникла проблема, что урлы вида `http://example.com/myaction/myevent/42/file-name.jpg` выдают 404 ошибку. К тому же, без выдачи стандартной страницы для такого рода ошибок. Выяснилось, что за это отвечает строка:
https://github.com/altocms/altocms/blob/master/common/config/config.php#L632

В связи с тем, что в .htaccess прописано следующее:
```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ ./index.php
```
можно сделать вывод, что обрабатываются только урлы скриптов, но никак не урлы фактически существующих статических файлов.
Поскольку эта строка не выполняет свою работу, может быть, от неё вовсе отказаться? Если нет, то как мне решить вопрос с отдачей файлов скриптом из плагина?

**Comment by aVadim483** [comment]
Да, предполагается, что статика (файлы с определенным набором расширений, включая картинки) либо явно отдается сервером, либо ее просто нет. И если ее нет, то запрос будет адресовываться движку, а движок обрубает обработку такого запроса (ведь файла нет) на ранней стадии. Такой подход позволяет значительно разгрузить движок, когда идут запросу к несуществующим картинкам и прочей статике (а такое на живых проектах случается нередко). 

Простой пример: по каким-то причинам нет аватары, и мы загружаем страницу, где эта аватара встречается с десяток раз (лента топиков, лента комментариев с активным юзером и т.д.). И тогда (если этого правила не будет) с десяток раз будет вхолостую запускаться движок и обрабатывать несуществующий УРЛ по полной, с попыткой определить экшен, с генерацией вебстраницы и т.д.

Решение:
Добавить в конфиг-секцию `router.uri` правило на обработку определенного УРЛа, чтоб это правило шло первым. Примерно так, как сейчас задается правило на обработку ассетов, например, что-то типа:
```
$aRules = Config::Get('router.uri');
$config['$root$']['router']['uri'] = array(
    '[~^attach/(\d+)/([\w\-\.]+/.+)$~i]' => 'asset/$1/$2',
) + $aRules;
```

**Comment by shtrih** [comment]
Ещё нехватает константы типа медиа-ресурса. Например, у меня разрешено загружать файлы любого типа, в `Mresource` доступно [7 констант](https://github.com/altocms/altocms/blob/master/common/classes/modules/mresource/Mresource.class.php#L17-L23), которые не подходят для загружаемых файлов в моем случае. Нужно что-то более абстрактное, типа «прочие файлы».

**Comment by shtrih** [comment]
Для роутера написал:
```php
$aRules = Config::Get('router.uri');
$config['$root$']['router']['uri'] = array(
    '[~^myfileupload/get/(\d+)/.+$~i]' => 'myfileupload/get/$1'
) + $aRules;
```
Но это ни на что не повлияло. Урл вида `http://altocms.lcl/multiplefileupload/get/64/my-file.jpg` выдаёт 404.

**Comment by shtrih** [comment]
Вывел [$aRouterUriRules](https://github.com/altocms/altocms/blob/master/engine/classes/core/Router.class.php#L428). Моё правило есть, но на последнем месте.

**Comment by aVadim483** [comment]
Видимо, без Config::Set() тут не обойтись. Позже посмотрю, сейчас нет возможности

**Comment by shtrih** [comment]
Ок. В моём случае, солюшеном будет:
```php
Config::Set(
    'router.uri',
    [
        '[~^(multiplefileupload/get/\d+)/.+$~i]' => '$1',
        Config::KEY_REPLACE                      => true,
    ] + Config::Get('router.uri')
);
```

**Comment by shtrih** [comment]
Ну и вопрос по константам https://github.com/altocms/altocms/issues/735#issuecomment-141039552 всё ещё актуален.
