### ISSUE TITLE
Возможные проблемы с youtube и другими видео сервисами

### ISSUE THREAD

**Issue by 1099511627776** [altocms/altocms#737]
Возможны проблемы при отображении видео на сайтах с http**S** вот в этом коде
```
       $sText = preg_replace(
            '/<video>http(?:s|):\/\/(?:www\.|m.|)youtu\.be\/([a-zA-Z0-9_\-]+)(&.+)?<\/video>/Ui',
            '<iframe width="' . $iWidth . '" height="' . $iHeight . '" src="http://www.youtube.com/embed/$1" ' . $sIframeAttr . '></iframe>',
            $sText
        );
```
Этот код вызовет в Mozilla Firefox ошибку [mixed content blocking] (https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23/)
для решения этой проблемы есть 2 варианты
1. *src="http://www.youtube.com/embed/$1"** меняем на *src="//www.youtube.com/embed/$1"*
2. Переделываем логику регекспа чтоб он также выбирал протокол из УРЛа

П.С. могу сделать pull request но надо определится с методом. Жду предложений

**Comment by aVadim483** [comment]
Вариант 1 мне кажется более верным

**Comment by 1099511627776** [comment]
Согласен но такой вариант может не работать с некоторыми очень старыми браузерами. Насколько старыми - пока не готов ответить

**Comment by aVadim483** [comment]
Боюсь, с очень старыми браузерами у нас много чего может не работать. Например, те же атрибуты тегов "data-", которые активно используются, да и универсальный `<!DOCTYPE html>` - это ж все HTML5, который тоже старыми браузерами не понимается
