### ISSUE TITLE
Фикс для быстрого постраничного перехода

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#740]
Фикс для быстрого постраничного перехода при клике на иконки вверх-вниз в тулбаре. В коде были поставлены заглушки, а рабочий код, унаследованный от ЛС, удален. Сейчас при достижении последнего топика переход на следующую страницу не происходит. Оформите кто-нибудь фикс:

\common\templates\frontend\libs\js\engine\toolbar.js

Найти строку 64:
```
ls.pagination.next(true);
```

Заменить на:
```
            var page=$('.js-paging-next-page');
            if (page.length && page.attr('href')) {
                window.location=page.attr('href')+'#goTopic=0';
            }
```
Найти строку 78:
```
ls.pagination.prev(true);
```

Заменить на:
```
            var page=$('.js-paging-prev-page');
            if (page.length && page.attr('href')) {
                window.location=page.attr('href')+'#goTopic=last';
            }
```

\common\templates\skin\experience-simple\tpls\commons\common.pagination.tpl

Найти 21 строку и вставить в class
```
js-paging-prev-page
```

То же самое проделать в шабе experience

После фикса файл \common\templates\frontend\libs\js\engine\pagination.js, возможно, будет не нужен.

**Comment by shtrih** [comment]
На самом деле, по адресу `common/templates/frontend/ls/js/toolbar.js` есть аналогичный скрипт, в котором всё именно так, как ты хочешь сделать. Наряду с `common/templates/frontend/libs/js/engine/toolbar.js`, подключен также скрипт `common/templates/frontend/libs/js/engine/pagination.js`, который и отвечает за метод `ls.pagination.next(true)`. Переход по страницам не работает потому, что в pagination.js прописаны селекторы `.js-pagination-next/prev`, а во всех шаблонах `js-paging-next/prev-page`.

**Comment by shtrih** [comment]
В конечном итоге, решением будет проставить правильные классы либо в `toolbar.js`, либо в шаблонах.

**Comment by bambarbia-kergudu** [comment]
Код я у себя поправил и выложил фикс сюда. Глубже копать не стал, так как уже закопан по самую шею, хочется просто перезапустить сайт )) Если все делается проще, отлично.
