### ISSUE TITLE
"Свободный" доступ к закрытым блогам, созданным одним и тем же пользователем

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#743]
Админ создал два закрытых блога. Юзер отправляет запрос в первый закрытый блог, получает одобрение от админа. Теперь заходит во второй закрытый блог, отправляет запрос на вступление, обновляет страницу клавишей F5 и сразу получает доступ ко всем записям блога, хотя админ еще не одобрил запрос на вступление во второй закрытый блог. Админ в данном случае одно и то же лицо.

**Comment by aVadim483** [comment]
Обычные закрытые блоги с настройками по умолчанию?

**Comment by aVadim483** [comment]
Разобрался
