### ISSUE TITLE
Запрос на подписку на закрытый блог открывает все скрытые записи в нем

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#744]
Главный баг: запрос на подписку на закрытый блог открывает все скрытый записи раздела до момента одобрения/отклонения админом.

Попытаюсь описать рабочие и нерабочие варианты с подпиской на блог, возможно, это как-то связано с предыдущим багом. 

Юзер отправляет запрос:
1. (+) Если пользователь отправляет запрос на подписку на закрытый блог и получает отказ, то при повторной отправке запроса должно появляется предупреждение о полученно ранее отказе (это работает).
2. (-) У админа должна быть возможность пригласить ранее отвергнутого пользователя (сейчас идет вечная загрузка при попытке отправки приглашения через страницу управления блогом).
3. (-) Если пользователь отправил запрос на подписку на закрытый блог, то при попытке отправки админом встречного приглашения происходит бесконечная обработка запроса, а должно по идее появляться предупреждении о том, что пользователь уже отправил запрос, и он ждет подтверждения в личных сообщениях у админа. Удаление письма без прочтения должно быть равносильно отказу, чтобы не получился замкнутый круг, когда запрос был отправлен, а админ его просто удалил, юзер в этом случае не может отправить повторный запрос, а админ выслать приглашение.
4. (-) Если пользователь отписался от закрытого блога, в котором он раньше состоял, то после отправки повторного запроса админу на вступление он почему-то сразу видит темы из закрытого раздела. Юзер не должен видеть закрытый раздел до подтверждения запроса админом, хоть он раньше и состоял в нем, но сейчас никаких привилегий нет.
5. Перед отпиской от закрытого блога должно появляться предупреждение с подтверждением согласия, чтобы не было случайных отписок.

Юзер получает приглашение:
1. (-) Если пользователь получил повторное приглашение вступить в закрытый блог, после того, как он из него когда-то вышел, через личные сообщения, то темы из закрытого блога должны оставаться для него закрытыми до подтверждения им вступления (сейчас приглашаемый пользователь видит все темы, хотя письмо в личке лежит не прочитанным).
2. (-) Если пользователь отказался от приглашения, то все остается так, как будто его и не приглашали (сейчас пользователю после отказа остается доступен закрытый блог и при нажатии на кнопку отписки в блоге происходит бесконечная загрузка). Админ не может повторно пригласить такого пользователя и если пользователь после отказа удалит приглашение, то останется вечным пользователем блога.
3. (=) Если пользователь отказался от приглашения, то у него должна быть возможность отправить запрос на вступление, а у админа отправить приглашение.

**Comment by aVadim483** [comment]
>Удаление письма без прочтения должно быть равносильно отказу, чтобы не получился замкнутый круг, когда запрос был отправлен, а админ его просто удалил, юзер в этом случае не может отправить повторный запрос, а админ выслать приглашение.

В текущей версии это не получится сделать. Дело в том, что все письма сейчас равнозначны, и ссылки на подтверждение/отклонение - это просто ссылки, которые вставлены в тело письма.

Для решения подобных кейсов должна быть возможность задавать для писем дополнительные свойства и действия. И в этом случае, кроме прочего, можно будет задавать действие, выполняемое при удалении письма. В планах для будущих версий такое есть.

Остальное все решаемо. Пункты 1.4 и 2.1 уже закрыты коммитами https://github.com/altocms/altocms/commit/ad4df5fa1d83f809011685ab48e361bb42615e3f и https://github.com/altocms/altocms/commit/a87b59a675cda72b769c908e32bf8c4a728a5e94

**Comment by bambarbia-kergudu** [comment]
Спасибо, Вадим. Сегодня-завтра буду тестировать. Все, что выходит за рамки нынешней архитектуры двига, остается на будущее. Я лишь указал на недостатки.

**Comment by aVadim483** [comment]
И исходя из моего предыдущего комментария п.1.3 должен немного иначе работать: если юзер уже отправил запрос на подписку, а админ его приглашает, то приглашение юзеру все ж уходит. Именно потому, что админ мог письмо с запросом случайно удалить, и тогда получаем клинч - ни юзер не может повторно отправить запрос, ни админ не может его пригласить. Поэтому пусть уж лучше у админа будет возможность отправить приглашение.

**Comment by aVadim483** [comment]
Все это сделано, но с некоторыми дополнениями. Т.к. удаление письма с запросом на подписку или с приглашением на подписку проходит бесследно без всяких действий, то сделал так:

1) Если юзер отправил запрос на подписку, а админ случайно удалил это письмо, то админ может отправить встречное предложение подписаться на блог и юзер может его принять.

2) Точно так же, если юзеру было отправлено приглашение подписаться, а он удалил это письмо, то он может отправить запрос на подписку в этот блог, чтоб админ мог подтвердить.

Остальные кейсы отработал тоже, теперь никаких зависаний и бесконечных загрузок быть не должно
