### ISSUE TITLE
Не работает rss-лента комментариев внутри топика

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#748]
Ссылки вида http://www.alto119m.ru/rss/comments/2/ приводят на несуществующую страницу с сообщением "К сожалению, такой страницы не существует. Вероятно, она была удалена с сервера, либо ее здесь никогда не было.", хотя комментарии в топике есть.

**Comment by aVadim483** [comment]
А такого обработчика в движке вообще нет. Где-то в шаблонах есть такая ссылка?

**Comment by inliquid** [comment]
В версии 1.0.x есть. А ссылка добавляется в шаблоне 

```<link rel="alternate" type="application/rss+xml" href="http://example.com/rss/comments/923/" title="abc"/>```

**Comment by bambarbia-kergudu** [comment]
Лента рсс комментариев была в Альто со времен ЛС, если возможность вырезали в линейке 1.1.x, то нужно зачистить код от остатков. Ссылка на рсс комментарии появляется в html-коде на всех страницах внутри топика.

Если удалить из шаблона default.tpl код 

```        
        {if $aHtmlRssAlternate}
            <link rel="alternate" type="application/rss+xml" href="{$aHtmlRssAlternate.url}" title="{$aHtmlRssAlternate.title}">
        {/if}
```

то ссылка на главную рсс ленту в коде тоже пропадает, так как на эту конструкцию повешены все ссылки рсс лент. Из {$aHtmlRssAlternate.url} нужно исключить ссылки на рсс ленту комментариев или восстановить прежний функционал. После тикет можно будет закрывать.

**Comment by aVadim483** [comment]
Восстановил функционал
