### ISSUE TITLE
Неправильная работа с конфигами для загрузки изображений

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#750]
Пытаюсь запретить загрузку png картинок для фотографий в профиле. Расширил стандартное правило

```
$config['module']['uploader']['images']['profile_photo'] = array(
    '$extends$' => '___module.uploader.images.default___',
    'image_extensions' => array('gif', 'jpg', 'jpeg'),
    'transform' => array(

        'max_width'  => 200,        // максимальная ширина сохраняемого изображения
        'max_height' => 200,        // максимальная высота сохраняемого изображения

        'aspect_ratio' => '1',      // соотношение ширины и высоты
        'watermark' => array(
            'enable' => false,
        ),
        '@mime(png)'  => array(
            //'save_as' => 'jpg',
        ),
    )
);
```
Из 'image_extensions' убрал png, файлы все равно заливаются. Если разрешить заливку png и раскомментировать строку 'save_as' => 'jpg', png фотки не конвертируются в jpg (может быть, на серваке должна быть установлена какая-то библиотека для конверта?). Единственное что точно работает, это настройка размеров по высоте и ширине, остальное не проверял. Пришел к выводу, что выборочное отключение правил для загрузки фоток не работает. Единственный рабочий способ - это полностью запретить заливку файлов в png, но это не то, что нужно.

Альто 1.1.8

**Comment by aVadim483** [comment]
Да, управление конфигом перестало быть очевидным, слишком много наворотов уже. Надо мануал писать. Но для твоего случая нужно так:
```
$config['module']['uploader']['images']['profile_photo'] = array(
    '$extends$' => '___module.uploader.images.default___',
    '$reset$' => true,
    'image_extensions' => array('gif', 'jpg', 'jpeg'),
    'transform' => array(

        'max_width'  => 200,        // максимальная ширина сохраняемого изображения
        'max_height' => 200,        // максимальная высота сохраняемого изображения

        'aspect_ratio' => '1',      // соотношение ширины и высоты
        'watermark' => array(
            'enable' => false,
        ),
        '@mime(png)'  => array(
            //'save_as' => 'jpg',
        ),
    )
);
```
Здесь директива `'$reset$' => true` означает, что идущие ниже значения ключей должны не дополнять расширяемую конфиг-секцию, а переустанавливаться заданными значениями.

**Comment by bambarbia-kergudu** [comment]
Только от этого не легче  )) Пробовал вставлять код в настройки шаба, локальные настройки и главные. png фотки все равно заливаются, а случае разрешения на заливку не конвертируются в jpg. 

А еще я не нашел, как запретить сохранять оригинальные фотки, оставляя только "обрезки":

Сейчас создаются
0u57387ff4-584fc94e-43907c42.jpg - оригинал (вот этот файл не нужен)
0u57387ff4-584fc94e-43907c42.jpg-190x190-crop.jpg - обрезок на 190
0u57387ff4-584fc94e-43907c42.jpg-128x128-crop.jpg - обрезок на 128

```
    'original' => array(
        'save' => false,            // надо ли сохрагять оригинальное изображение
        'suffix' => '-original',    // суффикс оригинального изображения
    ),
```
Опция ни на что не влияет.

**Comment by bambarbia-kergudu** [comment]
Хотя, если я правильно понимаю, файлы
0u57387ff4-584fc94e-43907c42.jpg-190x190-crop.jpg - обрезок на 190
0u57387ff4-584fc94e-43907c42.jpg-128x128-crop.jpg - обрезок на 128

Делаются на основе 0u57387ff4-584fc94e-43907c42.jpg не автоматически, а по мере обращения к тем страницам, где в шабах выволятся картинки с размерами 128 и 190px, поэтому его удалить не получится.

**Comment by aVadim483** [comment]
Что касается "обрезков", то да, они создаются по запросу. Поэтому нужен какой-то исходник, из которого они должны нарезаться. 

А вот насчет настроек конфига - перепроверю еще раз

**Comment by bambarbia-kergudu** [comment]
Спасибо, сейчас главное настройки, в худшем случае отключу заливку png вообще. Иначу файлы без конверта в jpg займут все место.
