### ISSUE TITLE
После редактирования меню слетает скин

### ISSUE THREAD

**Issue by orthograf** [altocms/altocms#755]
После редактирования меню слетает скин на тот, что установлен "по умолчанию" в основном конфиге движка. Для воспроизведения:

Админка:
1. Активируем любой скин (например StartKit)
2. Настройки/Менеджер меню
3. user/редактировать
4. Редактировать подменю
5. wall/скрыть

Сайт:
Обновляем страницу - шаблон StartKit слетел на Experiens Simple.

(Альто 1.1.12)

**Comment by bambarbia-kergudu** [comment]
Достаточно просто поменять скин, зайти в менеджер меню и нажать на кнопку "Сбросить меню в начальное состояние".

**Comment by orthograf** [comment]
И да... - не просто слетает скин. Переписываются и другие настройки шаблонов... (всё ещё не проверил).
