### ISSUE TITLE
Множественные сообщения E_NOTICE Undefined index: video

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#758]
После обновления страницы в логах появляется по две строки с E_NOTICE, лог быстро забивается. Сборка чистая с гитхаба (1.1.13), ошибки появляются сразу после установки двига.

```
2015-10-05 15:02:15
E_NOTICE [8] Undefined index: video (Z:\home\alto1113.ru\www\engine\classes\core\DataArray.class.php on line 78)
2015-10-05 15:02:14
E_NOTICE [8] Undefined index: video (Z:\home\alto1113.ru\www\engine\classes\core\DataArray.class.php on line 78)
2015-10-05 15:02:12
E_NOTICE [8] Undefined index: video (Z:\home\alto1113.ru\www\engine\classes\core\DataArray.class.php on line 78)
```

**Comment by ieasyweb** [comment]
Добавлю: пишется даже при обновлении страницы админки, плюс через каждые 5-10 этих, добавляется
<pre><code>E_NOTICE [8] Array to string conversion (/home/p324421/www/test.ru/engine/classes/modules/img/Img.class.php on line 143)</code></pre>

**Comment by aVadim483** [comment]
Воспроизвести не смог, но понял, где может быть проблема и пофиксил

**Comment by bambarbia-kergudu** [comment]
Второй ошибки у меня не было, но первая больше не беспокоит, журнал чист. Спасибо.
