### ISSUE TITLE
Ошибка Gmagick

### ISSUE THREAD

**Issue by Liandr** [altocms/altocms#759]
На сервере был установлен пакет Gmagick 1.1.7-0.2.RC2.el7, Imagick отсутствовал.
Вылезала ошибка
PHP Fatal error:  Non-static method Gmagick::getversion() cannot be called statically, assuming $this from incompatible context in ***/engine/classes/modules/img/Img.class.php on line 75
После замены Gmagick на Imagick всё заработало.

**Comment by aVadim483** [comment]
fixed
