### ISSUE TITLE
Проблема с удаленными топиками в ленте активности

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#763]
Если быть точнее - проблема с комментариями. Чистка удаленных комментариев через админку не помогает. Некоторые остаются. Возможно причина в ключевом слове 'онлайн'

![1](https://cloud.githubusercontent.com/assets/6797881/10560959/85df71f4-7523-11e5-9438-f32a7f5ff611.png)

Тем не менее, некоторые комментарии остаются и "Активность" пытается честно сформировать на них ссылку, для чего нужен объект топика. А топик удален. В результате для типов событий 
- 'add_comment' и
- 'vote_comment'

Имеем такую картинку вместо активности

E_ERROR [1] Call to a member function getUrl() on a non-object

Как результат обращения к ```$oTarget->getTarget()->getUrl()```

Файл - _action.stream.events.tpl_.

**Comment by aVadim483** [comment]
А как удалялись топики?

**Comment by inliquid** [comment]
Пользователь с правами админа в блоге удалил из своего интерфейса.

**Comment by inliquid** [comment]
Возможно есть еще такой момент (сразу не заметил - т.к. это другой лог) Похоже сообщение вывелось при удалении из админки

2015-10-16 15:56:06
SQL Error: Cannot delete or update a parent row: a foreign key constraint fails (`alto`.`alto_comment_online`, CONSTRAINT `alto_topic_comment_online_fk1` FOREIGN KEY (`comment_id`) REFERENCES `alto_comment` (`comment_id`) ON DELETE CASCADE ON UPDATE CASCADE) at /var/www/example.com/common/classes/modules/comment/mapper/Comment.mapper.class.php line 792
DELETE FROM alto_comment WHERE target_id IN ('752') AND target_type = 'topic'

**Comment by aVadim483** [comment]
А версия движка какая?

**Comment by inliquid** [comment]
1.0.x

**Comment by aVadim483** [comment]
Обновил админку в ветке 1.0.х - https://github.com/altocms/altocms/commit/68cde1d890d2749e7d3f74f75aacd4877370075d

Добавлена проверка комментариев (не онлайн) удаленных топиков

Скачать целиком можно здесь: https://github.com/altocms/altocms/tree/1.0.x (справа кнопка Download ZIP)

**Comment by inliquid** [comment]
Однако, кнопка не активна
![1](https://cloud.githubusercontent.com/assets/6797881/10695381/217caca8-79ac-11e5-8eec-ff439d975bba.png)

**Comment by inliquid** [comment]
Ок, исправил условия в шаблоне сам. 

Однако, все равно не работает эта штука.

```SQL Error: Cannot delete or update a parent row: a foreign key constraint fails (`alto`.`alto_comment`, CONSTRAINT `alto_topic_comment_fk` FOREIGN KEY (`comment_pid`) REFERENCES `alto_comment` (`comment_id`) ON DELETE CASCADE ON UPDATE CASCADE) at /var/www/example.com/common/classes/modules/admin/mapper/Admin.mapper.class.php line 485 --- Array ( [code] => 1451 [message] => Cannot delete or update a parent row: a foreign key constraint fails (`alto`.`alto_comment`, CONSTRAINT `alto_topic_comment_fk` FOREIGN KEY (`comment_pid`) REFERENCES `alto_comment` (`comment_id`) ON DELETE CASCADE ON UPDATE CASCADE) [query] => DELETE FROM alto_comment WHERE target_type='topic' AND target_id IN ('378', '381', '752') [context] => /var/www/example.com/common/classes/modules/admin/mapper/Admin.mapper.class.php line 485 ) ```

Не удаляются комментарии.
