### ISSUE TITLE
Не добавляются элементы меню

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#765]
В менеджере меню не получается добавить более одного корневого элемента.

**Comment by migarus** [comment]
у меня та же проблема :( Как скоро будет устранена данная проблема?

**Comment by aVadim483** [comment]
Исправлено

**Comment by ieasyweb** [comment]
Заменил файлы, но по прежнему только один подпункт добавляется. И в него можно вложить только один, и во вложенный так же только один и т.д.

**Comment by shtrih** [comment]
Подтверждаю, баг остался.

**Comment by migarus** [comment]
Тоже подтверждаю, что баг остался.

**Comment by migarus** [comment]
Исправьте пожалуйста этот баг! Очень сильно нужен! (

**Comment by aVadim483** [comment]
Да, как оказалось, не все варианты предусмотрел. Сейчас обновил. Тикет пока не закрываю, если есть возможность, проверьте, плиз, и дайте знать о результатах

**Comment by migarus** [comment]
Все отлично теперь. Можно закрывать, спасибо :)
