### ISSUE TITLE
В меню топиков не прописываются классы active

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#766]
Продолжим бороться с конструктором меню ))

При просмотре "Интересных" материалов на главной странице класс active не прописывается в меню, правило 

        'good'                 => array(
            'text'    => '{{blog_menu_all_good}}',
            'link'    => '___path.root.url___',
            'active'  => array('topic_kind' => array('good')),
        ),

не работает. Внутри блогов все работает правильно, на главной странице условие good игнорится.

В шаблоне experience прописано правило 
```
'good'                 => array(
            'active'  => array('topic_kind' => array('index')),
        ),
```

, которое срабатывает только на главной странице, а при переходе по страницам 

http://test_site.ru/index/page3/
http://test_site.ru/index/page4/
http://test_site.ru/index/pageN/

меню "Интересные" теряет класс active

При выборе фильтров "1 день", "неделя", "месяц" и "за весь период" в меню "Обсуждаемые" и "Топ" класс active не прописывается у выбранных подменю, правила

```
        '24h' => array(
            'text'   => '{{blog_menu_top_period_24h}}',
            'link'   => '___path.root.url___/index/discussed/?period=1',
            'active' => array('compare_param' => array(0, 1)),
        ),
        '7d'  => array(
            'text'   => '{{blog_menu_top_period_7d}}',
            'link'   => '___path.root.url___/index/discussed/?period=7',
            'active' => array('compare_param' => array(0, 7)),
        ),
        '30d' => array(
            'text'   => '{{blog_menu_top_period_30d}}',
            'link'   => '___path.root.url___/index/discussed/?period=30',
            'active' => array('compare_param' => array(0, 30)),
        ),
        'all' => array(
            'text'   => '{{blog_menu_top_period_all}}',
            'link'   => '___path.root.url___/index/discussed/?period=all',
            'active' => array('compare_param' => array(0, 'all')),
        ),
```
		
```		
		    '24h' => array(
                'text'   => '{{blog_menu_top_period_24h}}',
                'link'   => '___path.root.url___/index/top/?period=1',
                'active' => array('compare_param' => array(0, 1)),
            ),
            '7d'  => array(
                'text'   => '{{blog_menu_top_period_7d}}',
                'link'   => '___path.root.url___/index/top/?period=7',
                'active' => array('compare_param' => array(0, 7)),
            ),
            '30d' => array(
                'text'   => '{{blog_menu_top_period_30d}}',
                'link'   => '___path.root.url___/index/top/?period=30',
                'active' => array('compare_param' => array(0, 30)),
            ),
            'all' => array(
                'text'   => '{{blog_menu_top_period_all}}',
                'link'   => '___path.root.url___/index/top/?period=all',
                'active' => array('compare_param' => array(0, 'all')),
            ),
```

не работают. Проверить можно на демо сайте, перейдя по ссылке http://demo.altocms.com/new/index/discussed/?period=7 , а затем открыв меню "Обсуждаемые", подменю за 7 дней не подсветится.

Ошибки на первый взгляд несущественные, но бросаются в глаза, снижают юзабилити и путают юзеров. Если исправить перечисленные ошибки, меню, наконец-то, станет полностью рабочим. Тестировал на версии 1.1.13

**Comment by aVadim483** [comment]
Пофиксил. Только если шаблон свой, то требуются правки в нем:
1) для пункта 'good' все ж правило должно быть такое:
```
'good' => array(
      'active'  => array('topic_kind' => array('good')),
),
```
2) а для того, чтоб в подменю активным был период, правило такое:
```
'active' => array('compare_get_param' => array('period', 1)),
```

**Comment by bambarbia-kergudu** [comment]
Спасибо. Позже проверю и о результате отпишу

**Comment by aVadim483** [comment]
Пока не закрываю тикет, вдруг чего-то упустил

**Comment by bambarbia-kergudu** [comment]
При выборе любого периода во вкладке "Обсуждаемые", выбранный период одновременно подсвечивается и в меню "Топ".

![menu_trouble](https://cloud.githubusercontent.com/assets/13256983/10867296/870d93b2-807c-11e5-9317-7a90a4ee39dd.jpg)

**Comment by bambarbia-kergudu** [comment]
Вкладка Новые внутри блогов (/blog/blog-name/newall/page3)  теряет класс active при выборе

Надо в  common/classes/actions/ActionBlog.class.php эту строку  

```$this->sMenuSubItemSelect = $this->sTopicFilter == 'all' ? 'new' : $this->sTopicFilter;```

заменить в двух строках 622 и 1111 на эту

```$this->sMenuSubItemSelect = $this->sTopicFilter == 'newall' ? 'new' : $this->sTopicFilter;```

Тогда все пашет нормально

**Comment by bambarbia-kergudu** [comment]
Вадим, а нельзя добавить в ссылку "Лента" в меню топика счетчик с количеством новых изменений, как это сделано в меню юзера в верхнем правом углу шаблона. В счетчик нужно выводить то количество изменений, что выводятся сейчас под иконкой матюгальника в меню юзера. Тогда бы вкладка была бы не просто ссылкой, но и выполняла информативную роль.

**Comment by bambarbia-kergudu** [comment]
Со счетчиком в ленте, вроде бы, разобрался - значение можно дергать через "count_track"

**Comment by aVadim483** [comment]
С активными пунктами подменю все немного сложнее оказалось. Но пофиксил.

**Comment by aVadim483** [comment]
Все получилось со счетчиком?

**Comment by bambarbia-kergudu** [comment]
Да, счетчик в ленту добавил через count_track, точнее на основе него дописал функцию в Menu.class.php и вывел значение с нужным мне оформлением в меню топика.

Фикс фильтром проверю чуть позже, тикет пока не закрывай.

**Comment by bambarbia-kergudu** [comment]
Менял файлы вручную, чтобы весь двиг не качать. Сайт не грузится и выдает ошибку: 

```
Parse error: syntax error, unexpected '=', expecting ')' in Z:\home\test_site.ru\www\engine\classes\modules\viewer\plugs\function.menu.php on line 74

E_PARSE [4] syntax error, unexpected '=', expecting ')'
See details in error.log
```

Если строку 
``` if (!empty($sSubmenuHtml = smarty_function_menu($aSettings))) { ```

Заменить на бывшее значение:
``` if (!is_null($sSubmenuHtml = smarty_function_menu($aSettings))) { ```

То меню начинает работать правильно: фильтры выбираются и в логах ошибок нет ))

**Comment by aVadim483** [comment]
Это особенности версий PHP иногда вылезают: под версией 5.5 и выше ошибки нет. Но исправил, теперь и на 5.3 работает

**Comment by bambarbia-kergudu** [comment]
Теперь все работает, спасибо.

А вот это 
```
//$this->sMenuSubItemSelect = $this->sTopicFilter == 'newall' ? 'new' : $this->sTopicFilter;
$this->sMenuSubItemSelect = $this->sTopicFilter == 'all' ? 'new' : $this->sTopicFilter;
```
в common/classes/actions/ActionBlog.class.php (стр. 662 и 1112) я бы, все же, закоментировал наоборот )) Если это, конечно, не особенность пхп 5.5 ))) $this->sTopicFilter == 'newall' относится к /blog/blog-name/newall/, а не к фильтрам периода /blog/blog-name/discussed/?period=all.
