### ISSUE TITLE
Тайные блоги видны при поиске по блогам

### ISSUE THREAD

**Issue by bambarbia-kergudu** [altocms/altocms#774]
1. Тайные блоги показываются в результате ajax-поиска по блогам у всех пользователей, включая гостей, хотя изначально тайных блогов в общем списке блогов нет. Поиск идет на странице /blogs/. 
2. У подписчиков, модераторов и админов тайного блога тайный блог не показывается в списке блогов на странице /blogs/, тайный блог виден только главному админу сайта.

Альто 1.1.16

**Comment by aVadim483** [comment]
П.1 исправлен, п.2 будет исправлен только в следующей версии (вынес его отдельным тикетом)
