### ISSUE TITLE
На офф.сайте

### ISSUE THREAD

**Issue by ieasyweb** [altocms/altocms#775]
комментарии не отправляются, ну, и,
<code>E_WARNING [2] json_encode(): double INF does not conform to the JSON spec, encoded as 0 (/var/www/vhosts/alto-cms.com/altocms.com/engine/include/functions/Main.php on line 166)</code>
![screenshot_23](https://cloud.githubusercontent.com/assets/13599688/11174818/72eaf3b6-8c5c-11e5-88ab-be70f6c7dd1b.png)

браузер Макстон

**Comment by aVadim483** [comment]
fixed
