### ISSUE TITLE
Не устанавливается домен для куков

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#776]
Проблемы с установкой домена для куков не позволяют авторизоваться пользователю на поддомене. (Например если профиль пользователя вынести на поддомен.)

Исходная проблема описывалась здесь: http://altocms.ru/1441.html и была связана с 2мя сайтами, однако, ровно такое же поведение имеет место если

1. Сайт всего один
2. Кеш выключен - вообще никаких изменений на самом деле не влечет за собой

Описание проблемы. 

В поле  хост для куков устанавливаю  '.example.com' или 'example.com'.

1. Логинюсь (сайт example.com). В таблице session появляется сессия.
2. Нажимаю на "выход", выход срабатывает. Пробую войти снова — ничего не получается. Ошибок в логах нет.
3. В таблице session сессия помечена как завершенная. Войти не получается пока запись из таблицы не будет удалена.

Еще нашел что в таблицах storage почему-то записываются 2 группы параметров

custom.config.sys.session.host
custom.config.sys.session.path

и

custom.config.sys.cookie.host
custom.config.sys.cookie.path

Параметр custom.config.sys.session.host — всегда пустой s:0:"", указанное в админке значение записывается в _custom.config.sys.cookie.host_. Попробовал руками вписать в custom.config.sys.session.host то же самое значение, но не помогло.

**Comment by aVadim483** [comment]
Пока не могу понять, в чем дело - проблема то воспроизводиться, то нет, носит "плавающий" характер

**Comment by inliquid** [comment]
Скажите, если надо протестировать при каких-то определенных условиях.

**Comment by aVadim483** [comment]
Да я сам пока не пойму. Сначала воспроизвел проблему. Через пару дней вдруг все нормально стало работать, причем, куки без проблем работали как на основном домене, так и на поддомене подхватывались. А сейчас проблема на локальном сайте опять воспроизводится. Но я уже не помню, чего такого сделал, из-за чего нормально все стало в прошлый раз работать. Но пробую разобраться

**Comment by inliquid** [comment]
Куки подхватываются но после разлогинивания не получается снова войти.

**Comment by aVadim483** [comment]
В общем, эксперименты показали, что если экспериментировать с доменами, то можно, в результате получить две одинаковые куки: одна на домене 'site.com', другая - на домене '.site.com'. В этом корень проблем. Причем, под Фоксом проблемы сейчас не наблюдаю, только под Хромом.

**Comment by inliquid** [comment]
В общем я настроил. Заполнять надо оба параметра. Почему раньше не срабатывало когда я делал это напрямую в базе не знаю. Немного странная логика, но работает.
