### ISSUE TITLE
Не хватает border в списке пользователей на стиле experience-simple

### ISSUE THREAD

**Issue by KitsuneSolar** [altocms/altocms#786]
![2015-12-10 15-49-45](https://cloud.githubusercontent.com/assets/12877339/11715799/059776ec-9f56-11e5-94a4-e0e0b9a78318.png)

Здесь:
https://github.com/altocms/altocms/blob/master/common/plugins/rating/templates/skin/experience-simple/tpls/user/user.list.line.inject.tpl

Удалить `rowspan="3"` у `td`.

**Comment by aVadim483** [comment]
fixed
