### ISSUE TITLE
Удаление блога

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#787]
Если администратор удаляет блог с переносом всех постов в другой блог, необходимо затем вручную сбрасывать кеш.

**Comment by aVadim483** [comment]
fixed

**Comment by inliquid** [comment]
Вадим, к сожалению исправление не работает. По-прежнему приходится чистить в админке.

**Comment by inliquid** [comment]
Вот что происходит если не сбросить, при открытии нового блога, куда все перемещено

```
]][END:1450069621.562-566E4E75891AF]

[LOG:1450648272.771-567722D0BC21F][2015-12-21 00:51:12][PID:5915][ERROR][[
E_ERROR [1] Call to a member function GetUrl() on null (/var/www/example.com/common/classes/modules/topic/entity/Topic.entity.class.php on line 599)
--- call stack ---
Func::_callStackError() in /var/www/example.com/engine/include/Func.php on line 147
Func::_errorLog() in /var/www/example.com/engine/include/Func.php on line 274
Func::_errorHandler() in /var/www/example.com/engine/include/Func.php on line 69
Func::done()
--- end ---
```

**Comment by aVadim483** [comment]
Ошибку воспроизвел. Сейчас (после фикса https://github.com/altocms/altocms/commit/bb43f6093aca002f42f005b3fdd4d1c06182543c) она у меня не воспроизводится. Полагаю, проблема решена
