### ISSUE TITLE
Сломана выборка только новых сообщений

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#791]
Этот коммит ломает выборку "Только новые" в личных сообщениях.

https://github.com/altocms/altocms/commit/6870ebac00a3b6bd1264b51bb7313b31f44c8f0c

**Comment by aVadim483** [comment]
Только что проверил - работает выборка нормально. Я помню, что было такое в процессе - сломалась выборка новых, - но позже был фикс. В текущей дев-версии проблем не вижу

**Comment by aVadim483** [comment]
Т.к. на текущей дев-версии проблема не воспроизводится, тикет закрываю. Если вдруг вылезет - переоткройте тикет
