### ISSUE TITLE
Функция Salt()

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#792]
```    /**
     * Returns hash of salted string
     *
     * @param   string      $sData
     * @param   string|null $sType
     *
     * @return  string
     */
    public function Salted($sData, $sType = null) {
        $sSalt = Config::Get('security.salt_' . $sType);
        if ($sSalt !== false && !$sSalt) {
            $sSalt = $sType;
        }
        return F::DoSalt($sData, $sSalt);
    }
```

Вот в этом условии что вообще происходит? 
`$sSalt = $sType;`
Соль подменяется на строку типа, например, 'sess' ?

И зачем вообще это условие нужно.

**Comment by aVadim483** [comment]
В общем случае может использовать несколько видов "соли", в т.ч. и определяемых сторонними разработчиками. При этом соль можно задавать как в конфиге (тогда в этот метод передает "тип" соли), либо можно передавать непосредственно значение соли.

**Comment by inliquid** [comment]
Я про то, что здесь косяк... Значение заменяется не тем. Если соль задана, она в этой ф-ии подменяется на тип, вместо того, чтобы использовать значение.

**Comment by inliquid** [comment]
Или я чего-то не понимаю?

**Comment by aVadim483** [comment]
```
// Получаем значение типа соли из конфига
$sSalt = Config::Get('security.salt_' . $sType);
// Если соль этого типа не задана, то возвращается NULL,
// если возвращается FALSE, то это явное указание игнорировать соль этого типа
if ($sSalt !== false && !$sSalt) {
    // если соль не игнорируется, но и не задана, то в качестве соли используется ее тип
    $sSalt = $sType;
}
```
Таким образом, если соль в конфиге задана (т.е. `Config::Get('security.salt_' . $sType)` возвращает строку, а не `FALSE` или `NULL`), то никакой подмены не происходит

**Comment by inliquid** [comment]
Спасибо, понял, ошибки нет.
