### ISSUE TITLE
Проблемы с поиском

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#796]
1. После всех изменений в версии 1.1 не работает поиск по тегам - их содержимое не учитывается.

2. Если искать некую фразу целиком, заключив ее в кавычки, например "что такое", ломается выделение тегами searched-item фразы, можно проверить на сайте altocms.ru.

При этом если в кавычки взять адрес сайта - выделение тегами работает нормально.

**Comment by aVadim483** [comment]
По п.1 не понял, вот поиск по тегу: http://demo.altocms.com/new/tag/%D0%9C%D1%83%D1%80%D0%B7%D0%B8%D0%BB%D0%BA%D0%B0/

**Comment by inliquid** [comment]
Да похоже проблема только если теги содержат спецсимволы. Например если в слове содержится '_' - не ищется.

**Comment by aVadim483** [comment]
Стандартная php-функция `urlencode()`, которая используется для преобразований тегов в URL, не кодирует символы '.', '-', '_' (точка, дефис, подчеркивание). А это могло иногда приводить к тому, что движок неверно воспринимает URL. В общем, сделал так, чтоб эти символы тоже кодировались. Больше подобных проблем быть не должно

**Comment by inliquid** [comment]
Вадим вы меня не поняли похоже. Имелось в виду, что при поиске через search теги не учитываются. В предыдущей версии (на 1.0.x) если поисковая фраза была в тегах, то топики попадали в выдачу.
По аналогии с запросом выше.
http://demo.altocms.com/new/search/topics/?q=%D0%BC%D1%83%D1%80%D0%B7%D0%B8%D0%BB%D0%BA%D0%B0
Должен выдать топик, но не выдает.
