### ISSUE TITLE
Уязвимости типа DoS

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#797]
Система поиска по-прежнему представляет собой уязвимость, позволяющую легко положить любой сайт. Еще раз подчеркну, речь не идет о DDoS. Просто обычный отказ в обслуживании благодаря серии "правильных" запросов с одного хиленького компа.

1) Новая система поиска формирует слишком тяжелые запросы к БД при этом не позволяя практически никак их ограничить. (Кроме длины самого запроса, что не очень эффективно) Например, на одном сайте с примерно 1000 топиков данный поисковый запрос (просто первое что под руку попалось)

`https://github.com/altocms/altocms/commit/49e9bc3e87a274444cd07d26d3e88871b09cd6ea/dffsdfsdfsdf/s`

выполняется в БД почти 3 сек!!!

Он превращается в следующее

```string(2010) " SELECT t.topic_id, (LOWER(t.topic_title) REGEXP '[[:<:]]https[[:space:]]+github[[:space:]]+com[[:space:]]+altocms[[:space:]]+altocms[[:space:]]+commit[[:space:]]+49e9bc3e87a274444cd07d26d3e88871b09cd6ea[[:space:]]+dffsdfsdfsdf[[:space:]]+s[[:>:]]')*10,8+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]https[[:space:]]+github[[:space:]]+com[[:space:]]+altocms[[:space:]]+altocms[[:space:]]+commit[[:space:]]+49e9bc3e87a274444cd07d26d3e88871b09cd6ea[[:space:]]+dffsdfsdfsdf[[:space:]]+s[[:>:]]')*9+(LOWER(t.topic_title) REGEXP '[[:<:]]https[[:>:]]')*1,2+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]https[[:>:]]')*1+(LOWER(t.topic_title) REGEXP '[[:<:]]github[[:>:]]')*1,2+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]github[[:>:]]')*1+(LOWER(t.topic_title) REGEXP '[[:<:]]com[[:>:]]')*1,2+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]com[[:>:]]')*1+(LOWER(t.topic_title) REGEXP '[[:<:]]altocms[[:>:]]')*1,2+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]altocms[[:>:]]')*1+(LOWER(t.topic_title) REGEXP '[[:<:]]altocms[[:>:]]|[[:<:]]commit[[:>:]]|[[:<:]]49e9bc3e87a274444cd07d26d3e88871b09cd6ea[[:>:]]|[[:<:]]dffsdfsdfsdf[[:>:]]|[[:<:]]s[[:>:]]')*1,2+(LOWER(tc.topic_text_source) REGEXP '[[:<:]]altocms[[:>:]]|[[:<:]]commit[[:>:]]|[[:<:]]49e9bc3e87a274444cd07d26d3e88871b09cd6ea[[:>:]]|[[:<:]]dffsdfsdfsdf[[:>:]]|[[:<:]]s[[:>:]]')*1 AS weight FROM ?_topic AS t INNER JOIN ?_topic_content AS tc ON tc.topic_id=t.topic_id WHERE (topic_publish=1) AND topic_index_ignore=0 AND ( (LOWER(t.topic_title) REGEXP ?) OR (LOWER(tc.topic_text_source) REGEXP ?) ) ORDER BY weight ...```

Т.е. как видно, символы в запросе рассматриваются как разделение слов в выражении. 
При этом я поставил ограничение поисковой строки в 100 символов, по умолчанию было 255. И все равно - 3 сек! И это без поиска по комментариям, которых почти 10 тыс!

Легко  видеть, что можно разбить данную фразу на еще большее число составляющих, еще более утяжелив запрос. Просто генерируя произвольные запросы к БД подобного типа можно ее хорошенько приложить.

Т.о. возникает необходимость

- фильтровать лишние символы, так чтобы они не рассматривались как разделители выражения
- ввести ограничение на число составляющих выражения, к примеру чтобы поисковая фраза могла содержать не больше 3 слов

2) Некоторое время назад по моей рекомендации была реализована защита от флуда, учитывающая интервал времени между поисковыми запросами. Это хорошо, но я еще раз посмотрел ее реализацию и вижу в ней глобальный косяк. Он заключается в том, что система хранит данные в сессии, то есть, она защищает себя от флуда запросов __обычных, регулярных пользователей__. 

Тем не менее, как вы понимаете основная угроза исходит не от них. А злоумышленник явно не станет писать скрипт, который будет держать открытой 1 единственную сессию! 

Таким образом необходимо модифицировать систему - сохранять время последнего запроса и IP адрес в кеш, сравнивая затем дату последнего обращения, и при повторном обращении с того же IP адреса в течение заданного интервала - отбивать запрос.

**Comment by aVadim483** [comment]
1) Организация поиска встроенными средствами СУБД через регэкспы - это большая нагрузка по определению. Пропускать поисковый запрос через дополнительные фильтры (по символам ли, по числу слов или как-то еще) - это можно, конечно. Но это не решает проблему в принципе, т.к. при быстром росте числе записей рано или поздно все равно упретесь в долгие запросы.

2) Ограничение по IP - палка о двух концах. Это можно делать только опционально (на усмотрение админа сайта), т.к. совпадение внешних IP для разных юзеров из одной локальной сети - это вовсе не редкость.

**Comment by inliquid** [comment]
1) То что это в любом случае большая нагрузка, понятно. Хотелось бы при этом иметь возможность более гибко настраивать систему. Например, я предлагаю дать возможность ограничить число слов в выражении. Например 3. Подавляющее большинство обычных пользователей ищет 1 слово, 88% - 1 или 2 слова. И очень редко вбивают 3 слова, или ссылку. 

При этом если человек вбил ссылку она не долна рассматриваться как набор слов, а так и долна искаться как 1 слово.


2) Да, конечно ситуация когда под 1 IP сидит несколько пользователей не редка. Однако, ситуация когда из под 1 IP поисковые запросы приходя чаще раза в 2 сек в течение минуты или невозможна, или крайне редка. (Скорее невозможна) Поэтому я и предлагаю дать возможность настроить такую защиту. Пусть лучше будет 1-2 ложных срабатывания в год, чем у злоумышленника будут развязаны руки.

Кстати такая ситуация не выдумка, были реальные кейсы когда с 1-2 хостов пытались положить сервер.

Единственная альтернатива это или вообще закрыть поиск неавторизованным, или добавлять в форму капчу.

**Comment by aVadim483** [comment]
Предлагаемые опции обратную совместимость не ломают и в реализации просты, так что добавлю их.
