### ISSUE TITLE
Кеш не очищается целиком из админки

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#800]
Команда на сброс кеша из админки Cache_Clean() на приводит в фактическому очищению всех данных. В частности, сразу после ее выполнения:

Обновляю страницу и вижу что мемкеш исправно отдает данные по ключам user_{id}
Вот лог мемкеша. (У меня есть более подробный лог где я могу видеть и сами данные - показывать не буду)
```
<30 get b8b1fda95bfb8fceb9df51811b5518e7
>30 sending key b8b1fda95bfb8fceb9df51811b5518e7
>30 END

```

**Comment by aVadim483** [comment]
Я не знаю, как Вы проверяете, но вот примитивный код:
```
        $sData = 'something';
        E::Cache_Set($sData, $sData);
        $sResult = E::Cache_Get($sData);
        var_dump($sResult);
        E::Cache_Clean();
        $sResult = E::Cache_Get($sData);
        var_dump($sResult);
        exit;
```
Первый раз var_dump вернет строку 'something', второй - значение false, которое говорит о том, что в кеше значения по ключу нет. Возможно, у Вас значение пишется где-то после сброса

**Comment by inliquid** [comment]
В других ситуациях проблем не замечал, но здесь проблема есть. Пользовательские сущности остаются в кеше, в результате чего я не могу после возникновения такой ситуации http://altocms.ru/1491.html вернуть сайт в работающее состояние пока не перезапущу мемкеш.

Проверяю в трех местах. Выше вывод логов мемкеша. Еще в 2х местах непосредственно в коде добавлены file_put_contents.

Пользовательская сущность возвращается после вызова Cache_Clean. Никаких дополнительных вызовов Cache_Set (отслеживаю все обращения) я не вижу.

**Comment by inliquid** [comment]
Вообще один Set проскакивает, возможно что действительно устанавливается сущность сразу после или в момент сброса в кеше.

**Comment by aVadim483** [comment]
>или в момент сброса в кеше

Что значит в "момент сброса"? В момент сброса происходит сброс кеша, это отдельная команда. Запись в пустой кеш может быть только __после__ сброса. Смотрите логику работы, ловите, где идет запись. Либо воспользуйтесь методом
```
E::Cache_SetDisabled(true);
```
Этот метод отключает кеш до перезагрузки страницы

**Comment by inliquid** [comment]
В момент сброса, означает за время обработки одного нажатия на кнопку сброса. В частности при обработке одного POST запроса один и тот же параметр, например пользовательская сессия может устанавливаться несколько раз. Вообще погрузившись в дебри изучения кеширования вынужден констатировать что здесь совсем все плохо. Самый фундаментальный косяк заключается в том, что кеш устанавливается только при обработке Get-запросов. А при обновлениях он тупо скидывается по тегам. В итоге никакого преимущества по отношению к банальному MySQL query cache не вижу. В нем абсолютно такая же логика - кеш живет, пока нет обновлений в таблице, тогда он скидывается. В логике движка тоже самое.

Чтобы был выигрыш нужно при обновлениях делать Delete/Set конкретного обновленного параметра. Или что-то еще более сложное с инкрементами и конкуренцией.

А так получается кто-то на сайте проголосовал - помаши пользовательским данным в кеше ручкой. В замен дополнительные накладные расходы в виде сотен обращений в кеш при каждом вызове.

**Comment by aVadim483** [comment]
>В итоге никакого преимущества по отношению к банальному MySQL query cache не вижу

То, что Вы не видите, вовсе не означает, что преимуществ нет. Все проверяется элементарно - врем отработки с кешем, и время отработки без оного. С кешем в большинстве случаев время отработки меньше, иногда в разы. Но если накладные расходы принципиальны, то кеш всегда можно отключить.

**Comment by inliquid** [comment]
Возможно query cache нужно еще настроить. При операциях только чтения выигрыш может и есть. А когда будет чтение/запись? Тогда в обоих случаях все равно будем лезть в БД, и либо будут доп затраты на отдельный кеш, либо нет.

**Comment by aVadim483** [comment]
Мне кажется, Вы не очень хорошо представляете, как работает кеш движка, и поэтому не видите разницы между кешированием записи таблицы базы данных и кешированием топика, как сущности.

Но это, собственно, не относится к сути багрепорта. Очевидно, что метод Cache_Clean() работает, как положено, кеш сбрасывается. Какой компонент и в каком месте потом пишет информацию в кеш - это, не видя кода, определить невозможно в принципе. Поэтому тикет закрываю

**Comment by inliquid** [comment]
Боюсь это вы плохо понимаете как работает query cache. Да и зачем он вообще нужен в нагруженных системах. Нет, не для "ускорения".
