### ISSUE TITLE
ERROR 404 при выходе из AdminCP

### ISSUE THREAD

**Issue by KitsuneSolar** [altocms/altocms#804]
Если нажать в выпадающем меню пользователя на странице AdminCP пункт "Выход", браузера перебрасывает на страницу 404. При этом адсинистратора разлогинивает корректно.

**Comment by aVadim483** [comment]
Не получилось воспроизвести, при выходе из админки нормально сработал редирект на главную

**Comment by aVadim483** [comment]
Пока закрываю тикет, если проблема повторится и понятно будет, как ее воспроизвести, переоткройте его
