### ISSUE TITLE
Невозможно изменить тип дополнительного поля топика через редактирование

### ISSUE THREAD

**Issue by inliquid** [altocms/altocms#807]
Тип уже добавленного поля не меняется через редактирование в админке.

**Comment by aVadim483** [comment]
Изменение типа возможно, только если не было еще введено ни одного значения. В противном случае возникает не вполне однозначная задача преобразования значений.

Но согласен, что должно какое-то сообщение выводится на этот счет

**Comment by inliquid** [comment]
Ну ни одного топика не было еще создано. Просто добавил поле и увидел что тип не тот, попробовал поменять - не получилось.
