### ISSUE TITLE
Watermark: задание процентных координат положения накладываемой картинки

### ISSUE THREAD

**Issue by shtrih** [altocms/altocms#809]
Сейчас координаты абсолютные в пикселях. Из-за этого невозможно поместить вотермарк в центре картинки, например.

**Comment by aVadim483** [comment]
Указание в процентах не решит эту задачу, т.к. задаются координаты угла. Тут, скорее, надо предопределенные строковые константы вводить. Напр.:
```
        'watermark' => array(
            'enable' => false,
            'image' => array(
                'path' => '___path.static.dir___/___path.uploads.root___',
                'file' => 'altocms.png',
                'topleft' => false,
                'position' => 'center',
            ),
        ),
```

**Comment by shtrih** [comment]
Если поместить начала координат в центр вотермарка… Но, в общем-то да, особо позиционировать, наверное не имеет смысла, центра достаточно.
