### ISSUE TITLE
Russian in visual editor with english site language

### ISSUE THREAD

**Issue by maxlovic** [altocms/altocms#812]
AltoCMS version 1.1.17. Site language: english. Enabled "visual editor" in admin panel.
Russian text in the editor. Формат, всплывающие подсказки - все на русском.
Template: experience-simple
Так же в этом шаблоне в файле action.profile.created_photos,tpl должно быть:
```javascript
<div id="js-profile-user-photos" class="panel panel-default user-friends sidebar flat">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-20">
                <div class="modal-title">{$aLang.user_menu_publication_photos} <span id="aim-pages-container"></span></div>
```
А там вместо {$aLang.user_menu_publication_photos} стоит "Фотографии".

**Comment by aVadim483** [comment]
fixed
