### ISSUE TITLE
Проблема с изминением ссылок

### ISSUE THREAD

**Issue by lk0dee** [altocms/altocms#818]
Как на сайте сказано, делала по примеру и добавлял в конфиг. К примеру адрес админки изменяется без проблем, но если добавить еще одну страницу, допустим юзер

$config['router']['rewrite'] = array(
    'abradmin' => 'admin',
);
$config['router']['uri'] = array(
    'admin' => '404',
);

$config['router']['rewrite'] = array(
    'users' => 'people',
);
$config['router']['uri'] = array(
    'people' => 'index',
);

ВЫглядит вот так, изминения не работают, работает что-то одно, в данном случае последний вариант, это изменение с пепл на юсерс, админка перестает работать, становится стандартный адрес admin/

**Comment by aVadim483** [comment]
Правильно будет так:
```
$config['router']['rewrite'] = array(
    'abradmin' => 'admin',
    'users' => 'people',
);
$config['router']['uri'] = array(
    'admin' => '404',
    'people' => 'index',
);
```
Т.е. нужно объединять правила
