### ISSUE TITLE
Проект поддерживаеться?

### ISSUE THREAD

**Issue by xDESTROYx** [altocms/altocms#820]

**Comment by aVadim483** [comment]
А история коммитов не дает ответа на этот вопрос?

https://github.com/altocms/altocms/commits/1.2.x

**Comment by xDESTROYx** [comment]
ой, не увидел 1.2 ветки. Извиняюсь.
Смотрел  1.0 а там: Latest commit 5e0613f on 22 Feb

**Comment by aVadim483** [comment]
Это особенность гитхаба - по умолчанию показывает коммиты в мастер-ветку
