### ISSUE TITLE
Ошибка SQL при публикации топика

### ISSUE THREAD

**Issue by toby3d** [altocms/altocms#821]
Alto CMS: 1.1.19.3
PHP: 7.0.4
UTF8 в PCRE, Mbstring, SimpleXML: Да
Графические пакеты: GD

Сервер: Localhost via UNIX socket
Тип сервера: MariaDB
Версия сервера: 10.1.10-MariaDB - Source distribution
Версия протокола: 10
Кодировка сервера: UTF-8 Unicode (utf8)

Apache/2.4.18 (Unix) OpenSSL/1.0.2g PHP/7.0.4 mod_perl/2.0.8-dev Perl/v5.16.3

Все необходимые права на каталоги выданы, установка производится успешно, никаких иных проблем во взаимодействии с админкой и/или другими настройками пока не замечено. Но при создании топика после нажатия "Отправить" идёт переброс на страницу следующего содержания:

```
SQL Error: Got error 'this version of PCRE is compiled without UTF support at offset 0' from regexp at /alto.local/common/classes/modules/topic/mapper/Topic.mapper.class.php line 256 --- Array ( [code] => 1139 [message] => Got error 'this version of PCRE is compiled without UTF support at offset 0' from regexp [query] => SELECT topic_id FROM alto_topic WHERE topic_url = 'lorem' OR topic_url RLIKE '^lorem-[0-9]+$' [context] => /alto.local/common/classes/modules/topic/mapper/Topic.mapper.class.php line 256 )
```

Переустановка CMS проблему не решает, файлы системы не трогал вовсе. В логах админки наблюдается идентичная запись:
```
2016-04-27 20:40:43
SQL Error: Got error 'this version of PCRE is compiled without UTF support at offset 0' from regexp at /alto.local/common/classes/modules/topic/mapper/Topic.mapper.class.php line 256
SELECT topic_id FROM alto_topic WHERE topic_url = 'lorem' OR topic_url RLIKE '^lorem-[0-9]+$'
```

**Comment by aVadim483** [comment]
Сам я никогда с подобной ошибкой не сталкивался, но гугл говорит, что она не так уж и редко встречается. В детали не вникал, но понял так, что PHP надо пересобирать, задав правильно параметр --with-pcre=...

**Comment by toby3d** [comment]
@aVadim483 Конфигурация валидная, но похоже на обработку запросов влияет версия PHP. В ранних версиях с идентичными настройками всё работает безукоризненно.

**Comment by maxicms** [comment]
Проблема в том что php скорее всего собран без поддержки PCRE или с более старой версией библиотеки, вариант есть или пересобрать php или обновить непосредственно PCRE или попробовать использовать вот такой код в хататексе если это позволяет апач
```
php_value output_buffering "Off"
php_value mbstring.language "neutral"
php_value mbstring.encoding_translation "Off"
php_value mbstring.http_input "pass"
php_value mbstring.http_output "pass"
php_value mbstring.internal_encoding "UTF-8"
php_value mbstring.substitute_character "none"
php_value mbstring.func_overload "none"
php_value mbstring.detect_order "UTF-8,EUC-JP,SJIS,JIS,ASCII,UTF-16"
```
