### ISSUE TITLE
Не устанавливается новая версия

### ISSUE THREAD

**Issue by webwaymen** [altocms/altocms#826]
Не устанавливается новая версия. Скачиваю новую версию по ссылке с сайта, при утсановвке выходит такая ошибка: 
Parse error: syntax error, unexpected '[' in C:\OpenServer\domains\22.ff\engine\classes\core\Engine.class.php on line 1469

E_PARSE [4] syntax error, unexpected '['
See details in error.log

**Comment by aVadim483** [comment]
Требуется php 5.4
