### ISSUE TITLE
Решение ошибки 1001 и 1002

### ISSUE THREAD

**Issue by BIT-you** [altocms/altocms#827]
Кроется в вот в этой ошибке : session_start(): Cannot send session cache limiter - headers already sent (output started at engine/include/Func.php:195) (engine/classes/modules/session/Session.class.php on line 113)
Решение в .htaccess
php_value session.save_path _tmp/sessions

**Comment by aVadim483** [comment]
Это решило ошибку в Вашем конкретном случае. Но рецепт не является универсальным, зависит от настроек сервера, и поможет далеко не всем. При правильной настройке сервера таких ошибок вообще не возникает.

Возможно, у Вас на сервере не удаляются автоматически старые файлы php-сессий, и произошло переполнение директории (есть лимит, сколько файлов может быть в директории). Переназначив директорию, мы решим эту проблему на время, пока новая директория не переполнится.
