### ISSUE TITLE
Хук write_item

### ISSUE THREAD

**Issue by venticello** [altocms/altocms#832]
Хук используется в файлах
modal.write.tpl 
topic.type_default-edit.tpl 
и параметры вызова одни и те же, а оформления элементов меню создания нового типа контента разное.

**Comment by aVadim483** [comment]
Да, получается что смысл хука в шаблонах один и тот же, а визуально результат отличается. Похоже, что в шаблоне topic.type_default-edit.tpl банальная ошибка копипаста, и там должно быть, на самом деле так:
```
{hook run='write_item' isPopup=false}
```
Т.е. `isPopup=true` - это вызов хука в модальном (попап) окне. Учитывая этот параметр, можно возвращать нужный результат. Возможно, стоит еще в обработчик шаблонного хука всегда передавать имя шаблона, где он вызван, так больше будет возможности для анализа внутри обработчика

**Comment by venticello** [comment]
Я тоже так подумал, если бы хотя бы этот параметр вызова менялся уже можно было бы менять стили.

**Comment by venticello** [comment]
Отлично.
