### ISSUE TITLE
Вызов хуков в экшенах

### ISSUE THREAD

**Issue by mifkys** [altocms/altocms#838]
Приветствую! Сейчас в большинстве (если не во всех) экшенах в конце евентов идет вызов хуков под названием _show, благодаря которым можно поправить что-то при показе страницы. Почему эти хуки вызываются перед проставлением мета-тегов? Иногда нужно изменить заголовок страницы, добавив определенные слова. К примеру, хотелось бы на страницах EventShowBlog выводить не только название блога, а что-то вроде "Блог НАЗВАНИЕ" и др. Может, стоит перенести хуки в самый конец евента перед установкой шаблона?

**Comment by aVadim483** [comment]
В плагине можно переопределить метод `EventShowBlog()` и там задать название. Т.е. в плагине это будет выглядеть как-то так:
```
protected function EventShowBlog() {
    parent::EventShowBlog();
    E::Module('Viewer')->SetHtmlTitle('Тут название');
}
```
Хотя согласен, что метаданные сейчас задаются не лучшим способом, и это нужно менять

**Comment by mifkys** [comment]
Вот оно что. Хотя бы так, спасибо.

**Comment by mifkys** [comment]
Хм, а как в заголовок передавать переменную из наследуемого экшена? При попытке вставить $oBlog->getTitle() ругается, что неизвестная переменна.

**Comment by aVadim483** [comment]
В данном случае нужно использовать не `$oBlog`, а `$this->oCurrentBlog`

**Comment by mifkys** [comment]
А если не рассматривать данный случай? Какой принцип обращения к перменным из родителя при вызове в дочернем методе?

**Comment by aVadim483** [comment]
В дочернем классе можно получить доступ к любым свойствам и методам родительского класса (кроме `private`). Здесь `$oBlog` - это переменная внутри родительского метода, поэтому доступа к ней нет. А `$this->oCurrentBlog` - это свойство класса, поэтому есть доступ "снаружи"

**Comment by mifkys** [comment]
М, я почему-то считал, что есть доступ и к переменным внутри родительского метода. Мы же его наследуем как бы тоже (: В общем, ошибался. Спасибо.
