### ISSUE TITLE
\common\templates\skin\start-kit\themes\green\style.css

### ISSUE THREAD

**Issue by Segr** [altocms/altocms#840]
В начале файла ошибка:
Warning: PHP Startup: Unable to load dynamic library 'd:/www-server/modules/php/PHP-5.6/ext/php_imagick.dll' ....

**Comment by aVadim483** [comment]
Исправлено этим коммитом: https://github.com/altocms/altocms/commit/66463a12e680bfbd1469022e93759915e381718e
