### ISSUE TITLE
Будущее движка

### ISSUE THREAD

**Issue by sersar** [altocms/altocms#846]
Привет!
Так как на сайте альто ответа не получил (печально всё там) спрошу тут. 
Занимаешся ли ещё движком? Вижу правки делаешь и это радует.
Поднимаю сейчас сайт на движке и внося изменения (обновляю библиотеки) не знаю стоит ли об найденных замечаниях писать.

**Comment by partizan007** [comment]
Привет!
Интересует тот же вопрос))
Вадим - ты забросил движок или все же есть перспективы развития?
